// BytecodeModule → C source (§1.9). Reads the in-memory bytecode emitted by
// the bytecode pass and produces a single .c file ready to compile against
// runtime/c/vader_runtime.c.
//
// Strategy:
// - Each fn is emitted as a C function with a generated C signature.
// - The bytecode's value stack maps to a chain of generated C tmp vars (one
//   per push); the C compiler folds the chain back into expression form.
// - Structured control (`block`/`loop`/`if`) uses C labels + goto for `br`
//   semantics. The label naming derives from the open-ip so jumps resolve
//   without a runtime label stack.
// - Primitives flow as their native C type; struct/array refs as `void*`;
//   union slots and `any` as `vader_box_t`. The emitter inserts box/unbox
//   sequences whenever a value flows across the boundary (γ representation).
// - Imports for `std/io` map to the runtime's `vader_*` functions; the
//   tag-aware ones (read_file, read_line, write_file) receive the BcType
//   indices for the `string` and `Error` variants resolved per module.

import type {BytecodeModule, BcFunction, BcImport, BcSignature} from "../bytecode/module.ts";
import type { Op } from "../bytecode/ops.ts";
import type { ArrayKind, BcDataEntry, BcStruct, BcType, ValType } from "../bytecode/types.ts";
import { arrayKindIndex, arrayKindOf, inlineVariantPayload, nullableRefVariant } from "../bytecode/types.ts";

import {
  cTypeFor, cTypeForSignatureSlot, cTypeForVal, cTypeForValBare, emitFunctions,
  isRefVal, signatureFor, valTypeOfBcType, zeroInit,
} from "./body.ts";
import { emitVtableDispatchers, emitVtableForwardDecls } from "./ops.ts";

export function emitC(m: BytecodeModule): string {
  const ctx = newCtx(m);
  const out: string[] = [];

  out.push(`/* Generated by vader — do not edit. */`);
  out.push(`#include "vader.h"`);
  out.push(`#include <stddef.h>`);
  out.push(`#include <stdlib.h>`);     /* atexit (registered in main) */
  out.push(`#include <string.h>`);
  out.push(``);

  emitTypeDecls(ctx, out);
  emitForwardDecls(ctx, out);
  emitFnSigTypedefs(ctx, out);
  emitFnTrampolines(ctx, out);
  emitTypeInfoTable(ctx, out);
  emitImportShims(ctx, out);
  emitVtableForwardDecls(ctx, out);
  emitFunctions(ctx, out);
  emitVtableDispatchers(ctx, out);
  emitMain(ctx, out);

  return out.join("\n") + "\n";
}

// =========================================================================
// Context
// =========================================================================

export interface EmitCtx {
  readonly module: BytecodeModule;
  readonly stringTagIndex: number;       // -1 if absent
  readonly errorTagIndex: number;        // -1 if absent
  /** C identifier for each fn slot (mangled name, sanitised). */
  readonly fnNames: readonly string[];
  /** C identifier for each struct (BcType slot). */
  readonly structNames: readonly (string | null)[];
  /** Tag value for each primitive ValType — used when boxing a typed value
   *  into a `ref`/`any` slot (e.g. passing `i32` to a fn expecting `ref`).
   *  -1 means the type isn't materialised in this module's type table.  */
  readonly primitiveTagOf: ReadonlyMap<ValType, number>;
  /** Inverse of `module.implTable`: trait name → struct type-indices that
   *  implement it. Built once so `is Trait` checks don't re-scan the table. */
  readonly structIdxsByTrait: ReadonlyMap<string, readonly number[]>;
  /** Fn indices that may allocate — directly via a `struct.new` / `array.new`
   *  / `string.concat` / `intrinsic` / `make_closure`, indirectly via a
   *  `call.import` / `call.indirect` / `virtual.call` (conservative), or
   *  transitively via a `call` to another may-alloc fn. Fns NOT in this set
   *  skip the shadow-stack frame entirely — no `vader_gc_frame_t` setup,
   *  no `gc_top` push/pop, no `gc_roots[]` array. */
  readonly mayAlloc: ReadonlySet<number>;
  /** Struct type indices that appear as a target of `struct.set` somewhere
   *  in the module. These structs need a heap-allocated body so the mutation
   *  is observable to every alias of the value ; the inline-variant rep
   *  (encoded directly in `vader_box_t.payload`) only fits truly immutable
   *  values. Closure environments, `Counter { value: i32 }`-style mutables,
   *  and any single-field struct the user writes to fall into this set. */
  readonly mutatedStructs: ReadonlySet<number>;
}

function newCtx(m: BytecodeModule): EmitCtx {
  const fnNames = m.functions.map((f) => sanitise(f.name));
  const structNames: (string | null)[] = m.types.map((t) =>
    t.kind === "struct" ? `vader_struct_${sanitise(t.name)}_t` : null);
  let stringIdx = -1, errorIdx = -1;
  const primitiveTagOf = new Map<ValType, number>();
  for (let i = 0; i < m.types.length; i++) {
    const t = m.types[i]!;
    if (t.kind === "primitive") {
      primitiveTagOf.set(t.val, i);
      if (t.val === "string") stringIdx = i;
    }
    if (t.kind === "ref" && t.traitName === "Error") errorIdx = i;
  }
  const structIdxsByTrait = new Map<string, number[]>();
  for (const [structIdx, traits] of m.implTable) {
    for (const traitName of traits) {
      const list = structIdxsByTrait.get(traitName);
      if (list !== undefined) list.push(structIdx);
      else structIdxsByTrait.set(traitName, [structIdx]);
    }
  }
  return {
    module: m, stringTagIndex: stringIdx, errorTagIndex: errorIdx,
    fnNames, structNames, primitiveTagOf, structIdxsByTrait,
    mayAlloc: computeMayAlloc(m),
    mutatedStructs: computeMutatedStructs(m),
  };
}

/** Walk every fn body once and collect the type indices of every struct
 *  that's a target of a `struct.set` / `struct.set_stack` op. Used by the
 *  inline-variant fast path : structs in this set must keep the heap rep
 *  so mutations are visible to aliases. */
function computeMutatedStructs(m: BytecodeModule): ReadonlySet<number> {
  const out = new Set<number>();
  for (const fn of m.functions) {
    for (const op of fn.body) {
      if (op.kind === "struct.set" || op.kind === "struct.set_stack") {
        out.add(op.typeIndex);
      }
    }
  }
  return out;
}

// Bytecode-level callgraph analysis: which fns may trigger a GC allocation
// (transitively). Used by `emitFunctionBody` to skip the shadow-stack frame
// for pure leaf-ish fns — `inc(x) = x + 1`, accessor methods, predicates.
//
// Direct allocators: `struct.new`, `array.new`, `array.push`, `string.concat`,
// `intrinsic` (string-builder family), `make_closure`. Indirect allocators
// (conservative — unknown target): `call.import`, `call.indirect`,
// `virtual.call`. Transitive: any `call` to a fn already in the set.
function computeMayAlloc(m: BytecodeModule): Set<number> {
  const mayAlloc = new Set<number>();

  for (let fi = 0; fi < m.functions.length; fi++) {
    const fn = m.functions[fi]!;
    for (const op of fn.body) {
      switch (op.kind) {
        case "struct.new":
        case "array.new":
        case "array.push":
        case "string.concat":
        case "intrinsic":
        case "make_closure":
        case "call.import":
        case "call.indirect":
        case "virtual.call":
          mayAlloc.add(fi);
          break;
      }
      if (mayAlloc.has(fi)) break;
    }
  }

  let changed = true;
  while (changed) {
    changed = false;
    for (let fi = 0; fi < m.functions.length; fi++) {
      if (mayAlloc.has(fi)) continue;
      const fn = m.functions[fi]!;
      for (const op of fn.body) {
        if (op.kind === "call" && mayAlloc.has(op.fnIndex)) {
          mayAlloc.add(fi);
          changed = true;
          break;
        }
      }
    }
  }

  return mayAlloc;
}

// =========================================================================
// Type declarations
// =========================================================================

function emitTypeDecls(ctx: EmitCtx, out: string[]): void {
  // Forward declarations for every struct so field references compile in any
  // order; bodies follow.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind === "struct") {
      out.push(`typedef struct ${ctx.structNames[i]!} ${ctx.structNames[i]!};`);
    }
  }
  out.push(``);

  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind !== "struct") continue;
    const cname = ctx.structNames[i]!;
    out.push(`struct ${cname} {`);
    out.push(`    vader_obj_header_t header;`);
    for (const field of t.fields) {
      const fieldType = ctx.module.types[field.typeIndex]!;
      // `T | null` where T is a single heap type stores as a raw `void*` (NULL
      // for the null variant, an obj pointer for T). Saves 16 B vs the full
      // `vader_box_t` per field. The C emit at FieldGet / FieldSet boxes back
      // to / unboxes from `vader_box_t` so the rest of the program sees a
      // uniform value representation.
      if (fieldType.kind === "union" && nullableRefVariant(fieldType, ctx.module.types) !== null) {
        out.push(`    void* f_${sanitise(field.name)};`);
        continue;
      }
      out.push(`    ${cTypeFor(ctx, fieldType)} f_${sanitise(field.name)};`);
    }
    out.push(`};`);
  }
  out.push(``);

  // String literals as named struct constants — one decl per pool entry,
  // pre-sized to the UTF-8 byte length. The C compiler interns the data
  // array regardless ; folding the pointer + length into one
  // `vader_string_t` static lets `string.const` resolve to a bare name
  // instead of a `vader_string_new(_data, _len)` call.
  for (let i = 0; i < ctx.module.strings.length; i++) {
    const s = ctx.module.strings[i]!;
    const bytes = new TextEncoder().encode(s);
    out.push(`static const vader_string_t vader_str_${i} = { ${cStringLitFromBytes(bytes)}, ${bytes.length} };`);
  }
  out.push(``);

  emitDataPool(ctx, out);
}

// =========================================================================
// Data pool — module-level `const T[]` literals emitted as `.rodata` statics.
// Each pool entry produces :
//   - a packed wrapper struct `__vader_data_<i>_t` holding the buf + slots
//   - a static const vader_array_t header pointing into the wrapper
// `data.const <i>` op resolves to `vader_box_obj(<type>, &__vader_data_<i>)`.
// The GC scanner skips static pointers via its arena bound checks.
// =========================================================================

function emitDataPool(ctx: EmitCtx, out: string[]): void {
  if (ctx.module.dataPool.length === 0) return;
  for (let i = 0; i < ctx.module.dataPool.length; i++) {
    emitDataEntry(i, ctx.module.dataPool[i]!, out);
  }
  out.push(``);
}

function emitDataEntry(idx: number, entry: BcDataEntry, out: string[]): void {
  const cType = cTypeForArrayKind(entry.kind);
  const kindIdx = arrayKindIndex(entry.kind);
  const length = entry.items.length;
  // Wrapper packs the buf header + a fixed-size slot array. The buf's
  // `slots` flex-array would otherwise prevent static initialisation ;
  // the wrapper sidesteps that by giving the slots their own storage.
  // First member is `vader_array_buf_t` so `(vader_array_buf_t*) &w.buf`
  // is a legal cast.
  out.push(`static const struct {`);
  out.push(`    vader_array_buf_t buf;`);
  out.push(`    ${cType} slots[${length}];`);
  out.push(`} __vader_data_buf_${idx} = {`);
  out.push(`    .buf = {`);
  out.push(`        .header = { VADER_TYPE_INDEX_ARRAY_BUF, 0, 0, 0, NULL },`);
  out.push(`        .capacity = ${length}u, .length = ${length}u,`);
  out.push(`        .element_kind = ${kindIdx}u, ._pad = {0,0,0,0,0,0,0}`);
  out.push(`    },`);
  out.push(`    .slots = { ${entry.items.map((v) => formatDataItem(entry.kind, v)).join(", ")} }`);
  out.push(`};`);
  out.push(`static const vader_array_t __vader_data_${idx} = {`);
  out.push(`    .header = { 0, 0, 0, 0, NULL },`);
  out.push(`    .length = ${length}u, .capacity = ${length}u, .offset = 0u,`);
  out.push(`    .buf = (vader_array_buf_t*) &__vader_data_buf_${idx}.buf,`);
  out.push(`};`);
}

function cTypeForArrayKind(k: ArrayKind): string {
  switch (k) {
    case "u8":   return "uint8_t";
    case "u16":  return "uint16_t";
    case "u32":  return "uint32_t";
    case "u64":  return "uint64_t";
    case "i8":   return "int8_t";
    case "i16":  return "int16_t";
    case "i32":  return "int32_t";
    case "i64":  return "int64_t";
    case "f32":  return "float";
    case "f64":  return "double";
    case "char": return "uint32_t";
    case "bool": return "uint8_t";
    case "boxed":
      throw new Error("c-emit: data pool kind 'boxed' not allowed");
  }
}

function formatDataItem(kind: ArrayKind, v: bigint): string {
  switch (kind) {
    case "u8":   return `${BigInt.asUintN(8, v).toString()}u`;
    case "u16":  return `${BigInt.asUintN(16, v).toString()}u`;
    case "u32":  return `${BigInt.asUintN(32, v).toString()}u`;
    case "u64":  return `UINT64_C(${BigInt.asUintN(64, v).toString()})`;
    case "i8":   return `${BigInt.asIntN(8, v).toString()}`;
    case "i16":  return `${BigInt.asIntN(16, v).toString()}`;
    case "i32":  return i32LitC(Number(BigInt.asIntN(32, v)));
    case "i64":  return i64LitC(BigInt.asIntN(64, v));
    case "char": return `${BigInt.asUintN(32, v).toString()}u`;
    case "bool": return v === 0n ? "0u" : "1u";
    case "f32":  return floatLit(f32FromBits(Number(BigInt.asUintN(32, v))), "f");
    case "f64":  return floatLit(f64FromBits(BigInt.asUintN(64, v)), "");
    case "boxed":
      throw new Error("c-emit: data pool kind 'boxed' not allowed");
  }
}

const FLOAT_BUF = new ArrayBuffer(8);
const FLOAT_DV = new DataView(FLOAT_BUF);

function f32FromBits(bits: number): number {
  FLOAT_DV.setUint32(0, bits, true);
  return FLOAT_DV.getFloat32(0, true);
}

function f64FromBits(bits: bigint): number {
  FLOAT_DV.setBigUint64(0, bits, true);
  return FLOAT_DV.getFloat64(0, true);
}

// =========================================================================
// Forward declarations
// =========================================================================

function emitForwardDecls(ctx: EmitCtx, out: string[]): void {
  for (let i = 0; i < ctx.module.functions.length; i++) {
    const fn = ctx.module.functions[i]!;
    out.push(`static ${signatureFor(ctx, fn)};`);
  }
  out.push(``);
}

// =========================================================================
// Function-pointer typedefs and per-fn trampolines (for fn values / closures)
// =========================================================================

function emitFnSigTypedefs(ctx: EmitCtx, out: string[]): void {
  // One typedef per BcFn type. Every callable signature includes a leading
  // `void* env` so closures (Phase 3) can be invoked through the same path.
  // Globals route through a per-fn trampoline that ignores env.
  //
  // B1 slots (nullable-ref unions whose non-null variant is a single heap
  // struct) pass through the ABI as `void*` instead of `vader_box_t` —
  // `cTypeForSignatureSlot` picks the right C type per slot. The
  // `vader_fn_t.code` pointer is cast to this typedef in the call.indirect
  // emitter ; B1 args are pre-stripped to `void*` there, and B1 returns
  // are re-boxed.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind !== "fn") continue;
    const paramVals = t.params.map((p) => valTypeOfBcType(ctx.module.types[p]!));
    const retVal = valTypeOfBcType(ctx.module.types[t.returnType]!);
    const params = paramVals.map((p, j) =>
      `${cTypeForSignatureSlot(ctx, t.params[j]!, p)} a${j}`);
    const cret = retVal === "void"
      ? "void"
      : cTypeForSignatureSlot(ctx, t.returnType, retVal);
    const head = `void* env`;
    out.push(`typedef ${cret} (*vader_fn_sig_${i}_t)(${params.length === 0 ? head : `${head}, ${params.join(", ")}`});`);
  }
  out.push(``);
}

// =========================================================================
// Type info table — pointer maps consumed by the GC scanner
// =========================================================================

function emitTypeInfoTable(ctx: EmitCtx, out: string[]): void {
  const types = ctx.module.types;

  // Per-type ptr-offset arrays. We collect into a buffer first so the table
  // initialiser can reference each by name. `offsetof` is resolved at C compile
  // time so we don't have to know struct sizes in TypeScript.
  //
  // Two parallel arrays per struct:
  //   - `_ptrs[]`     box-bearing fields (vader_box_t)
  //   - `_strs[]`     raw vader_string_t fat-ptr fields
  // The string GC needs the latter because string fields are stored inline
  // as primitive `vader_string_t`, not as boxes — the box-aliased mark
  // walk would otherwise miss them.
  for (let i = 0; i < types.length; i++) {
    const t = types[i]!;
    if (t.kind === "struct") {
      const cname = ctx.structNames[i]!;
      const offsets: string[] = [];
      const stringOffsets: string[] = [];
      const refOffsets: string[] = [];
      for (const field of t.fields) {
        const ftype = types[field.typeIndex]!;
        if (ftype.kind === "union" && nullableRefVariant(ftype, types) !== null) {
          // `T | null` field — stored as a raw `void*` (NULL = null variant,
          // non-null = obj pointer). Saves 16 B vs the equivalent box ;
          // listed separately so the scanner walks it with `scan_raw`.
          refOffsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        } else if (ftype.kind !== "primitive") {
          // Heap-bearing field — its C type is `vader_box_t`. Tracing this
          // slot requires checking the box tag at scan time.
          offsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        } else if (ftype.val === "string") {
          // Raw `vader_string_t` field. The Cheney scan ignores it (the
          // buffer lives in the non-moving string arena), but the string
          // mark-sweep collector must reach it.
          stringOffsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        }
      }
      if (offsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_ptrs[] = { ${offsets.join(", ")} };`);
      }
      if (stringOffsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_strs[] = { ${stringOffsets.join(", ")} };`);
      }
      if (refOffsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_refs[] = { ${refOffsets.join(", ")} };`);
      }
    } else if (t.kind === "fn") {
      // vader_fn_t has `code` (function pointer — NOT a heap ref, must not
      // be scanned) and `env` (heap pointer to the closure environment).
      out.push(`static const uint16_t vader_type_${i}_ptrs[] = { offsetof(vader_fn_t, env) };`);
    } else if (t.kind === "array") {
      // The buf is a raw pointer to a header-bearing object — scan_raw treatment.
      out.push(`static const uint16_t vader_type_${i}_ptrs[] = { offsetof(vader_array_t, buf) };`);
    }
  }

  out.push(``);
  // Fixed length so missing entries (primitives, unions, refs — no GC info)
  // zero-initialise to `VADER_TYPE_KIND_NONE`. Without the explicit size, C
  // would size the array to `max-designated-index + 1`, and any later
  // `vader_type_info_table[tag]` read with `tag` past the last designated
  // entry but below `vader_type_info_count` would walk off the array.
  out.push(`const vader_type_info_t vader_type_info_table[${types.length}] = {`);
  for (let i = 0; i < types.length; i++) {
    const t = types[i]!;
    if (t.kind === "struct") {
      // Inline-variant structs (empty-body / single-primitive-field /
      // single-ref-field) are encoded directly inside `vader_box_t.payload`
      // — they never get a heap allocation. Mutated structs are excluded :
      // they keep the heap rep so `struct.set` is observable across aliases.
      const inlinePayload = !ctx.mutatedStructs.has(i)
        ? inlineVariantPayload(t, types)
        : null;
      if (inlinePayload === "void" || (inlinePayload !== null && inlinePayload !== "ref")) {
        // Empty + primitive inline : `payload` is non-pointer data, GC skips
        // the slot. Leave the entry at its zero-init KIND_NONE so
        // `vader_gc_scan_box` short-circuits before touching the payload.
        continue;
      }
      if (inlinePayload === "ref") {
        // Single-ref-field inline : `payload.obj` IS the referent's heap
        // pointer (the wrapper struct itself never allocates). GC reaches
        // through via `scan_raw`, reading the referent's own type tag from
        // its header — no per-tag scan info needed here.
        out.push(`    [${i}] = { VADER_TYPE_KIND_INLINE_REF, 0, NULL, 0, 0, NULL, 0, NULL },`);
        continue;
      }
      const cname = ctx.structNames[i]!;
      const boxFields = t.fields.filter((f) => {
        const ft = types[f.typeIndex]!;
        if (ft.kind === "union" && nullableRefVariant(ft, types) !== null) return false;
        return ft.kind !== "primitive";
      });
      const strFields = t.fields.filter((f) => {
        const ft = types[f.typeIndex]!;
        return ft.kind === "primitive" && ft.val === "string";
      });
      const refFields = t.fields.filter((f) => {
        const ft = types[f.typeIndex]!;
        return ft.kind === "union" && nullableRefVariant(ft, types) !== null;
      });
      const ptrArr = boxFields.length > 0 ? `vader_type_${i}_ptrs` : "NULL";
      const strArr = strFields.length > 0 ? `vader_type_${i}_strs` : "NULL";
      const refArr = refFields.length > 0 ? `vader_type_${i}_refs` : "NULL";
      out.push(`    [${i}] = { VADER_TYPE_KIND_STRUCT, sizeof(${cname}), ${ptrArr}, ${boxFields.length}, ${strFields.length}, ${strArr}, ${refFields.length}, ${refArr} },`);
    } else if (t.kind === "fn") {
      out.push(`    [${i}] = { VADER_TYPE_KIND_FN, sizeof(vader_fn_t), vader_type_${i}_ptrs, 1, 0, NULL, 0, NULL },`);
    } else if (t.kind === "array") {
      out.push(`    [${i}] = { VADER_TYPE_KIND_ARRAY, sizeof(vader_array_t), vader_type_${i}_ptrs, 1, 0, NULL, 0, NULL },`);
    }
    // primitive / union / ref → entry implicitly zero-initialised
    // (VADER_TYPE_KIND_NONE), which the GC interprets as "non-heap, skip".
  }
  out.push(`};`);
  out.push(`const size_t vader_type_info_count = ${types.length};`);
  out.push(``);
}

function emitFnTrampolines(ctx: EmitCtx, out: string[]): void {
  // Walk every fn body to discover which fns are taken by reference and
  // which lifted fns get instantiated via `make_closure`. Each kind needs a
  // matching wrapper:
  //   - `fn.ref`        — wrapper drops env (global fn used as a value)
  //   - `make_closure`  — wrapper boxes env into vader_box_t before calling
  //                       (the lifted fn's signature takes `ref env`)
  const fnRefMap = new Map<number, number>();        // fnIndex → BcFn typeIndex
  const closureMap = new Map<number, number>();      // lifted fnIndex → BcFn typeIndex
  for (const fn of ctx.module.functions) {
    for (const op of fn.body) {
      if (op.kind === "fn.ref") fnRefMap.set(op.fnIndex, op.typeIndex);
      else if (op.kind === "make_closure") closureMap.set(op.fnIndex, op.typeIndex);
    }
  }
  if (fnRefMap.size === 0 && closureMap.size === 0) return;

  for (const [fnIndex, typeIndex] of fnRefMap) {
    const fn = ctx.module.functions[fnIndex]!;
    const cname = ctx.fnNames[fnIndex]!;
    const params = fn.signature.params.map((p, j) => `${cTypeForValBare(p)} a${j}`);
    const cret = fn.signature.result === "void" ? "void" : cTypeForValBare(fn.signature.result);
    const argList = fn.signature.params.map((_, j) => `a${j}`).join(", ");
    out.push(`static ${cret} vader_fn_tramp_${fnIndex}(${params.length === 0 ? "void* env" : `void* env, ${params.join(", ")}`}) {`);
    out.push(`    (void) env;`);
    if (fn.signature.result === "void") {
      out.push(`    ${cname}(${argList});`);
    } else {
      out.push(`    return ${cname}(${argList});`);
    }
    out.push(`}`);
    out.push(`static vader_fn_t vader_fn_static_${fnIndex} = { { ${typeIndex}u, 0u, 0u, 0u, NULL }, (void*) &vader_fn_tramp_${fnIndex}, NULL };`);
  }

  // Lifted-lambda wrappers — the bytecode signature of a lifted fn is
  // `(ref, ...originalParams) → ret` where the leading `ref` is the env
  // boxed as vader_box_t. The wrapper takes `void* env`, boxes it, and
  // invokes the underlying lifted fn. The `make_closure` op grabs the
  // wrapper's address at allocation time.
  for (const [fnIndex, _typeIndex] of closureMap) {
    const fn = ctx.module.functions[fnIndex]!;
    const cname = ctx.fnNames[fnIndex]!;
    if (fn.signature.params.length === 0) {
      // Defensive — a lifted fn always has at least the env param.
      continue;
    }
    // Skip the env param at index 0; the rest mirror the original lambda's params.
    const tailParams = fn.signature.params.slice(1).map((p, j) => `${cTypeForValBare(p)} a${j}`);
    const tailArgs = fn.signature.params.slice(1).map((_, j) => `a${j}`).join(", ");
    const cret = fn.signature.result === "void" ? "void" : cTypeForValBare(fn.signature.result);
    const head = tailParams.length === 0 ? "void* env" : `void* env, ${tailParams.join(", ")}`;
    out.push(`static ${cret} vader_fn_lift_${fnIndex}(${head}) {`);
    // Box raw env back into the vader_box_t shape the lifted fn expects.
    // The BcFn type index of the env doesn't matter to the lifted fn body —
    // only the raw obj pointer is dereferenced via struct.get on the env
    // struct's fields. Tag 0 is reserved for null and is harmless here.
    out.push(`    vader_box_t env_box; env_box.tag = 0u; env_box._pad = 0u; env_box.payload.obj = env;`);
    const callArgs = tailArgs.length === 0 ? `env_box` : `env_box, ${tailArgs}`;
    if (fn.signature.result === "void") {
      out.push(`    ${cname}(${callArgs});`);
    } else {
      out.push(`    return ${cname}(${callArgs});`);
    }
    out.push(`}`);
  }
  out.push(``);
}

// =========================================================================
// Import shims
// =========================================================================

function emitImportShims(ctx: EmitCtx, out: string[]): void {
  // Unused-import pruning happens upstream in `pruneUnusedImports` (see
  // `src/midir/emit.ts`) so the bytecode module already carries only the
  // imports actually referenced by `call.import` ops. Every backend (VM,
  // C-emit, future WASM) and every serialiser (`.vir` text/binary) gets
  // the compact table for free.
  for (let i = 0; i < ctx.module.imports.length; i++) {
    const imp = ctx.module.imports[i]!;
    const shim = importShim(ctx, imp, i);
    if (shim !== null) out.push(shim);
  }
  out.push(``);
}

function importShim(ctx: EmitCtx, imp: BcImport, idx: number): string | null {
  const name = `vader_import_${idx}`;
  const params = imp.signature.params.map((vt, j) => `${cTypeForVal(ctx, vt)} a${j}`).join(", ");
  const ret = cTypeForVal(ctx, imp.signature.result);
  const head = `static ${ret} ${name}(${params || "void"})`;

  // Built-in std/io routes — implemented by the runtime.
  switch (imp.mangledName) {
    case "std_io$print":
      return `${head} { vader_print(a0); }`;
    case "std_io$println":
      return `${head} { vader_println(a0); }`;
    case "std_testing$panic":
      return `${head} { vader_panic(a0); }`;
    case "std_io$eprint":
      return `${head} { vader_eprint(a0); }`;
    case "std_io$eprintln":
      return `${head} { vader_eprintln(a0); }`;
    case "std_io$exists":
      return `${head} { return vader_exists(a0); }`;
    case "std_io$is_dir":
      return `${head} { return vader_is_dir(a0); }`;
    case "std_io$read_dir": {
      const strIdx = ctx.stringTagIndex;
      if (strIdx < 0) return `${head} { vader_trap("read_dir: no string type"); }`;
      const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
      if (arrIdx < 0) return `${head} { vader_trap("read_dir: no [string] type"); }`;
      return `${head} { return vader_read_dir(a0, ${arrIdx}u, ${strIdx}u, ${tagOrTrap(ctx, "error")}); }`;
    }
    case "std_io$read_file":
      return `${head} { return vader_read_file(a0, ${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$write_file":
      return `${head} { return vader_write_file(a0, a1, 0u, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$read_line":
      return `${head} { return vader_read_line(${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$read_stdin":
      return `${head} { return vader_read_stdin(a0, ${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;

    case "std_string$byte_len":    return `${head} { return vader_string_byte_len(a0); }`;
    case "std_string$slice":       return `${head} { return vader_string_slice(a0, a1, a2); }`;
    case "std_string$contains":    return `${head} { return vader_string_contains(a0, a1); }`;
    case "std_string$starts_with": return `${head} { return vader_string_starts_with(a0, a1); }`;
    case "std_string$ends_with":   return `${head} { return vader_string_ends_with(a0, a1); }`;
    case "std_string$trim":        return `${head} { return vader_string_trim(a0); }`;
    case "std_string$to_upper":    return `${head} { return vader_string_to_upper(a0); }`;
    case "std_string$to_lower":    return `${head} { return vader_string_to_lower(a0); }`;
    // `string implements Index(usize, char)` is `@intrinsic`-impl in std/core,
    // so the host provides the body under the impl-method mangled name.
    case "std_core$string$Index$at":
      return `${head} { return vader_string_char_at(a0, a1); }`;
    case "std_string$byte_at":
      return `${head} { return vader_string_byte_at(a0, a1); }`;
    case "std_string$split": {
      const strIdx = ctx.stringTagIndex;
      if (strIdx < 0) return `${head} { vader_trap("split: no string type"); }`;
      const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
      if (arrIdx < 0) return `${head} { vader_trap("split: no [string] type"); }`;
      return `${head} { return vader_box_obj(${arrIdx}u, vader_string_split(a0, a1, ${arrIdx}u, ${strIdx}u)); }`;
    }
    case "std_string$parse_int":
      return `${head} { return vader_string_parse_int(a0, ${primTagOrTrap(ctx, "i32")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_string$parse_float":
      return `${head} { return vader_string_parse_float(a0, ${primTagOrTrap(ctx, "f64")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_core$string$Hash$hash":
      return `${head} { return vader_string_hash(a0); }`;

    // `@intrinsic <T> implements Display` for primitives — each shim spins
    // up a one-shot StringBuilder, calls the matching append_display_<T>
    // helper, then finishes. Reuses existing runtime infrastructure rather
    // than introducing parallel `vader_<T>_to_string` helpers.
    case "std_core$i8$Display$to_string":
    case "std_core$i16$Display$to_string":
    case "std_core$i32$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_i32(sb, (int32_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$i64$Display$to_string":
    case "std_core$isize$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_i64(sb, (int64_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$u8$Display$to_string":
    case "std_core$u16$Display$to_string":
    case "std_core$u32$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_u32(sb, (uint32_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$u64$Display$to_string":
    case "std_core$usize$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_u64(sb, (uint64_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$f32$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_f32(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$f64$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_f64(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$bool$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_bool(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$char$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_char(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$string$Display$to_string":
      return `${head} { return a0; }`;

    case "std_string_builder$StringBuilder$Display$to_string": {
      // `@intrinsic StringBuilder implements Display` — receiver is a boxed
      // StringBuilder whose only field `parts` holds the string[] buffer.
      // The mangled struct name is `<module>$StringBuilder` (or just
      // `StringBuilder` when the module stem matches the type name).
      const sbIdx = ctx.module.types.findIndex(
        (t) => t.kind === "struct"
            && (t.name === "StringBuilder" || t.name.endsWith("$StringBuilder")),
      );
      if (sbIdx < 0) return `${head} { vader_trap("StringBuilder type not found"); }`;
      const sbType = ctx.module.types[sbIdx] as BcStruct;
      // Inline-ref rep : StringBuilder's `parts` field IS the box payload,
      // there's no separate heap struct to deref. `a0.payload.obj` is the
      // string[] array obj pointer directly.
      const sbInline = !ctx.mutatedStructs.has(sbIdx) && inlineVariantPayload(sbType, ctx.module.types) === "ref";
      if (sbInline) {
        return `${head} { return vader_string_concat_all((vader_array_t*) a0.payload.obj); }`;
      }
      const sbCName = ctx.structNames[sbIdx]!;
      return `${head} { vader_box_t parts = ((${sbCName}*) a0.payload.obj)->f_parts; return vader_string_concat_all((vader_array_t*) parts.payload.obj); }`;
    }

    case "std_runtime$collect":      return `${head} { vader_gc_collect(); }`;
    case "std_runtime$collections":  return `${head} { return (int32_t) vader_gc_get_stats().total_collections; }`;
    case "std_runtime$bytes_used":   return `${head} { return (int32_t) vader_gc_get_stats().bytes_used; }`;
    case "std_runtime$bytes_copied": return `${head} { return (int32_t) vader_gc_get_stats().total_copied; }`;

    case "std_time$now_unix_ms": return `${head} { return vader_clock_realtime_ms(); }`;
    case "std_time$monotonic_ns": return `${head} { return vader_clock_monotonic_ns(); }`;

    case "std_math$sqrt":  return `${head} { return vader_math_sqrt(a0); }`;
    case "std_math$pow":   return `${head} { return vader_math_pow(a0, a1); }`;
    case "std_math$floor": return `${head} { return vader_math_floor(a0); }`;
    case "std_math$ceil":  return `${head} { return vader_math_ceil(a0); }`;
    case "std_math$round": return `${head} { return vader_math_round(a0); }`;
    case "std_math$sin":   return `${head} { return vader_math_sin(a0); }`;
    case "std_math$cos":   return `${head} { return vader_math_cos(a0); }`;
    case "std_math$tan":   return `${head} { return vader_math_tan(a0); }`;

    case "std_process$spawn_run":
      return `${head} { return vader_spawn_run((vader_array_t*) a0.payload.obj); }`;
    case "std_process$spawn_last_stdout":
      return `${head} { return vader_spawn_last_stdout(); }`;
    case "std_process$spawn_last_stderr":
      return `${head} { return vader_spawn_last_stderr(); }`;

    default:
      // Foreign imports — emit a stub that traps, the user supplies linkage
      // via `cc <user>.o` post-MVP.
      return `${head} { vader_trap("unbound import: ${imp.mangledName}"); }`;
  }
}

function tagOrTrap(ctx: EmitCtx, kind: "string" | "error"): string {
  const idx = kind === "string" ? ctx.stringTagIndex : ctx.errorTagIndex;
  if (idx < 0) return `0u /* ${kind} tag absent */`;
  return `${idx}u`;
}

/** Primitive-type tag lookup for runtime calls that must box their result with
 *  the user-visible type's BcType index (e.g. `parse_int` boxing as `i32` so
 *  `match r { is i32 -> ... }` succeeds). */
function primTagOrTrap(ctx: EmitCtx, val: ValType): string {
  const idx = ctx.primitiveTagOf.get(val);
  if (idx === undefined) return `0u /* ${val} tag absent */`;
  return `${idx}u`;
}

// =========================================================================
// `main` entry
// =========================================================================

function emitMain(ctx: EmitCtx, out: string[]): void {
  const main = ctx.module.functions.findIndex((f) => f.isMain && f.body.length > 0);
  if (main < 0) {
    out.push(`int main(int argc, char** argv) { (void)argc; (void)argv; return 0; }`);
    return;
  }
  const fn = ctx.module.functions[main]!;
  const cname = ctx.fnNames[main]!;
  // Typechecker (T3033) guarantees the signature is `()` or `([string])` → i32.
  const takesArgv = fn.signature.params.length === 1;
  out.push(`int main(int argc, char** argv) {`);
  // Register the GC arena release at exit. Process death frees on Unix, but
  // an explicit shutdown is correct for embedded / atexit-aware tooling and
  // gives sanitisers a clean baseline.
  out.push(`    atexit(vader_gc_shutdown);`);
  let callArgs = "";
  if (takesArgv) {
    const strIdx = ctx.stringTagIndex;
    const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
    if (strIdx < 0 || arrIdx < 0) {
      out.push(`    (void)argc; (void)argv; vader_trap("main(argv): missing [string] type"); return 1;`);
      out.push(`}`);
      return;
    }
    out.push(`    vader_box_t __args = vader_box_obj(${arrIdx}u, vader_runtime_argv(argc, argv, ${arrIdx}u, ${strIdx}u));`);
    callArgs = "__args";
  } else {
    out.push(`    (void)argc; (void)argv;`);
  }
  if (fn.signature.result === "void") {
    out.push(`    ${cname}(${callArgs});`);
    out.push(`    return 0;`);
  } else {
    out.push(`    return (int) ${cname}(${callArgs});`);
  }
  out.push(`}`);
}

// =========================================================================
// String / identifier escapes
// =========================================================================

/** C keywords (C11 + a few common identifiers like `restrict` reserved by
 *  many compilers). Any user identifier that happens to match one is suffixed
 *  with `_v` so the emitted C is always valid. */
const C_RESERVED: ReadonlySet<string> = new Set([
  "auto", "break", "case", "char", "const", "continue", "default", "do",
  "double", "else", "enum", "extern", "float", "for", "goto", "if", "inline",
  "int", "long", "register", "restrict", "return", "short", "signed",
  "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned",
  "void", "volatile", "while", "_Alignas", "_Alignof", "_Atomic", "_Bool",
  "_Complex", "_Generic", "_Imaginary", "_Noreturn", "_Static_assert",
  "_Thread_local",
]);

export function sanitise(raw: string): string {
  const out = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return C_RESERVED.has(out) ? `${out}_v` : out;
}

export function cStringLit(s: string): string {
  return cStringLitFromBytes(new TextEncoder().encode(s));
}

export function cStringLitFromBytes(bytes: Uint8Array): string {
  let out = '"';
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i]!;
    if (b === 0x5c) out += "\\\\";
    else if (b === 0x22) out += "\\\"";
    else if (b === 0x0a) out += "\\n";
    else if (b === 0x0d) out += "\\r";
    else if (b === 0x09) out += "\\t";
    else if (b < 0x20 || b >= 0x7f) {
      // C `\x` escapes are unbounded — they consume every following hex digit
      // until the first non-hex character. If the next byte happens to be a
      // hex digit (or a continuation byte from a multi-byte UTF-8 codepoint),
      // close the escape with `""` so the digits start a fresh literal piece.
      out += `\\x${b.toString(16).padStart(2, "0")}`;
      const next = bytes[i + 1];
      if (next !== undefined && isCHexDigit(next)) out += '""';
    } else out += String.fromCharCode(b);
  }
  out += '"';
  return out;
}

function isCHexDigit(b: number): boolean {
  return (b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x46) || (b >= 0x61 && b <= 0x66);
}

export function escapeC(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

export function floatLit(v: number, suffix: string): string {
  if (!Number.isFinite(v)) {
    if (Number.isNaN(v)) return "(0.0/0.0)";
    return v > 0 ? "(1.0/0.0)" : "(-1.0/0.0)";
  }
  const s = v.toString();
  return s.includes(".") || s.includes("e") ? s + suffix : `${s}.0${suffix}`;
}

const I32_MIN = -2147483648;
const I32_MAX =  2147483647;
const I64_MIN_BIG = -(1n << 63n);
const I64_MAX_BIG =  (1n << 63n) - 1n;

/** C source for an i32 literal. Values outside the signed range round-trip
 *  through `(int32_t)UINT32_C(N)` to silence -Wconstant-conversion: the
 *  literal is born unsigned, then reinterpreted via two's complement.
 *  `INT32_MIN` itself can't be written as `INT32_C(-2147483648)` — that
 *  parses as unary minus applied to `2147483648`, which doesn't fit i32
 *  and is UB on strict toolchains; emit `INT32_MIN` (a stdint.h macro). */
export function i32LitC(value: number): string {
  if (value === I32_MIN) return `INT32_MIN`;
  if (value >= I32_MIN && value <= I32_MAX) return `INT32_C(${value})`;
  return `(int32_t)UINT32_C(${value >>> 0})`;
}

/** C source for an i64 literal. Same logic as `i32LitC` but for the 64-bit
 *  range. The bigint stays exact so unsigned values up to 2^64-1 round-trip
 *  through `(int64_t)UINT64_C(N)`. `INT64_MIN` likewise needs the macro to
 *  dodge the unary-minus / overflow trap. */
export function i64LitC(value: bigint): string {
  if (value === I64_MIN_BIG) return `INT64_MIN`;
  if (value >= I64_MIN_BIG && value <= I64_MAX_BIG) return `INT64_C(${value.toString()})`;
  const u = value & ((1n << 64n) - 1n);
  return `(int64_t)UINT64_C(${u.toString()})`;
}
