// BytecodeModule → C source (§1.9). Reads the in-memory bytecode emitted by
// the bytecode pass and produces a single .c file ready to compile against
// runtime/c/vader_runtime.c.
//
// Strategy:
// - Each fn is emitted as a C function with a generated C signature.
// - The bytecode's value stack maps to a chain of generated C tmp vars (one
//   per push); the C compiler folds the chain back into expression form.
// - Structured control (`block`/`loop`/`if`) uses C labels + goto for `br`
//   semantics. The label naming derives from the open-ip so jumps resolve
//   without a runtime label stack.
// - Primitives flow as their native C type; struct/array refs as `void*`;
//   union slots and `any` as `vader_box_t`. The emitter inserts box/unbox
//   sequences whenever a value flows across the boundary (γ representation).
// - Imports for `std/io` map to the runtime's `vader_*` functions; the
//   tag-aware ones (read_file, read_line, write_file) receive the BcType
//   indices for the `string` and `Error` variants resolved per module.

import type { BytecodeModule, BcFunction, BcImport } from "../bytecode/module.ts";
import type { Op } from "../bytecode/ops.ts";
import { INTRINSIC_TABLE } from "../bytecode/ops.ts";
import type { BcType, ValType } from "../bytecode/types.ts";
import { isMainMangled } from "../monomorphize/mono-ast.ts";

export function emitC(m: BytecodeModule): string {
  const ctx = newCtx(m);
  const out: string[] = [];

  out.push(`/* Generated by vader — do not edit. */`);
  out.push(`#include "vader.h"`);
  out.push(`#include <stddef.h>`);
  out.push(`#include <stdlib.h>`);     /* atexit (registered in main) */
  out.push(`#include <string.h>`);
  out.push(``);

  emitTypeDecls(ctx, out);
  emitForwardDecls(ctx, out);
  emitFnSigTypedefs(ctx, out);
  emitFnTrampolines(ctx, out);
  emitTypeInfoTable(ctx, out);
  emitImportShims(ctx, out);
  emitVtableForwardDecls(ctx, out);
  emitFunctions(ctx, out);
  emitVtableDispatchers(ctx, out);
  emitMain(ctx, out);

  return out.join("\n") + "\n";
}

// =========================================================================
// Context
// =========================================================================

interface EmitCtx {
  readonly module: BytecodeModule;
  readonly stringTagIndex: number;       // -1 if absent
  readonly errorTagIndex: number;        // -1 if absent
  /** C identifier for each fn slot (mangled name, sanitised). */
  readonly fnNames: readonly string[];
  /** C identifier for each struct (BcType slot). */
  readonly structNames: readonly (string | null)[];
  /** Tag value for each primitive ValType — used when boxing a typed value
   *  into a `ref`/`any` slot (e.g. passing `i32` to a fn expecting `ref`).
   *  -1 means the type isn't materialised in this module's type table.  */
  readonly primitiveTagOf: ReadonlyMap<ValType, number>;
  /** Inverse of `module.implTable`: trait name → struct type-indices that
   *  implement it. Built once so `is Trait` checks don't re-scan the table. */
  readonly structIdxsByTrait: ReadonlyMap<string, readonly number[]>;
}

function newCtx(m: BytecodeModule): EmitCtx {
  const fnNames = m.functions.map((f) => sanitise(f.name));
  const structNames: (string | null)[] = m.types.map((t) =>
    t.kind === "struct" ? `vader_struct_${sanitise(t.name)}_t` : null);
  let stringIdx = -1, errorIdx = -1;
  const primitiveTagOf = new Map<ValType, number>();
  for (let i = 0; i < m.types.length; i++) {
    const t = m.types[i]!;
    if (t.kind === "primitive") {
      primitiveTagOf.set(t.val, i);
      if (t.val === "string") stringIdx = i;
    }
    if (t.kind === "ref" && t.traitName === "Error") errorIdx = i;
  }
  const structIdxsByTrait = new Map<string, number[]>();
  for (const [structIdx, traits] of m.implTable) {
    for (const traitName of traits) {
      const list = structIdxsByTrait.get(traitName);
      if (list !== undefined) list.push(structIdx);
      else structIdxsByTrait.set(traitName, [structIdx]);
    }
  }
  return {
    module: m, stringTagIndex: stringIdx, errorTagIndex: errorIdx,
    fnNames, structNames, primitiveTagOf, structIdxsByTrait,
  };
}

// =========================================================================
// Type declarations
// =========================================================================

function emitTypeDecls(ctx: EmitCtx, out: string[]): void {
  // Forward declarations for every struct so field references compile in any
  // order; bodies follow.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind === "struct") {
      out.push(`typedef struct ${ctx.structNames[i]!} ${ctx.structNames[i]!};`);
    }
  }
  out.push(``);

  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind !== "struct") continue;
    const cname = ctx.structNames[i]!;
    out.push(`struct ${cname} {`);
    out.push(`    vader_obj_header_t header;`);
    for (const field of t.fields) {
      const fty = cTypeFor(ctx, ctx.module.types[field.typeIndex]!);
      out.push(`    ${fty} f_${sanitise(field.name)};`);
    }
    out.push(`};`);
  }
  out.push(``);

  // String literals as named constants — C string literals embed null bytes
  // safely if we declare with `static const char[]`. Length is the UTF-8
  // byte count (matches vader_string_t.len), not the JS UTF-16 unit count.
  for (let i = 0; i < ctx.module.strings.length; i++) {
    const s = ctx.module.strings[i]!;
    const bytes = new TextEncoder().encode(s);
    out.push(`static const char vader_str_${i}_data[] = ${cStringLitFromBytes(bytes)};`);
    out.push(`static const size_t vader_str_${i}_len = ${bytes.length};`);
  }
  out.push(``);
}

// =========================================================================
// Forward declarations
// =========================================================================

function emitForwardDecls(ctx: EmitCtx, out: string[]): void {
  for (let i = 0; i < ctx.module.functions.length; i++) {
    const fn = ctx.module.functions[i]!;
    out.push(`static ${signatureFor(ctx, fn)};`);
  }
  out.push(``);
}

// =========================================================================
// Function-pointer typedefs and per-fn trampolines (for fn values / closures)
// =========================================================================

function emitFnSigTypedefs(ctx: EmitCtx, out: string[]): void {
  // One typedef per BcFn type. Every callable signature includes a leading
  // `void* env` so closures (Phase 3) can be invoked through the same path.
  // Globals route through a per-fn trampoline that ignores env.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind !== "fn") continue;
    const paramVals = t.params.map((p) => valTypeOfBcType(ctx.module.types[p]!));
    const retVal = valTypeOfBcType(ctx.module.types[t.returnType]!);
    const params = paramVals.map((p, j) => `${cTypeForValBare(p)} a${j}`);
    const cret = retVal === "void" ? "void" : cTypeForValBare(retVal);
    const head = `void* env`;
    out.push(`typedef ${cret} (*vader_fn_sig_${i}_t)(${params.length === 0 ? head : `${head}, ${params.join(", ")}`});`);
  }
  out.push(``);
}

// =========================================================================
// Type info table — pointer maps consumed by the GC scanner
// =========================================================================

function emitTypeInfoTable(ctx: EmitCtx, out: string[]): void {
  const types = ctx.module.types;

  // Per-type ptr-offset arrays. We collect into a buffer first so the table
  // initialiser can reference each by name. `offsetof` is resolved at C compile
  // time so we don't have to know struct sizes in TypeScript.
  for (let i = 0; i < types.length; i++) {
    const t = types[i]!;
    if (t.kind === "struct") {
      const cname = ctx.structNames[i]!;
      const offsets: string[] = [];
      for (const field of t.fields) {
        const ftype = types[field.typeIndex]!;
        if (ftype.kind !== "primitive") {
          // Heap-bearing field — its C type is `vader_box_t`. Tracing this
          // slot requires checking the box tag at scan time.
          offsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        }
      }
      if (offsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_ptrs[] = { ${offsets.join(", ")} };`);
      }
    } else if (t.kind === "fn") {
      // vader_fn_t has `code` (function pointer — NOT a heap ref, must not
      // be scanned) and `env` (heap pointer to the closure environment).
      out.push(`static const uint16_t vader_type_${i}_ptrs[] = { offsetof(vader_fn_t, env) };`);
    } else if (t.kind === "array") {
      // The buf is a raw pointer to a header-bearing object — scan_raw treatment.
      out.push(`static const uint16_t vader_type_${i}_ptrs[] = { offsetof(vader_array_t, buf) };`);
    }
  }

  out.push(``);
  out.push(`const vader_type_info_t vader_type_info_table[] = {`);
  for (let i = 0; i < types.length; i++) {
    const t = types[i]!;
    if (t.kind === "struct") {
      const cname = ctx.structNames[i]!;
      const hasPtrs = t.fields.some((f) => types[f.typeIndex]!.kind !== "primitive");
      const ptrArr = hasPtrs ? `vader_type_${i}_ptrs` : "NULL";
      const ptrCount = hasPtrs ? t.fields.filter((f) => types[f.typeIndex]!.kind !== "primitive").length : 0;
      out.push(`    [${i}] = { VADER_TYPE_KIND_STRUCT, sizeof(${cname}), ${ptrArr}, ${ptrCount}, 0 },`);
    } else if (t.kind === "fn") {
      out.push(`    [${i}] = { VADER_TYPE_KIND_FN, sizeof(vader_fn_t), vader_type_${i}_ptrs, 1, 0 },`);
    } else if (t.kind === "array") {
      out.push(`    [${i}] = { VADER_TYPE_KIND_ARRAY, sizeof(vader_array_t), vader_type_${i}_ptrs, 1, 0 },`);
    }
    // primitive / union / ref → entry implicitly zero-initialised
    // (VADER_TYPE_KIND_NONE), which the GC interprets as "non-heap, skip".
  }
  out.push(`};`);
  out.push(`const size_t vader_type_info_count = ${types.length};`);
  out.push(``);
}

function emitFnTrampolines(ctx: EmitCtx, out: string[]): void {
  // Walk every fn body to discover which fns are taken by reference and
  // which lifted fns get instantiated via `make_closure`. Each kind needs a
  // matching wrapper:
  //   - `fn.ref`        — wrapper drops env (global fn used as a value)
  //   - `make_closure`  — wrapper boxes env into vader_box_t before calling
  //                       (the lifted fn's signature takes `ref env`)
  const fnRefMap = new Map<number, number>();        // fnIndex → BcFn typeIndex
  const closureMap = new Map<number, number>();      // lifted fnIndex → BcFn typeIndex
  for (const fn of ctx.module.functions) {
    for (const op of fn.body) {
      if (op.kind === "fn.ref") fnRefMap.set(op.fnIndex, op.typeIndex);
      else if (op.kind === "make_closure") closureMap.set(op.fnIndex, op.typeIndex);
    }
  }
  if (fnRefMap.size === 0 && closureMap.size === 0) return;

  for (const [fnIndex, typeIndex] of fnRefMap) {
    const fn = ctx.module.functions[fnIndex]!;
    const cname = ctx.fnNames[fnIndex]!;
    const params = fn.signature.params.map((p, j) => `${cTypeForValBare(p)} a${j}`);
    const cret = fn.signature.result === "void" ? "void" : cTypeForValBare(fn.signature.result);
    const argList = fn.signature.params.map((_, j) => `a${j}`).join(", ");
    out.push(`static ${cret} vader_fn_tramp_${fnIndex}(${params.length === 0 ? "void* env" : `void* env, ${params.join(", ")}`}) {`);
    out.push(`    (void) env;`);
    if (fn.signature.result === "void") {
      out.push(`    ${cname}(${argList});`);
    } else {
      out.push(`    return ${cname}(${argList});`);
    }
    out.push(`}`);
    out.push(`static vader_fn_t vader_fn_static_${fnIndex} = { { ${typeIndex}u, 0u, NULL }, (void*) &vader_fn_tramp_${fnIndex}, NULL };`);
  }

  // Lifted-lambda wrappers — the bytecode signature of a lifted fn is
  // `(ref, ...originalParams) → ret` where the leading `ref` is the env
  // boxed as vader_box_t. The wrapper takes `void* env`, boxes it, and
  // invokes the underlying lifted fn. The `make_closure` op grabs the
  // wrapper's address at allocation time.
  for (const [fnIndex, _typeIndex] of closureMap) {
    const fn = ctx.module.functions[fnIndex]!;
    const cname = ctx.fnNames[fnIndex]!;
    if (fn.signature.params.length === 0) {
      // Defensive — a lifted fn always has at least the env param.
      continue;
    }
    // Skip the env param at index 0; the rest mirror the original lambda's params.
    const tailParams = fn.signature.params.slice(1).map((p, j) => `${cTypeForValBare(p)} a${j}`);
    const tailArgs = fn.signature.params.slice(1).map((_, j) => `a${j}`).join(", ");
    const cret = fn.signature.result === "void" ? "void" : cTypeForValBare(fn.signature.result);
    const head = tailParams.length === 0 ? "void* env" : `void* env, ${tailParams.join(", ")}`;
    out.push(`static ${cret} vader_fn_lift_${fnIndex}(${head}) {`);
    // Box raw env back into the vader_box_t shape the lifted fn expects.
    // The BcFn type index of the env doesn't matter to the lifted fn body —
    // only the raw obj pointer is dereferenced via struct.get on the env
    // struct's fields. Tag 0 is reserved for null and is harmless here.
    out.push(`    vader_box_t env_box; env_box.tag = 0u; env_box._pad = 0u; env_box.payload.obj = env;`);
    const callArgs = tailArgs.length === 0 ? `env_box` : `env_box, ${tailArgs}`;
    if (fn.signature.result === "void") {
      out.push(`    ${cname}(${callArgs});`);
    } else {
      out.push(`    return ${cname}(${callArgs});`);
    }
    out.push(`}`);
  }
  out.push(``);
}

// =========================================================================
// Import shims
// =========================================================================

function emitImportShims(ctx: EmitCtx, out: string[]): void {
  for (let i = 0; i < ctx.module.imports.length; i++) {
    const imp = ctx.module.imports[i]!;
    const shim = importShim(ctx, imp, i);
    if (shim !== null) out.push(shim);
  }
  out.push(``);
}

function importShim(ctx: EmitCtx, imp: BcImport, idx: number): string | null {
  const name = `vader_import_${idx}`;
  const params = imp.signature.params.map((vt, j) => `${cTypeForVal(ctx, vt)} a${j}`).join(", ");
  const ret = cTypeForVal(ctx, imp.signature.result);
  const head = `static ${ret} ${name}(${params || "void"})`;

  // Built-in std/io routes — implemented by the runtime.
  switch (imp.mangledName) {
    case "std_io$print":
      return `${head} { vader_print(a0); }`;
    case "std_io$println":
      return `${head} { vader_println(a0); }`;
    case "std_io$eprint":
      return `${head} { vader_eprint(a0); }`;
    case "std_io$eprintln":
      return `${head} { vader_eprintln(a0); }`;
    case "std_io$exists":
      return `${head} { return vader_exists(a0); }`;
    case "std_io$read_file":
      return `${head} { return vader_read_file(a0, ${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$write_file":
      return `${head} { return vader_write_file(a0, a1, 0u, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$read_line":
      return `${head} { return vader_read_line(${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;

    case "std_string$len":         return `${head} { return vader_string_len(a0); }`;
    case "std_string$slice":       return `${head} { return vader_string_slice(a0, a1, a2); }`;
    case "std_string$contains":    return `${head} { return vader_string_contains(a0, a1); }`;
    case "std_string$starts_with": return `${head} { return vader_string_starts_with(a0, a1); }`;
    case "std_string$ends_with":   return `${head} { return vader_string_ends_with(a0, a1); }`;
    case "std_string$trim":        return `${head} { return vader_string_trim(a0); }`;
    case "std_string$to_upper":    return `${head} { return vader_string_to_upper(a0); }`;
    case "std_string$to_lower":    return `${head} { return vader_string_to_lower(a0); }`;
    case "std_string$char_at":
      return `${head} { return vader_string_char_at(a0, a1); }`;
    case "std_string$split": {
      const strIdx = ctx.stringTagIndex;
      if (strIdx < 0) return `${head} { vader_trap("split: no string type"); }`;
      const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
      if (arrIdx < 0) return `${head} { vader_trap("split: no [string] type"); }`;
      return `${head} { return vader_box_obj(${arrIdx}u, vader_string_split(a0, a1, ${arrIdx}u, ${strIdx}u)); }`;
    }
    case "std_string$parse_int":
      return `${head} { return vader_string_parse_int(a0, ${primTagOrTrap(ctx, "i32")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_string$parse_float":
      return `${head} { return vader_string_parse_float(a0, ${primTagOrTrap(ctx, "f64")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_core$hash_string":
      return `${head} { return vader_string_hash(a0); }`;
    case "std_string_builder$concat_all":
      return `${head} { return vader_string_concat_all((vader_array_t*) a0.payload.obj); }`;

    case "std_runtime$collect":      return `${head} { vader_gc_collect(); }`;
    case "std_runtime$collections":  return `${head} { return (int32_t) vader_gc_get_stats().total_collections; }`;
    case "std_runtime$bytes_used":   return `${head} { return (int32_t) vader_gc_get_stats().bytes_used; }`;
    case "std_runtime$bytes_copied": return `${head} { return (int32_t) vader_gc_get_stats().total_copied; }`;

    case "std_math$sqrt":  return `${head} { return vader_math_sqrt(a0); }`;
    case "std_math$pow":   return `${head} { return vader_math_pow(a0, a1); }`;
    case "std_math$floor": return `${head} { return vader_math_floor(a0); }`;
    case "std_math$ceil":  return `${head} { return vader_math_ceil(a0); }`;
    case "std_math$round": return `${head} { return vader_math_round(a0); }`;
    case "std_math$sin":   return `${head} { return vader_math_sin(a0); }`;
    case "std_math$cos":   return `${head} { return vader_math_cos(a0); }`;
    case "std_math$tan":   return `${head} { return vader_math_tan(a0); }`;

    case "std_process$spawn_run":
      return `${head} { return vader_spawn_run((vader_array_t*) a0.payload.obj); }`;
    case "std_process$spawn_last_stdout":
      return `${head} { return vader_spawn_last_stdout(); }`;
    case "std_process$spawn_last_stderr":
      return `${head} { return vader_spawn_last_stderr(); }`;

    default:
      // Foreign imports — emit a stub that traps, the user supplies linkage
      // via `cc <user>.o` post-MVP.
      return `${head} { vader_trap("unbound import: ${imp.mangledName}"); }`;
  }
}

function tagOrTrap(ctx: EmitCtx, kind: "string" | "error"): string {
  const idx = kind === "string" ? ctx.stringTagIndex : ctx.errorTagIndex;
  if (idx < 0) return `0u /* ${kind} tag absent */`;
  return `${idx}u`;
}

/** Primitive-type tag lookup for runtime calls that must box their result with
 *  the user-visible type's BcType index (e.g. `parse_int` boxing as `i32` so
 *  `match r { is i32 -> ... }` succeeds). */
function primTagOrTrap(ctx: EmitCtx, val: ValType): string {
  const idx = ctx.primitiveTagOf.get(val);
  if (idx === undefined) return `0u /* ${val} tag absent */`;
  return `${idx}u`;
}

// =========================================================================
// Function bodies
// =========================================================================

function emitFunctions(ctx: EmitCtx, out: string[]): void {
  for (let i = 0; i < ctx.module.functions.length; i++) {
    emitFunctionBody(ctx, ctx.module.functions[i]!, i, out);
    out.push(``);
  }
}

function emitFunctionBody(ctx: EmitCtx, fn: BcFunction, _fnIndex: number, out: string[]): void {
  out.push(`static ${signatureFor(ctx, fn)} {`);

  // Collect addresses of every ref-typed slot that needs to be a GC root —
  // the C emit takes their `&` to pin them on the C stack and chains the
  // resulting array through the shadow stack frame. Ref-typed *tmps* are
  // gathered during body emission (via `state.refTmpIndices`); locals,
  // params and block-result slots are known up front.
  const rootAddrs: string[] = [];

  for (let i = 0; i < fn.signature.params.length; i++) {
    if (isRefVal(fn.signature.params[i]!)) rootAddrs.push(`&l${i}`);
  }

  // Declare local slots (params already declared in the signature). `void`
  // slots are runtime-meaningless placeholders the lowerer uses to thread
  // block-trailing exprs past `defer`s; we skip emitting a real variable and
  // make local.{get,set,tee} on those slots be no-ops at the op-level.
  for (let i = 0; i < fn.locals.length; i++) {
    const slot = fn.signature.params.length + i;
    const local = fn.locals[i]!;
    if (local.val === "void") continue;
    out.push(`    ${cTypeForVal(ctx, local.val)} l${slot} = ${zeroInit(ctx, local.val)};`);
    if (isRefVal(local.val)) rootAddrs.push(`&l${slot}`);
  }

  // Per-op tmp vars: every push allocates a fresh `tN`. The stack tracks
  // `{ name, val }` so we know how to coerce when crossing slot boundaries.
  const state: FnState = {
    fn, ctx,
    stack: [],
    tmpCounter: 0,
    out,
    indent: "    ",
    labels: precomputeLabels(fn),
    scopeStack: [],
    refTmpIndices: [],
  };

  // Pre-declare every block result tmp so jumps can assign without scope
  // gymnastics. We do this by walking the labels table.
  for (const l of state.labels.openInfo) {
    if (l !== null && l.resultType !== "void") {
      out.push(`    ${cTypeForVal(ctx, l.resultType)} blockres_${l.openIp} = ${zeroInit(ctx, l.resultType)};`);
      if (isRefVal(l.resultType)) rootAddrs.push(`&blockres_${l.openIp}`);
    }
  }

  // Reserve a position for the ref-tmp pre-declarations and the frame setup.
  // We splice these in after the body is emitted (when `refTmpIndices` and
  // `tmpCounter` are final).
  const preludePos = out.length;

  for (let ip = 0; ip < fn.body.length; ip++) {
    const op = fn.body[ip]!;
    emitOp(state, ip, op);
  }

  // Build prelude: ref-tmp declarations + gc_roots + frame push. Even when
  // the function has no ref slots we still push a frame so `emitReturn` can
  // unconditionally pop without a runtime check; the cost is two memory ops
  // per call, which the C compiler usually folds away.
  const prelude: string[] = [];
  for (const idx of state.refTmpIndices) {
    prelude.push(`    vader_box_t t${idx} = vader_box_null();`);
    rootAddrs.push(`&t${idx}`);
  }
  if (rootAddrs.length > 0) {
    prelude.push(`    vader_box_t* gc_roots[${rootAddrs.length}] = { ${rootAddrs.join(", ")} };`);
  }
  const rootsExpr = rootAddrs.length > 0 ? `gc_roots` : `NULL`;
  prelude.push(`    vader_gc_frame_t gc_frame = { vader_gc_top, ${rootAddrs.length}u, 0u, ${rootsExpr} };`);
  prelude.push(`    vader_gc_top = &gc_frame;`);

  // Defensive pop on fall-through: if the body falls past its last op without
  // an explicit return (void fn with implicit end), restore the caller's
  // frame before returning. Explicit returns (`emitReturn`) pop before
  // issuing `return`, so this line is dead in those paths.
  out.push(`    vader_gc_top = gc_frame.prev;`);

  out.splice(preludePos, 0, ...prelude);

  out.push(`}`);
}

function isRefVal(v: ValType): boolean {
  return v === "ref" || v === "any";
}

// ------------------------------------------------------------- per-fn state

interface FnState {
  readonly fn: BcFunction;
  readonly ctx: EmitCtx;
  readonly stack: { name: string; val: ValType }[];
  tmpCounter: number;
  readonly out: string[];
  indent: string;
  readonly labels: LabelTable;
  readonly scopeStack: ActiveScope[];
  /** tmp indices that hold ref-typed values — pre-declared in the function
   *  prelude and registered as GC roots via the shadow stack frame. */
  readonly refTmpIndices: number[];
}

interface OpenLabel {
  readonly openIp: number;
  readonly endIp: number;
  readonly elseIp: number;     // -1 if none
  readonly kind: "block" | "loop" | "if";
  readonly resultType: ValType;
}

/** Mutable runtime view of an `OpenLabel` while emit walks its body. The
 *  `unreachable` flag flips on after a `(br|return|unreachable)` op — tells
 *  `else`/`end` to skip the result-pop since the stack past that point is
 *  polymorphic per WASM semantics. Reset by `else` (the else branch starts
 *  reachable again). */
interface ActiveScope extends OpenLabel {
  unreachable: boolean;
}

interface LabelTable {
  readonly openInfo: readonly (OpenLabel | null)[];   // one entry per ip
  readonly endOf:    ReadonlyMap<number, number>;
  readonly elseOf:   ReadonlyMap<number, number>;
  readonly endOfElse: ReadonlyMap<number, number>;
}

function precomputeLabels(fn: BcFunction): LabelTable {
  const openInfo: (OpenLabel | null)[] = new Array(fn.body.length).fill(null);
  const endOf = new Map<number, number>();
  const elseOf = new Map<number, number>();
  const endOfElse = new Map<number, number>();
  type Stk = { openIp: number; kind: "block" | "loop" | "if"; resultType: ValType; elseIp: number };
  const stk: Stk[] = [];
  for (let i = 0; i < fn.body.length; i++) {
    const op = fn.body[i]!;
    if (op.kind === "block" || op.kind === "loop" || op.kind === "if") {
      stk.push({ openIp: i, kind: op.kind, resultType: op.result, elseIp: -1 });
    } else if (op.kind === "else") {
      const top = stk[stk.length - 1];
      if (top !== undefined) { top.elseIp = i; elseOf.set(top.openIp, i); }
    } else if (op.kind === "end") {
      const top = stk.pop();
      if (top !== undefined) {
        endOf.set(top.openIp, i);
        if (top.elseIp >= 0) endOfElse.set(top.elseIp, i);
        openInfo[top.openIp] = { openIp: top.openIp, endIp: i, elseIp: top.elseIp,
                                  kind: top.kind, resultType: top.resultType };
      }
    }
  }
  return { openInfo, endOf, elseOf, endOfElse };
}

// ------------------------------------------------------------- op dispatch

function emitOp(s: FnState, ip: number, op: Op): void {
  const k = op.kind;
  switch (k) {
    case "drop":     s.stack.pop(); return;
    case "dup": {
      const top = peek(s); s.stack.push({ name: top.name, val: top.val }); return;
    }

    case "local.get": {
      const val = slotValType(s, op.slot);
      if (val === "void") return;       // void slots: no real storage, no push
      const t = newTmp(s, val);
      line(s, `${decl(s, val, t)} = l${op.slot};`);
      return;
    }
    case "local.set": {
      const slotVal = slotValType(s, op.slot);
      if (slotVal === "void") return;   // void slots: nothing on the stack to consume
      const v = pop(s);
      line(s, `l${op.slot} = ${coerce(s, v.name, v.val, slotVal)};`);
      return;
    }
    case "local.tee": {
      const slotVal = slotValType(s, op.slot);
      if (slotVal === "void") return;
      const v = pop(s);
      line(s, `l${op.slot} = ${coerce(s, v.name, v.val, slotVal)};`);
      // Re-push a fresh tmp typed as the slot. Critical when the source is a
      // boxed value (`any`/`ref`) but the slot is a primitive — peeking would
      // leave the box on the stack and break downstream typed ops.
      const t = newTmp(s, slotVal);
      line(s, `${decl(s, slotVal, t)} = l${op.slot};`);
      return;
    }

    case "i32.const":    return pushLit(s, "i32", i32LitC(op.value));
    case "i64.const":    return pushLit(s, "i64", i64LitC(op.value));
    case "f32.const":    return pushLit(s, "f32", floatLit(op.value, "f"));
    case "f64.const":    return pushLit(s, "f64", floatLit(op.value, ""));
    case "bool.const":   return pushLit(s, "bool", op.value ? "true" : "false");
    case "char.const":   return pushLit(s, "char", `${op.value}u`);
    case "null.const": {
      // Tag the null literal with the `null` primitive's BcType index when
      // it's available — keeps `type_check` semantics consistent across
      // boxed and unboxed paths.
      const tag = s.ctx.primitiveTagOf.get("null") ?? 0;
      return pushLit(s, "any", `vader_box_obj(${tag}u, NULL)`);
    }
    case "string.const": {
      const t = newTmp(s, "string");
      line(s, `vader_string_t ${t} = vader_string_new(vader_str_${op.index}_data, vader_str_${op.index}_len);`);
      return;
    }

    case "bool.and":   return pushBinop(s, "bool", "&&", "bool");
    case "bool.or":    return pushBinop(s, "bool", "||", "bool");
    case "bool.not":   return pushUnop(s, "bool", "!", "bool");

    case "string.concat": return pushFnCall2(s, "string", "vader_string_concat");
    case "string.eq":  return pushFnCall2(s, "bool", "vader_string_eq");
    case "string.ne": {
      const r = pop(s); const l = pop(s);
      const t = newTmp(s, "bool");
      line(s, `bool ${t} = !vader_string_eq(${l.name}, ${r.name});`);
      return;
    }
    case "char.eq":    return pushBinop(s, "char", "==", "bool");
    case "char.ne":    return pushBinop(s, "char", "!=", "bool");
    case "char.lt":    return pushBinop(s, "char", "<",  "bool");
    case "char.le":    return pushBinop(s, "char", "<=", "bool");
    case "char.gt":    return pushBinop(s, "char", ">",  "bool");
    case "char.ge":    return pushBinop(s, "char", ">=", "bool");
    case "bool.eq":    return pushBinop(s, "bool", "==", "bool");
    case "bool.ne":    return pushBinop(s, "bool", "!=", "bool");
    case "ref.eq":     return pushBinopAny(s, "==", "bool");
    case "ref.ne":     return pushBinopAny(s, "!=", "bool");

    case "block":
    case "loop":
    case "if":         return emitOpenScope(s, ip, op);
    case "else":       return emitElse(s, ip);
    case "end":        return emitEnd(s, ip);
    case "br":         return emitBr(s, ip, op.depth, /*conditional*/ false);
    case "br_if":      return emitBr(s, ip, op.depth, /*conditional*/ true);
    case "return":     return emitReturn(s);
    case "unreachable":
      line(s, `vader_unreachable("${escapeC(s.fn.name)}+${ip}");`);
      markUnreachable(s);
      return;

    case "call":         return emitCall(s, op);
    case "call.import":  return emitCallImport(s, op);
    case "call.indirect":return emitCallIndirect(s, op);
    case "virtual.call": return emitVirtualCall(s, op);
    case "fn.ref":       return emitFnRef(s, op);
    case "make_closure": return emitMakeClosure(s, op);
    case "intrinsic":    return emitIntrinsic(s, op);

    case "struct.new":   return emitStructNew(s, op);
    case "struct.get":   return emitStructGet(s, op);
    case "struct.set":   return emitStructSet(s, op);

    case "array.new":    return emitArrayNew(s, op);
    case "array.get":    return emitArrayGet(s, op);
    case "array.set":    return emitArraySet(s, op);
    case "array.len": {
      const arr = pop(s);
      const t = newTmp(s, "i32");
      line(s, `int32_t ${t} = (int32_t) vader_array_len((vader_array_t*) ${asObjPtr(arr)});`);
      return;
    }
    case "array.push": {
      const value = pop(s);
      const arr = pop(s);
      line(s, `vader_array_push((vader_array_t*) ${asObjPtr(arr)}, ${boxExpr(s.ctx, value.name, value.val, op.typeIndex)});`);
      return;
    }

    case "type_check":   return emitTypeCheck(s, op);
    case "ref.cast":     return emitRefCast(s, op);
  }

  // Templated typed numeric ops: <type>.<verb> or <type>.to_<type>
  emitNumericOp(s, k);
}

// ------------------------------------------------------------- structured control

function emitOpenScope(s: FnState, ip: number, op: Op): void {
  const info = labelOf(s, ip);
  if (info !== null) s.scopeStack.push({ ...info, unreachable: false });
  if (op.kind === "if") {
    const cond = pop(s);
    line(s, `if (${cond.name}) {`);
    s.indent += "    ";
    return;
  }
  if (op.kind === "loop") {
    line(s, `loop_${ip}: {`);
    s.indent += "    ";
    return;
  }
  if (op.kind === "block") {
    line(s, `{`);
    s.indent += "    ";
    return;
  }
}

function emitElse(s: FnState, ip: number): void {
  // Close the then-branch's resultPush, then open else. If the then-branch
  // ended unreachable, `blockres_X` keeps its zeroInit value — control never
  // reaches it (polymorphic-stack invariant).
  const info = scopeForElseEnd(s, ip);
  const top = s.scopeStack.at(-1);
  const wasUnreachable = top?.unreachable ?? false;
  if (info !== null && info.resultType !== "void" && !wasUnreachable && s.stack.length > 0) {
    const v = pop(s);
    line(s, `blockres_${info.openIp} = ${coerce(s, v.name, v.val, info.resultType)};`);
  }
  if (top !== undefined) top.unreachable = false;     // else branch is reachable
  popIndent(s);
  line(s, `} else { /* else */`);
  s.indent += "    ";
}

function emitEnd(s: FnState, ip: number): void {
  const info = scopeForEnd(s, ip);
  const top = s.scopeStack.at(-1);
  const wasUnreachable = top?.unreachable ?? false;
  if (info !== null && info.resultType !== "void" && !wasUnreachable && s.stack.length > 0) {
    const v = pop(s);
    line(s, `blockres_${info.openIp} = ${coerce(s, v.name, v.val, info.resultType)};`);
  }
  popIndent(s);
  if (info !== null) {
    line(s, `} end_${info.openIp}: ;`);
    s.scopeStack.pop();
    if (info.resultType !== "void") {
      const t = newTmp(s, info.resultType);
      line(s, `${decl(s, info.resultType, t)} = blockres_${info.openIp};`);
    }
  } else {
    line(s, `}`);
  }
}

function markUnreachable(s: FnState): void {
  const top = s.scopeStack.at(-1);
  if (top !== undefined) top.unreachable = true;
}

function emitBr(s: FnState, _ip: number, depth: number, conditional: boolean): void {
  // Walk the open scopes via the label table — at any point, the active label
  // stack consists of all `OpenLabel`s whose [openIp, endIp) range contains
  // the current ip. We can rebuild it by counting active scopes.
  const active = activeScopes(s);
  const idx = active.length - 1 - depth;
  if (idx < 0) { line(s, `/* br depth ${depth} out of range */`); return; }
  const target = active[idx]!;
  // Loop targets jump back to the loop start (continue); block/if jump past end.
  const dest = target.kind === "loop" ? `loop_${target.openIp}` : `end_${target.openIp}`;

  const condGuard = (body: string) => conditional
    ? `if (${pop(s).name}) { ${body} }`
    : body;

  // Block/if branch with a result: hoist top-of-stack into the block's result
  // before jumping. WASM verifier guarantees the type matches.
  if (target.kind !== "loop" && target.resultType !== "void" && s.stack.length > 0) {
    const v = peek(s);
    line(s, condGuard(`blockres_${target.openIp} = ${coerce(s, v.name, v.val, target.resultType)}; goto ${dest};`));
  } else {
    line(s, condGuard(`goto ${dest};`));
  }
  // Unconditional `br` makes the rest of the enclosing scope unreachable —
  // tells `else`/`end` not to pop a stale top-of-stack as the result.
  if (!conditional) markUnreachable(s);
}

function activeScopes(s: FnState): OpenLabel[] {
  return s.scopeStack;
}

function emitReturn(s: FnState): void {
  // Pop the shadow-stack frame first, then return. For non-void returns we
  // capture the value into a tmp before popping (the expression may read from
  // frame-pinned locals — capturing a snapshot makes the order safe).
  if (s.fn.signature.result === "void") {
    line(s, `{ vader_gc_top = gc_frame.prev; return; }`);
  } else {
    const v = pop(s);
    const ret = coerce(s, v.name, v.val, s.fn.signature.result);
    const cret = cTypeForVal(s.ctx, s.fn.signature.result);
    line(s, `{ ${cret} __vret = ${ret}; vader_gc_top = gc_frame.prev; return __vret; }`);
  }
  markUnreachable(s);
}

// ------------------------------------------------------------- calls

function emitCall(s: FnState, op: Extract<Op, { kind: "call" }>): void {
  const callee = s.ctx.module.functions[op.fnIndex]!;
  const args: string[] = [];
  for (let i = callee.signature.params.length - 1; i >= 0; i--) {
    const v = pop(s);
    args.unshift(coerce(s, v.name, v.val, callee.signature.params[i]!));
  }
  if (callee.signature.result === "void") {
    line(s, `${s.ctx.fnNames[op.fnIndex]!}(${args.join(", ")});`);
  } else {
    const t = newTmp(s, callee.signature.result);
    line(s, `${decl(s, callee.signature.result, t)} = ${s.ctx.fnNames[op.fnIndex]!}(${args.join(", ")});`);
  }
}

function emitCallImport(s: FnState, op: Extract<Op, { kind: "call.import" }>): void {
  const imp = s.ctx.module.imports[op.importIndex]!;
  const args: string[] = [];
  for (let i = imp.signature.params.length - 1; i >= 0; i--) {
    const v = pop(s);
    args.unshift(coerce(s, v.name, v.val, imp.signature.params[i]!));
  }
  const callee = `vader_import_${op.importIndex}`;
  if (imp.signature.result === "void") {
    line(s, `${callee}(${args.join(", ")});`);
  } else {
    const t = newTmp(s, imp.signature.result);
    line(s, `${decl(s, imp.signature.result, t)} = ${callee}(${args.join(", ")});`);
  }
}

function emitFnRef(s: FnState, op: Extract<Op, { kind: "fn.ref" }>): void {
  const tmp = newTmp(s, "ref");
  line(s, `${decl(s, "ref", tmp)} = vader_box_obj(${op.typeIndex}u, &vader_fn_static_${op.fnIndex});`);
}

function emitVirtualCall(s: FnState, op: Extract<Op, { kind: "virtual.call" }>): void {
  // Stack at entry: …args, receiver. Pop receiver first, then args (reverse
  // order); the dispatch helper takes (receiver, ...args) in source order.
  const recv = pop(s);
  const recvBoxed = coerce(s, recv.name, recv.val, "any");
  const tailCount = op.paramCount - 1;
  const args: string[] = [];
  for (let i = 0; i < tailCount; i++) args.push(pop(s).name);
  args.reverse();

  const helper = vtableHelperName(op.vtableKey);
  const sig = vtableSignatures(s.ctx).get(op.vtableKey);
  if (sig === undefined) {
    line(s, `vader_unreachable("no vtable for ${escapeC(op.vtableKey)}");`);
    return;
  }
  if (sig.result === "void") {
    line(s, `${helper}(${[recvBoxed, ...args].join(", ")});`);
    return;
  }
  const tmp = newTmp(s, sig.result);
  line(s, `${decl(s, sig.result, tmp)} = ${helper}(${[recvBoxed, ...args].join(", ")});`);
}

function vtableHelperName(key: string): string {
  return `vader_vt_${sanitise(key.replace(".", "__"))}`;
}

/** Per-vtable canonical signature, derived from the first impl fn in each
 *  table. All impls of a given trait method share their non-receiver param
 *  types (the receiver is taken as `any`/`vader_box_t` in the dispatcher). */
function vtableSignatures(ctx: EmitCtx): ReadonlyMap<string, BcSignature> {
  const out = new Map<string, BcSignature>();
  for (const [key, table] of ctx.module.vtables) {
    const firstFnIdx = table.values().next().value;
    if (firstFnIdx === undefined) continue;
    const fn = ctx.module.functions[firstFnIdx];
    if (fn === undefined) continue;
    out.set(key, fn.signature);
  }
  return out;
}

/** Forward-declare every vtable dispatcher up front so user fns that call
 *  them compile before the dispatcher bodies are emitted. */
function emitVtableForwardDecls(ctx: EmitCtx, out: string[]): void {
  if (ctx.module.vtables.size === 0) return;
  out.push(``);
  out.push(`/* ----------------------------------------------- vtable forwards */`);
  for (const [key, table] of ctx.module.vtables) {
    const firstFnIdx = table.values().next().value;
    if (firstFnIdx === undefined) continue;
    const sig = ctx.module.functions[firstFnIdx]!.signature;
    const tailParams = sig.params.slice(1);
    const formal = tailParams.length > 0
      ? `vader_box_t recv, ${tailParams.map((t, i) => `${cTypeForVal(ctx, t)} a${i}`).join(", ")}`
      : `vader_box_t recv`;
    out.push(`static ${cTypeForVal(ctx, sig.result)} ${vtableHelperName(key)}(${formal});`);
  }
}

/** Emit one dispatch helper per (trait, method) entry: `static <ret>
 *  vader_vt_<key>(vader_box_t recv, <args>)` whose body switches on
 *  `recv.tag` and forwards to the matching impl fn. The unbox-and-cast
 *  per case mirrors what the cascade used to do inline at every call site,
 *  but consolidated to one fn per vtable key. */
function emitVtableDispatchers(ctx: EmitCtx, out: string[]): void {
  if (ctx.module.vtables.size === 0) return;
  out.push(``);
  out.push(`/* ----------------------------------------------- vtable dispatchers */`);
  for (const [key, table] of ctx.module.vtables) {
    const firstFnIdx = table.values().next().value;
    if (firstFnIdx === undefined) continue;
    const sig = ctx.module.functions[firstFnIdx]!.signature;
    const helper = vtableHelperName(key);
    const tailParams = sig.params.slice(1);
    const tailParamDecls = tailParams.map((t, i) => `${cTypeForVal(ctx, t)} a${i}`).join(", ");
    const formal = tailParams.length > 0
      ? `vader_box_t recv, ${tailParamDecls}`
      : `vader_box_t recv`;
    const cret = cTypeForVal(ctx, sig.result);
    out.push(`static ${cret} ${helper}(${formal}) {`);
    out.push(`    switch (recv.tag) {`);
    for (const [tag, fnIdx] of table) {
      const calleeName = ctx.fnNames[fnIdx]!;
      const calleeSig = ctx.module.functions[fnIdx]!.signature;
      const recvParam = calleeSig.params[0]!;
      const recvCArg = coerceExpr(ctx, "recv", "any", recvParam);
      const allArgs = [recvCArg, ...tailParams.map((_, i) => `a${i}`)].join(", ");
      if (sig.result === "void") {
        out.push(`        case ${tag}u: ${calleeName}(${allArgs}); return;`);
      } else {
        out.push(`        case ${tag}u: return ${calleeName}(${allArgs});`);
      }
    }
    out.push(`        default: vader_unreachable("vtable miss in ${escapeC(key)}");`);
    out.push(`    }`);
    if (sig.result !== "void") {
      // Defensive: every path in the switch returns or traps, but C wants a
      // post-switch return for non-void. `vader_unreachable` is noreturn.
      out.push(`    vader_unreachable("vtable miss in ${escapeC(key)}");`);
    }
    out.push(`}`);
  }
}

function emitMakeClosure(s: FnState, op: Extract<Op, { kind: "make_closure" }>): void {
  // Pop env (a vader_box_t whose payload.obj is the env struct), allocate a
  // fresh vader_fn_t, set code = lifted-fn wrapper + env = the env ptr,
  // and box the result with the closure's BcFn type tag.
  const envBox = pop(s);
  const tmp = newTmp(s, "ref");
  const fnObj = `closure_${s.tmpCounter++}`;
  line(s, `vader_fn_t* ${fnObj} = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));`);
  line(s, `vader_obj_header_init(${fnObj}, ${op.typeIndex}u);`);
  line(s, `${fnObj}->code = (void*) &vader_fn_lift_${op.fnIndex};`);
  line(s, `${fnObj}->env = ${envBox.name}.payload.obj;`);
  line(s, `${decl(s, "ref", tmp)} = vader_box_obj(${op.typeIndex}u, ${fnObj});`);
}

function emitCallIndirect(s: FnState, op: Extract<Op, { kind: "call.indirect" }>): void {
  const t = s.ctx.module.types[op.typeIndex];
  if (t === undefined || t.kind !== "fn") {
    line(s, `vader_unreachable("call.indirect on non-fn type");`);
    return;
  }
  // Stack order (WASM convention): args... then fn ref on top.
  const fnVal = pop(s);
  const args: string[] = [];
  for (let i = t.params.length - 1; i >= 0; i--) {
    const v = pop(s);
    const expectedVal = valTypeOfBcType(s.ctx.module.types[t.params[i]!]!);
    args.unshift(coerce(s, v.name, v.val, expectedVal));
  }
  const retVal = valTypeOfBcType(s.ctx.module.types[t.returnType]!);
  const fnObj = `fnobj_${s.tmpCounter++}`;
  line(s, `vader_fn_t* ${fnObj} = (vader_fn_t*) ${fnVal.name}.payload.obj;`);
  const callArgs = args.length === 0 ? `${fnObj}->env` : `${fnObj}->env, ${args.join(", ")}`;
  const call = `((vader_fn_sig_${op.typeIndex}_t) ${fnObj}->code)(${callArgs})`;
  if (retVal === "void") {
    line(s, `${call};`);
  } else {
    const tmp = newTmp(s, retVal);
    line(s, `${decl(s, retVal, tmp)} = ${call};`);
  }
}

function emitIntrinsic(s: FnState, op: Extract<Op, { kind: "intrinsic" }>): void {
  switch (op.id) {
    case INTRINSIC_TABLE.builderNew.id: {
      const t = newTmp(s, "any");
      line(s, `${t}.tag = 0; ${t}._pad = 0; ${t}.payload.obj = vader_builder_new();`);
      return;
    }
    case INTRINSIC_TABLE.builderAppendStr.id: {
      const str = pop(s);
      const sb = pop(s);
      line(s, `vader_builder_append_str((vader_builder_t*) ${sb.name}.payload.obj, ${str.name});`);
      return;
    }
    case INTRINSIC_TABLE.builderAppendDisplay.id: {
      const v = pop(s);
      const sb = pop(s);
      const fn = displayFnFor(v.val);
      const arg = displayCoerce(v.name, v.val);
      line(s, `${fn}((vader_builder_t*) ${sb.name}.payload.obj, ${arg});`);
      return;
    }
    case INTRINSIC_TABLE.builderFinish.id: {
      const sb = pop(s);
      const t = newTmp(s, "string");
      line(s, `vader_string_t ${t} = vader_builder_finish((vader_builder_t*) ${sb.name}.payload.obj);`);
      return;
    }
  }
}

function displayFnFor(v: ValType): string {
  switch (v) {
    case "i8": case "i16": case "i32":  return "vader_builder_append_display_i32";
    case "u8": case "u16": case "u32":  return "vader_builder_append_display_u32";
    case "i64":   return "vader_builder_append_display_i64";
    case "u64": case "usize": return "vader_builder_append_display_u64";
    case "f32":   return "vader_builder_append_display_f32";
    case "f64":   return "vader_builder_append_display_f64";
    case "bool":  return "vader_builder_append_display_bool";
    case "char":  return "vader_builder_append_display_char";
    case "string":return "vader_builder_append_display_string";
    default:      return "vader_builder_append_display_string";   // fallback — caller stringifies
  }
}

function displayCoerce(name: string, v: ValType): string {
  if (v === "i8" || v === "i16") return `(int32_t) ${name}`;
  if (v === "u8" || v === "u16") return `(uint32_t) ${name}`;
  return name;
}

// ------------------------------------------------------------- struct / array

function emitStructNew(s: FnState, op: Extract<Op, { kind: "struct.new" }>): void {
  const t = s.ctx.module.types[op.typeIndex]!;
  if (t.kind !== "struct") return;
  const cname = s.ctx.structNames[op.typeIndex]!;
  // Pop fields right-to-left.
  const fieldVals: { name: string; val: ValType }[] = [];
  for (let i = t.fields.length - 1; i >= 0; i--) fieldVals.unshift(pop(s));
  const tmp = newTmp(s, "ref");
  line(s, `${cname}* ${tmp}_obj = (${cname}*) vader_gc_alloc(sizeof(${cname}));`);
  line(s, `vader_obj_header_init(${tmp}_obj, ${op.typeIndex}u);`);
  for (let i = 0; i < t.fields.length; i++) {
    const f = t.fields[i]!;
    const fval = valTypeOfField(s.ctx, f.typeIndex);
    const v = fieldVals[i]!;
    line(s, `${tmp}_obj->f_${sanitise(f.name)} = ${coerce(s, v.name, v.val, fval)};`);
  }
  // Always emit struct values as boxed vader_box_t so they flow uniformly
  // through `ref` slots and across fn boundaries. struct.get unboxes via
  // .payload.obj before downcasting.
  line(s, `${decl(s, "ref", tmp)} = vader_box_obj(${op.typeIndex}u, ${tmp}_obj);`);
}

function emitStructGet(s: FnState, op: Extract<Op, { kind: "struct.get" }>): void {
  const t = s.ctx.module.types[op.typeIndex]!;
  if (t.kind !== "struct") return;
  const cname = s.ctx.structNames[op.typeIndex]!;
  const obj = pop(s);
  const f = t.fields[op.fieldIndex]!;
  const fval = valTypeOfField(s.ctx, f.typeIndex);
  const tmp = newTmp(s, fval);
  line(s, `${decl(s, fval, tmp)} = ((${cname}*) ${asObjPtr(obj)})->f_${sanitise(f.name)};`);
}

function emitStructSet(s: FnState, op: Extract<Op, { kind: "struct.set" }>): void {
  const t = s.ctx.module.types[op.typeIndex]!;
  if (t.kind !== "struct") return;
  const cname = s.ctx.structNames[op.typeIndex]!;
  const value = pop(s);
  const obj = pop(s);
  const f = t.fields[op.fieldIndex]!;
  const fval = valTypeOfField(s.ctx, f.typeIndex);
  line(s, `((${cname}*) ${asObjPtr(obj)})->f_${sanitise(f.name)} = ${coerce(s, value.name, value.val, fval)};`);
}

/** Coerce a stack value holding a heap reference to a `void*`. Boxed values
 *  (vader_box_t) need `.payload.obj`; typed pointer slots (struct/array C
 *  variables) are usable directly. */
function asObjPtr(v: { name: string; val: ValType }): string {
  if (v.val === "ref" || v.val === "any") return `${v.name}.payload.obj`;
  return v.name;
}

function emitArrayNew(s: FnState, op: Extract<Op, { kind: "array.new" }>): void {
  const elements: { name: string; val: ValType }[] = [];
  for (let i = op.length - 1; i >= 0; i--) elements.unshift(pop(s));
  const tmp = newTmp(s, "ref");
  line(s, `vader_array_t* ${tmp}_arr = vader_array_new(${op.typeIndex}u, ${op.length}u);`);
  for (let i = 0; i < op.length; i++) {
    const v = elements[i]!;
    line(s, `${tmp}_arr->buf->slots[${i}] = ${boxExpr(s.ctx, v.name, v.val, op.typeIndex)};`);
  }
  line(s, `${decl(s, "ref", tmp)} = vader_box_obj(${op.typeIndex}u, ${tmp}_arr);`);
}

function emitArrayGet(s: FnState, _op: Extract<Op, { kind: "array.get" }>): void {
  const idx = pop(s);
  const arr = pop(s);
  const tmp = newTmp(s, "any");
  line(s, `${decl(s, "any", tmp)} = vader_array_get((vader_array_t*) ${asObjPtr(arr)}, (size_t) ${idx.name});`);
}

function emitArraySet(s: FnState, op: Extract<Op, { kind: "array.set" }>): void {
  const value = pop(s);
  const idx = pop(s);
  const arr = pop(s);
  line(s, `vader_array_set((vader_array_t*) ${asObjPtr(arr)}, (size_t) ${idx.name}, ${boxExpr(s.ctx, value.name, value.val, op.typeIndex)});`);
}

function emitTypeCheck(s: FnState, op: Extract<Op, { kind: "type_check" }>): void {
  const v = pop(s);
  const tmp = newTmp(s, "bool");
  // The value's static `val` tells us whether we're testing a boxed slot or
  // a primitively-typed one. For boxed values we compare tags; for primitives
  // we compare the slot's static type against the target tag.
  if (v.val === "ref" || v.val === "any") {
    const targetType = s.ctx.module.types[op.typeIndex];
    // For trait references, check whether the value's tag corresponds to any
    // struct that implements the trait (using the module's impl table).
    // Also always include a direct tag comparison against op.typeIndex itself:
    // built-in ref types like Error are tagged with their own type index.
    if (targetType?.kind === "ref" && targetType.traitName !== null) {
      const cond = traitCheckExpr(s.ctx, v.name, targetType.traitName, op.typeIndex);
      line(s, `bool ${tmp} = ${cond};`);
    } else {
      line(s, `bool ${tmp} = (${v.name}.tag == ${op.typeIndex}u);`);
    }
  } else {
    // Primitive slot can only match if its static ValType corresponds to the
    // target type's primitive (or struct/array typeIndex matches).
    line(s, `bool ${tmp} = ${primitiveMatchesType(s.ctx, v.val, op.typeIndex) ? "true" : "false"};`);
  }
}

/** Build the C boolean expression that checks whether `vName` (a `vader_box_t`)
 *  has a tag corresponding to any struct implementing `traitName`, or is
 *  directly tagged as the trait ref type itself (e.g. built-in Error). */
function traitCheckExpr(ctx: EmitCtx, vName: string, traitName: string, refTypeIndex: number): string {
  const structIdxs = ctx.structIdxsByTrait.get(traitName) ?? [];
  const tags = [refTypeIndex, ...structIdxs];
  return tags.map((idx) => `(${vName}.tag == ${idx}u)`).join(" || ");
}

function emitRefCast(s: FnState, op: Extract<Op, { kind: "ref.cast" }>): void {
  const v = pop(s);
  // Determine target ValType from the type table.
  const target = s.ctx.module.types[op.typeIndex]!;
  const targetVal = valTypeOfBcType(target);
  const tmp = newTmp(s, targetVal);
  if (v.val === "ref" || v.val === "any") {
    line(s, `${decl(s, targetVal, tmp)} = ${unboxExpr(v.name, targetVal)};`);
  } else {
    line(s, `${decl(s, targetVal, tmp)} = (${cTypeForVal(s.ctx, targetVal)}) ${v.name};`);
  }
}

// ------------------------------------------------------------- numeric

function emitNumericOp(s: FnState, kind: string): void {
  // <type>.to_<type> or <type>.<verb>
  const dot = kind.indexOf(".");
  const t = kind.slice(0, dot);
  const verb = kind.slice(dot + 1);
  if (verb.startsWith("to_")) return emitConvert(s, t as ValType, verb.slice(3) as ValType);
  emitTypedBinop(s, t as ValType, verb);
}

function emitConvert(s: FnState, from: ValType, to: ValType): void {
  const v = pop(s);
  const tmp = newTmp(s, to);
  if (from === to) {
    line(s, `${decl(s, to, tmp)} = ${v.name};`);
  } else {
    line(s, `${decl(s, to, tmp)} = (${cTypeForVal(s.ctx, to)}) ${v.name};`);
  }
}

function emitTypedBinop(s: FnState, t: ValType, verb: string): void {
  if (verb === "neg" || verb === "bitnot") {
    const v = pop(s);
    const tmp = newTmp(s, t);
    const op = verb === "neg" ? "-" : "~";
    line(s, `${decl(s, t, tmp)} = ${op}${v.name};`);
    return;
  }
  const r = pop(s);
  const l = pop(s);
  const arith: Record<string, string> = {
    add: "+", sub: "-", mul: "*", div: "/", rem: "%",
    bitand: "&", bitor: "|", bitxor: "^", shl: "<<", shr: ">>",
  };
  const cmp: Record<string, string> = {
    eq: "==", ne: "!=", lt: "<", le: "<=", gt: ">", ge: ">=",
  };
  if (arith[verb]) {
    const tmp = newTmp(s, t);
    line(s, `${decl(s, t, tmp)} = ${l.name} ${arith[verb]} ${r.name};`);
    return;
  }
  if (cmp[verb]) {
    const tmp = newTmp(s, "bool");
    line(s, `${decl(s, "bool", tmp)} = ${l.name} ${cmp[verb]} ${r.name};`);
    return;
  }
  // Unhandled — emit a trap so the failure surfaces at runtime.
  line(s, `vader_unreachable("unhandled op ${kind(t, verb)}");`);
}

function kind(t: ValType, verb: string): string { return `${t}.${verb}`; }

// ------------------------------------------------------------- helpers

function pushBinop(s: FnState, _t: ValType, op: string, resultT: ValType): void {
  const r = pop(s); const l = pop(s);
  const tmp = newTmp(s, resultT);
  line(s, `${decl(s, resultT, tmp)} = ${l.name} ${op} ${r.name};`);
}

function pushBinopAny(s: FnState, op: string, resultT: ValType): void {
  const r = pop(s); const l = pop(s);
  const tmp = newTmp(s, resultT);
  // Box/ref equality: compare object identity for heap kinds. With γ
  // representation, both sides are `void*` if they're refs, so direct compare.
  line(s, `${decl(s, resultT, tmp)} = (${l.name} ${op} ${r.name});`);
}

function pushUnop(s: FnState, _t: ValType, op: string, resultT: ValType): void {
  const v = pop(s);
  const tmp = newTmp(s, resultT);
  line(s, `${decl(s, resultT, tmp)} = ${op}${v.name};`);
}

function pushFnCall2(s: FnState, resultT: ValType, fn: string): void {
  const r = pop(s); const l = pop(s);
  const tmp = newTmp(s, resultT);
  line(s, `${decl(s, resultT, tmp)} = ${fn}(${l.name}, ${r.name});`);
}

function pushLit(s: FnState, t: ValType, lit: string): void {
  const tmp = newTmp(s, t);
  line(s, `${decl(s, t, tmp)} = ${lit};`);
}

function newTmp(s: FnState, val: ValType): string {
  const idx = s.tmpCounter++;
  const name = `t${idx}`;
  s.stack.push({ name, val });
  if (val === "ref" || val === "any") s.refTmpIndices.push(idx);
  return name;
}

/** Tmp declaration prefix. Ref-typed tmps are pre-declared in the prelude
 *  (see `emitFunctionBody`) so they can be `&`-taken into the GC root array;
 *  body emission produces a bare assignment for them. Primitives still get a
 *  fresh `<ctype> name` declaration on first use. */
function decl(s: FnState, val: ValType, name: string): string {
  if (val === "ref" || val === "any") return name;
  return `${cTypeForVal(s.ctx, val)} ${name}`;
}

function pop(s: FnState): { name: string; val: ValType } {
  const v = s.stack.pop();
  if (v === undefined) return { name: "0", val: "i32" };  // defensive — emitter bug
  return v;
}

function peek(s: FnState): { name: string; val: ValType } {
  const v = s.stack[s.stack.length - 1];
  if (v === undefined) return { name: "0", val: "i32" };
  return v;
}

function line(s: FnState, code: string): void { s.out.push(`${s.indent}${code}`); }

function popIndent(s: FnState): void { s.indent = s.indent.slice(4); }

function slotValType(s: FnState, slot: number): ValType {
  if (slot < s.fn.signature.params.length) return s.fn.signature.params[slot]!;
  return s.fn.locals[slot - s.fn.signature.params.length]!.val;
}

function labelOf(s: FnState, ip: number): OpenLabel | null {
  return s.labels.openInfo[ip] ?? null;
}

function scopeForElseEnd(s: FnState, elseIp: number): OpenLabel | null {
  // Find the open scope whose elseIp matches.
  for (const info of s.labels.openInfo) {
    if (info !== null && info.elseIp === elseIp) return info;
  }
  return null;
}

function scopeForEnd(s: FnState, endIp: number): OpenLabel | null {
  for (const info of s.labels.openInfo) {
    if (info !== null && info.endIp === endIp) return info;
  }
  return null;
}

// ------------------------------------------------------------- coercions

function coerce(s: FnState, name: string, from: ValType, to: ValType): string {
  return coerceExpr(s.ctx, name, from, to);
}

/** Pure-expression coerce — no FnState, no `line(s, ...)` side effects.
 *  Used by the per-vtable dispatchers emitted at module scope where there
 *  is no enclosing fn state. */
function coerceExpr(ctx: EmitCtx, name: string, from: ValType, to: ValType): string {
  if (from === to) return name;
  if ((to === "ref" || to === "any") && (from === "ref" || from === "any")) return name;
  if (to === "ref" || to === "any") {
    return boxExprUnknown(ctx, name, from);
  }
  if (from === "ref" || from === "any") {
    return unboxExpr(name, to);
  }
  return `(${cTypeForVal(ctx, to)}) ${name}`;
}

function boxExpr(_ctx: EmitCtx, name: string, val: ValType, typeIndex: number): string {
  switch (val) {
    case "i8": case "i16": case "i32": return `vader_box_i32(${typeIndex}u, ${name})`;
    case "u8": case "u16": case "u32": return `vader_box_i32(${typeIndex}u, (int32_t)(uint32_t) ${name})`;
    case "i64":  return `vader_box_i64(${typeIndex}u, ${name})`;
    case "u64": case "usize": return `vader_box_i64(${typeIndex}u, (int64_t)(uint64_t) ${name})`;
    case "f32":  return `vader_box_f64(${typeIndex}u, (double) ${name})`;
    case "f64":  return `vader_box_f64(${typeIndex}u, ${name})`;
    case "bool": return `vader_box_bool(${typeIndex}u, ${name})`;
    case "char": return `vader_box_i32(${typeIndex}u, (int32_t) ${name})`;
    case "string": return `vader_box_string(${typeIndex}u, ${name})`;
    case "null":   return `vader_box_null()`;
    case "void":   return `vader_box_null()`;
    case "ref": case "any": return name;
  }
}

function boxExprUnknown(ctx: EmitCtx, name: string, val: ValType): string {
  // Used when boxing without an explicit target type-index (e.g. passing a
  // primitive-typed value into a `ref` slot via a fn call). The right tag is
  // the BcType index of this primitive in the module's type table; if the
  // type isn't materialised (no use site referenced it), we fall back to 0
  // and the receiver's `type_check` will simply miss.
  const tag = ctx.primitiveTagOf.get(val) ?? 0;
  return boxExpr(ctx, name, val, tag);
}

function unboxExpr(name: string, target: ValType): string {
  switch (target) {
    case "i8": case "i16": case "i32": case "u8": case "u16": case "u32":
    case "i64": case "u64": case "usize": case "char":
      return `((${cTypeForValBare(target)}) ${name}.payload.i)`;
    case "f32": case "f64":
      return `((${cTypeForValBare(target)}) ${name}.payload.f)`;
    case "bool":   return `${name}.payload.b`;
    case "string": return `${name}.payload.s`;
    case "null":   return `vader_box_null()`;
    case "void":   return `((void) 0)`;
    case "ref": case "any": return name;
  }
}

function cTypeForValBare(v: ValType): string {
  switch (v) {
    case "i8":  return "int8_t";
    case "i16": return "int16_t";
    case "i32": return "int32_t";
    case "i64": return "int64_t";
    case "u8":  return "uint8_t";
    case "u16": return "uint16_t";
    case "u32": return "uint32_t";
    case "u64": return "uint64_t";
    case "usize": return "size_t";
    case "f32": return "float";
    case "f64": return "double";
    case "bool":return "bool";
    case "char":return "uint32_t";
    case "string": return "vader_string_t";
    case "null": return "vader_box_t";    // null is a tagged box at runtime
    case "void": return "void";
    case "ref": case "any": return "vader_box_t";
  }
}

function cTypeForVal(_ctx: EmitCtx, v: ValType): string {
  return cTypeForValBare(v);
}

function valTypeOfField(_ctx: EmitCtx, _typeIndex: number): ValType {
  const t = _ctx.module.types[_typeIndex]!;
  return valTypeOfBcType(t);
}

function valTypeOfBcType(t: BcType): ValType {
  switch (t.kind) {
    case "primitive": return t.val;
    case "struct":
    case "array":
    case "ref":
    case "fn":
      return "ref";
    case "union":
      return "ref";
  }
}

function cTypeFor(_ctx: EmitCtx, t: BcType): string {
  switch (t.kind) {
    case "primitive": return cTypeForValBare(t.val);
    // All heap types are stored as `vader_box_t` everywhere (locals, struct
    // fields, array elements). This keeps boxing/unboxing localised to the
    // value coercion helper and avoids type mismatches between the value
    // stack and struct field storage.
    case "struct":
    case "array":
    case "union":
    case "ref":
    case "fn":
      return `vader_box_t`;
  }
}

function primitiveMatchesType(ctx: EmitCtx, slotVal: ValType, typeIndex: number): boolean {
  const t = ctx.module.types[typeIndex]!;
  if (t.kind === "primitive") return t.val === slotVal;
  return false;
}

function zeroInit(_ctx: EmitCtx, v: ValType): string {
  switch (v) {
    case "i8": case "i16": case "i32": case "u8": case "u16": case "u32":
    case "i64": case "u64": case "usize": case "char":
      return "0";
    case "f32": case "f64": return "0.0";
    case "bool": return "false";
    case "string": return "vader_string_new(\"\", 0)";
    case "null":   return "vader_box_null()";
    case "void":   return "0";
    case "ref": case "any":  return "vader_box_null()";
  }
}

function signatureFor(ctx: EmitCtx, fn: BcFunction): string {
  const params = fn.signature.params.map((p, i) => `${cTypeForVal(ctx, p)} l${i}`).join(", ");
  const ret = cTypeForVal(ctx, fn.signature.result);
  const cret = ret === "void" ? "void" : ret;
  return `${cret} ${sanitise(fn.name)}(${params || "void"})`;
}

// =========================================================================
// `main` entry
// =========================================================================

function emitMain(ctx: EmitCtx, out: string[]): void {
  const main = ctx.module.functions.findIndex((f) => isMainMangled(f.name) && f.body.length > 0);
  if (main < 0) {
    out.push(`int main(int argc, char** argv) { (void)argc; (void)argv; return 0; }`);
    return;
  }
  const fn = ctx.module.functions[main]!;
  const cname = ctx.fnNames[main]!;
  // Typechecker (T3033) guarantees the signature is `()` or `([string])` → i32.
  const takesArgv = fn.signature.params.length === 1;
  out.push(`int main(int argc, char** argv) {`);
  // Register the GC arena release at exit. Process death frees on Unix, but
  // an explicit shutdown is correct for embedded / atexit-aware tooling and
  // gives sanitisers a clean baseline.
  out.push(`    atexit(vader_gc_shutdown);`);
  let callArgs = "";
  if (takesArgv) {
    const strIdx = ctx.stringTagIndex;
    const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
    if (strIdx < 0 || arrIdx < 0) {
      out.push(`    (void)argc; (void)argv; vader_trap("main(argv): missing [string] type"); return 1;`);
      out.push(`}`);
      return;
    }
    out.push(`    vader_box_t __args = vader_box_obj(${arrIdx}u, vader_runtime_argv(argc, argv, ${arrIdx}u, ${strIdx}u));`);
    callArgs = "__args";
  } else {
    out.push(`    (void)argc; (void)argv;`);
  }
  if (fn.signature.result === "void") {
    out.push(`    ${cname}(${callArgs});`);
    out.push(`    return 0;`);
  } else {
    out.push(`    return (int) ${cname}(${callArgs});`);
  }
  out.push(`}`);
}

// =========================================================================
// String / identifier escapes
// =========================================================================

/** C keywords (C11 + a few common identifiers like `restrict` reserved by
 *  many compilers). Any user identifier that happens to match one is suffixed
 *  with `_v` so the emitted C is always valid. */
const C_RESERVED: ReadonlySet<string> = new Set([
  "auto", "break", "case", "char", "const", "continue", "default", "do",
  "double", "else", "enum", "extern", "float", "for", "goto", "if", "inline",
  "int", "long", "register", "restrict", "return", "short", "signed",
  "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned",
  "void", "volatile", "while", "_Alignas", "_Alignof", "_Atomic", "_Bool",
  "_Complex", "_Generic", "_Imaginary", "_Noreturn", "_Static_assert",
  "_Thread_local",
]);

function sanitise(raw: string): string {
  const out = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return C_RESERVED.has(out) ? `${out}_v` : out;
}

function cStringLit(s: string): string {
  return cStringLitFromBytes(new TextEncoder().encode(s));
}

function cStringLitFromBytes(bytes: Uint8Array): string {
  let out = '"';
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i]!;
    if (b === 0x5c) out += "\\\\";
    else if (b === 0x22) out += "\\\"";
    else if (b === 0x0a) out += "\\n";
    else if (b === 0x0d) out += "\\r";
    else if (b === 0x09) out += "\\t";
    else if (b < 0x20 || b >= 0x7f) {
      // C `\x` escapes are unbounded — they consume every following hex digit
      // until the first non-hex character. If the next byte happens to be a
      // hex digit (or a continuation byte from a multi-byte UTF-8 codepoint),
      // close the escape with `""` so the digits start a fresh literal piece.
      out += `\\x${b.toString(16).padStart(2, "0")}`;
      const next = bytes[i + 1];
      if (next !== undefined && isCHexDigit(next)) out += '""';
    } else out += String.fromCharCode(b);
  }
  out += '"';
  return out;
}

function isCHexDigit(b: number): boolean {
  return (b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x46) || (b >= 0x61 && b <= 0x66);
}

function escapeC(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

function floatLit(v: number, suffix: string): string {
  if (!Number.isFinite(v)) {
    if (Number.isNaN(v)) return "(0.0/0.0)";
    return v > 0 ? "(1.0/0.0)" : "(-1.0/0.0)";
  }
  const s = v.toString();
  return s.includes(".") || s.includes("e") ? s + suffix : `${s}.0${suffix}`;
}

const I32_MIN = -2147483648;
const I32_MAX =  2147483647;
const I64_MIN_BIG = -(1n << 63n);
const I64_MAX_BIG =  (1n << 63n) - 1n;

/** C source for an i32 literal. Values outside the signed range round-trip
 *  through `(int32_t)UINT32_C(N)` to silence -Wconstant-conversion: the
 *  literal is born unsigned, then reinterpreted via two's complement. */
function i32LitC(value: number): string {
  if (value >= I32_MIN && value <= I32_MAX) return `INT32_C(${value})`;
  return `(int32_t)UINT32_C(${value >>> 0})`;
}

/** C source for an i64 literal. Same logic as `i32LitC` but for the 64-bit
 *  range. The bigint stays exact so unsigned values up to 2^64-1 round-trip
 *  through `(int64_t)UINT64_C(N)`. */
function i64LitC(value: bigint): string {
  if (value >= I64_MIN_BIG && value <= I64_MAX_BIG) return `INT64_C(${value.toString()})`;
  const u = value & ((1n << 64n) - 1n);
  return `(int64_t)UINT64_C(${u.toString()})`;
}
