// BytecodeModule → C source (§1.9). Reads the in-memory bytecode emitted by
// the bytecode pass and produces a single .c file ready to compile against
// runtime/c/vader_runtime.c.
//
// Strategy:
// - Each fn is emitted as a C function with a generated C signature.
// - The bytecode's value stack maps to a chain of generated C tmp vars (one
//   per push); the C compiler folds the chain back into expression form.
// - Structured control (`block`/`loop`/`if`) uses C labels + goto for `br`
//   semantics. The label naming derives from the open-ip so jumps resolve
//   without a runtime label stack.
// - Primitives flow as their native C type; struct/array refs as `void*`;
//   union slots and `any` as `vader_box_t`. The emitter inserts box/unbox
//   sequences whenever a value flows across the boundary (γ representation).
// - Imports for `std/io` map to the runtime's `vader_*` functions; the
//   tag-aware ones (read_file, read_line, write_file) receive the BcType
//   indices for the `string` and `Error` variants resolved per module.

import type {BcImport, BytecodeModule} from "../bytecode/module.ts";
import type {ArrayKind, BcDataEntry, BcStruct, ValType} from "../bytecode/types.ts";
import {arrayKindIndex, inlineVariantPayload, nullableRefVariant, sizeOfBcType} from "../bytecode/types.ts";

import {
  boxExpr,
  cTypeFor,
  cTypeForSignatureSlot,
  cTypeForVal,
  cTypeForValBare,
  emitFunctions,
  signatureFor,
  unboxExpr,
  valTypeOfBcType,
} from "./body.ts";
import {emitVtableDispatchers, emitVtableForwardDecls} from "./ops.ts";
import {emitVtables} from "./emit-vtable.ts";

export interface EmitOptions {
  /** When true (the user passed `--release`), skip `#line` directives — the
   *  resulting C compiles a touch faster and the binary is meant to be
   *  shipped, not stepped through. Default false : debug builds get `#line`
   *  threaded through every op so `gdb`/`lldb` show Vader source. */
  readonly release?: boolean;
}

export function emitC(m: BytecodeModule, opts: EmitOptions = {}): string {
  const ctx = newCtx(m, opts.release === true);
  const out: string[] = [];

  out.push(`/* Generated by vader — do not edit. */`);
  out.push(`#include "vader.h"`);
  out.push(`#include <stddef.h>`);
  out.push(`#include <stdlib.h>`);     /* atexit (registered in main) */
  out.push(`#include <string.h>`);
  out.push(``);

  emitTypeDecls(ctx, out);
  emitForwardDecls(ctx, out);
  emitFnSigTypedefs(ctx, out);
  emitFnTrampolines(ctx, out);
  emitTypeInfoTable(ctx, out);
  emitImportShims(ctx, out);
  emitVtableForwardDecls(ctx, out);
  emitFunctions(ctx, out);
  emitVtableDispatchers(ctx, out);
  emitMain(ctx, out);

  return out.join("\n") + "\n";
}

// =========================================================================
// Context
// =========================================================================

export interface EmitCtx {
  readonly module: BytecodeModule;
  readonly stringTagIndex: number;       // -1 if absent
  readonly errorTagIndex: number;        // -1 if absent
  /** C identifier for each fn slot (mangled name, sanitised). */
  readonly fnNames: readonly string[];
  /** C identifier for each struct (BcType slot). */
  readonly structNames: readonly (string | null)[];
  /** Tag value for each primitive ValType — used when boxing a typed value
   *  into a `ref`/`any` slot (e.g. passing `i32` to a fn expecting `ref`).
   *  -1 means the type isn't materialised in this module's type table.  */
  readonly primitiveTagOf: ReadonlyMap<ValType, number>;
  /** Inverse of `module.implTable`: trait name → struct type-indices that
   *  implement it. Built once so `is Trait` checks don't re-scan the table. */
  readonly structIdxsByTrait: ReadonlyMap<string, readonly number[]>;
  /** Fn indices that may allocate — directly via a `struct.new` / `array.new`
   *  / `string.concat` / `intrinsic` / `make_closure`, indirectly via a
   *  `call.import` / `call.indirect` / `virtual.call` (conservative), or
   *  transitively via a `call` to another may-alloc fn. Fns NOT in this set
   *  skip the shadow-stack frame entirely — no `vader_gc_frame_t` setup,
   *  no `gc_top` push/pop, no `gc_roots[]` array. */
  readonly mayAlloc: ReadonlySet<number>;
  /** Struct type indices that appear as a target of `struct.set` somewhere
   *  in the module. These structs need a heap-allocated body so the mutation
   *  is observable to every alias of the value ; the inline-variant rep
   *  (encoded directly in `vader_box_t.payload`) only fits truly immutable
   *  values. Closure environments, `Counter { value: i32 }`-style mutables,
   *  and any single-field struct the user writes to fall into this set. */
  readonly mutatedStructs: ReadonlySet<number>;
  /** Concrete struct type-index → its all-`Any` counterpart type-index, when
   *  one was registered (via erasure dedupe's extra entry). Used at the
   *  virtual.call / call boundary : if the runtime receiver carries the
   *  Any-counterpart tag, the C-emit re-packs the heap layout into the
   *  expected inline-eligible struct's payload shape. */
  readonly anyCounterpartOf: ReadonlyMap<number, number>;
  /** Per-concrete-struct-typeIndex, the set of sibling layout
   *  type-indices that could carry the same logical value at runtime.
   *  Used to dispatch the boundary reshape against multiple possible
   *  runtime shapes (e.g. anonymous tuples where `[usize, T]` →
   *  `[usize, Any]` is a different layout than `[Any, Any]`, and both
   *  may flow into a `[usize, string]` call site depending on which
   *  erased fn produced the value). Subset of `anyCounterpartOf` —
   *  the latter picks one canonical Any-version ; this one enumerates
   *  every sibling so the boundary reshape can switch on the runtime
   *  tag. */
  readonly siblingLayoutsOf: ReadonlyMap<number, readonly number[]>;
  /** Set when `--release` was passed. Gates `#line` directives in the per-op
   *  body emit — debug builds emit them so `gdb`/`lldb` step through the
   *  original Vader source. */
  readonly release: boolean;
}

function newCtx(m: BytecodeModule, release: boolean): EmitCtx {
  const fnNames = m.functions.map((f) => sanitise(f.name));
  const structNames: (string | null)[] = m.types.map((t) =>
    t.kind === "struct" ? `vader_struct_${sanitise(t.name)}_t` : null);
  let stringIdx = -1, errorIdx = -1;
  const primitiveTagOf = new Map<ValType, number>();
  for (let i = 0; i < m.types.length; i++) {
    const t = m.types[i]!;
    if (t.kind === "primitive") {
      primitiveTagOf.set(t.val, i);
      if (t.val === "string") stringIdx = i;
    }
    if (t.kind === "ref" && t.traitName === "Error") errorIdx = i;
  }
  const structIdxsByTrait = new Map<string, number[]>();
  for (const [structIdx, traits] of m.implTable) {
    for (const traitName of traits) {
      const list = structIdxsByTrait.get(traitName);
      if (list !== undefined) list.push(structIdx);
      else structIdxsByTrait.set(traitName, [structIdx]);
    }
  }
  const erasureGroups = computeErasureGroups(m);
  return {
    module: m, stringTagIndex: stringIdx, errorTagIndex: errorIdx,
    fnNames, structNames, primitiveTagOf, structIdxsByTrait,
    mayAlloc: computeMayAlloc(m),
    mutatedStructs: computeMutatedStructs(m),
    anyCounterpartOf: erasureGroups.anyCounterpartOf,
    siblingLayoutsOf: erasureGroups.siblingLayoutsOf,
    release,
  };
}

/** Group struct types by their source decl's symbol id ; for each group,
 *  identify the all-`Any`-args entry (every field's BcType is `ref` —
 *  i.e. an opaque heap pointer — which is the post-erasure shape) and
 *  link every other entry in the group to it. Used by `emitErasureBoundaryConversion`
 *  to recognise when a runtime box carries the heap-form layout of an
 *  otherwise inline-eligible struct.
 *
 *  Two grouping keys :
 *    - `symbolId` — set by `internStructDecl` for user `struct[T]` decls
 *      (Yield(T), Box(T), Repeat(T), …).
 *    - anonymous tuples — no symbolId ; group by `tuple:${arity}` so
 *      `[i32, string]` and `[Any, Any]` link as siblings. */
function groupStructsByShape(m: BytecodeModule): Map<string | number, number[]> {
  const groups = new Map<string | number, number[]>();
  for (let i = 0; i < m.types.length; i++) {
    const t = m.types[i]!;
    if (t.kind !== "struct") continue;
    const key = t.symbolId ?? (t.name.startsWith("__Tuple_") ? `tuple:${t.fields.length}` : undefined);
    if (key === undefined) continue;
    const list = groups.get(key);
    if (list !== undefined) list.push(i);
    else groups.set(key, [i]);
  }
  return groups;
}

function fieldsConvertible(m: BytecodeModule, iA: number, iB: number): boolean {
  const a = m.types[iA] as BcStruct;
  const b = m.types[iB] as BcStruct;
  if (a.fields.length !== b.fields.length) return false;
  for (let k = 0; k < a.fields.length; k++) {
    const va = valTypeOfBcType(m.types[a.fields[k]!.typeIndex]!);
    const vb = valTypeOfBcType(m.types[b.fields[k]!.typeIndex]!);
    if (va === vb) continue;
    if (va === "ref" || va === "any" || vb === "ref" || vb === "any") continue;
    return false;
  }
  return true;
}

function computeErasureGroups(m: BytecodeModule): {
  anyCounterpartOf: Map<number, number>;
  siblingLayoutsOf: Map<number, readonly number[]>;
} {
  const groups = groupStructsByShape(m);
  const anyCounterpartOf = new Map<number, number>();
  const siblingLayoutsOf = new Map<number, readonly number[]>();
  for (const indices of groups.values()) {
    if (indices.length < 2) continue;
    // Siblings : every other entry in the group whose fields are
    // pairwise convertible to ours. Anonymous-tuple grouping keys on
    // arity alone, so `[char, usize]` and `[string, ref]` land in the
    // same group ; reshape only makes sense when each field position
    // is either same-ValType or one side is ref/any (the
    // boxing/unboxing branches in `emitHeapStructReshapeForSibling`
    // cover those — anything else would emit an invalid C cast like
    // `(vader_string_t) some_uint32`).
    for (const i of indices) {
      const peers = indices.filter((j) => j !== i && fieldsConvertible(m, i, j));
      siblingLayoutsOf.set(i, peers);
    }
    // Any-counterpart : the entry whose fields are all heap refs (the
    // post-erasure shared shape). Concrete entries have at least one
    // primitive / typed field ; skip the group when no canonical
    // all-ref entry exists.
    const anyIdx = indices.find((i) => {
      const t = m.types[i] as { kind: "struct"; fields: readonly { typeIndex: number }[] };
      return t.fields.every((f) => m.types[f.typeIndex]?.kind === "ref");
    });
    if (anyIdx === undefined) continue;
    for (const i of indices) {
      if (i !== anyIdx) anyCounterpartOf.set(i, anyIdx);
    }
  }
  return { anyCounterpartOf, siblingLayoutsOf };
}

/** Walk every fn body once and collect the type indices of every struct
 *  that's a target of a `struct.set` / `struct.set_stack` op. Used by the
 *  inline-variant fast path : structs in this set must keep the heap rep
 *  so mutations are visible to aliases. */
function computeMutatedStructs(m: BytecodeModule): ReadonlySet<number> {
  const out = new Set<number>();
  for (const fn of m.functions) {
    for (const op of fn.body) {
      if (op.kind === "struct.set" || op.kind === "struct.set_stack") {
        out.add(op.typeIndex);
      }
    }
  }
  return out;
}

// Bytecode-level callgraph analysis: which fns may trigger a GC allocation
// (transitively). Used by `emitFunctionBody` to skip the shadow-stack frame
// for pure leaf-ish fns — `inc(x) = x + 1`, accessor methods, predicates.
//
// Direct allocators: `struct.new`, `array.new`, `array.push`, `string.concat`,
// `intrinsic` (string-builder family), `make_closure`. Indirect allocators
// (conservative — unknown target): `call.import`, `call.indirect`,
// `virtual.call`. Transitive: any `call` to a fn already in the set.
function computeMayAlloc(m: BytecodeModule): Set<number> {
  const mayAlloc = new Set<number>();

  for (let fi = 0; fi < m.functions.length; fi++) {
    const fn = m.functions[fi]!;
    for (const op of fn.body) {
      switch (op.kind) {
        case "struct.new":
        case "array.new":
        case "array.push":
        case "string.concat":
        case "intrinsic":
        case "make_closure":
        case "call.import":
        case "call.indirect":
        case "virtual.call":
          mayAlloc.add(fi);
          break;
      }
      if (mayAlloc.has(fi)) break;
    }
  }

  let changed = true;
  while (changed) {
    changed = false;
    for (let fi = 0; fi < m.functions.length; fi++) {
      if (mayAlloc.has(fi)) continue;
      const fn = m.functions[fi]!;
      for (const op of fn.body) {
        if (op.kind === "call" && mayAlloc.has(op.fnIndex)) {
          mayAlloc.add(fi);
          changed = true;
          break;
        }
      }
    }
  }

  return mayAlloc;
}

// =========================================================================
// Type declarations
// =========================================================================

function emitTypeDecls(ctx: EmitCtx, out: string[]): void {
  // Forward declarations for every struct so field references compile in any
  // order; bodies follow.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind === "struct") {
      out.push(`typedef struct ${ctx.structNames[i]!} ${ctx.structNames[i]!};`);
    }
  }
  out.push(``);

  // Emit each struct's body plus, when applicable, a header-less mirror
  // twin used by the packed-payload fast path. Mirroring lets the C
  // compiler do the layout for fields packed directly into
  // `vader_box_t.payload.packed[]`. Mutated structs are excluded from
  // the inline-variant fast path so the mirror is never needed.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind !== "struct") continue;
    const cname = ctx.structNames[i]!;
    out.push(`struct ${cname} {`);
    out.push(`    vader_obj_header_t header;`);
    for (const field of t.fields) {
      const fieldType = ctx.module.types[field.typeIndex]!;
      // `T | null` where T is a single heap type stores as a raw `void*` (NULL
      // for the null variant, an obj pointer for T). Saves 16 B vs the full
      // `vader_box_t` per field. The C emit at FieldGet / FieldSet boxes back
      // to / unboxes from `vader_box_t` so the rest of the program sees a
      // uniform value representation.
      if (fieldType.kind === "union" && nullableRefVariant(fieldType, ctx.module.types) !== null) {
        out.push(`    void* f_${sanitise(field.name)};`);
        continue;
      }
      out.push(`    ${cTypeFor(ctx, fieldType)} f_${sanitise(field.name)};`);
    }
    out.push(`};`);

    const isPacked = !ctx.mutatedStructs.has(i)
      && inlineVariantPayload(t, ctx.module.types) === "packed";
    if (isPacked) {
      out.push(`typedef struct {`);
      for (const field of t.fields) {
        const fieldType = ctx.module.types[field.typeIndex]!;
        out.push(`    ${cTypeFor(ctx, fieldType)} f_${sanitise(field.name)};`);
      }
      out.push(`} ${packedStructName(cname)};`);
    }
  }
  out.push(``);

  // The comptime atom table defines the `ATOM_LIT_<i>` u32 macros that
  // the per-literal `vader_str_<i>` aliases below resolve through, so
  // emit it first.
  emitAtomComptimeTable(ctx, out);

  // String literal aliases — each `vader_str_<i>` is now a `u32` (atom
  // id) initialised from the matching `ATOM_LIT_<i>` macro. body.ts and
  // static_table.ts still reference `vader_str_<i>` ; keeping the alias
  // means no rewriter pass is needed across the per-op emit logic.
  for (let i = 0; i < ctx.module.strings.length; i++) {
    out.push(`static const vader_string_t vader_str_${i} = ATOM_LIT_${i};`);
  }
  out.push(``);

  emitDataPool(ctx, out);
}

// =========================================================================
// Compile-time atom table — see docs/ATOM_INTERNING.md.
//
// Every string literal in the bytecode pool is serialised as a PERM atom
// in the binary's `.rodata`. The emitted `main` hands this table to
// `vader_atom_init_with_comptime` at startup ; the runtime memcpys it
// into the live atom table at indices `1 .. N` (index 0 is reserved for
// VADER_ATOM_EMPTY) and rebuilds the intern hash over it.
//
// The `ATOM_LIT_<i>` macros expose each literal's runtime atom id as a
// C compile-time constant — usable in `case ATOM_LIT_X:` once Phase 1
// flips `vader_string_t = u32` and the codegen emits literals as bare
// atom ids instead of `vader_str_<i>` fat-ptrs.
// =========================================================================

function emitAtomComptimeTable(ctx: EmitCtx, out: string[]): void {
  out.push(`/* Compile-time atom table — see docs/ATOM_INTERNING.md. */`);
  const strings = ctx.module.strings;
  if (strings.length === 0) {
    // Empty modules still emit a 1-entry placeholder so callers can take
    // `&vader_atom_comptime_table[0]` without UB ; the count of 0 tells
    // the runtime to ignore it.
    out.push(`static const vader_atom_entry_t vader_atom_comptime_table[1] = { { 0u, 0u, 0u, 0u, 0u, "" } };`);
    out.push(`#define VADER_COMPTIME_ATOM_COUNT 0u`);
    out.push(``);
    return;
  }

  // Blob : every literal's bytes followed by an inline NUL ("\0"
  // sentinel after each literal, so `data[len]` reads NUL for owners).
  // C concatenates the adjacent string literals into one `.rodata` array.
  const enc = new TextEncoder();
  const offsets: number[] = [];
  const lens: number[] = [];
  let offset = 0;
  const blobLines: string[] = [];
  for (let i = 0; i < strings.length; i++) {
    const bytes = enc.encode(strings[i]!);
    blobLines.push(`    ${cStringLitFromBytes(bytes)} "\\0"`);
    offsets.push(offset);
    lens.push(bytes.length);
    offset += bytes.length + 1;
  }
  out.push(`static const char vader_atom_blob[] =`);
  for (const line of blobLines) out.push(line);
  out.push(`;`);
  out.push(``);

  // Entry table — one PERM owner per literal, pointing into the blob.
  // Field order : { parent, parent_offset, len, flags, _pad, data }.
  out.push(`static const vader_atom_entry_t vader_atom_comptime_table[] = {`);
  for (let i = 0; i < strings.length; i++) {
    out.push(`    { 0u, 0u, ${lens[i]}u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[${offsets[i]}] },`);
  }
  out.push(`};`);
  out.push(``);

  // Macros : `ATOM_LIT_<i>` is the runtime atom id for the i-th literal
  // in `ctx.module.strings`. +1 because the runtime installs the empty
  // atom at index 0 before the comptime block.
  for (let i = 0; i < strings.length; i++) {
    out.push(`#define ATOM_LIT_${i} ${i + 1}u`);
  }
  out.push(`#define VADER_COMPTIME_ATOM_COUNT ${strings.length}u`);
  out.push(``);
}

// =========================================================================
// Data pool — module-level `const T[]` literals emitted as `.rodata` statics.
// Each pool entry produces :
//   - a packed wrapper struct `__vader_data_<i>_t` holding the buf + slots
//   - a static const vader_array_t header pointing into the wrapper
// `data.const <i>` op resolves to `vader_box_obj(<type>, &__vader_data_<i>)`.
// The GC scanner skips static pointers via its arena bound checks.
// =========================================================================

function emitDataPool(ctx: EmitCtx, out: string[]): void {
  if (ctx.module.dataPool.length === 0) return;
  for (let i = 0; i < ctx.module.dataPool.length; i++) {
    emitDataEntry(i, ctx.module.dataPool[i]!, out);
  }
  out.push(``);
}

function emitDataEntry(idx: number, entry: BcDataEntry, out: string[]): void {
  const cType = cTypeForArrayKind(entry.kind);
  const kindIdx = arrayKindIndex(entry.kind);
  const length = entry.items.length;
  // Wrapper packs the buf header + a fixed-size slot array. The buf's
  // `slots` flex-array would otherwise prevent static initialisation ;
  // the wrapper sidesteps that by giving the slots their own storage.
  // First member is `vader_array_buf_t` so `(vader_array_buf_t*) &w.buf`
  // is a legal cast.
  out.push(`static const struct {`);
  out.push(`    vader_array_buf_t buf;`);
  out.push(`    ${cType} slots[${length}];`);
  out.push(`} __vader_data_buf_${idx} = {`);
  out.push(`    .buf = {`);
  out.push(`        .header = { VADER_TYPE_INDEX_ARRAY_BUF, 0, 0, 0, NULL },`);
  out.push(`        .capacity = ${length}u, .length = ${length}u,`);
  out.push(`        .element_kind = ${kindIdx}u, ._pad = {0,0,0,0,0,0,0}`);
  out.push(`    },`);
  out.push(`    .slots = { ${entry.items.map((v) => formatDataItem(entry.kind, v)).join(", ")} }`);
  out.push(`};`);
  out.push(`static const vader_array_t __vader_data_${idx} = {`);
  out.push(`    .header = { 0, 0, 0, 0, NULL },`);
  out.push(`    .length = ${length}u, .capacity = ${length}u, .offset = 0u,`);
  out.push(`    .buf = (vader_array_buf_t*) &__vader_data_buf_${idx}.buf,`);
  out.push(`};`);
}

function cTypeForArrayKind(k: ArrayKind): string {
  switch (k) {
    case "u8":   return "uint8_t";
    case "u16":  return "uint16_t";
    case "u32":  return "uint32_t";
    case "u64":  return "uint64_t";
    case "i8":   return "int8_t";
    case "i16":  return "int16_t";
    case "i32":  return "int32_t";
    case "i64":  return "int64_t";
    case "f32":  return "float";
    case "f64":  return "double";
    case "char": return "uint32_t";
    case "bool": return "uint8_t";
    case "boxed":
      throw new Error("c-emit: data pool kind 'boxed' not allowed");
  }
}

function formatDataItem(kind: ArrayKind, v: bigint): string {
  switch (kind) {
    case "u8":   return `${BigInt.asUintN(8, v).toString()}u`;
    case "u16":  return `${BigInt.asUintN(16, v).toString()}u`;
    case "u32":  return `${BigInt.asUintN(32, v).toString()}u`;
    case "u64":  return `UINT64_C(${BigInt.asUintN(64, v).toString()})`;
    case "i8":   return `${BigInt.asIntN(8, v).toString()}`;
    case "i16":  return `${BigInt.asIntN(16, v).toString()}`;
    case "i32":  return i32LitC(Number(BigInt.asIntN(32, v)));
    case "i64":  return i64LitC(BigInt.asIntN(64, v));
    case "char": return `${BigInt.asUintN(32, v).toString()}u`;
    case "bool": return v === 0n ? "0u" : "1u";
    case "f32":  return floatLit(f32FromBits(Number(BigInt.asUintN(32, v))), "f");
    case "f64":  return floatLit(f64FromBits(BigInt.asUintN(64, v)), "");
    case "boxed":
      throw new Error("c-emit: data pool kind 'boxed' not allowed");
  }
}

const FLOAT_BUF = new ArrayBuffer(8);
const FLOAT_DV = new DataView(FLOAT_BUF);

function f32FromBits(bits: number): number {
  FLOAT_DV.setUint32(0, bits, true);
  return FLOAT_DV.getFloat32(0, true);
}

function f64FromBits(bits: bigint): number {
  FLOAT_DV.setBigUint64(0, bits, true);
  return FLOAT_DV.getFloat64(0, true);
}

// =========================================================================
// Forward declarations
// =========================================================================

function emitForwardDecls(ctx: EmitCtx, out: string[]): void {
  for (let i = 0; i < ctx.module.functions.length; i++) {
    const fn = ctx.module.functions[i]!;
    out.push(`static ${signatureFor(ctx, fn)};`);
  }
  out.push(``);
}

// =========================================================================
// Function-pointer typedefs and per-fn trampolines (for fn values / closures)
// =========================================================================

function emitFnSigTypedefs(ctx: EmitCtx, out: string[]): void {
  // One typedef per BcFn type. Every callable signature includes a leading
  // `void* env` so closures (Phase 3) can be invoked through the same path.
  // Globals route through a per-fn trampoline that ignores env.
  //
  // B1 slots (nullable-ref unions whose non-null variant is a single heap
  // struct) pass through the ABI as `void*` instead of `vader_box_t` —
  // `cTypeForSignatureSlot` picks the right C type per slot. The
  // `vader_fn_t.code` pointer is cast to this typedef in the call.indirect
  // emitter ; B1 args are pre-stripped to `void*` there, and B1 returns
  // are re-boxed.
  for (let i = 0; i < ctx.module.types.length; i++) {
    const t = ctx.module.types[i]!;
    if (t.kind !== "fn") continue;
    const paramVals = t.params.map((p) => valTypeOfBcType(ctx.module.types[p]!));
    const retVal = valTypeOfBcType(ctx.module.types[t.returnType]!);
    const params = paramVals.map((p, j) =>
      `${cTypeForSignatureSlot(ctx, t.params[j]!, p)} a${j}`);
    const cret = retVal === "void"
      ? "void"
      : cTypeForSignatureSlot(ctx, t.returnType, retVal);
    const head = `void* env`;
    out.push(`typedef ${cret} (*vader_fn_sig_${i}_t)(${params.length === 0 ? head : `${head}, ${params.join(", ")}`});`);
  }
  // Canonical erased fn-pointer signatures per arity. Used by
  // `call.indirect` to cast `closure->code` uniformly so the lift /
  // tramp wrapper (which always exposes the erased vader_box_t ABI)
  // can be called from either concrete-typed or erased-typed call
  // sites without a calling-convention mismatch.
  const maxArity = ctx.module.types.reduce((acc, t) =>
    t.kind === "fn" ? Math.max(acc, t.params.length) : acc, 0);
  for (let n = 0; n <= maxArity; n++) {
    const tail = Array.from({ length: n }, (_, j) => `vader_box_t a${j}`).join(", ");
    const head = n === 0 ? "void* env" : `void* env, ${tail}`;
    out.push(`typedef vader_box_t (*vader_fn_erased_sig_${n}_t)(${head});`);
  }
  out.push(``);
}

// =========================================================================
// Type info table — pointer maps consumed by the GC scanner
// =========================================================================

function emitTypeInfoTable(ctx: EmitCtx, out: string[]): void {
  const types = ctx.module.types;

  // Per-type ptr-offset arrays. We collect into a buffer first so the table
  // initialiser can reference each by name. `offsetof` is resolved at C compile
  // time so we don't have to know struct sizes in TypeScript.
  //
  // Two parallel arrays per struct:
  //   - `_ptrs[]`     box-bearing fields (vader_box_t)
  //   - `_strs[]`     raw vader_string_t fat-ptr fields
  // The string GC needs the latter because string fields are stored inline
  // as primitive `vader_string_t`, not as boxes — the box-aliased mark
  // walk would otherwise miss them.
  for (let i = 0; i < types.length; i++) {
    const t = types[i]!;
    if (t.kind === "struct") {
      const cname = ctx.structNames[i]!;
      const offsets: string[] = [];
      const stringOffsets: string[] = [];
      const refOffsets: string[] = [];
      for (const field of t.fields) {
        const ftype = types[field.typeIndex]!;
        if (ftype.kind === "union" && nullableRefVariant(ftype, types) !== null) {
          // `T | null` field — stored as a raw `void*` (NULL = null variant,
          // non-null = obj pointer). Saves 16 B vs the equivalent box ;
          // listed separately so the scanner walks it with `scan_raw`.
          refOffsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        } else if (ftype.kind !== "primitive") {
          // Heap-bearing field — its C type is `vader_box_t`. Tracing this
          // slot requires checking the box tag at scan time.
          offsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        } else if (ftype.val === "string") {
          // Raw `vader_string_t` field. The Cheney scan ignores it (the
          // buffer lives in the non-moving string arena), but the string
          // mark-sweep collector must reach it.
          stringOffsets.push(`offsetof(${cname}, f_${sanitise(field.name)})`);
        }
      }
      if (offsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_ptrs[] = { ${offsets.join(", ")} };`);
      }
      if (stringOffsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_strs[] = { ${stringOffsets.join(", ")} };`);
      }
      if (refOffsets.length > 0) {
        out.push(`static const uint16_t vader_type_${i}_refs[] = { ${refOffsets.join(", ")} };`);
      }
    } else if (t.kind === "fn") {
      // vader_fn_t has `code` (function pointer — NOT a heap ref, must not
      // be scanned) and `env` (heap pointer to the closure environment).
      out.push(`static const uint16_t vader_type_${i}_ptrs[] = { offsetof(vader_fn_t, env) };`);
    } else if (t.kind === "array") {
      // The buf is a raw pointer to a header-bearing object — scan_raw treatment.
      out.push(`static const uint16_t vader_type_${i}_ptrs[] = { offsetof(vader_array_t, buf) };`);
    }
  }

  out.push(``);
  // Fixed length so missing entries (primitives, unions, refs — no GC info)
  // zero-initialise to `VADER_TYPE_KIND_NONE`. Without the explicit size, C
  // would size the array to `max-designated-index + 1`, and any later
  // `vader_type_info_table[tag]` read with `tag` past the last designated
  // entry but below `vader_type_info_count` would walk off the array.
  out.push(`const vader_type_info_t vader_type_info_table[${types.length}] = {`);
  for (let i = 0; i < types.length; i++) {
    const t = types[i]!;
    if (t.kind === "struct") {
      // Inline-variant structs (empty-body / single-primitive-field /
      // single-ref-field / multi-field POD packed into `payload.packed[]`)
      // are encoded directly inside `vader_box_t.payload` — they never
      // get a heap allocation. Mutated structs are excluded : they keep
      // the heap rep so `struct.set` is observable across aliases.
      const inlinePayload = !ctx.mutatedStructs.has(i)
        ? inlineVariantPayload(t, types)
        : null;
      if (inlinePayload === "void" || (inlinePayload !== null && inlinePayload !== "ref")) {
        // Empty / single-primitive / packed-multi-field : `payload` is
        // non-pointer data, GC skips the slot. Leave the entry at its
        // zero-init KIND_NONE so `vader_gc_scan_box` short-circuits before
        // touching the payload.
        continue;
      }
      if (inlinePayload === "ref") {
        // Single-ref-field inline : `payload.obj` IS the referent's heap
        // pointer (the wrapper struct itself never allocates). GC reaches
        // through via `scan_raw`, reading the referent's own type tag from
        // its header — no per-tag scan info needed here.
        out.push(`    [${i}] = { VADER_TYPE_KIND_INLINE_REF, 0, NULL, 0, 0, NULL, 0, NULL },`);
        continue;
      }
      const cname = ctx.structNames[i]!;
      const boxFields = t.fields.filter((f) => {
        const ft = types[f.typeIndex]!;
        if (ft.kind === "union" && nullableRefVariant(ft, types) !== null) return false;
        return ft.kind !== "primitive";
      });
      const strFields = t.fields.filter((f) => {
        const ft = types[f.typeIndex]!;
        return ft.kind === "primitive" && ft.val === "string";
      });
      const refFields = t.fields.filter((f) => {
        const ft = types[f.typeIndex]!;
        return ft.kind === "union" && nullableRefVariant(ft, types) !== null;
      });
      const ptrArr = boxFields.length > 0 ? `vader_type_${i}_ptrs` : "NULL";
      const strArr = strFields.length > 0 ? `vader_type_${i}_strs` : "NULL";
      const refArr = refFields.length > 0 ? `vader_type_${i}_refs` : "NULL";
      out.push(`    [${i}] = { VADER_TYPE_KIND_STRUCT, sizeof(${cname}), ${ptrArr}, ${boxFields.length}, ${strFields.length}, ${strArr}, ${refFields.length}, ${refArr} },`);
    } else if (t.kind === "fn") {
      out.push(`    [${i}] = { VADER_TYPE_KIND_FN, sizeof(vader_fn_t), vader_type_${i}_ptrs, 1, 0, NULL, 0, NULL },`);
    } else if (t.kind === "array") {
      out.push(`    [${i}] = { VADER_TYPE_KIND_ARRAY, sizeof(vader_array_t), vader_type_${i}_ptrs, 1, 0, NULL, 0, NULL },`);
    }
    // primitive / union / ref → entry implicitly zero-initialised
    // (VADER_TYPE_KIND_NONE), which the GC interprets as "non-heap, skip".
  }
  out.push(`};`);
  out.push(`const size_t vader_type_info_count = ${types.length};`);
  out.push(``);

  // Per-type size table — backs the runtime path of `@size_of(t)`. Indexed
  // by typeIndex (the same slot `type.const N` encodes) ; the table is
  // emitted unconditionally so the placeholder `type.const` box payload
  // round-trip stays valid regardless of whether the user code actually
  // reads it. Sizes computed by the shared `sizeOfBcType` helper.
  out.push(`const size_t vader_type_size[${types.length}] = {`);
  for (let i = 0; i < types.length; i++) {
    out.push(`    [${i}] = ${sizeOfBcType(types[i]!)}u,`);
  }
  out.push(`};`);
  out.push(``);

  // Per-tag trait-method vtables. Override the weak fallback in
  // `vader_runtime.c` so `vader_virtual_dispatch` resolves correctly for
  // any concrete type implementing a trait.
  emitVtables(ctx.module, ctx.fnNames, out);
}

function emitFnTrampolines(ctx: EmitCtx, out: string[]): void {
  // Walk every fn body to discover which fns are taken by reference and
  // which lifted fns get instantiated via `make_closure`. Each kind needs a
  // matching wrapper:
  //   - `fn.ref`        — wrapper drops env (global fn used as a value)
  //   - `make_closure`  — wrapper boxes env into vader_box_t before calling
  //                       (the lifted fn's signature takes `ref env`)
  const fnRefMap = new Map<number, number>();        // fnIndex → BcFn typeIndex
  const closureMap = new Map<number, number>();      // lifted fnIndex → BcFn typeIndex
  for (const fn of ctx.module.functions) {
    for (const op of fn.body) {
      if (op.kind === "fn.ref") fnRefMap.set(op.fnIndex, op.typeIndex);
      else if (op.kind === "make_closure") closureMap.set(op.fnIndex, op.typeIndex);
    }
  }
  if (fnRefMap.size === 0 && closureMap.size === 0) return;

  // Trampolines + lift wrappers use a canonical erased signature
  // (vader_box_t for every arg + return) so a single function pointer
  // can be safely cast at any `call.indirect` site regardless of
  // whether the static fn type at the call site is concrete
  // (`(i32) -> i32`) or erased (`(Any) -> Any`). Inside, each arg gets
  // unboxed to the underlying fn's concrete ValType, the actual fn is
  // called, the return is boxed. Costs one box+unbox per arg+return
  // per indirect call — acceptable for the correctness gain ;
  // statically-known direct calls still hit `emitCall` and skip the
  // wrapper entirely.
  for (const [fnIndex, typeIndex] of fnRefMap) {
    const fn = ctx.module.functions[fnIndex]!;
    const cname = ctx.fnNames[fnIndex]!;
    const tailParams = fn.signature.params.map((_, j) => `vader_box_t a${j}`);
    const head = tailParams.length === 0 ? "void* env" : `void* env, ${tailParams.join(", ")}`;
    out.push(`static vader_box_t vader_fn_tramp_${fnIndex}(${head}) {`);
    out.push(`    (void) env;`);
    const unboxedArgs = fn.signature.params.map((p, j) => unboxExpr(`a${j}`, p)).join(", ");
    if (fn.signature.result === "void") {
      out.push(`    ${cname}(${unboxedArgs});`);
      out.push(`    return vader_box_null();`);
    } else {
      const callExpr = `${cname}(${unboxedArgs})`;
      const boxed = fn.signature.result === "ref" || fn.signature.result === "any"
        ? callExpr
        : boxExpr(ctx, callExpr, fn.signature.result, fn.signature.resultType);
      out.push(`    return ${boxed};`);
    }
    out.push(`}`);
    out.push(`static vader_fn_t vader_fn_static_${fnIndex} = { { ${typeIndex}u, 0u, 0u, 0u, NULL }, (void*) &vader_fn_tramp_${fnIndex}, NULL };`);
  }

  for (const [fnIndex, _typeIndex] of closureMap) {
    const fn = ctx.module.functions[fnIndex]!;
    const cname = ctx.fnNames[fnIndex]!;
    if (fn.signature.params.length === 0) continue;
    // Skip the env slot (index 0) — the wrapper takes `void* env`
    // and boxes it back into the vader_box_t the lifted fn expects.
    const tailVals = fn.signature.params.slice(1);
    const tailParams = tailVals.map((_, j) => `vader_box_t a${j}`);
    const head = tailParams.length === 0 ? "void* env" : `void* env, ${tailParams.join(", ")}`;
    out.push(`static vader_box_t vader_fn_lift_${fnIndex}(${head}) {`);
    out.push(`    vader_box_t env_box; env_box.tag = 0u; env_box._pad = 0u; env_box.payload.obj = env;`);
    const unboxedTail = tailVals.map((p, j) => unboxExpr(`a${j}`, p)).join(", ");
    const callArgs = unboxedTail.length === 0 ? `env_box` : `env_box, ${unboxedTail}`;
    if (fn.signature.result === "void") {
      out.push(`    ${cname}(${callArgs});`);
      out.push(`    return vader_box_null();`);
    } else {
      const callExpr = `${cname}(${callArgs})`;
      const boxed = fn.signature.result === "ref" || fn.signature.result === "any"
        ? callExpr
        : boxExpr(ctx, callExpr, fn.signature.result, fn.signature.resultType);
      out.push(`    return ${boxed};`);
    }
    out.push(`}`);
  }
  out.push(``);
}

// =========================================================================
// Import shims
// =========================================================================

function emitImportShims(ctx: EmitCtx, out: string[]): void {
  // Unused-import pruning happens upstream in `pruneUnusedImports` (see
  // `src/midir/emit.ts`) so the bytecode module already carries only the
  // imports actually referenced by `call.import` ops. Every backend (VM,
  // C-emit, future WASM) and every serialiser (`.vir` text/binary) gets
  // the compact table for free.
  const shims: string[] = [];
  const externDecls: string[] = [];
  const seenExtern = new Set<string>();
  for (let i = 0; i < ctx.module.imports.length; i++) {
    const imp = ctx.module.imports[i]!;
    if (imp.isExtern && !seenExtern.has(imp.externName)) {
      seenExtern.add(imp.externName);
      const params = imp.signature.params.map(externCType).join(", ");
      const ret = externCType(imp.signature.result);
      externDecls.push(`extern ${ret} ${imp.externName}(${params || "void"});`);
    }
    const shim = importShim(ctx, imp, i);
    if (shim !== null) shims.push(shim);
  }
  if (externDecls.length > 0) {
    out.push(`// User @extern foreign symbols — resolved by the linker.`);
    for (const d of externDecls) out.push(d);
    out.push(``);
  }
  for (const s of shims) out.push(s);
  out.push(``);
}

function importShim(ctx: EmitCtx, imp: BcImport, idx: number): string | null {
  const name = `vader_import_${idx}`;
  const params = imp.signature.params.map((vt, j) => `${cTypeForVal(ctx, vt)} a${j}`).join(", ");
  const ret = cTypeForVal(ctx, imp.signature.result);
  const head = `static ${ret} ${name}(${params || "void"})`;

  // Built-in std/io routes — implemented by the runtime.
  switch (imp.mangledName) {
    case "std_io$write":
      // `out: Stream` — defaults to i32 repr ; runtime traps on any tag
      // outside {Stdout=0, Stderr=1}.
      return `${head} { vader_write(a0, a1); }`;
    case "std_abort$panic":
      return `${head} { vader_panic(a0); }`;
    case "std_io$exists":
      return `${head} { return vader_exists(a0); }`;
    case "std_io$is_dir":
      return `${head} { return vader_is_dir(a0); }`;
    case "std_io$read_dir": {
      const strIdx = ctx.stringTagIndex;
      if (strIdx < 0) return `${head} { vader_trap("read_dir: no string type"); }`;
      const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
      if (arrIdx < 0) return `${head} { vader_trap("read_dir: no [string] type"); }`;
      return `${head} { return vader_read_dir(a0, ${arrIdx}u, ${strIdx}u, ${tagOrTrap(ctx, "error")}); }`;
    }
    case "std_io$read_file":
      return `${head} { return vader_read_file(a0, ${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$write_file":
      return `${head} { return vader_write_file(a0, a1, 0u, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$read_line":
      return `${head} { return vader_read_line(${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_io$read_stdin":
      return `${head} { return vader_read_stdin(a0, ${tagOrTrap(ctx, "string")}, ${tagOrTrap(ctx, "error")}); }`;

    // Internal fold target (`s.bytes().len()` lowers to this). Kept though the
    // public byte_len export was removed — the fold resolves it by symbol.
    case "std_string$byte_len":    return `${head} { return vader_string_byte_len(a0); }`;
    // `string implements Index(usize, char)` is `@intrinsic`-impl in std/core ;
    // the host provides the body under the impl-method mangled name.
    // Indexes by codepoint ; for byte access use `bytes()`.
    case "std_core$string$Index$at":
      return `${head} { return vader_string_codepoint_at(a0, a1); }`;
    case "std_string$bytes": {
      // Zero-copy `const u8[]` view aliasing the string's interned bytes.
      // `const u8[]` and `u8[]` intern to the same BcType (immutability is a
      // typecheck-only concept), so any array-of-u8 entry is the right tag.
      const u8Idx = ctx.module.types.findIndex(t => t.kind === "primitive" && t.val === "u8");
      if (u8Idx < 0) return `${head} { vader_trap("bytes: no u8 type"); }`;
      const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === u8Idx);
      if (arrIdx < 0) return `${head} { vader_trap("bytes: no u8[] type"); }`;
      return `${head} { return vader_box_obj(${arrIdx}u, vader_string_bytes_view(a0, ${arrIdx}u, ${u8Idx}u)); }`;
    }
    case "std_string$as_string":
      // Inverse of `bytes()`. The `const u8[]` arrives boxed ; O(1) atom_slice
      // on a borrowed `bytes()` slice, gather+intern on a materialised array.
      return `${head} { return vader_string_as_string((vader_array_t*) a0.payload.obj); }`;
    case "std_string$parse_float":
      return `${head} { return vader_string_parse_float(a0, ${primTagOrTrap(ctx, "f64")}, ${tagOrTrap(ctx, "error")}); }`;
    case "std_core$string$Hash$hash":
      return `${head} { return vader_string_hash(a0); }`;

    // `@intrinsic <T> implements Display` for primitives — each shim spins
    // up a one-shot StringBuilder, calls the matching append_display_<T>
    // helper, then finishes. Reuses existing runtime infrastructure rather
    // than introducing parallel `vader_<T>_to_string` helpers.
    case "std_core$i8$Display$to_string":
    case "std_core$i16$Display$to_string":
    case "std_core$i32$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_i32(sb, (int32_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$i64$Display$to_string":
    case "std_core$isize$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_i64(sb, (int64_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$u8$Display$to_string":
    case "std_core$u16$Display$to_string":
    case "std_core$u32$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_u32(sb, (uint32_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$u64$Display$to_string":
    case "std_core$usize$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_u64(sb, (uint64_t) a0); return vader_builder_finish(sb); }`;
    case "std_core$f32$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_f32(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$f64$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_f64(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$bool$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_bool(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$char$Display$to_string":
      return `${head} { vader_builder_t* sb = vader_builder_new(); vader_builder_append_display_char(sb, a0); return vader_builder_finish(sb); }`;
    case "std_core$string$Display$to_string":
      return `${head} { return a0; }`;

    case "std_string_builder$StringBuilder$Display$to_string": {
      // `@intrinsic StringBuilder implements Display` — receiver is a boxed
      // StringBuilder whose only field `parts` holds the string[] buffer.
      // The mangled struct name is `<module>$StringBuilder` (or just
      // `StringBuilder` when the module stem matches the type name).
      const sbIdx = ctx.module.types.findIndex(
        (t) => t.kind === "struct"
            && (t.name === "StringBuilder" || t.name.endsWith("$StringBuilder")),
      );
      if (sbIdx < 0) return `${head} { vader_trap("StringBuilder type not found"); }`;
      const sbType = ctx.module.types[sbIdx] as BcStruct;
      // Inline-ref rep : StringBuilder's `parts` field IS the box payload,
      // there's no separate heap struct to deref. `a0.payload.obj` is the
      // string[] array obj pointer directly.
      const sbInline = !ctx.mutatedStructs.has(sbIdx) && inlineVariantPayload(sbType, ctx.module.types) === "ref";
      if (sbInline) {
        return `${head} { return vader_string_concat_all((vader_array_t*) a0.payload.obj); }`;
      }
      const sbCName = ctx.structNames[sbIdx]!;
      return `${head} { vader_box_t parts = ((${sbCName}*) a0.payload.obj)->f_parts; return vader_string_concat_all((vader_array_t*) parts.payload.obj); }`;
    }

    case "std_runtime$collect":      return `${head} { vader_gc_collect(); }`;
    case "std_runtime$collections":  return `${head} { return (int32_t) vader_gc_get_stats().total_collections; }`;
    case "std_runtime$bytes_used":   return `${head} { return (int32_t) vader_gc_get_stats().bytes_used; }`;
    case "std_runtime$bytes_copied": return `${head} { return (int32_t) vader_gc_get_stats().total_copied; }`;

    case "std_time$now_unix_ms": return `${head} { return vader_clock_realtime_ms(); }`;
    case "std_time$monotonic_ns": return `${head} { return vader_clock_monotonic_ns(); }`;

    case "std_math$sqrt":  return `${head} { return vader_math_sqrt(a0); }`;
    case "std_math$pow":   return `${head} { return vader_math_pow(a0, a1); }`;
    case "std_math$floor": return `${head} { return vader_math_floor(a0); }`;
    case "std_math$ceil":  return `${head} { return vader_math_ceil(a0); }`;
    case "std_math$round": return `${head} { return vader_math_round(a0); }`;
    case "std_math$sin":   return `${head} { return vader_math_sin(a0); }`;
    case "std_math$cos":   return `${head} { return vader_math_cos(a0); }`;
    case "std_math$tan":   return `${head} { return vader_math_tan(a0); }`;

    case "std_process$spawn_run":
      return `${head} { return vader_spawn_run((vader_array_t*) a0.payload.obj); }`;
    case "std_process$spawn_last_stdout":
      return `${head} { return vader_spawn_last_stdout(); }`;
    case "std_process$spawn_last_stderr":
      return `${head} { return vader_spawn_last_stderr(); }`;

    default:
      // User `@extern` — emit a forwarding shim that calls the real C
      // symbol (caller links via `--ldflags`). The forward `extern` decl
      // is emitted once per module by `userExternDeclarations()` above.
      if (imp.isExtern) return userExternShim(ctx, imp, head, ret);
      // Anything else hitting the default arm is a bytecode that requested
      // a host-fn the c-emit doesn't recognise — likely a compiler-runtime
      // version skew. Stay loud at runtime.
      return `${head} { vader_trap("unbound import: ${imp.mangledName}"); }`;
  }
}

/** Threshold below which a `string` extern arg is marshalled on the
 *  caller frame's stack instead of going through `malloc` /
 *  `vader_string_to_cstr`. 4 KiB stays well under any reasonable
 *  `ulimit -s` and covers the overwhelmingly common case (paths,
 *  identifiers, log lines). Larger strings fall back to the heap path. */
const VADER_EXTERN_STACK_CSTR_THRESHOLD = 4096;

function userExternShim(ctx: EmitCtx, imp: BcImport, head: string, ret: string): string {
  const stringIndices: number[] = [];
  const callArgs: string[] = [];
  for (let j = 0; j < imp.signature.params.length; j++) {
    if (imp.signature.params[j] === "string") {
      stringIndices.push(j);
      callArgs.push(`c${j}`);
    } else {
      callArgs.push(`a${j}`);
    }
  }
  // Hybrid string marshalling — stack-allocated NUL copy via a VLA for
  // small strings (no malloc/free in the steady state), heap fallback
  // through the runtime helper for anything past the threshold. Without
  // the stack path, a `c_strlen("hello")` paid malloc+free per call.
  const T = VADER_EXTERN_STACK_CSTR_THRESHOLD;
  const lines: string[] = [];
  for (const j of stringIndices) {
    lines.push(`char _b${j}[a${j}.len < ${T} ? a${j}.len + 1 : 1];`);
    lines.push(`const char* c${j};`);
    lines.push(`if (a${j}.len < ${T}) { if (a${j}.len > 0) memcpy(_b${j}, a${j}.ptr, a${j}.len); _b${j}[a${j}.len] = 0; c${j} = _b${j}; } else { c${j} = vader_string_to_cstr(a${j}); }`);
  }
  const isVoid = imp.signature.result === "void";
  const callExpr = `${imp.externName}(${callArgs.join(", ")})`;
  // Only heap-allocated copies need freeing — the VLA path lives on the
  // shim's stack frame and is reclaimed on return.
  const freeLines: string[] = [];
  for (let i = stringIndices.length - 1; i >= 0; i--) {
    const j = stringIndices[i]!;
    freeLines.push(`if (a${j}.len >= ${T}) vader_cstr_free(c${j});`);
  }
  if (isVoid) {
    lines.push(`${callExpr};`);
    lines.push(...freeLines);
    lines.push(`return;`);
  } else if (stringIndices.length === 0) {
    lines.push(`return ${callExpr};`);
  } else {
    lines.push(`${ret} r = ${callExpr};`);
    lines.push(...freeLines);
    lines.push(`return r;`);
  }
  return `${head} { ${lines.join(" ")} }`;
}

/** Map a `ValType` to its FOREIGN C-ABI type for `@extern` declarations
 *  — differs from `cTypeForVal` only on `string`, which the foreign side
 *  consumes as `const char*` (the shim marshals between `vader_string_t`
 *  and that). */
function externCType(v: ValType): string {
  if (v === "string") return "const char*";
  return cTypeForValBare(v);
}

function tagOrTrap(ctx: EmitCtx, kind: "string" | "error"): string {
  const idx = kind === "string" ? ctx.stringTagIndex : ctx.errorTagIndex;
  if (idx < 0) return `0u /* ${kind} tag absent */`;
  return `${idx}u`;
}

/** Primitive-type tag lookup for runtime calls that must box their result with
 *  the user-visible type's BcType index (e.g. `parse_int` boxing as `i32` so
 *  `match r { is i32 -> ... }` succeeds). */
function primTagOrTrap(ctx: EmitCtx, val: ValType): string {
  const idx = ctx.primitiveTagOf.get(val);
  if (idx === undefined) return `0u /* ${val} tag absent */`;
  return `${idx}u`;
}

// =========================================================================
// `main` entry
// =========================================================================

function emitMain(ctx: EmitCtx, out: string[]): void {
  const main = ctx.module.functions.findIndex((f) => f.isMain && f.body.length > 0);
  if (main < 0) {
    out.push(`int main(int argc, char** argv) { (void)argc; (void)argv; return 0; }`);
    return;
  }
  const fn = ctx.module.functions[main]!;
  const cname = ctx.fnNames[main]!;
  // Typechecker (T3033) guarantees the signature is `()` or `([string])` → i32.
  const takesArgv = fn.signature.params.length === 1;
  out.push(`int main(int argc, char** argv) {`);
  // Atom table init — must come before any code that interns or looks up
  // string atoms. Phase 0.d wires the comptime literals only ; Phase 1
  // will start consuming them once `vader_string_t` flips to `u32`.
  // `atexit(vader_atom_shutdown)` runs after `vader_gc_shutdown` thanks
  // to the LIFO ordering of atexit handlers.
  out.push(`    vader_atom_init_with_comptime(vader_atom_comptime_table, VADER_COMPTIME_ATOM_COUNT);`);
  out.push(`    atexit(vader_atom_shutdown);`);
  // Register the GC arena release at exit. Process death frees on Unix, but
  // an explicit shutdown is correct for embedded / atexit-aware tooling and
  // gives sanitisers a clean baseline.
  out.push(`    atexit(vader_gc_shutdown);`);
  let callArgs = "";
  if (takesArgv) {
    const strIdx = ctx.stringTagIndex;
    const arrIdx = ctx.module.types.findIndex(t => t.kind === "array" && t.element === strIdx);
    if (strIdx < 0 || arrIdx < 0) {
      out.push(`    (void)argc; (void)argv; vader_trap("main(argv): missing [string] type"); return 1;`);
      out.push(`}`);
      return;
    }
    out.push(`    vader_box_t __args = vader_box_obj(${arrIdx}u, vader_runtime_argv(argc, argv, ${arrIdx}u, ${strIdx}u));`);
    callArgs = "__args";
  } else {
    out.push(`    (void)argc; (void)argv;`);
  }
  if (fn.signature.result === "void") {
    out.push(`    ${cname}(${callArgs});`);
    out.push(`    return 0;`);
  } else {
    out.push(`    return (int) ${cname}(${callArgs});`);
  }
  out.push(`}`);
}

// =========================================================================
// String / identifier escapes
// =========================================================================

/** C keywords (C11 + a few common identifiers like `restrict` reserved by
 *  many compilers). Any user identifier that happens to match one is suffixed
 *  with `_v` so the emitted C is always valid. */
const C_RESERVED: ReadonlySet<string> = new Set([
  "auto", "break", "case", "char", "const", "continue", "default", "do",
  "double", "else", "enum", "extern", "float", "for", "goto", "if", "inline",
  "int", "long", "register", "restrict", "return", "short", "signed",
  "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned",
  "void", "volatile", "while", "_Alignas", "_Alignof", "_Atomic", "_Bool",
  "_Complex", "_Generic", "_Imaginary", "_Noreturn", "_Static_assert",
  "_Thread_local", "main",
]);

export function sanitise(raw: string): string {
  const out = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return C_RESERVED.has(out) ? `${out}_v` : out;
}

/** Maps a regular struct's C identifier (`vader_struct_<name>_t`) to its
 *  packed-payload mirror twin (`vader_packed_<name>_t`). The mirror is
 *  emitted by `emitTypeDecls` next to the regular typedef when the struct
 *  fits the multi-field packed-payload inline-variant. */
export function packedStructName(structCName: string): string {
  return structCName.replace(/^vader_struct_/, "vader_packed_");
}

export function cStringLit(s: string): string {
  return cStringLitFromBytes(new TextEncoder().encode(s));
}

export function cStringLitFromBytes(bytes: Uint8Array): string {
  let out = '"';
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i]!;
    if (b === 0x5c) out += "\\\\";
    else if (b === 0x22) out += "\\\"";
    else if (b === 0x0a) out += "\\n";
    else if (b === 0x0d) out += "\\r";
    else if (b === 0x09) out += "\\t";
    else if (b < 0x20 || b >= 0x7f) {
      // C `\x` escapes are unbounded — they consume every following hex digit
      // until the first non-hex character. If the next byte happens to be a
      // hex digit (or a continuation byte from a multi-byte UTF-8 codepoint),
      // close the escape with `""` so the digits start a fresh literal piece.
      out += `\\x${b.toString(16).padStart(2, "0")}`;
      const next = bytes[i + 1];
      if (next !== undefined && isCHexDigit(next)) out += '""';
    } else out += String.fromCharCode(b);
  }
  out += '"';
  return out;
}

function isCHexDigit(b: number): boolean {
  return (b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x46) || (b >= 0x61 && b <= 0x66);
}

export function escapeC(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

export function floatLit(v: number, suffix: string): string {
  if (!Number.isFinite(v)) {
    if (Number.isNaN(v)) return "(0.0/0.0)";
    return v > 0 ? "(1.0/0.0)" : "(-1.0/0.0)";
  }
  const s = v.toString();
  return s.includes(".") || s.includes("e") ? s + suffix : `${s}.0${suffix}`;
}

const I32_MIN = -2147483648;
const I32_MAX =  2147483647;
const I64_MIN_BIG = -(1n << 63n);
const I64_MAX_BIG =  (1n << 63n) - 1n;

/** C source for an i32 literal. Values outside the signed range round-trip
 *  through `(int32_t)UINT32_C(N)` to silence -Wconstant-conversion: the
 *  literal is born unsigned, then reinterpreted via two's complement.
 *  `INT32_MIN` itself can't be written as `INT32_C(-2147483648)` — that
 *  parses as unary minus applied to `2147483648`, which doesn't fit i32
 *  and is UB on strict toolchains; emit `INT32_MIN` (a stdint.h macro). */
export function i32LitC(value: number): string {
  if (value === I32_MIN) return `INT32_MIN`;
  if (value >= I32_MIN && value <= I32_MAX) return `INT32_C(${value})`;
  return `(int32_t)UINT32_C(${value >>> 0})`;
}

/** C source for an i64 literal. Same logic as `i32LitC` but for the 64-bit
 *  range. The bigint stays exact so unsigned values up to 2^64-1 round-trip
 *  through `(int64_t)UINT64_C(N)`. `INT64_MIN` likewise needs the macro to
 *  dodge the unary-minus / overflow trap. */
export function i64LitC(value: bigint): string {
  if (value === I64_MIN_BIG) return `INT64_MIN`;
  if (value >= I64_MIN_BIG && value <= I64_MAX_BIG) return `INT64_C(${value.toString()})`;
  const u = value & ((1n << 64n) - 1n);
  return `(int64_t)UINT64_C(${u.toString()})`;
}
