/* Generated by vader — do not edit. */
#include "vader.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

typedef struct vader_struct___defer_env_snippet_1_t vader_struct___defer_env_snippet_1_t;
typedef struct vader_struct___defer_env_snippet_3_t vader_struct___defer_env_snippet_3_t;
typedef struct vader_struct___defer_env_snippet_5_t vader_struct___defer_env_snippet_5_t;
typedef struct vader_struct_std_core_Buffer_t vader_struct_std_core_Buffer_t;
typedef struct vader_struct__Cell_i32_t vader_struct__Cell_i32_t;

struct vader_struct___defer_env_snippet_1_t {
    vader_obj_header_t header;
    vader_box_t f_cap_0;
};
struct vader_struct___defer_env_snippet_3_t {
    vader_obj_header_t header;
    vader_box_t f_cap_0;
};
struct vader_struct___defer_env_snippet_5_t {
    vader_obj_header_t header;
    vader_box_t f_cap_0;
};
struct vader_struct_std_core_Buffer_t {
    vader_obj_header_t header;
};
struct vader_struct__Cell_i32_t {
    vader_obj_header_t header;
    int32_t f_value;
};

/* Compile-time atom table — see docs/ATOM_INTERNING.md. */
static const char vader_atom_blob[] =
    "continue: " "\0"
    ":" "\0"
    "break: " "\0"
    "after round " "\0"
    "  defer of a copy, round " "\0"
    "\n" "\0";

static const vader_atom_entry_t vader_atom_comptime_table[] = {
    { 0u, 0u, 10u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[0] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[11] },
    { 0u, 0u, 7u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[13] },
    { 0u, 0u, 12u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[21] },
    { 0u, 0u, 25u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[34] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[60] },
};

#define VADER_COMPTIME_ATOM_COUNT 6u

static int32_t snippet_main(void);
static void __defer_snippet_0(void* l0);
static void __defer_snippet_2(void* l0);
static void __defer_snippet_4(void* l0);
static vader_string_t concat_2(vader_string_t l0, vader_string_t l1);
static void* std_core_new_byte_buffer(size_t l0);
static vader_string_t std_core_finish_buffer(void* l0, size_t l1);
static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2);
static size_t std_core_write_int(void* l0, size_t l1, int64_t l2);
static void std_io_write(uint8_t l0, vader_string_t l1);
static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2);
static void std_io_println__string(vader_string_t l0);
static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0);
static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2);
static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1);
static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2);

typedef vader_box_t (*vader_fn_erased_sig_0_t)(void* env);

static vader_box_t vader_fn_lift___defer_snippet_0(void* env) {
    __defer_snippet_0(env);
    return vader_box_null();
}

static vader_box_t vader_fn_lift___defer_snippet_2(void* env) {
    __defer_snippet_2(env);
    return vader_box_null();
}

static vader_box_t vader_fn_lift___defer_snippet_4(void* env) {
    __defer_snippet_4(env);
    return vader_box_null();
}

static const uint16_t vader_fn_ptr_offsets[] = { offsetof(vader_fn_t, env) };
static const uint16_t vader_array_ptr_offsets[] = { offsetof(vader_array_t, buf) };

const vader_type_info_t vader_type_info_table[16] = {
    [1] = { .slot_size = 4 },
    [2] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___defer_env_snippet_1_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___defer_env_snippet_1_t, f_cap_0) },
        .ptr_count = 1,
    },
    [4] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___defer_env_snippet_3_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___defer_env_snippet_3_t, f_cap_0) },
        .ptr_count = 1,
    },
    [5] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___defer_env_snippet_5_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___defer_env_snippet_5_t, f_cap_0) },
        .ptr_count = 1,
    },
    [6] = { .slot_size = 16 },
    [7] = { .slot_size = 16 },
    [8] = { .slot_size = 1 },
    [9] = { .slot_size = 8 },
    [10] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Buffer_t),
        .slot_size = 8,
    },
    [11] = { .slot_size = 8 },
    [12] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [13] = { .slot_size = 8 },
    [14] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct__Cell_i32_t), .slot_size = 8,
    },
    [15] = {
        .kind = VADER_TYPE_KIND_FN, .size = sizeof(vader_fn_t), .slot_size = 8,
        .ptr_offsets = vader_fn_ptr_offsets, .ptr_count = 1,
    },
};
const size_t vader_type_info_count = 16;

/* Headers named by `@c_header` — they own the prototypes below. */
#include <unistd.h>

static size_t vader_host_std_core_byte_len(vader_string_t a0) {
    return vader_string_byte_len(a0);
}

static void* vader_host_std_core_bytes(vader_string_t a0) {
    return (void*) vader_string_bytes_view(a0, 12u, 8u);
}

static ptrdiff_t vader_host_system_posix_sys_write(int32_t a0, void* a1, size_t a2) {
    vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1);
    return write(a0, s1.ptr, a2);
}

static int32_t snippet_main(void) {
    int32_t l0;
    void* l1 = NULL;
    void* l5 = NULL;
    void* l9 = NULL;
    void* l14 = NULL;
    size_t l2, l6, l10, l15;
    int64_t l3, l4, l7, l8, l11, l12, l16;
    vader_box_t l13 = vader_box_null();
    vader_string_t t0 = 0;
    void* t1 = NULL;
    vader_box_t* gc_roots[1] = { &l13 };
    void** gc_raw_roots[5] = { &l1, &l5, &l9, &l14, &t1 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 1u, 5u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 11 "tests/snippets/comptime_for_jumps/_main.vader"
    l0 = INT32_C(0);
    while ((l0 < INT32_C(2))) {
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 13 "tests/snippets/comptime_for_jumps/_main.vader"
        if (INT32_C(1) == INT32_C(2)) {
#line 16 "tests/snippets/comptime_for_jumps/_main.vader"
        } else {
            l1 = std_core_new_byte_buffer((size_t) 51);
            l2 = (size_t) 0;
            l2 = std_core_write_string_at(l1, l2, 1u);
            l3 = ((int64_t) (int32_t) l0);
            l2 = std_core_write_int(l1, l2, l3);
            l2 = std_core_write_string_at(l1, l2, 2u);
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 16 "tests/snippets/comptime_for_jumps/_main.vader"
            l4 = ((int64_t) 1);
            l2 = std_core_write_int(l1, l2, l4);
            t0 = std_core_finish_buffer(l1, l2);
            std_io_println__string(t0);
#line 13 "tests/snippets/comptime_for_jumps/_main.vader"
        }
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 13 "tests/snippets/comptime_for_jumps/_main.vader"
        if (INT32_C(2) == INT32_C(2)) {
#line 16 "tests/snippets/comptime_for_jumps/_main.vader"
        } else {
            l5 = std_core_new_byte_buffer((size_t) 51);
            l6 = (size_t) 0;
            l6 = std_core_write_string_at(l5, l6, 1u);
            l7 = ((int64_t) (int32_t) l0);
            l6 = std_core_write_int(l5, l6, l7);
            l6 = std_core_write_string_at(l5, l6, 2u);
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 16 "tests/snippets/comptime_for_jumps/_main.vader"
            l8 = ((int64_t) 2);
            l6 = std_core_write_int(l5, l6, l8);
            t0 = std_core_finish_buffer(l5, l6);
            std_io_println__string(t0);
#line 13 "tests/snippets/comptime_for_jumps/_main.vader"
        }
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 13 "tests/snippets/comptime_for_jumps/_main.vader"
        if (INT32_C(3) == INT32_C(2)) {
#line 16 "tests/snippets/comptime_for_jumps/_main.vader"
        } else {
            l9 = std_core_new_byte_buffer((size_t) 51);
            l10 = (size_t) 0;
            l10 = std_core_write_string_at(l9, l10, 1u);
            l11 = ((int64_t) (int32_t) l0);
            l10 = std_core_write_int(l9, l10, l11);
            l10 = std_core_write_string_at(l9, l10, 2u);
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 16 "tests/snippets/comptime_for_jumps/_main.vader"
            l12 = ((int64_t) 3);
            l10 = std_core_write_int(l9, l10, l12);
            t0 = std_core_finish_buffer(l9, l10);
            std_io_println__string(t0);
#line 13 "tests/snippets/comptime_for_jumps/_main.vader"
        }
#line 12 "tests/snippets/comptime_for_jumps/_main.vader"
#line 11 "tests/snippets/comptime_for_jumps/_main.vader"
        l0 = (l0 + INT32_C(1));
    }
#line 19 "tests/snippets/comptime_for_jumps/_main.vader"
    l0 = INT32_C(0);
    while ((l0 < INT32_C(2))) {
        vader_struct__Cell_i32_t* _a0_obj = (vader_struct__Cell_i32_t*) vader_gc_alloc(sizeof(vader_struct__Cell_i32_t));
        vader_obj_header_init(_a0_obj, 14u);
        _a0_obj->f_value = l0;
        t1 = (void*) _a0_obj;
        l13 = vader_ref_box(t1);
#line 20 "tests/snippets/comptime_for_jumps/_main.vader"
        {
#line 21 "tests/snippets/comptime_for_jumps/_main.vader"
            vader_struct___defer_env_snippet_1_t* _a1_obj = (vader_struct___defer_env_snippet_1_t*) vader_gc_alloc(sizeof(vader_struct___defer_env_snippet_1_t));
            vader_obj_header_init(_a1_obj, 2u);
            _a1_obj->f_cap_0 = l13;
            t1 = (void*) _a1_obj;
            vader_fn_t* _a2_closure = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));
            vader_obj_header_init(_a2_closure, 15u);
            _a2_closure->code = (void*) &vader_fn_lift___defer_snippet_0;
            _a2_closure->env = t1;
            t1 = (void*) _a2_closure;
            vader_defer_push(vader_ref_box(t1));
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
            if (INT32_C(1) == INT32_C(2)) {
#line 23 "tests/snippets/comptime_for_jumps/_main.vader"
                vader_defer_pop_exec(1u);
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
#line 25 "tests/snippets/comptime_for_jumps/_main.vader"
            } else {
                l1 = std_core_new_byte_buffer((size_t) 48);
                l2 = (size_t) 0;
                l2 = std_core_write_string_at(l1, l2, 3u);
                l3 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l13.payload.obj)->f_value);
                l2 = std_core_write_int(l1, l2, l3);
                l2 = std_core_write_string_at(l1, l2, 2u);
#line 20 "tests/snippets/comptime_for_jumps/_main.vader"
#line 25 "tests/snippets/comptime_for_jumps/_main.vader"
                l4 = ((int64_t) 1);
                l2 = std_core_write_int(l1, l2, l4);
                t0 = std_core_finish_buffer(l1, l2);
                std_io_println__string(t0);
                vader_defer_pop_exec(1u);
#line 21 "tests/snippets/comptime_for_jumps/_main.vader"
                vader_struct___defer_env_snippet_3_t* _a3_obj = (vader_struct___defer_env_snippet_3_t*) vader_gc_alloc(sizeof(vader_struct___defer_env_snippet_3_t));
                vader_obj_header_init(_a3_obj, 4u);
                _a3_obj->f_cap_0 = l13;
                t1 = (void*) _a3_obj;
                vader_fn_t* _a4_closure = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));
                vader_obj_header_init(_a4_closure, 15u);
                _a4_closure->code = (void*) &vader_fn_lift___defer_snippet_2;
                _a4_closure->env = t1;
                t1 = (void*) _a4_closure;
                vader_defer_push(vader_ref_box(t1));
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
                if (INT32_C(2) == INT32_C(2)) {
#line 23 "tests/snippets/comptime_for_jumps/_main.vader"
                    vader_defer_pop_exec(1u);
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
#line 25 "tests/snippets/comptime_for_jumps/_main.vader"
                } else {
                    l5 = std_core_new_byte_buffer((size_t) 48);
                    l6 = (size_t) 0;
                    l6 = std_core_write_string_at(l5, l6, 3u);
                    l7 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l13.payload.obj)->f_value);
                    l6 = std_core_write_int(l5, l6, l7);
                    l6 = std_core_write_string_at(l5, l6, 2u);
#line 20 "tests/snippets/comptime_for_jumps/_main.vader"
#line 25 "tests/snippets/comptime_for_jumps/_main.vader"
                    l8 = ((int64_t) 2);
                    l6 = std_core_write_int(l5, l6, l8);
                    t0 = std_core_finish_buffer(l5, l6);
                    std_io_println__string(t0);
                    vader_defer_pop_exec(1u);
#line 21 "tests/snippets/comptime_for_jumps/_main.vader"
                    vader_struct___defer_env_snippet_5_t* _a5_obj = (vader_struct___defer_env_snippet_5_t*) vader_gc_alloc(sizeof(vader_struct___defer_env_snippet_5_t));
                    vader_obj_header_init(_a5_obj, 5u);
                    _a5_obj->f_cap_0 = l13;
                    t1 = (void*) _a5_obj;
                    vader_fn_t* _a6_closure = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));
                    vader_obj_header_init(_a6_closure, 15u);
                    _a6_closure->code = (void*) &vader_fn_lift___defer_snippet_4;
                    _a6_closure->env = t1;
                    t1 = (void*) _a6_closure;
                    vader_defer_push(vader_ref_box(t1));
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
                    if (INT32_C(3) == INT32_C(2)) {
#line 23 "tests/snippets/comptime_for_jumps/_main.vader"
                        vader_defer_pop_exec(1u);
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
#line 25 "tests/snippets/comptime_for_jumps/_main.vader"
                    } else {
                        l9 = std_core_new_byte_buffer((size_t) 48);
                        l10 = (size_t) 0;
                        l10 = std_core_write_string_at(l9, l10, 3u);
                        l11 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l13.payload.obj)->f_value);
                        l10 = std_core_write_int(l9, l10, l11);
                        l10 = std_core_write_string_at(l9, l10, 2u);
#line 20 "tests/snippets/comptime_for_jumps/_main.vader"
#line 25 "tests/snippets/comptime_for_jumps/_main.vader"
                        l12 = ((int64_t) 3);
                        l10 = std_core_write_int(l9, l10, l12);
                        t0 = std_core_finish_buffer(l9, l10);
                        std_io_println__string(t0);
                        vader_defer_pop_exec(1u);
#line 22 "tests/snippets/comptime_for_jumps/_main.vader"
                    }
                }
            }
#line 20 "tests/snippets/comptime_for_jumps/_main.vader"
        }
#line 27 "tests/snippets/comptime_for_jumps/_main.vader"
        l14 = std_core_new_byte_buffer((size_t) 32);
        l15 = (size_t) 0;
        l15 = std_core_write_string_at(l14, l15, 4u);
        l16 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l13.payload.obj)->f_value);
        l15 = std_core_write_int(l14, l15, l16);
        t0 = std_core_finish_buffer(l14, l15);
        std_io_println__string(t0);
#line 19 "tests/snippets/comptime_for_jumps/_main.vader"
        l0 = (l0 + INT32_C(1));
    }
#line 29 "tests/snippets/comptime_for_jumps/_main.vader"
    { vader_gc_top = gc_frame.prev; return INT32_C(0); }
}

static void __defer_snippet_0(void* l0) {
    void* l1 = NULL;
    size_t l2;
    int64_t l3;
    vader_string_t t0 = 0;
    void** gc_raw_roots[2] = { &l0, &l1 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 21 "tests/snippets/comptime_for_jumps/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 45);
    l2 = (size_t) 0;
    l2 = std_core_write_string_at(l1, l2, 5u);
    l3 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) ((vader_struct___defer_env_snippet_1_t*) l0)->f_cap_0.payload.obj)->f_value);
    l2 = std_core_write_int(l1, l2, l3);
    t0 = std_core_finish_buffer(l1, l2);
    std_io_println__string(t0);
    { vader_gc_top = gc_frame.prev; return; }
}

static void __defer_snippet_2(void* l0) {
    void* l1 = NULL;
    size_t l2;
    int64_t l3;
    vader_string_t t0 = 0;
    void** gc_raw_roots[2] = { &l0, &l1 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 21 "tests/snippets/comptime_for_jumps/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 45);
    l2 = (size_t) 0;
    l2 = std_core_write_string_at(l1, l2, 5u);
    l3 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) ((vader_struct___defer_env_snippet_3_t*) l0)->f_cap_0.payload.obj)->f_value);
    l2 = std_core_write_int(l1, l2, l3);
    t0 = std_core_finish_buffer(l1, l2);
    std_io_println__string(t0);
    { vader_gc_top = gc_frame.prev; return; }
}

static void __defer_snippet_4(void* l0) {
    void* l1 = NULL;
    size_t l2;
    int64_t l3;
    vader_string_t t0 = 0;
    void** gc_raw_roots[2] = { &l0, &l1 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 21 "tests/snippets/comptime_for_jumps/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 45);
    l2 = (size_t) 0;
    l2 = std_core_write_string_at(l1, l2, 5u);
    l3 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) ((vader_struct___defer_env_snippet_5_t*) l0)->f_cap_0.payload.obj)->f_value);
    l2 = std_core_write_int(l1, l2, l3);
    t0 = std_core_finish_buffer(l1, l2);
    std_io_println__string(t0);
    { vader_gc_top = gc_frame.prev; return; }
}

static vader_string_t concat_2(vader_string_t l0, vader_string_t l1) {
    size_t l2, l3;
    void* l4 = NULL;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l4 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l1, &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    l2 = vader_host_std_core_byte_len(l0);
    l3 = vader_host_std_core_byte_len(l1);
    t0 = (l2 + l3);
    l3 = (size_t) (int64_t) t0;
    l4 = std_core_usize_BufferAlloc_new_buffer_vt(l3);
    std_core_Buffer_ByteAccess_write_string_vt(l4, (size_t) 0, l0);
    std_core_Buffer_ByteAccess_write_string_vt(l4, l2, l1);
    t1 = std_core_Buffer_ByteAccess_intern_string_vt(l4, l3);
    { vader_string_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_new_byte_buffer(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 101 "lib/std/core/primitives.vader"
    t0 = std_core_usize_BufferAlloc_new_buffer_vt(l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t std_core_finish_buffer(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 104 "lib/std/core/primitives.vader"
    t0 = std_core_Buffer_ByteAccess_intern_string_vt(l0, l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2) {
    size_t l3;
#line 121 "lib/std/core/primitives.vader"
    std_core_Buffer_ByteAccess_write_string_vt(l0, l1, l2);
#line 122 "lib/std/core/primitives.vader"
    l3 = vader_host_std_core_byte_len(l2);
    return (size_t) (int64_t) (l1 + l3);
}

static size_t std_core_write_int(void* l0, size_t l1, int64_t l2) {
    bool l3;
    size_t l4, l6;
    int64_t l5;
    uint8_t l7, l8;
    int64_t t0;
    int32_t t1;
#line 127 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 128 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 129 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 127 "lib/std/core/primitives.vader"
    }
#line 131 "lib/std/core/primitives.vader"
    l3 = (l2 < INT64_C(0));
#line 132 "lib/std/core/primitives.vader"
    if ((l2 > INT64_C(0))) {
        l2 = -(l2);
    }
#line 133 "lib/std/core/primitives.vader"
    l4 = (size_t) 0;
#line 134 "lib/std/core/primitives.vader"
    l5 = l2;
#line 135 "lib/std/core/primitives.vader"
    while (l5 != INT64_C(0)) {
#line 136 "lib/std/core/primitives.vader"
        t0 = (l4 + INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 137 "lib/std/core/primitives.vader"
        l5 = vader_div_i64(l5, INT64_C(10));
#line 135 "lib/std/core/primitives.vader"
    }
#line 139 "lib/std/core/primitives.vader"
    if (l3) {
        t0 = (l4 + INT64_C(1));
        l6 = (size_t) (int64_t) t0;
    } else {
        l6 = l4;
    }
#line 140 "lib/std/core/primitives.vader"
    t0 = (l1 + l6);
    l4 = (size_t) (int64_t) t0;
#line 141 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 142 "lib/std/core/primitives.vader"
        t0 = (l4 - INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 143 "lib/std/core/primitives.vader"
        t0 = vader_mod_i64(l2, INT64_C(10));
        t1 = (((int32_t) (int64_t) -(t0)) & INT32_C(255));
        l7 = (uint8_t) (int32_t) t1;
        t1 = ((INT32_C(48) + l7) & INT32_C(255));
        l8 = (uint8_t) (int32_t) t1;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l4, l8);
#line 144 "lib/std/core/primitives.vader"
        l2 = vader_div_i64(l2, INT64_C(10));
#line 141 "lib/std/core/primitives.vader"
    }
#line 146 "lib/std/core/primitives.vader"
    if (l3) {
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 45);
    }
#line 147 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l6);
}

static void std_io_write(uint8_t l0, vader_string_t l1) {
    void* l2 = NULL;
    void* l6 = NULL;
    size_t l3, l4, l5, l7, l9;
    int32_t l8;
    int64_t t0;
    void** gc_raw_roots[2] = { &l2, &l6 };
    vader_string_t* gc_atom_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 205 "lib/std/io/io.vader"
    l2 = vader_host_std_core_bytes(l1);
#line 206 "lib/std/io/io.vader"
    l3 = (size_t) 0;
#line 207 "lib/std/io/io.vader"
    for (;;) {
#line 208 "lib/std/io/io.vader"
        l4 = ((vader_array_t*) l2)->length;
        if ((l3 >= l4)) {
#line 209 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 208 "lib/std/io/io.vader"
        }
#line 211 "lib/std/io/io.vader"
        l5 = ((vader_array_t*) l2)->length;
        vader_array_t* _a0_arr = vader_array_slice((vader_array_t*) l2, (size_t) l3, (size_t) l5);
        l6 = (void*) _a0_arr;
#line 212 "lib/std/io/io.vader"
        l7 = ((vader_array_t*) l6)->length;
        l8 = std_io_write_bytes(l0, l6, l7);
#line 213 "lib/std/io/io.vader"
        if ((l8 <= INT32_C(0))) {
#line 214 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 213 "lib/std/io/io.vader"
        }
#line 216 "lib/std/io/io.vader"
        t0 = ((int64_t) (int32_t) l8);
        l9 = (size_t) (int64_t) t0;
        t0 = (l3 + l9);
        l3 = (size_t) (int64_t) t0;
#line 207 "lib/std/io/io.vader"
        continue;
    }
#line 209 "lib/std/io/io.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2) {
    int32_t l3;
    ptrdiff_t t0;
    void** gc_raw_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 177 "lib/std/io/io.vader"
    if (l0 == INT32_C(0)) {
        l3 = INT32_C(1);
    } else {
        l3 = INT32_C(2);
    }
#line 180 "lib/std/io/io.vader"
    t0 = vader_host_system_posix_sys_write(l3, l1, l2);
    { int32_t __vret = ((int32_t) (ptrdiff_t) t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_println__string(vader_string_t l0) {
    vader_string_t l1 = 0;
    vader_string_t* gc_atom_roots[2] = { &l0, &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL, 2u, gc_atom_roots };
    vader_gc_top = &gc_frame;
#line 235 "lib/std/io/io.vader"
    l1 = concat_2(l0, 6u);
    std_io_write((uint8_t) 0, l1);
    { vader_gc_top = gc_frame.prev; return; }
}

static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
    t0 = (void*) vader_buffer_new((size_t) l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2) {
    vader_buffer_store_u8((vader_buffer_t*) l0, (size_t) l1, (uint8_t) l2);
    return;
}

static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    t0 = vader_buffer_intern_string((vader_buffer_t*) l0, (size_t) l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2) {
    vader_buffer_write_string((vader_buffer_t*) l0, (size_t) l1, l2);
    return;
}

int main(int argc, char** argv) {
    vader_atom_init_with_comptime(vader_atom_comptime_table, VADER_COMPTIME_ATOM_COUNT);
    atexit(vader_atom_shutdown);
    atexit(vader_gc_shutdown);
    (void) argc;
    (void) argv;
    return (int) snippet_main();
}
