/* Generated by vader — do not edit. */
#include "vader.h"
#include <stddef.h>
#include <string.h>

typedef struct vader_struct_std_collections_Entry__i32__i32_t vader_struct_std_collections_Entry__i32__i32_t;
typedef struct vader_struct_std_collections_MutableMap__i32__i32_t vader_struct_std_collections_MutableMap__i32__i32_t;

struct vader_struct_std_collections_Entry__i32__i32_t {
    vader_obj_header_t header;
    int32_t f_key;
    int32_t f_value;
    vader_box_t f_next;
};
struct vader_struct_std_collections_MutableMap__i32__i32_t {
    vader_obj_header_t header;
    vader_box_t f_buckets;
    size_t f_size;
};

static const char vader_str_0_data[] = "size = ";
static const size_t vader_str_0_len = 7;
static const char vader_str_1_data[] = "v1: missing";
static const size_t vader_str_1_len = 11;
static const char vader_str_2_data[] = "v1 = ";
static const size_t vader_str_2_len = 5;
static const char vader_str_3_data[] = "v17: missing";
static const size_t vader_str_3_len = 12;
static const char vader_str_4_data[] = "v17 = ";
static const size_t vader_str_4_len = 6;
static const char vader_str_5_data[] = "has 2? ";
static const size_t vader_str_5_len = 7;
static const char vader_str_6_data[] = "has 99? ";
static const size_t vader_str_6_len = 8;
static const char vader_str_7_data[] = "v1b: missing";
static const size_t vader_str_7_len = 12;
static const char vader_str_8_data[] = "v1b = ";
static const size_t vader_str_8_len = 6;

static int32_t tests_snippets_mutable_map__main_vader_main(void);
static uint64_t std_core_i32_Hash_hash(int32_t l0);
static bool std_core_i32_Eq_equals(int32_t l0, int32_t l1);
static int32_t std_collections_bucket_index(uint64_t l0);
static void std_collections_std_collections_put__i32__i32(vader_box_t l0, int32_t l1, int32_t l2);
static vader_box_t std_collections_std_collections_get__i32__i32(vader_box_t l0, int32_t l1);
static bool std_collections_std_collections_contains_key__i32__i32(vader_box_t l0, int32_t l1);
static size_t std_collections_std_collections_len__i32__i32(vader_box_t l0);


static const uint16_t vader_type_0_ptrs[] = { offsetof(vader_struct_std_collections_Entry__i32__i32_t, f_next) };
static const uint16_t vader_type_4_ptrs[] = { offsetof(vader_struct_std_collections_MutableMap__i32__i32_t, f_buckets) };
static const uint16_t vader_type_5_ptrs[] = { offsetof(vader_array_t, buf) };

const vader_type_info_t vader_type_info_table[] = {
    [0] = { VADER_TYPE_KIND_STRUCT, sizeof(vader_struct_std_collections_Entry__i32__i32_t), vader_type_0_ptrs, 1, 0 },
    [4] = { VADER_TYPE_KIND_STRUCT, sizeof(vader_struct_std_collections_MutableMap__i32__i32_t), vader_type_4_ptrs, 1, 0 },
    [5] = { VADER_TYPE_KIND_ARRAY, sizeof(vader_array_t), vader_type_5_ptrs, 1, 0 },
};
const size_t vader_type_info_count = 7;

static void vader_import_0(vader_string_t a0) { vader_print(a0); }
static void vader_import_1(vader_string_t a0) { vader_println(a0); }
static vader_box_t vader_import_2(void) { return vader_read_line(0u /* string tag absent */, 0u /* error tag absent */); }
static vader_box_t vader_import_3(vader_string_t a0) { return vader_read_file(a0, 0u /* string tag absent */, 0u /* error tag absent */); }
static vader_box_t vader_import_4(vader_string_t a0, vader_string_t a1) { return vader_write_file(a0, a1, 0u, 0u /* error tag absent */); }
static bool vader_import_5(vader_string_t a0) { return vader_exists(a0); }

static int32_t tests_snippets_mutable_map__main_vader_main(void) {
    vader_box_t l0 = vader_box_null();
    vader_box_t l1 = vader_box_null();
    vader_box_t l2 = vader_box_null();
    vader_box_t l3 = vader_box_null();
    vader_box_t l4 = vader_box_null();
    vader_box_t l5 = vader_box_null();
    vader_box_t l6 = vader_box_null();
    vader_box_t l7 = vader_box_null();
    vader_box_t l8 = vader_box_null();
    vader_box_t l9 = vader_box_null();
    vader_box_t l10 = vader_box_null();
    vader_box_t l11 = vader_box_null();
    vader_box_t l12 = vader_box_null();
    vader_box_t t0 = vader_box_null();
    vader_box_t t2 = vader_box_null();
    vader_box_t t5 = vader_box_null();
    vader_box_t t8 = vader_box_null();
    vader_box_t t11 = vader_box_null();
    vader_box_t t13 = vader_box_null();
    vader_box_t t14 = vader_box_null();
    vader_box_t t16 = vader_box_null();
    vader_box_t t18 = vader_box_null();
    vader_box_t t20 = vader_box_null();
    vader_box_t t23 = vader_box_null();
    vader_box_t t25 = vader_box_null();
    vader_box_t t27 = vader_box_null();
    vader_box_t t28 = vader_box_null();
    vader_box_t t29 = vader_box_null();
    vader_box_t t31 = vader_box_null();
    vader_box_t t33 = vader_box_null();
    vader_box_t t36 = vader_box_null();
    vader_box_t t38 = vader_box_null();
    vader_box_t t40 = vader_box_null();
    vader_box_t t41 = vader_box_null();
    vader_box_t t42 = vader_box_null();
    vader_box_t t44 = vader_box_null();
    vader_box_t t46 = vader_box_null();
    vader_box_t t47 = vader_box_null();
    vader_box_t t50 = vader_box_null();
    vader_box_t t52 = vader_box_null();
    vader_box_t t54 = vader_box_null();
    vader_box_t t55 = vader_box_null();
    vader_box_t t58 = vader_box_null();
    vader_box_t t60 = vader_box_null();
    vader_box_t t63 = vader_box_null();
    vader_box_t t65 = vader_box_null();
    vader_box_t t68 = vader_box_null();
    vader_box_t t70 = vader_box_null();
    vader_box_t t72 = vader_box_null();
    vader_box_t t73 = vader_box_null();
    vader_box_t t74 = vader_box_null();
    vader_box_t* gc_roots[51] = { &l0, &l1, &l2, &l3, &l4, &l5, &l6, &l7, &l8, &l9, &l10, &l11, &l12, &t0, &t2, &t5, &t8, &t11, &t13, &t14, &t16, &t18, &t20, &t23, &t25, &t27, &t28, &t29, &t31, &t33, &t36, &t38, &t40, &t41, &t42, &t44, &t46, &t47, &t50, &t52, &t54, &t55, &t58, &t60, &t63, &t65, &t68, &t70, &t72, &t73, &t74 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 51u, 0u, gc_roots };
    vader_gc_top = &gc_frame;
    vader_array_t* t0_arr = vader_array_new(5u, 0u);
    t0 = vader_box_obj(5u, t0_arr);
    int64_t t1 = INT64_C(0);
    vader_struct_std_collections_MutableMap__i32__i32_t* t2_obj = (vader_struct_std_collections_MutableMap__i32__i32_t*) vader_alloc(sizeof(vader_struct_std_collections_MutableMap__i32__i32_t));
    t2_obj->header.type_index = 4u;
    t2_obj->header._pad = 0u;
    t2_obj->header.forward = NULL;
    t2_obj->f_buckets = (vader_box_t) t0;
    t2_obj->f_size = (size_t) t1;
    t2 = vader_box_obj(4u, t2_obj);
    l0 = t2;
    int32_t t3 = INT32_C(1);
    int32_t t4 = INT32_C(10);
    std_collections_std_collections_put__i32__i32(t2, t3, t4);
    t5 = l0;
    int32_t t6 = INT32_C(2);
    int32_t t7 = INT32_C(20);
    std_collections_std_collections_put__i32__i32(t5, t6, t7);
    t8 = l0;
    int32_t t9 = INT32_C(17);
    int32_t t10 = INT32_C(170);
    std_collections_std_collections_put__i32__i32(t8, t9, t10);
    t11.tag = 0; t11._pad = 0; t11.payload.obj = vader_builder_new();
    l1 = t11;
    vader_string_t t12 = vader_string_new(vader_str_0_data, vader_str_0_len);
    vader_builder_append_str((vader_builder_t*) t11.payload.obj, t12);
    t13 = l1;
    t14 = l0;
    size_t t15 = std_collections_std_collections_len__i32__i32(t14);
    vader_builder_append_display_u64((vader_builder_t*) t13.payload.obj, t15);
    t16 = l1;
    vader_string_t t17 = vader_builder_finish((vader_builder_t*) t16.payload.obj);
    vader_import_1(t17);
    t18 = l0;
    int32_t t19 = INT32_C(1);
    t20 = std_collections_std_collections_get__i32__i32(t18, t19);
    l2 = t20;
    l3 = t20;
    bool t21 = (t20.tag == 3u);
    if (t21) {
        vader_string_t t22 = vader_string_new(vader_str_1_data, vader_str_1_len);
        vader_import_1(t22);
    } else { /* else */
        t23 = l3;
        bool t24 = (t23.tag == 1u);
        if (t24) {
            t25.tag = 0; t25._pad = 0; t25.payload.obj = vader_builder_new();
            l4 = t25;
            vader_string_t t26 = vader_string_new(vader_str_2_data, vader_str_2_len);
            vader_builder_append_str((vader_builder_t*) t25.payload.obj, t26);
            t27 = l4;
            t28 = l2;
            vader_builder_append_display_string((vader_builder_t*) t27.payload.obj, t28);
            t29 = l4;
            vader_string_t t30 = vader_builder_finish((vader_builder_t*) t29.payload.obj);
            vader_import_1(t30);
        } else { /* else */
            vader_unreachable("tests_snippets_mutable_map__main_vader$main+50");
        } end_38: ;
    } end_32: ;
    t31 = l0;
    int32_t t32 = INT32_C(17);
    t33 = std_collections_std_collections_get__i32__i32(t31, t32);
    l5 = t33;
    l6 = t33;
    bool t34 = (t33.tag == 3u);
    if (t34) {
        vader_string_t t35 = vader_string_new(vader_str_3_data, vader_str_3_len);
        vader_import_1(t35);
    } else { /* else */
        t36 = l6;
        bool t37 = (t36.tag == 1u);
        if (t37) {
            t38.tag = 0; t38._pad = 0; t38.payload.obj = vader_builder_new();
            l7 = t38;
            vader_string_t t39 = vader_string_new(vader_str_4_data, vader_str_4_len);
            vader_builder_append_str((vader_builder_t*) t38.payload.obj, t39);
            t40 = l7;
            t41 = l5;
            vader_builder_append_display_string((vader_builder_t*) t40.payload.obj, t41);
            t42 = l7;
            vader_string_t t43 = vader_builder_finish((vader_builder_t*) t42.payload.obj);
            vader_import_1(t43);
        } else { /* else */
            vader_unreachable("tests_snippets_mutable_map__main_vader$main+77");
        } end_65: ;
    } end_59: ;
    t44.tag = 0; t44._pad = 0; t44.payload.obj = vader_builder_new();
    l8 = t44;
    vader_string_t t45 = vader_string_new(vader_str_5_data, vader_str_5_len);
    vader_builder_append_str((vader_builder_t*) t44.payload.obj, t45);
    t46 = l8;
    t47 = l0;
    int32_t t48 = INT32_C(2);
    bool t49 = std_collections_std_collections_contains_key__i32__i32(t47, t48);
    vader_builder_append_display_bool((vader_builder_t*) t46.payload.obj, t49);
    t50 = l8;
    vader_string_t t51 = vader_builder_finish((vader_builder_t*) t50.payload.obj);
    vader_import_1(t51);
    t52.tag = 0; t52._pad = 0; t52.payload.obj = vader_builder_new();
    l9 = t52;
    vader_string_t t53 = vader_string_new(vader_str_6_data, vader_str_6_len);
    vader_builder_append_str((vader_builder_t*) t52.payload.obj, t53);
    t54 = l9;
    t55 = l0;
    int32_t t56 = INT32_C(99);
    bool t57 = std_collections_std_collections_contains_key__i32__i32(t55, t56);
    vader_builder_append_display_bool((vader_builder_t*) t54.payload.obj, t57);
    t58 = l9;
    vader_string_t t59 = vader_builder_finish((vader_builder_t*) t58.payload.obj);
    vader_import_1(t59);
    t60 = l0;
    int32_t t61 = INT32_C(1);
    int32_t t62 = INT32_C(999);
    std_collections_std_collections_put__i32__i32(t60, t61, t62);
    t63 = l0;
    int32_t t64 = INT32_C(1);
    t65 = std_collections_std_collections_get__i32__i32(t63, t64);
    l10 = t65;
    l11 = t65;
    bool t66 = (t65.tag == 3u);
    if (t66) {
        vader_string_t t67 = vader_string_new(vader_str_7_data, vader_str_7_len);
        vader_import_1(t67);
    } else { /* else */
        t68 = l11;
        bool t69 = (t68.tag == 1u);
        if (t69) {
            t70.tag = 0; t70._pad = 0; t70.payload.obj = vader_builder_new();
            l12 = t70;
            vader_string_t t71 = vader_string_new(vader_str_8_data, vader_str_8_len);
            vader_builder_append_str((vader_builder_t*) t70.payload.obj, t71);
            t72 = l12;
            t73 = l10;
            vader_builder_append_display_string((vader_builder_t*) t72.payload.obj, t73);
            t74 = l12;
            vader_string_t t75 = vader_builder_finish((vader_builder_t*) t74.payload.obj);
            vader_import_1(t75);
        } else { /* else */
            vader_unreachable("tests_snippets_mutable_map__main_vader$main+132");
        } end_120: ;
    } end_114: ;
    int32_t t76 = INT32_C(0);
    { int32_t __vret = t76; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

static uint64_t std_core_i32_Hash_hash(int32_t l0) {
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL };
    vader_gc_top = &gc_frame;
    int32_t t0 = l0;
    uint64_t t1 = (uint64_t) t0;
    { uint64_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

static bool std_core_i32_Eq_equals(int32_t l0, int32_t l1) {
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL };
    vader_gc_top = &gc_frame;
    int32_t t0 = l0;
    int32_t t1 = l1;
    bool t2 = t0 == t1;
    { bool __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

static int32_t std_collections_bucket_index(uint64_t l0) {
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL };
    vader_gc_top = &gc_frame;
    uint64_t t0 = l0;
    int32_t t1 = INT32_C(16);
    uint64_t t2 = (uint64_t) t1;
    uint64_t t3 = t0 % t2;
    int32_t t4 = (int32_t) t3;
    { int32_t __vret = t4; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

static void std_collections_std_collections_put__i32__i32(vader_box_t l0, int32_t l1, int32_t l2) {
    int32_t l3 = 0;
    uint64_t l4 = 0;
    int32_t l5 = 0;
    vader_box_t l6 = vader_box_null();
    bool l7 = false;
    bool l8 = false;
    vader_box_t l9 = vader_box_null();
    vader_box_t l10 = vader_box_null();
    vader_box_t t0 = vader_box_null();
    vader_box_t t1 = vader_box_null();
    vader_box_t t9 = vader_box_null();
    vader_box_t t10 = vader_box_null();
    vader_box_t t11 = vader_box_null();
    vader_box_t t18 = vader_box_null();
    vader_box_t t19 = vader_box_null();
    vader_box_t t21 = vader_box_null();
    vader_box_t t25 = vader_box_null();
    vader_box_t t28 = vader_box_null();
    vader_box_t t30 = vader_box_null();
    vader_box_t t34 = vader_box_null();
    vader_box_t t38 = vader_box_null();
    vader_box_t t39 = vader_box_null();
    vader_box_t t43 = vader_box_null();
    vader_box_t t44 = vader_box_null();
    vader_box_t t46 = vader_box_null();
    vader_box_t t47 = vader_box_null();
    vader_box_t t48 = vader_box_null();
    vader_box_t t49 = vader_box_null();
    vader_box_t t51 = vader_box_null();
    vader_box_t t52 = vader_box_null();
    vader_box_t t53 = vader_box_null();
    vader_box_t* gc_roots[27] = { &l0, &l6, &l9, &l10, &t0, &t1, &t9, &t10, &t11, &t18, &t19, &t21, &t25, &t28, &t30, &t34, &t38, &t39, &t43, &t44, &t46, &t47, &t48, &t49, &t51, &t52, &t53 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 27u, 0u, gc_roots };
    vader_gc_top = &gc_frame;
    t0 = l0;
    t1 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t0.payload.obj)->f_buckets;
    int32_t t2 = (int32_t) vader_array_len((vader_array_t*) t1.payload.obj);
    int32_t t3 = INT32_C(0);
    bool t4 = t2 == t3;
    if (t4) {
        int32_t t5 = INT32_C(0);
        l3 = t5;
        {
            loop_9: {
                int32_t t6 = l3;
                int32_t t7 = INT32_C(16);
                bool t8 = t6 >= t7;
                if (t8) { goto end_8; }
                t9 = l0;
                t10 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t9.payload.obj)->f_buckets;
                t11 = vader_box_obj(3u, NULL);
                vader_array_push((vader_array_t*) t10.payload.obj, t11);
                int32_t t12 = l3;
                int32_t t13 = INT32_C(1);
                int32_t t14 = t12 + t13;
                l3 = t14;
                goto loop_9;
            } end_9: ;
        } end_8: ;
    } end_5: ;
    int32_t t15 = l1;
    uint64_t t16 = std_core_i32_Hash_hash(t15);
    l4 = t16;
    int32_t t17 = std_collections_bucket_index(t16);
    l5 = t17;
    t18 = l0;
    t19 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t18.payload.obj)->f_buckets;
    int32_t t20 = l5;
    t21 = vader_array_get((vader_array_t*) t19.payload.obj, (size_t) t20);
    l6 = t21;
    bool t22 = false;
    l7 = t22;
    bool t23 = false;
    l8 = t23;
    {
        loop_41: {
            bool t24 = l7;
            if (t24) { goto end_40; }
            t25 = l6;
            l9 = t25;
            bool t26 = (t25.tag == 3u);
            if (t26) {
                bool t27 = true;
                l7 = t27;
            } else { /* else */
                t28 = l9;
                bool t29 = (t28.tag == 0u);
                if (t29) {
                    t30 = l6;
                    int32_t t31 = ((vader_struct_std_collections_Entry__i32__i32_t*) t30.payload.obj)->f_key;
                    int32_t t32 = l1;
                    bool t33 = std_core_i32_Eq_equals(t31, t32);
                    if (t33) {
                        t34 = l6;
                        int32_t t35 = l2;
                        ((vader_struct_std_collections_Entry__i32__i32_t*) t34.payload.obj)->f_value = t35;
                        bool t36 = true;
                        l8 = t36;
                        bool t37 = true;
                        l7 = t37;
                    } else { /* else */
                        t38 = l6;
                        t39 = ((vader_struct_std_collections_Entry__i32__i32_t*) t38.payload.obj)->f_next;
                        l6 = t39;
                    } end_58: ;
                } else { /* else */
                    vader_unreachable("std_collections$std_collections$put__i32__i32+72");
                } end_53: ;
            } end_47: ;
            goto loop_41;
        } end_41: ;
    } end_40: ;
    bool t40 = l8;
    if (t40) {
        { vader_gc_top = gc_frame.prev; return; }
    } end_79: ;
    int32_t t41 = l1;
    int32_t t42 = l2;
    t43 = l0;
    t44 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t43.payload.obj)->f_buckets;
    int32_t t45 = l5;
    t46 = vader_array_get((vader_array_t*) t44.payload.obj, (size_t) t45);
    vader_struct_std_collections_Entry__i32__i32_t* t47_obj = (vader_struct_std_collections_Entry__i32__i32_t*) vader_alloc(sizeof(vader_struct_std_collections_Entry__i32__i32_t));
    t47_obj->header.type_index = 0u;
    t47_obj->header._pad = 0u;
    t47_obj->header.forward = NULL;
    t47_obj->f_key = (int32_t) t41;
    t47_obj->f_value = (int32_t) t42;
    t47_obj->f_next = (vader_box_t) t46;
    t47 = vader_box_obj(0u, t47_obj);
    l10 = t47;
    t48 = l0;
    t49 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t48.payload.obj)->f_buckets;
    int32_t t50 = l5;
    t51 = l10;
    vader_array_set((vader_array_t*) t49.payload.obj, (size_t) t50, t51);
    t52 = l0;
    t53 = l0;
    size_t t54 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t53.payload.obj)->f_size;
    int64_t t55 = INT64_C(1);
    size_t t56 = t54 + t55;
    ((vader_struct_std_collections_MutableMap__i32__i32_t*) t52.payload.obj)->f_size = t56;
    vader_gc_top = gc_frame.prev;
}

static vader_box_t std_collections_std_collections_get__i32__i32(vader_box_t l0, int32_t l1) {
    uint64_t l2 = 0;
    int32_t l3 = 0;
    vader_box_t l4 = vader_box_null();
    vader_box_t l5 = vader_box_null();
    bool l6 = false;
    vader_box_t l7 = vader_box_null();
    vader_box_t t0 = vader_box_null();
    vader_box_t t1 = vader_box_null();
    vader_box_t t5 = vader_box_null();
    vader_box_t t9 = vader_box_null();
    vader_box_t t10 = vader_box_null();
    vader_box_t t12 = vader_box_null();
    vader_box_t t13 = vader_box_null();
    vader_box_t t16 = vader_box_null();
    vader_box_t t19 = vader_box_null();
    vader_box_t t21 = vader_box_null();
    vader_box_t t25 = vader_box_null();
    vader_box_t t28 = vader_box_null();
    vader_box_t t29 = vader_box_null();
    vader_box_t t30 = vader_box_null();
    vader_box_t* gc_roots[18] = { &l0, &l4, &l5, &l7, &t0, &t1, &t5, &t9, &t10, &t12, &t13, &t16, &t19, &t21, &t25, &t28, &t29, &t30 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 18u, 0u, gc_roots };
    vader_gc_top = &gc_frame;
    t0 = l0;
    t1 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t0.payload.obj)->f_buckets;
    int32_t t2 = (int32_t) vader_array_len((vader_array_t*) t1.payload.obj);
    int32_t t3 = INT32_C(0);
    bool t4 = t2 == t3;
    if (t4) {
        t5 = vader_box_obj(3u, NULL);
        { vader_box_t __vret = t5; vader_gc_top = gc_frame.prev; return __vret; }
    } end_5: ;
    int32_t t6 = l1;
    uint64_t t7 = std_core_i32_Hash_hash(t6);
    l2 = t7;
    int32_t t8 = std_collections_bucket_index(t7);
    l3 = t8;
    t9 = l0;
    t10 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t9.payload.obj)->f_buckets;
    int32_t t11 = l3;
    t12 = vader_array_get((vader_array_t*) t10.payload.obj, (size_t) t11);
    l4 = t12;
    t13 = vader_box_obj(3u, NULL);
    l5 = t13;
    bool t14 = false;
    l6 = t14;
    {
        loop_24: {
            bool t15 = l6;
            if (t15) { goto end_23; }
            t16 = l4;
            l7 = t16;
            bool t17 = (t16.tag == 3u);
            if (t17) {
                bool t18 = true;
                l6 = t18;
            } else { /* else */
                t19 = l7;
                bool t20 = (t19.tag == 0u);
                if (t20) {
                    t21 = l4;
                    int32_t t22 = ((vader_struct_std_collections_Entry__i32__i32_t*) t21.payload.obj)->f_key;
                    int32_t t23 = l1;
                    bool t24 = std_core_i32_Eq_equals(t22, t23);
                    if (t24) {
                        t25 = l4;
                        int32_t t26 = ((vader_struct_std_collections_Entry__i32__i32_t*) t25.payload.obj)->f_value;
                        l5 = vader_box_i32(1u, t26);
                        bool t27 = true;
                        l6 = t27;
                    } else { /* else */
                        t28 = l4;
                        t29 = ((vader_struct_std_collections_Entry__i32__i32_t*) t28.payload.obj)->f_next;
                        l4 = t29;
                    } end_41: ;
                } else { /* else */
                    vader_unreachable("std_collections$std_collections$get__i32__i32+53");
                } end_36: ;
            } end_30: ;
            goto loop_24;
        } end_24: ;
    } end_23: ;
    t30 = l5;
    { vader_box_t __vret = t30; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

static bool std_collections_std_collections_contains_key__i32__i32(vader_box_t l0, int32_t l1) {
    uint64_t l2 = 0;
    int32_t l3 = 0;
    vader_box_t l4 = vader_box_null();
    bool l5 = false;
    bool l6 = false;
    vader_box_t l7 = vader_box_null();
    vader_box_t t0 = vader_box_null();
    vader_box_t t1 = vader_box_null();
    vader_box_t t9 = vader_box_null();
    vader_box_t t10 = vader_box_null();
    vader_box_t t12 = vader_box_null();
    vader_box_t t16 = vader_box_null();
    vader_box_t t19 = vader_box_null();
    vader_box_t t21 = vader_box_null();
    vader_box_t t27 = vader_box_null();
    vader_box_t t28 = vader_box_null();
    vader_box_t* gc_roots[13] = { &l0, &l4, &l7, &t0, &t1, &t9, &t10, &t12, &t16, &t19, &t21, &t27, &t28 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 13u, 0u, gc_roots };
    vader_gc_top = &gc_frame;
    t0 = l0;
    t1 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t0.payload.obj)->f_buckets;
    int32_t t2 = (int32_t) vader_array_len((vader_array_t*) t1.payload.obj);
    int32_t t3 = INT32_C(0);
    bool t4 = t2 == t3;
    if (t4) {
        bool t5 = false;
        { bool __vret = t5; vader_gc_top = gc_frame.prev; return __vret; }
    } end_5: ;
    int32_t t6 = l1;
    uint64_t t7 = std_core_i32_Hash_hash(t6);
    l2 = t7;
    int32_t t8 = std_collections_bucket_index(t7);
    l3 = t8;
    t9 = l0;
    t10 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t9.payload.obj)->f_buckets;
    int32_t t11 = l3;
    t12 = vader_array_get((vader_array_t*) t10.payload.obj, (size_t) t11);
    l4 = t12;
    bool t13 = false;
    l5 = t13;
    bool t14 = false;
    l6 = t14;
    {
        loop_24: {
            bool t15 = l6;
            if (t15) { goto end_23; }
            t16 = l4;
            l7 = t16;
            bool t17 = (t16.tag == 3u);
            if (t17) {
                bool t18 = true;
                l6 = t18;
            } else { /* else */
                t19 = l7;
                bool t20 = (t19.tag == 0u);
                if (t20) {
                    t21 = l4;
                    int32_t t22 = ((vader_struct_std_collections_Entry__i32__i32_t*) t21.payload.obj)->f_key;
                    int32_t t23 = l1;
                    bool t24 = std_core_i32_Eq_equals(t22, t23);
                    if (t24) {
                        bool t25 = true;
                        l5 = t25;
                        bool t26 = true;
                        l6 = t26;
                    } else { /* else */
                        t27 = l4;
                        t28 = ((vader_struct_std_collections_Entry__i32__i32_t*) t27.payload.obj)->f_next;
                        l4 = t28;
                    } end_41: ;
                } else { /* else */
                    vader_unreachable("std_collections$std_collections$contains_key__i32__i32+52");
                } end_36: ;
            } end_30: ;
            goto loop_24;
        } end_24: ;
    } end_23: ;
    bool t29 = l5;
    { bool __vret = t29; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

static size_t std_collections_std_collections_len__i32__i32(vader_box_t l0) {
    vader_box_t t0 = vader_box_null();
    vader_box_t* gc_roots[2] = { &l0, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 2u, 0u, gc_roots };
    vader_gc_top = &gc_frame;
    t0 = l0;
    size_t t1 = ((vader_struct_std_collections_MutableMap__i32__i32_t*) t0.payload.obj)->f_size;
    { size_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
    vader_gc_top = gc_frame.prev;
}

int main(void) {
    return (int) tests_snippets_mutable_map__main_vader_main();
}
