/* Generated by vader — do not edit. Foreign imports. */
#include "vader.h"

typedef struct vader_struct_system_linux_LinuxStat_t vader_struct_system_linux_LinuxStat_t;
struct vader_struct_system_linux_LinuxStat_t {
    vader_obj_header_t header;
    uint64_t f_st_dev;
    uint64_t f_st_ino;
    uint64_t f_st_nlink;
    uint32_t f_st_mode;
};
// Headers named by `@c_header` — they own the prototypes below.
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>

// `@c_struct` layout — checked against the real headers.
_Static_assert(32 <= sizeof(struct stat), "struct stat prefix");
_Static_assert(sizeof(struct stat) <= 4096, "struct stat fits the interpreter block");
_Static_assert(offsetof(struct stat, st_dev) == 0, "struct stat.st_dev offset");
_Static_assert(sizeof(((struct stat*) 0)->st_dev) == sizeof(((vader_struct_system_linux_LinuxStat_t*) 0)->f_st_dev), "struct stat.st_dev");
_Static_assert(offsetof(struct stat, st_ino) == 8, "struct stat.st_ino offset");
_Static_assert(sizeof(((struct stat*) 0)->st_ino) == sizeof(((vader_struct_system_linux_LinuxStat_t*) 0)->f_st_ino), "struct stat.st_ino");
_Static_assert(offsetof(struct stat, st_nlink) == 16, "struct stat.st_nlink offset");
_Static_assert(sizeof(((struct stat*) 0)->st_nlink) == sizeof(((vader_struct_system_linux_LinuxStat_t*) 0)->f_st_nlink), "struct stat.st_nlink");
_Static_assert(offsetof(struct stat, st_mode) == 24, "struct stat.st_mode offset");
_Static_assert(sizeof(((struct stat*) 0)->st_mode) == sizeof(((vader_struct_system_linux_LinuxStat_t*) 0)->f_st_mode), "struct stat.st_mode");

static inline size_t vader_host_std_core_byte_len(vader_string_t a0) { return vader_string_byte_len(a0); }
static inline uint8_t vader_host_std_core_byte_at(vader_string_t a0, size_t a1) { return vader_string_byte_at(a0, a1); }
static inline vader_string_t vader_host_std_core_bytes_to_string(void* a0) { return vader_string_as_string((vader_array_t*) a0); }
static inline void* vader_host_std_core_bytes(vader_string_t a0) { return (void*) vader_string_bytes_view(a0, 11u, 169u); }
static inline uint64_t vader_host_std_core_string_Hash_hash(vader_string_t a0) { return vader_string_hash(a0); }
static inline vader_box_t vader_host_std_io_read_dir(vader_string_t a0) { vader_box_t r = vader_read_dir(a0, 8u, 163u, 398u); if (r.tag == 398u) { vader_struct_std_io_IOError_t* e = (vader_struct_std_io_IOError_t*) vader_gc_alloc(sizeof(vader_struct_std_io_IOError_t)); vader_obj_header_init(e, 398u); e->f_msg = r.payload.s; return vader_box_obj(398u, e); } return r; }
static inline vader_box_t vader_host_std_env_get_env(vader_string_t a0) { const char* c0 = vader_string_to_cstr(a0); const char* r = getenv(c0); vader_cstr_free_for(a0, c0); return r == NULL ? vader_box_null() : vader_box_i64(163u, (int64_t) vader_atom_intern(r, strlen(r))); }
static inline uint8_t vader_host_std_target_current_os(void) { return vader_current_os(); }
static inline uint8_t vader_host_std_target_current_arch(void) { return vader_current_arch(); }
static inline int32_t vader_host_system_linux_sys_stat_linux(vader_string_t a0, void* a1) { const char* c0 = vader_string_to_cstr(a0); struct stat p1; int32_t r = stat(c0, &p1); ((vader_struct_system_linux_LinuxStat_t*) a1)->f_st_dev = p1.st_dev; ((vader_struct_system_linux_LinuxStat_t*) a1)->f_st_ino = p1.st_ino; ((vader_struct_system_linux_LinuxStat_t*) a1)->f_st_nlink = p1.st_nlink; ((vader_struct_system_linux_LinuxStat_t*) a1)->f_st_mode = p1.st_mode; vader_cstr_free_for(a0, c0); return r; }
static inline ptrdiff_t vader_host_system_posix_sys_write(int32_t a0, void* a1, size_t a2) { vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); return write(a0, s1.ptr, a2); }
static inline ptrdiff_t vader_host_system_posix_sys_readlink(vader_string_t a0, void* a1, size_t a2) { const char* c0 = vader_string_to_cstr(a0); vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); ptrdiff_t r = readlink(c0, (void*) s1.ptr, a2); vader_cstr_free_for(a0, c0); return r; }
static inline vader_box_t vader_host_system_posix_sys_fopen(vader_string_t a0, vader_string_t a1) { const char* c0 = vader_string_to_cstr(a0); const char* c1 = vader_string_to_cstr(a1); void* r = fopen(c0, c1); vader_cstr_free_for(a0, c0); vader_cstr_free_for(a1, c1); return r == NULL ? vader_box_null() : vader_box_i64(165u, (int64_t) (intptr_t) r); }
static inline int32_t vader_host_system_posix_sys_fclose(void* a0) { return fclose(a0); }
static inline size_t vader_host_system_posix_sys_fread(void* a0, size_t a1, size_t a2, void* a3) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); return fread((void*) s0.ptr, a1, a2, a3); }
static inline size_t vader_host_system_posix_sys_fwrite(void* a0, size_t a1, size_t a2, void* a3) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); return fwrite(s0.ptr, a1, a2, a3); }
static inline vader_box_t vader_host_system_posix_sys_getcwd(void* a0, size_t a1) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); void* r = getcwd((void*) s0.ptr, a1); return r == NULL ? vader_box_null() : vader_box_i64(165u, (int64_t) (intptr_t) r); }
static inline int32_t vader_host_system_posix_sys_access(vader_string_t a0, int32_t a1) { const char* c0 = vader_string_to_cstr(a0); int32_t r = access(c0, a1); vader_cstr_free_for(a0, c0); return r; }
static inline bool vader_host_std_tty_raw_mode_begin(void) { return vader_terminal_raw_begin(); }
static inline void vader_host_std_tty_raw_mode_end(void) { vader_terminal_raw_end(); }
static inline int32_t vader_host_std_tty_columns(void) { return vader_terminal_columns(); }
static inline vader_string_t vader_host_std_tty_read_keys(int32_t a0) { return vader_terminal_read_keys(a0); }
static inline bool vader_host_std_tty_is_tty(int32_t a0) { return vader_is_tty(a0); }
static inline size_t vader_host_vader_vm_ffi_open(vader_string_t a0) { const char* c0 = vader_string_to_cstr(a0); void* r = vader_ffi_open(c0); vader_cstr_free_for(a0, c0); return (size_t) (uintptr_t) r; }
static inline size_t vader_host_vader_vm_ffi_symbol(size_t a0, vader_string_t a1) { const char* c1 = vader_string_to_cstr(a1); void* r = vader_ffi_symbol((void*) (uintptr_t) a0, c1); vader_cstr_free_for(a1, c1); return (size_t) (uintptr_t) r; }
static inline vader_string_t vader_host_vader_vm_ffi_call(size_t a0, void* a1, void* a2) { return vader_ffi_call((void*) (uintptr_t) a0, (vader_array_t*) a1, (vader_array_t*) a2); }
static inline void vader_host_std_abort_panic(vader_string_t a0) { vader_panic(a0); }
static inline int64_t vader_host_std_process_spawn_start(void* a0) { return vader_spawn_start((vader_array_t*) a0); }
static inline int32_t vader_host_std_process_spawn_poll(int64_t a0) { return vader_spawn_poll(a0); }
static inline void vader_host_std_process_spawn_kill(int64_t a0) { vader_spawn_kill(a0); }
static inline vader_string_t vader_host_std_process_spawn_take_stdout(int64_t a0) { return vader_spawn_take_stdout(a0); }
static inline vader_string_t vader_host_std_process_spawn_take_stderr(int64_t a0) { return vader_spawn_take_stderr(a0); }

