/* Generated by vader — do not edit. */
#include "vader.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

typedef struct vader_struct_snippet_Bag_t vader_struct_snippet_Bag_t;
typedef struct vader_struct___asyncstate_snippet_0_t vader_struct___asyncstate_snippet_0_t;
typedef struct vader_struct_std_core_Suspended_t vader_struct_std_core_Suspended_t;
typedef struct vader_struct___asyncstate_snippet_1_t vader_struct___asyncstate_snippet_1_t;
typedef struct vader_struct_std_core_Buffer_t vader_struct_std_core_Buffer_t;
typedef struct vader_struct_std_async_Sleep_t vader_struct_std_async_Sleep_t;

struct vader_struct_snippet_Bag_t {
    vader_obj_header_t header;
    void* f_items;
};
struct vader_struct___asyncstate_snippet_0_t {
    vader_obj_header_t header;
    void* f_s0;
    void* f_s1;
    void* f_s2;
    size_t f_s3;
    size_t f_s4;
    int32_t f_s5;
    vader_box_t f_s6;
    vader_box_t f_awaited;
    int32_t f_state;
};
struct vader_struct_std_core_Suspended_t {
    vader_obj_header_t header;
};
struct vader_struct___asyncstate_snippet_1_t {
    vader_obj_header_t header;
    void* f_s0;
    void* f_s1;
    void* f_s2;
    void* f_s3;
    vader_box_t f_awaited;
    int32_t f_state;
};
struct vader_struct_std_core_Buffer_t {
    vader_obj_header_t header;
};
struct vader_struct_std_async_Sleep_t {
    vader_obj_header_t header;
    int64_t f_ms;
    int64_t f_deadline;
    bool f_armed;
};

/* Compile-time atom table — see docs/ATOM_INTERNING.md. */
static const char vader_atom_blob[] =
    ":" "\0"
    " " "\0"
    "async" "\0"
    "array" "\0"
    "range" "\0"
    "empty range" "\0"
    "collect" "\0"
    "collect range" "\0"
    "filtered" "\0"
    "until" "\0"
    "empty array" "\0"
    "inclusive" "\0"
    "empty inclusive" "\0"
    "field" "\0"
    "split: " "\0"
    "async deadlock: a task is suspended with nothing left to wake it" "\0"
    "\n" "\0";

static const vader_atom_entry_t vader_atom_comptime_table[] = {
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[0] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[2] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[4] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[10] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[16] },
    { 0u, 0u, 11u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[22] },
    { 0u, 0u, 7u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[34] },
    { 0u, 0u, 13u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[42] },
    { 0u, 0u, 8u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[56] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[65] },
    { 0u, 0u, 11u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[71] },
    { 0u, 0u, 9u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[83] },
    { 0u, 0u, 15u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[93] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[109] },
    { 0u, 0u, 7u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[115] },
    { 0u, 0u, 64u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[123] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[188] },
};

#define VADER_COMPTIME_ATOM_COUNT 17u

static int64_t snippet_square(int32_t l0);
static bool snippet_odd(int32_t l0);
static void snippet_show(vader_string_t l0, void* l1);
static void* snippet_over_array(void* l0);
static void* snippet_over_range(int32_t l0, int32_t l1);
static void* snippet_over_inclusive(int32_t l0, int32_t l1);
static void* snippet_over_field(void* l0);
static int64_t snippet_split(void* l0);
static vader_box_t snippet_squares_later(void* l0);
static void* snippet_odd_squares(void* l0);
static void* snippet_until_big(void* l0);
static int32_t snippet_main(void);
static vader_box_t snippet___asyncstate_snippet_0_Async_resume(void* l0);
static vader_box_t snippet___asyncstate_snippet_1_Async_resume(void* l0);
static vader_string_t concat_2(vader_string_t l0, vader_string_t l1);
static void* std_core_new_byte_buffer(size_t l0);
static vader_string_t std_core_finish_buffer(void* l0, size_t l1);
static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2);
static size_t std_core_write_int(void* l0, size_t l1, int64_t l2);
static vader_box_t std_async_sleep(int64_t l0);
static int32_t std_async_run_async_main(vader_box_t l0);
static vader_box_t std_async_Sleep_Async_resume(void* l0);
static int32_t std_async_block_on__i32(vader_box_t l0);
static void std_io_write(uint8_t l0, vader_string_t l1);
static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2);
static void std_io_println__string(vader_string_t l0);
static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0);
static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2);
static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1);
static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2);

typedef vader_box_t (*vader_fn_erased_sig_0_t)(void* env);

static const uint16_t vader_array_ptr_offsets[] = { offsetof(vader_array_t, buf) };

const vader_type_info_t vader_type_info_table[25] = {
    [1] = { .slot_size = 4 },
    [2] = { .slot_size = 8 },
    [3] = { .slot_size = 1 },
    [4] = { .slot_size = 16 },
    [5] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [7] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [8] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_snippet_Bag_t), .slot_size = 8,
        .ref_offsets = (const uint16_t[]){ offsetof(vader_struct_snippet_Bag_t, f_items) },
        .ref_count = 1,
    },
    [9] = { .slot_size = 16 },
    [10] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___asyncstate_snippet_0_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___asyncstate_snippet_0_t, f_awaited) },
        .ptr_count = 1,
        .ref_offsets = (const uint16_t[]){ offsetof(vader_struct___asyncstate_snippet_0_t, f_s0), offsetof(vader_struct___asyncstate_snippet_0_t, f_s1), offsetof(vader_struct___asyncstate_snippet_0_t, f_s2) },
        .ref_count = 3,
    },
    [11] = { .slot_size = 16 },
    [12] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Suspended_t),
        .slot_size = 8,
    },
    [13] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___asyncstate_snippet_1_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___asyncstate_snippet_1_t, f_awaited) },
        .ptr_count = 1,
        .ref_offsets = (const uint16_t[]){ offsetof(vader_struct___asyncstate_snippet_1_t, f_s0), offsetof(vader_struct___asyncstate_snippet_1_t, f_s1), offsetof(vader_struct___asyncstate_snippet_1_t, f_s2), offsetof(vader_struct___asyncstate_snippet_1_t, f_s3) },
        .ref_count = 4,
    },
    [14] = { .slot_size = 16 },
    [15] = { .slot_size = 8 },
    [16] = { .slot_size = 16 },
    [17] = { .slot_size = 1 },
    [18] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Buffer_t),
        .slot_size = 8,
    },
    [19] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [20] = { .slot_size = 16 },
    [21] = { .slot_size = 16 },
    [22] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_async_Sleep_t),
        .slot_size = 8,
    },
    [23] = { .slot_size = 16 },
    [24] = { .slot_size = 8 },
};
const size_t vader_type_info_count = 25;

/* Headers named by `@c_header` — they own the prototypes below. */
#include <unistd.h>

static size_t vader_host_std_core_byte_len(vader_string_t a0) {
    return vader_string_byte_len(a0);
}

static void* vader_host_std_core_bytes(vader_string_t a0) {
    return (void*) vader_string_bytes_view(a0, 19u, 17u);
}

static int64_t vader_host_std_runtime_sched_now(void) {
    return vader_sched_now();
}

static void vader_host_std_runtime_sched_arm(int64_t a0) {
    vader_sched_arm(a0);
}

static int32_t vader_host_std_runtime_sched_park(void) {
    return vader_sched_park();
}

static void vader_host_std_abort_panic(vader_string_t a0) {
    vader_panic(a0);
}

static ptrdiff_t vader_host_system_posix_sys_write(int32_t a0, void* a1, size_t a2) {
    vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1);
    return write(a0, s1.ptr, a2);
}

/* vtable forwards */
static vader_box_t vader_vt_Async__resume(vader_box_t recv);

static int64_t snippet_square(int32_t l0) {
    int64_t l1, l2;
#line 15 "tests/snippets/array_reserved_by_loop/_main.vader"
    l1 = ((int64_t) (int32_t) l0);
    l2 = ((int64_t) (int32_t) l0);
    return (l1 * l2);
}

static bool snippet_odd(int32_t l0) {
    int32_t t0;
#line 17 "tests/snippets/array_reserved_by_loop/_main.vader"
    t0 = vader_mod_i32(l0, INT32_C(2));
    return t0 == INT32_C(1);
}

static void snippet_show(vader_string_t l0, void* l1) {
    vader_string_t l2 = 0;
    vader_string_t l7 = 0;
    void* l3 = NULL;
    void* l9 = NULL;
    size_t l4, l5, l8, l10;
    int64_t l6;
    int64_t t0;
    void** gc_raw_roots[3] = { &l1, &l3, &l9 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l2, &l7 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 20 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = concat_2(l0, 1u);
#line 21 "tests/snippets/array_reserved_by_loop/_main.vader"
    l3 = l1;
    l4 = ((vader_array_t*) l3)->length;
    l5 = (size_t) 0;
    while ((l5 < l4)) {
        vader_array_t* _a0_slotarr = ((vader_array_t*) l3);
        VADER_ARRAY_RESOLVE_BUF(_a0_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a0_slotarr, l5)
        l6 = ((int64_t*) _a0_slotarr->buf->slots)[_a0_slotarr->offset + (size_t) l5];
#line 22 "tests/snippets/array_reserved_by_loop/_main.vader"
        l7 = l2;
        l8 = vader_host_std_core_byte_len(l7);
        l9 = std_core_new_byte_buffer((size_t) (int64_t) (INT64_C(21) + l8));
        l10 = (size_t) 0;
        l10 = std_core_write_string_at(l9, l10, l7);
        l10 = std_core_write_string_at(l9, l10, 2u);
        l10 = std_core_write_int(l9, l10, l6);
        l2 = std_core_finish_buffer(l9, l10);
#line 21 "tests/snippets/array_reserved_by_loop/_main.vader"
        t0 = (l5 + INT64_C(1));
        l5 = (size_t) (int64_t) t0;
    }
#line 24 "tests/snippets/array_reserved_by_loop/_main.vader"
    std_io_println__string(l2);
#line 19 "tests/snippets/array_reserved_by_loop/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void* snippet_over_array(void* l0) {
    void* l1 = NULL;
    void* l3 = NULL;
    size_t l2, l4;
    int64_t l5;
    int32_t t0;
    int64_t t1;
    void** gc_raw_roots[3] = { &l0, &l1, &l3 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 28 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l1 = (void*) _a0_arr;
#line 29 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = ((vader_array_t*) l0)->length;
#line 28 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a1_arr = vader_array_repeat((vader_array_t*) l1, (size_t) l2);
    l1 = (void*) _a1_arr;
#line 29 "tests/snippets/array_reserved_by_loop/_main.vader"
    l3 = l0;
    l2 = ((vader_array_t*) l3)->length;
    l4 = (size_t) 0;
    {
        vader_array_t* _pc16_hdr = (vader_array_t*) l1;
        size_t _pc16_len = _pc16_hdr->length;
        size_t _pc16_cap = (_pc16_hdr->offset == 0 && !vader_array_is_borrowed(_pc16_hdr) && _pc16_hdr->length >= _pc16_hdr->buf->length) ? _pc16_hdr->capacity : (size_t) 0;
        void* _pc16_slots = _pc16_hdr->buf->slots;
        for (;;) {
            if ((l4 < l2)) {
                vader_array_t* _a2_slotarr = ((vader_array_t*) l3);
                VADER_ARRAY_RESOLVE_BUF(_a2_slotarr)
                VADER_ARRAY_CHECK_INDEX(_a2_slotarr, l4)
                t0 = ((int32_t*) _a2_slotarr->buf->slots)[_a2_slotarr->offset + (size_t) l4];
#line 30 "tests/snippets/array_reserved_by_loop/_main.vader"
                l5 = snippet_square(t0);
                if (VADER_LIKELY(_pc16_len < _pc16_cap)) {
                    ((int64_t*) _pc16_slots)[_pc16_len] = (int64_t) (l5);
                    _pc16_len += 1;
                } else {
                    _pc16_hdr->length = _pc16_len;
                    if (_pc16_hdr->buf->length < _pc16_len) {
                        _pc16_hdr->buf->length = _pc16_len;
                    }
                    vader_array_push_i64((vader_array_t*) l1, l5);
                    _pc16_hdr = (vader_array_t*) l1;
                    _pc16_len = _pc16_hdr->length;
                    _pc16_cap = (_pc16_hdr->offset == 0 && !vader_array_is_borrowed(_pc16_hdr) && _pc16_hdr->length >= _pc16_hdr->buf->length) ? _pc16_hdr->capacity : (size_t) 0;
                    _pc16_slots = _pc16_hdr->buf->slots;
                }
#line 29 "tests/snippets/array_reserved_by_loop/_main.vader"
                t1 = (l4 + INT64_C(1));
                l4 = (size_t) (int64_t) t1;
                continue;
            }
            _pc16_hdr->length = _pc16_len;
            if (_pc16_hdr->buf->length < _pc16_len) {
                _pc16_hdr->buf->length = _pc16_len;
            }
            break;
        }
    }
#line 32 "tests/snippets/array_reserved_by_loop/_main.vader"
    { void* __vret = l1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_over_range(int32_t l0, int32_t l1) {
    void* l2 = NULL;
    size_t l3;
    int32_t l4;
    int64_t l5;
    int64_t t0;
    void** gc_raw_roots[1] = { &l2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 36 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l2 = (void*) _a0_arr;
    if ((l0 < l1)) {
        t0 = ((int64_t) (int32_t) (l1 - l0));
        l3 = (size_t) (int64_t) t0;
    } else {
        l3 = (size_t) 0;
    }
    vader_array_t* _a1_arr = vader_array_repeat((vader_array_t*) l2, (size_t) l3);
    l2 = (void*) _a1_arr;
#line 37 "tests/snippets/array_reserved_by_loop/_main.vader"
    l4 = l0;
    {
        vader_array_t* _pc22_hdr = (vader_array_t*) l2;
        size_t _pc22_len = _pc22_hdr->length;
        size_t _pc22_cap = (_pc22_hdr->offset == 0 && !vader_array_is_borrowed(_pc22_hdr) && _pc22_hdr->length >= _pc22_hdr->buf->length) ? _pc22_hdr->capacity : (size_t) 0;
        void* _pc22_slots = _pc22_hdr->buf->slots;
        for (;;) {
            if ((l4 < l1)) {
#line 38 "tests/snippets/array_reserved_by_loop/_main.vader"
                l5 = snippet_square(l4);
                if (VADER_LIKELY(_pc22_len < _pc22_cap)) {
                    ((int64_t*) _pc22_slots)[_pc22_len] = (int64_t) (l5);
                    _pc22_len += 1;
                } else {
                    _pc22_hdr->length = _pc22_len;
                    if (_pc22_hdr->buf->length < _pc22_len) {
                        _pc22_hdr->buf->length = _pc22_len;
                    }
                    vader_array_push_i64((vader_array_t*) l2, l5);
                    _pc22_hdr = (vader_array_t*) l2;
                    _pc22_len = _pc22_hdr->length;
                    _pc22_cap = (_pc22_hdr->offset == 0 && !vader_array_is_borrowed(_pc22_hdr) && _pc22_hdr->length >= _pc22_hdr->buf->length) ? _pc22_hdr->capacity : (size_t) 0;
                    _pc22_slots = _pc22_hdr->buf->slots;
                }
#line 37 "tests/snippets/array_reserved_by_loop/_main.vader"
                l4 = (l4 + INT32_C(1));
                continue;
            }
            _pc22_hdr->length = _pc22_len;
            if (_pc22_hdr->buf->length < _pc22_len) {
                _pc22_hdr->buf->length = _pc22_len;
            }
            break;
        }
    }
#line 40 "tests/snippets/array_reserved_by_loop/_main.vader"
    { void* __vret = l2; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_over_inclusive(int32_t l0, int32_t l1) {
    void* l2 = NULL;
    size_t l3;
    int32_t l4;
    int64_t l5;
    int64_t t0;
    void** gc_raw_roots[1] = { &l2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 44 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l2 = (void*) _a0_arr;
    if ((l0 <= l1)) {
        t0 = (((int64_t) (int32_t) (l1 - l0)) + INT64_C(1));
        l3 = (size_t) (int64_t) t0;
    } else {
        l3 = (size_t) 0;
    }
    vader_array_t* _a1_arr = vader_array_repeat((vader_array_t*) l2, (size_t) l3);
    l2 = (void*) _a1_arr;
#line 45 "tests/snippets/array_reserved_by_loop/_main.vader"
    l4 = l0;
    {
        vader_array_t* _pc24_hdr = (vader_array_t*) l2;
        size_t _pc24_len = _pc24_hdr->length;
        size_t _pc24_cap = (_pc24_hdr->offset == 0 && !vader_array_is_borrowed(_pc24_hdr) && _pc24_hdr->length >= _pc24_hdr->buf->length) ? _pc24_hdr->capacity : (size_t) 0;
        void* _pc24_slots = _pc24_hdr->buf->slots;
        for (;;) {
            if ((l4 <= l1)) {
#line 46 "tests/snippets/array_reserved_by_loop/_main.vader"
                l5 = snippet_square(l4);
                if (VADER_LIKELY(_pc24_len < _pc24_cap)) {
                    ((int64_t*) _pc24_slots)[_pc24_len] = (int64_t) (l5);
                    _pc24_len += 1;
                } else {
                    _pc24_hdr->length = _pc24_len;
                    if (_pc24_hdr->buf->length < _pc24_len) {
                        _pc24_hdr->buf->length = _pc24_len;
                    }
                    vader_array_push_i64((vader_array_t*) l2, l5);
                    _pc24_hdr = (vader_array_t*) l2;
                    _pc24_len = _pc24_hdr->length;
                    _pc24_cap = (_pc24_hdr->offset == 0 && !vader_array_is_borrowed(_pc24_hdr) && _pc24_hdr->length >= _pc24_hdr->buf->length) ? _pc24_hdr->capacity : (size_t) 0;
                    _pc24_slots = _pc24_hdr->buf->slots;
                }
#line 45 "tests/snippets/array_reserved_by_loop/_main.vader"
                l4 = (l4 + INT32_C(1));
                continue;
            }
            _pc24_hdr->length = _pc24_len;
            if (_pc24_hdr->buf->length < _pc24_len) {
                _pc24_hdr->buf->length = _pc24_len;
            }
            break;
        }
    }
#line 48 "tests/snippets/array_reserved_by_loop/_main.vader"
    { void* __vret = l2; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_over_field(void* l0) {
    void* l1 = NULL;
    void* l3 = NULL;
    size_t l2, l4;
    int64_t l5;
    int32_t t0;
    int64_t t1;
    void** gc_raw_roots[3] = { &l0, &l1, &l3 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 56 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l1 = (void*) _a0_arr;
#line 57 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = ((vader_array_t*) ((vader_struct_snippet_Bag_t*) l0)->f_items)->length;
#line 56 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a1_arr = vader_array_repeat((vader_array_t*) l1, (size_t) l2);
    l1 = (void*) _a1_arr;
#line 57 "tests/snippets/array_reserved_by_loop/_main.vader"
    l3 = ((vader_struct_snippet_Bag_t*) l0)->f_items;
    l2 = ((vader_array_t*) l3)->length;
    l4 = (size_t) 0;
    {
        vader_array_t* _pc16_hdr = (vader_array_t*) l1;
        size_t _pc16_len = _pc16_hdr->length;
        size_t _pc16_cap = (_pc16_hdr->offset == 0 && !vader_array_is_borrowed(_pc16_hdr) && _pc16_hdr->length >= _pc16_hdr->buf->length) ? _pc16_hdr->capacity : (size_t) 0;
        void* _pc16_slots = _pc16_hdr->buf->slots;
        for (;;) {
            if ((l4 < l2)) {
                vader_array_t* _a2_slotarr = ((vader_array_t*) l3);
                VADER_ARRAY_RESOLVE_BUF(_a2_slotarr)
                VADER_ARRAY_CHECK_INDEX(_a2_slotarr, l4)
                t0 = ((int32_t*) _a2_slotarr->buf->slots)[_a2_slotarr->offset + (size_t) l4];
#line 58 "tests/snippets/array_reserved_by_loop/_main.vader"
                l5 = snippet_square(t0);
                if (VADER_LIKELY(_pc16_len < _pc16_cap)) {
                    ((int64_t*) _pc16_slots)[_pc16_len] = (int64_t) (l5);
                    _pc16_len += 1;
                } else {
                    _pc16_hdr->length = _pc16_len;
                    if (_pc16_hdr->buf->length < _pc16_len) {
                        _pc16_hdr->buf->length = _pc16_len;
                    }
                    vader_array_push_i64((vader_array_t*) l1, l5);
                    _pc16_hdr = (vader_array_t*) l1;
                    _pc16_len = _pc16_hdr->length;
                    _pc16_cap = (_pc16_hdr->offset == 0 && !vader_array_is_borrowed(_pc16_hdr) && _pc16_hdr->length >= _pc16_hdr->buf->length) ? _pc16_hdr->capacity : (size_t) 0;
                    _pc16_slots = _pc16_hdr->buf->slots;
                }
#line 57 "tests/snippets/array_reserved_by_loop/_main.vader"
                t1 = (l4 + INT64_C(1));
                l4 = (size_t) (int64_t) t1;
                continue;
            }
            _pc16_hdr->length = _pc16_len;
            if (_pc16_hdr->buf->length < _pc16_len) {
                _pc16_hdr->buf->length = _pc16_len;
            }
            break;
        }
    }
#line 60 "tests/snippets/array_reserved_by_loop/_main.vader"
    { void* __vret = l1; vader_gc_top = gc_frame.prev; return __vret; }
}

static int64_t snippet_split(void* l0) {
    void* l1 = NULL;
    void* l3 = NULL;
    void* l4 = NULL;
    size_t l2, l5;
    int32_t l6;
    int64_t l7, l8;
    int64_t t0;
    size_t t1;
    void** gc_raw_roots[4] = { &l0, &l1, &l3, &l4 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 4u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 65 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l1 = (void*) _a0_arr;
#line 68 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = ((vader_array_t*) l0)->length;
#line 65 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a1_arr = vader_array_repeat((vader_array_t*) l1, (size_t) l2);
    l1 = (void*) _a1_arr;
#line 66 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a2_arr = vader_array_new(5u, 0u, 8u, 2u);
    l3 = (void*) _a2_arr;
#line 68 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = ((vader_array_t*) l0)->length;
#line 66 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a3_arr = vader_array_repeat((vader_array_t*) l3, (size_t) l2);
    l3 = (void*) _a3_arr;
#line 68 "tests/snippets/array_reserved_by_loop/_main.vader"
    l4 = l0;
    l2 = ((vader_array_t*) l4)->length;
    l5 = (size_t) 0;
    while ((l5 < l2)) {
        vader_array_t* _a4_slotarr = ((vader_array_t*) l4);
        VADER_ARRAY_RESOLVE_BUF(_a4_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a4_slotarr, l5)
        l6 = ((int32_t*) _a4_slotarr->buf->slots)[_a4_slotarr->offset + (size_t) l5];
#line 69 "tests/snippets/array_reserved_by_loop/_main.vader"
        l7 = snippet_square(l6);
        vader_array_push_i64((vader_array_t*) l1, l7);
#line 70 "tests/snippets/array_reserved_by_loop/_main.vader"
        l8 = ((int64_t) (int32_t) ((l6 * INT32_C(2)) + INT32_C(100)));
        vader_array_push_i64((vader_array_t*) l3, l8);
#line 68 "tests/snippets/array_reserved_by_loop/_main.vader"
        t0 = (l5 + INT64_C(1));
        l5 = (size_t) (int64_t) t0;
    }
#line 72 "tests/snippets/array_reserved_by_loop/_main.vader"
    t1 = ((vader_array_t*) l1)->length;
    t0 = (t1 - INT64_C(1));
    l2 = (size_t) (int64_t) t0;
    vader_array_t* _a5_slotarr = ((vader_array_t*) l1);
    VADER_ARRAY_RESOLVE_BUF(_a5_slotarr)
    VADER_ARRAY_CHECK_INDEX(_a5_slotarr, l2)
    l7 = ((int64_t*) _a5_slotarr->buf->slots)[_a5_slotarr->offset + (size_t) l2];
    vader_array_t* _a6_slotarr = ((vader_array_t*) l3);
    VADER_ARRAY_RESOLVE_BUF(_a6_slotarr)
    VADER_ARRAY_CHECK_INDEX(_a6_slotarr, INT32_C(0))
    l8 = ((int64_t*) _a6_slotarr->buf->slots)[_a6_slotarr->offset + (size_t) INT32_C(0)];
    { int64_t __vret = (l7 + l8); vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_box_t snippet_squares_later(void* l0) {
    void* l1 = NULL;
    void* l2 = NULL;
    vader_box_t l3 = vader_box_null();
    void* t0 = NULL;
    vader_box_t* gc_roots[1] = { &l3 };
    void** gc_raw_roots[4] = { &l0, &l1, &l2, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 1u, 4u, gc_roots, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
    l1 = vader_box_obj(0u, NULL).payload.obj;
    l2 = vader_box_obj(0u, NULL).payload.obj;
    l3 = vader_box_obj(0u, NULL);
    vader_struct___asyncstate_snippet_0_t* _a0_obj = (vader_struct___asyncstate_snippet_0_t*) vader_gc_alloc(sizeof(vader_struct___asyncstate_snippet_0_t));
    vader_obj_header_init(_a0_obj, 10u);
    _a0_obj->f_s0 = l0;
    _a0_obj->f_s1 = l1;
    _a0_obj->f_s2 = l2;
    _a0_obj->f_s3 = (size_t) 0;
    _a0_obj->f_s4 = (size_t) 0;
    _a0_obj->f_s5 = INT32_C(0);
    _a0_obj->f_s6 = vader_box_obj(0u, NULL);
    _a0_obj->f_awaited = l3;
    _a0_obj->f_state = INT32_C(9);
    t0 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_odd_squares(void* l0) {
    void* l1 = NULL;
    void* l2 = NULL;
    size_t l3, l4;
    int32_t l5;
    int64_t l6;
    bool t0;
    int64_t t1;
    void** gc_raw_roots[3] = { &l0, &l1, &l2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 86 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l1 = (void*) _a0_arr;
#line 87 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = l0;
    l3 = ((vader_array_t*) l2)->length;
    l4 = (size_t) 0;
    {
        vader_array_t* _pc9_hdr = (vader_array_t*) l1;
        size_t _pc9_len = _pc9_hdr->length;
        size_t _pc9_cap = (_pc9_hdr->offset == 0 && !vader_array_is_borrowed(_pc9_hdr) && _pc9_hdr->length >= _pc9_hdr->buf->length) ? _pc9_hdr->capacity : (size_t) 0;
        void* _pc9_slots = _pc9_hdr->buf->slots;
        for (;;) {
            if ((l4 < l3)) {
                vader_array_t* _a1_slotarr = ((vader_array_t*) l2);
                VADER_ARRAY_RESOLVE_BUF(_a1_slotarr)
                VADER_ARRAY_CHECK_INDEX(_a1_slotarr, l4)
                l5 = ((int32_t*) _a1_slotarr->buf->slots)[_a1_slotarr->offset + (size_t) l4];
#line 88 "tests/snippets/array_reserved_by_loop/_main.vader"
                t0 = snippet_odd(l5);
                if (t0) {
#line 89 "tests/snippets/array_reserved_by_loop/_main.vader"
                    l6 = snippet_square(l5);
                    if (VADER_LIKELY(_pc9_len < _pc9_cap)) {
                        ((int64_t*) _pc9_slots)[_pc9_len] = (int64_t) (l6);
                        _pc9_len += 1;
                    } else {
                        _pc9_hdr->length = _pc9_len;
                        if (_pc9_hdr->buf->length < _pc9_len) {
                            _pc9_hdr->buf->length = _pc9_len;
                        }
                        vader_array_push_i64((vader_array_t*) l1, l6);
                        _pc9_hdr = (vader_array_t*) l1;
                        _pc9_len = _pc9_hdr->length;
                        _pc9_cap = (_pc9_hdr->offset == 0 && !vader_array_is_borrowed(_pc9_hdr) && _pc9_hdr->length >= _pc9_hdr->buf->length) ? _pc9_hdr->capacity : (size_t) 0;
                        _pc9_slots = _pc9_hdr->buf->slots;
                    }
#line 88 "tests/snippets/array_reserved_by_loop/_main.vader"
                }
#line 87 "tests/snippets/array_reserved_by_loop/_main.vader"
                t1 = (l4 + INT64_C(1));
                l4 = (size_t) (int64_t) t1;
                continue;
            }
            _pc9_hdr->length = _pc9_len;
            if (_pc9_hdr->buf->length < _pc9_len) {
                _pc9_hdr->buf->length = _pc9_len;
            }
            break;
        }
    }
#line 92 "tests/snippets/array_reserved_by_loop/_main.vader"
    { void* __vret = l1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_until_big(void* l0) {
    void* l1 = NULL;
    void* l2 = NULL;
    size_t l3, l4;
    int32_t l5;
    int64_t l6;
    int64_t t0;
    void** gc_raw_roots[3] = { &l0, &l1, &l2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 97 "tests/snippets/array_reserved_by_loop/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(5u, 0u, 8u, 2u);
    l1 = (void*) _a0_arr;
#line 98 "tests/snippets/array_reserved_by_loop/_main.vader"
    l2 = l0;
    l3 = ((vader_array_t*) l2)->length;
    l4 = (size_t) 0;
    {
        vader_array_t* _pc9_hdr = (vader_array_t*) l1;
        size_t _pc9_len = _pc9_hdr->length;
        size_t _pc9_cap = (_pc9_hdr->offset == 0 && !vader_array_is_borrowed(_pc9_hdr) && _pc9_hdr->length >= _pc9_hdr->buf->length) ? _pc9_hdr->capacity : (size_t) 0;
        void* _pc9_slots = _pc9_hdr->buf->slots;
        for (;;) {
            if ((l4 < l3)) {
                vader_array_t* _a1_slotarr = ((vader_array_t*) l2);
                VADER_ARRAY_RESOLVE_BUF(_a1_slotarr)
                VADER_ARRAY_CHECK_INDEX(_a1_slotarr, l4)
                l5 = ((int32_t*) _a1_slotarr->buf->slots)[_a1_slotarr->offset + (size_t) l4];
#line 99 "tests/snippets/array_reserved_by_loop/_main.vader"
                if ((l5 > INT32_C(3))) {
#line 102 "tests/snippets/array_reserved_by_loop/_main.vader"
                } else {
                    l6 = snippet_square(l5);
                    if (VADER_LIKELY(_pc9_len < _pc9_cap)) {
                        ((int64_t*) _pc9_slots)[_pc9_len] = (int64_t) (l6);
                        _pc9_len += 1;
                    } else {
                        _pc9_hdr->length = _pc9_len;
                        if (_pc9_hdr->buf->length < _pc9_len) {
                            _pc9_hdr->buf->length = _pc9_len;
                        }
                        vader_array_push_i64((vader_array_t*) l1, l6);
                        _pc9_hdr = (vader_array_t*) l1;
                        _pc9_len = _pc9_hdr->length;
                        _pc9_cap = (_pc9_hdr->offset == 0 && !vader_array_is_borrowed(_pc9_hdr) && _pc9_hdr->length >= _pc9_hdr->buf->length) ? _pc9_hdr->capacity : (size_t) 0;
                        _pc9_slots = _pc9_hdr->buf->slots;
                    }
#line 98 "tests/snippets/array_reserved_by_loop/_main.vader"
                    t0 = (l4 + INT64_C(1));
                    l4 = (size_t) (int64_t) t0;
                    continue;
#line 99 "tests/snippets/array_reserved_by_loop/_main.vader"
                }
#line 98 "tests/snippets/array_reserved_by_loop/_main.vader"
            }
            _pc9_hdr->length = _pc9_len;
            if (_pc9_hdr->buf->length < _pc9_len) {
                _pc9_hdr->buf->length = _pc9_len;
            }
            break;
        }
    }
#line 104 "tests/snippets/array_reserved_by_loop/_main.vader"
    { void* __vret = l1; vader_gc_top = gc_frame.prev; return __vret; }
}

static int32_t snippet_main(void) {
    void* l0 = NULL;
    void* l1 = NULL;
    void* l2 = NULL;
    void* l3 = NULL;
    vader_box_t l4 = vader_box_null();
    void* t0 = NULL;
    vader_box_t t1 = vader_box_null();
    int32_t t2;
    vader_box_t* gc_roots[2] = { &l4, &t1 };
    void** gc_raw_roots[5] = { &l0, &l1, &l2, &l3, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 2u, 5u, gc_roots, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
    l0 = vader_box_obj(0u, NULL).payload.obj;
    l1 = vader_box_obj(0u, NULL).payload.obj;
    l2 = vader_box_obj(0u, NULL).payload.obj;
    l3 = vader_box_obj(0u, NULL).payload.obj;
    l4 = vader_box_obj(0u, NULL);
    vader_struct___asyncstate_snippet_1_t* _a0_obj = (vader_struct___asyncstate_snippet_1_t*) vader_gc_alloc(sizeof(vader_struct___asyncstate_snippet_1_t));
    vader_obj_header_init(_a0_obj, 13u);
    _a0_obj->f_s0 = l0;
    _a0_obj->f_s1 = l1;
    _a0_obj->f_s2 = l2;
    _a0_obj->f_s3 = l3;
    _a0_obj->f_awaited = l4;
    _a0_obj->f_state = INT32_C(5);
    t0 = (void*) _a0_obj;
    t1 = vader_ref_box(t0);
    t2 = std_async_run_async_main(t1);
    { int32_t __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_box_t snippet___asyncstate_snippet_0_Async_resume(void* l0) {
    int32_t l1, l9;
    vader_box_t l2 = vader_box_null(), l4 = vader_box_null();
    vader_box_t l3;
    size_t l5, l6, l8, l12, l14, l16;
    void* l7 = NULL;
    void* l10 = NULL;
    void* l13 = NULL;
    void* l15 = NULL;
    void* l17 = NULL;
    int64_t l11;
    int32_t t0;
    void* t1 = NULL;
    vader_box_t t2 = vader_box_null();
    size_t t3;
    int64_t t4;
    vader_box_t* gc_roots[3] = { &l2, &l4, &t2 };
    void** gc_raw_roots[7] = { &l0, &l7, &l10, &l13, &l15, &l17, &t1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 3u, 7u, gc_roots, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
    for (;;) {
        t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
        if (t0 == INT32_C(0)) {
            ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(-1);
            continue;
        }
        t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
        if (t0 == INT32_C(1)) {
            l1 = INT32_C(-1);
            ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = l1;
            { vader_box_t __vret = vader_ref_box(((vader_struct___asyncstate_snippet_0_t*) l0)->f_s1); vader_gc_top = gc_frame.prev; return __vret; }
        }
        t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
        if (t0 == INT32_C(2)) {
            ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(1);
        } else {
            t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
            if (t0 == INT32_C(3)) {
                l2 = vader_vt_Async__resume(((vader_struct___asyncstate_snippet_0_t*) l0)->f_awaited);
                if (l2.tag == 12u) {
                    vader_struct_std_core_Suspended_t* _a0_obj = (vader_struct_std_core_Suspended_t*) vader_gc_alloc(sizeof(vader_struct_std_core_Suspended_t));
                    vader_obj_header_init(_a0_obj, 12u);
                    t1 = (void*) _a0_obj;
                    { vader_box_t __vret = vader_ref_box(t1); vader_gc_top = gc_frame.prev; return __vret; }
                }
                l3 = l2;
                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s6 = l3;
                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(2);
            } else {
                t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
                if (t0 == INT32_C(4)) {
#line 80 "tests/snippets/array_reserved_by_loop/_main.vader"
                    t2 = std_async_sleep(INT64_C(0));
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                    l4 = t2;
                    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_awaited = l4;
                    VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_0_t*) l0);
                    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(3);
                } else {
                    t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
                    if (t0 == INT32_C(5)) {
                        ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(4);
                    } else {
                        t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
                        if (t0 == INT32_C(6)) {
                            l5 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s4;
                            l6 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s3;
#line 77 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                            if ((l5 < l6)) {
                                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(7);
                            } else {
                                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(5);
                            }
                        } else {
                            t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
                            if (t0 == INT32_C(7)) {
                                l7 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s2;
                                l8 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s4;
#line 77 "tests/snippets/array_reserved_by_loop/_main.vader"
                                vader_array_t* _a1_slotarr = ((vader_array_t*) l7);
                                VADER_ARRAY_RESOLVE_BUF(_a1_slotarr)
                                VADER_ARRAY_CHECK_INDEX(_a1_slotarr, l8)
                                l9 = ((int32_t*) _a1_slotarr->buf->slots)[_a1_slotarr->offset + (size_t) l8];
                                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s5 = l9;
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                                l10 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s1;
                                t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s5;
#line 78 "tests/snippets/array_reserved_by_loop/_main.vader"
                                l11 = snippet_square(t0);
                                vader_array_push_i64((vader_array_t*) l10, l11);
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                                t3 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s4;
#line 77 "tests/snippets/array_reserved_by_loop/_main.vader"
                                t4 = (t3 + INT64_C(1));
                                l12 = (size_t) (int64_t) t4;
                                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s4 = l12;
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                                ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(6);
                            } else {
                                t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
                                if (t0 == INT32_C(8)) {
                                    l13 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s0;
#line 77 "tests/snippets/array_reserved_by_loop/_main.vader"
                                    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s2 = l13;
                                    VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_0_t*) l0);
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 77 "tests/snippets/array_reserved_by_loop/_main.vader"
                                    l14 = ((vader_array_t*) ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s2)->length;
                                    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s3 = l14;
                                    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s4 = (size_t) 0;
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                                    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(6);
                                } else {
                                    t0 = ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state;
                                    if (t0 == INT32_C(9)) {
#line 76 "tests/snippets/array_reserved_by_loop/_main.vader"
                                        vader_array_t* _a2_arr = vader_array_new(5u, 0u, 8u, 2u);
                                        l15 = (void*) _a2_arr;
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 77 "tests/snippets/array_reserved_by_loop/_main.vader"
                                        l16 = ((vader_array_t*) ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s0)->length;
#line 76 "tests/snippets/array_reserved_by_loop/_main.vader"
                                        vader_array_t* _a3_arr = vader_array_repeat((vader_array_t*) l15, (size_t) l16);
                                        l17 = (void*) _a3_arr;
                                        ((vader_struct___asyncstate_snippet_0_t*) l0)->f_s1 = l17;
                                        VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_0_t*) l0);
#line 75 "tests/snippets/array_reserved_by_loop/_main.vader"
                                        ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = INT32_C(8);
                                    } else {
                                        vader_struct_std_core_Suspended_t* _a4_obj = (vader_struct_std_core_Suspended_t*) vader_gc_alloc(sizeof(vader_struct_std_core_Suspended_t));
                                        vader_obj_header_init(_a4_obj, 12u);
                                        t1 = (void*) _a4_obj;
                                        { vader_box_t __vret = vader_ref_box(t1); vader_gc_top = gc_frame.prev; return __vret; }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        continue;
    }
    l1 = INT32_C(-1);
    ((vader_struct___asyncstate_snippet_0_t*) l0)->f_state = l1;
    { vader_box_t __vret = vader_ref_box(((vader_struct___asyncstate_snippet_0_t*) l0)->f_s1); vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_box_t snippet___asyncstate_snippet_1_Async_resume(void* l0) {
    int32_t l1, l19;
    void* l2 = NULL;
    void* l3 = NULL;
    void* l5 = NULL;
    void* l7 = NULL;
    void* l8 = NULL;
    void* l9 = NULL;
    void* l10 = NULL;
    void* l11 = NULL;
    void* l12 = NULL;
    void* l14 = NULL;
    void* l18 = NULL;
    void* l21 = NULL;
    void* l22 = NULL;
    void* l23 = NULL;
    void* l24 = NULL;
    void* l25 = NULL;
    void* l26 = NULL;
    void* l27 = NULL;
    void* l28 = NULL;
    vader_box_t l4 = vader_box_null(), l6 = vader_box_null();
    size_t l13, l15, l16, l29;
    int64_t l17, l20, l30;
    int32_t t0;
    void* t1 = NULL;
    vader_box_t t2 = vader_box_null();
    int64_t t3;
    vader_string_t t4 = 0;
    vader_box_t* gc_roots[3] = { &l4, &l6, &t2 };
    void** gc_raw_roots[21] = {
        &l0, &l2, &l3, &l5, &l7, &l8, &l9, &l10, &l11, &l12, &l14, &l18, &l21, &l22, &l23, &l24,
        &l25, &l26, &l27, &l28, &t1,
    };
    vader_string_t* gc_atom_roots[1] = { &t4 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 3u, 21u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
    for (;;) {
        t0 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state;
        if (t0 == INT32_C(0)) {
            ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = INT32_C(-1);
            continue;
        }
        t0 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state;
        if (t0 == INT32_C(1)) {
            l1 = INT32_C(-1);
            ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = l1;
#line 124 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
            { vader_box_t __vret = vader_box_i32(1u, INT32_C(0)); vader_gc_top = gc_frame.prev; return __vret; }
        }
        t0 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state;
        if (t0 == INT32_C(2)) {
            l2 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s2;
#line 122 "tests/snippets/array_reserved_by_loop/_main.vader"
            ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s3 = l2;
            VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_1_t*) l0);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
            l3 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s3;
#line 123 "tests/snippets/array_reserved_by_loop/_main.vader"
            snippet_show(3u, l3);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
            ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = INT32_C(1);
        } else {
            t0 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state;
            if (t0 == INT32_C(3)) {
                l4 = vader_vt_Async__resume(((vader_struct___asyncstate_snippet_1_t*) l0)->f_awaited);
                if (l4.tag == 12u) {
                    vader_struct_std_core_Suspended_t* _a0_obj = (vader_struct_std_core_Suspended_t*) vader_gc_alloc(sizeof(vader_struct_std_core_Suspended_t));
                    vader_obj_header_init(_a0_obj, 12u);
                    t1 = (void*) _a0_obj;
                    { vader_box_t __vret = vader_ref_box(t1); vader_gc_top = gc_frame.prev; return __vret; }
                }
                l5 = l4.payload.obj;
                ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s2 = l5;
                VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_1_t*) l0);
                ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = INT32_C(2);
            } else {
                t0 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state;
                if (t0 == INT32_C(4)) {
#line 122 "tests/snippets/array_reserved_by_loop/_main.vader"
                    t2 = snippet_squares_later(((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
                    l6 = t2;
                    ((vader_struct___asyncstate_snippet_1_t*) l0)->f_awaited = l6;
                    VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_1_t*) l0);
                    ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = INT32_C(3);
                } else {
                    t0 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state;
                    if (t0 == INT32_C(5)) {
#line 108 "tests/snippets/array_reserved_by_loop/_main.vader"
                        vader_array_t* _a1_arr = vader_array_new(7u, 5u, 7u, 1u);
                        ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 4u] = (int32_t) INT32_C(5);
                        ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 3u] = (int32_t) INT32_C(4);
                        ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 2u] = (int32_t) INT32_C(3);
                        ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 1u] = (int32_t) INT32_C(2);
                        ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 0u] = (int32_t) INT32_C(1);
                        l7 = (void*) _a1_arr;
                        ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0 = l7;
                        VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_1_t*) l0);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 109 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l8 = snippet_over_array(((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0);
                        snippet_show(4u, l8);
#line 110 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l9 = snippet_over_range(INT32_C(2), INT32_C(6));
                        snippet_show(5u, l9);
#line 111 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l10 = snippet_over_range(INT32_C(6), INT32_C(2));
                        snippet_show(6u, l10);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l11 = ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0;
#line 86 "lib/std/iter/iter.vader"
                        vader_array_t* _a2_arr = vader_array_new(5u, 0u, 8u, 2u);
                        l12 = (void*) _a2_arr;
#line 112 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l13 = ((vader_array_t*) l11)->length;
#line 86 "lib/std/iter/iter.vader"
                        vader_array_t* _a3_arr = vader_array_repeat((vader_array_t*) l12, (size_t) l13);
                        l14 = (void*) _a3_arr;
#line 112 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l15 = ((vader_array_t*) l11)->length;
                        l16 = (size_t) 0;
#line 87 "lib/std/iter/iter.vader"
                        while ((l16 < l15)) {
#line 112 "tests/snippets/array_reserved_by_loop/_main.vader"
                            vader_array_t* _a4_slotarr = ((vader_array_t*) l11);
                            VADER_ARRAY_RESOLVE_BUF(_a4_slotarr)
                            VADER_ARRAY_CHECK_INDEX(_a4_slotarr, l16)
                            t0 = ((int32_t*) _a4_slotarr->buf->slots)[_a4_slotarr->offset + (size_t) l16];
#line 309 "lib/std/iter/iter.vader"
                            l17 = snippet_square(t0);
#line 88 "lib/std/iter/iter.vader"
                            vader_array_push_i64((vader_array_t*) l14, l17);
#line 112 "tests/snippets/array_reserved_by_loop/_main.vader"
                            t3 = (l16 + INT64_C(1));
                            l16 = (size_t) (int64_t) t3;
#line 87 "lib/std/iter/iter.vader"
#line 112 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 87 "lib/std/iter/iter.vader"
                        }
#line 112 "tests/snippets/array_reserved_by_loop/_main.vader"
                        snippet_show(7u, l14);
#line 86 "lib/std/iter/iter.vader"
                        vader_array_t* _a5_arr = vader_array_new(5u, 0u, 8u, 2u);
                        t1 = (void*) _a5_arr;
                        vader_array_t* _a6_arr = vader_array_repeat((vader_array_t*) t1, (size_t) INT64_C(4));
                        l18 = (void*) _a6_arr;
#line 113 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l19 = INT32_C(0);
#line 87 "lib/std/iter/iter.vader"
                        while ((l19 < INT32_C(4))) {
#line 113 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 309 "lib/std/iter/iter.vader"
                            l20 = snippet_square(l19);
#line 88 "lib/std/iter/iter.vader"
                            vader_array_push_i64((vader_array_t*) l18, l20);
#line 113 "tests/snippets/array_reserved_by_loop/_main.vader"
                            l19 = (l19 + INT32_C(1));
#line 87 "lib/std/iter/iter.vader"
#line 113 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 87 "lib/std/iter/iter.vader"
                        }
#line 113 "tests/snippets/array_reserved_by_loop/_main.vader"
                        snippet_show(8u, l18);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 114 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l21 = snippet_odd_squares(((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0);
                        snippet_show(9u, l21);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 115 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l22 = snippet_until_big(((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0);
                        snippet_show(10u, l22);
#line 116 "tests/snippets/array_reserved_by_loop/_main.vader"
                        vader_array_t* _a7_arr = vader_array_new(7u, 0u, 7u, 1u);
                        l23 = (void*) _a7_arr;
                        ((vader_struct___asyncstate_snippet_1_t*) l0)->f_s1 = l23;
                        VADER_WRITE_BARRIER((vader_struct___asyncstate_snippet_1_t*) l0);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 117 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l24 = snippet_over_array(((vader_struct___asyncstate_snippet_1_t*) l0)->f_s1);
                        snippet_show(11u, l24);
#line 118 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l25 = snippet_over_inclusive(INT32_C(1), INT32_C(3));
                        snippet_show(12u, l25);
#line 119 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l26 = snippet_over_inclusive(INT32_C(3), INT32_C(1));
                        snippet_show(13u, l26);
#line 120 "tests/snippets/array_reserved_by_loop/_main.vader"
                        vader_array_t* _a8_arr = vader_array_new(7u, 2u, 7u, 1u);
                        ((int32_t*) _a8_arr->buf->slots)[_a8_arr->offset + 1u] = (int32_t) INT32_C(4);
                        ((int32_t*) _a8_arr->buf->slots)[_a8_arr->offset + 0u] = (int32_t) INT32_C(3);
                        t1 = (void*) _a8_arr;
                        vader_struct_snippet_Bag_t* _a9_obj = (vader_struct_snippet_Bag_t*) vader_gc_alloc(sizeof(vader_struct_snippet_Bag_t));
                        vader_obj_header_init(_a9_obj, 8u);
                        _a9_obj->f_items = t1;
                        t1 = (void*) _a9_obj;
                        l27 = snippet_over_field(t1);
                        snippet_show(14u, l27);
#line 121 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l28 = std_core_new_byte_buffer((size_t) 27);
                        l29 = (size_t) 0;
                        l29 = std_core_write_string_at(l28, l29, 15u);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 121 "tests/snippets/array_reserved_by_loop/_main.vader"
                        l30 = snippet_split(((vader_struct___asyncstate_snippet_1_t*) l0)->f_s0);
                        l29 = std_core_write_int(l28, l29, l30);
                        t4 = std_core_finish_buffer(l28, l29);
                        std_io_println__string(t4);
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
                        ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = INT32_C(4);
                    } else {
                        vader_struct_std_core_Suspended_t* _a10_obj = (vader_struct_std_core_Suspended_t*) vader_gc_alloc(sizeof(vader_struct_std_core_Suspended_t));
                        vader_obj_header_init(_a10_obj, 12u);
                        t1 = (void*) _a10_obj;
                        { vader_box_t __vret = vader_ref_box(t1); vader_gc_top = gc_frame.prev; return __vret; }
                    }
                }
            }
        }
        continue;
    }
    l1 = INT32_C(-1);
    ((vader_struct___asyncstate_snippet_1_t*) l0)->f_state = l1;
#line 124 "tests/snippets/array_reserved_by_loop/_main.vader"
#line 107 "tests/snippets/array_reserved_by_loop/_main.vader"
    { vader_box_t __vret = vader_box_i32(1u, INT32_C(0)); vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t concat_2(vader_string_t l0, vader_string_t l1) {
    size_t l2, l3;
    void* l4 = NULL;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l4 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l1, &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    l2 = vader_host_std_core_byte_len(l0);
    l3 = vader_host_std_core_byte_len(l1);
    t0 = (l2 + l3);
    l3 = (size_t) (int64_t) t0;
    l4 = std_core_usize_BufferAlloc_new_buffer_vt(l3);
    std_core_Buffer_ByteAccess_write_string_vt(l4, (size_t) 0, l0);
    std_core_Buffer_ByteAccess_write_string_vt(l4, l2, l1);
    t1 = std_core_Buffer_ByteAccess_intern_string_vt(l4, l3);
    { vader_string_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_new_byte_buffer(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 101 "lib/std/core/primitives.vader"
    t0 = std_core_usize_BufferAlloc_new_buffer_vt(l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t std_core_finish_buffer(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 104 "lib/std/core/primitives.vader"
    t0 = std_core_Buffer_ByteAccess_intern_string_vt(l0, l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2) {
    size_t l3;
#line 121 "lib/std/core/primitives.vader"
    std_core_Buffer_ByteAccess_write_string_vt(l0, l1, l2);
#line 122 "lib/std/core/primitives.vader"
    l3 = vader_host_std_core_byte_len(l2);
    return (size_t) (int64_t) (l1 + l3);
}

static size_t std_core_write_int(void* l0, size_t l1, int64_t l2) {
    bool l3;
    size_t l4, l6;
    int64_t l5;
    uint8_t l7, l8;
    int64_t t0;
    int32_t t1;
#line 127 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 128 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 129 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 127 "lib/std/core/primitives.vader"
    }
#line 131 "lib/std/core/primitives.vader"
    l3 = (l2 < INT64_C(0));
#line 132 "lib/std/core/primitives.vader"
    if ((l2 > INT64_C(0))) {
        l2 = -(l2);
    }
#line 133 "lib/std/core/primitives.vader"
    l4 = (size_t) 0;
#line 134 "lib/std/core/primitives.vader"
    l5 = l2;
#line 135 "lib/std/core/primitives.vader"
    while (l5 != INT64_C(0)) {
#line 136 "lib/std/core/primitives.vader"
        t0 = (l4 + INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 137 "lib/std/core/primitives.vader"
        l5 = vader_div_i64(l5, INT64_C(10));
#line 135 "lib/std/core/primitives.vader"
    }
#line 139 "lib/std/core/primitives.vader"
    if (l3) {
        t0 = (l4 + INT64_C(1));
        l6 = (size_t) (int64_t) t0;
    } else {
        l6 = l4;
    }
#line 140 "lib/std/core/primitives.vader"
    t0 = (l1 + l6);
    l4 = (size_t) (int64_t) t0;
#line 141 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 142 "lib/std/core/primitives.vader"
        t0 = (l4 - INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 143 "lib/std/core/primitives.vader"
        t0 = vader_mod_i64(l2, INT64_C(10));
        t1 = (((int32_t) (int64_t) -(t0)) & INT32_C(255));
        l7 = (uint8_t) (int32_t) t1;
        t1 = ((INT32_C(48) + l7) & INT32_C(255));
        l8 = (uint8_t) (int32_t) t1;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l4, l8);
#line 144 "lib/std/core/primitives.vader"
        l2 = vader_div_i64(l2, INT64_C(10));
#line 141 "lib/std/core/primitives.vader"
    }
#line 146 "lib/std/core/primitives.vader"
    if (l3) {
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 45);
    }
#line 147 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l6);
}

static vader_box_t std_async_sleep(int64_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 55 "lib/std/async/async.vader"
    vader_struct_std_async_Sleep_t* _a0_obj = (vader_struct_std_async_Sleep_t*) vader_gc_alloc(sizeof(vader_struct_std_async_Sleep_t));
    vader_obj_header_init(_a0_obj, 22u);
    _a0_obj->f_ms = l0;
    _a0_obj->f_deadline = INT64_C(0);
    _a0_obj->f_armed = false;
    t0 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static int32_t std_async_run_async_main(vader_box_t l0) {
    int32_t t0;
    vader_box_t* gc_roots[1] = { &l0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 1u, 0u, gc_roots, NULL, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 68 "lib/std/async/async.vader"
    t0 = std_async_block_on__i32(l0);
    { int32_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_box_t std_async_Sleep_Async_resume(void* l0) {
    int64_t l1, l2;
    bool t0;
    int64_t t1;
    void* t2 = NULL;
    void** gc_raw_roots[2] = { &l0, &t2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 39 "lib/std/async/async.vader"
    t0 = ((vader_struct_std_async_Sleep_t*) l0)->f_armed;
    if (!(t0)) {
#line 40 "lib/std/async/async.vader"
        ((vader_struct_std_async_Sleep_t*) l0)->f_armed = true;
#line 41 "lib/std/async/async.vader"
        l1 = vader_host_std_runtime_sched_now();
        l2 = ((vader_struct_std_async_Sleep_t*) l0)->f_ms;
        l1 = (l1 + l2);
        ((vader_struct_std_async_Sleep_t*) l0)->f_deadline = l1;
#line 42 "lib/std/async/async.vader"
        t1 = ((vader_struct_std_async_Sleep_t*) l0)->f_deadline;
        vader_host_std_runtime_sched_arm(t1);
#line 39 "lib/std/async/async.vader"
    }
#line 44 "lib/std/async/async.vader"
    l1 = vader_host_std_runtime_sched_now();
    l2 = ((vader_struct_std_async_Sleep_t*) l0)->f_deadline;
    if ((l1 >= l2)) {
        { vader_gc_top = gc_frame.prev; return vader_box_obj(0u, NULL); }
    }
#line 45 "lib/std/async/async.vader"
    vader_struct_std_core_Suspended_t* _a0_obj = (vader_struct_std_core_Suspended_t*) vader_gc_alloc(sizeof(vader_struct_std_core_Suspended_t));
    vader_obj_header_init(_a0_obj, 12u);
    t2 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t2); vader_gc_top = gc_frame.prev; return __vret; }
}

static int32_t std_async_block_on__i32(vader_box_t l0) {
    vader_box_t l1 = vader_box_null();
    int32_t t0;
    vader_box_t* gc_roots[2] = { &l0, &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 2u, 0u, gc_roots, NULL, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 80 "lib/std/async/async.vader"
    for (;;) {
#line 81 "lib/std/async/async.vader"
        l1 = vader_vt_Async__resume(l0);
#line 82 "lib/std/async/async.vader"
        if (l1.tag == 12u) {
#line 83 "lib/std/async/async.vader"
            t0 = vader_host_std_runtime_sched_park();
            if (t0 == INT32_C(1)) {
#line 84 "lib/std/async/async.vader"
                vader_host_std_abort_panic(16u);
                vader_unreachable("a no-return call returned");
#line 83 "lib/std/async/async.vader"
            }
#line 82 "lib/std/async/async.vader"
#line 87 "lib/std/async/async.vader"
        } else {
            t0 = ((int32_t) l1.payload.i);
            { int32_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
#line 82 "lib/std/async/async.vader"
        }
#line 80 "lib/std/async/async.vader"
        continue;
    }
#line 87 "lib/std/async/async.vader"
    t0 = ((int32_t) l1.payload.i);
    { int32_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_write(uint8_t l0, vader_string_t l1) {
    void* l2 = NULL;
    void* l6 = NULL;
    size_t l3, l4, l5, l7, l9;
    int32_t l8;
    int64_t t0;
    void** gc_raw_roots[2] = { &l2, &l6 };
    vader_string_t* gc_atom_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 205 "lib/std/io/io.vader"
    l2 = vader_host_std_core_bytes(l1);
#line 206 "lib/std/io/io.vader"
    l3 = (size_t) 0;
#line 207 "lib/std/io/io.vader"
    for (;;) {
#line 208 "lib/std/io/io.vader"
        l4 = ((vader_array_t*) l2)->length;
        if ((l3 >= l4)) {
#line 209 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 208 "lib/std/io/io.vader"
        }
#line 211 "lib/std/io/io.vader"
        l5 = ((vader_array_t*) l2)->length;
        vader_array_t* _a0_arr = vader_array_slice((vader_array_t*) l2, (size_t) l3, (size_t) l5);
        l6 = (void*) _a0_arr;
#line 212 "lib/std/io/io.vader"
        l7 = ((vader_array_t*) l6)->length;
        l8 = std_io_write_bytes(l0, l6, l7);
#line 213 "lib/std/io/io.vader"
        if ((l8 <= INT32_C(0))) {
#line 214 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 213 "lib/std/io/io.vader"
        }
#line 216 "lib/std/io/io.vader"
        t0 = ((int64_t) (int32_t) l8);
        l9 = (size_t) (int64_t) t0;
        t0 = (l3 + l9);
        l3 = (size_t) (int64_t) t0;
#line 207 "lib/std/io/io.vader"
        continue;
    }
#line 209 "lib/std/io/io.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2) {
    int32_t l3;
    ptrdiff_t t0;
    void** gc_raw_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 177 "lib/std/io/io.vader"
    if (l0 == INT32_C(0)) {
        l3 = INT32_C(1);
    } else {
        l3 = INT32_C(2);
    }
#line 180 "lib/std/io/io.vader"
    t0 = vader_host_system_posix_sys_write(l3, l1, l2);
    { int32_t __vret = ((int32_t) (ptrdiff_t) t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_println__string(vader_string_t l0) {
    vader_string_t l1 = 0;
    vader_string_t* gc_atom_roots[2] = { &l0, &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL, 2u, gc_atom_roots };
    vader_gc_top = &gc_frame;
#line 235 "lib/std/io/io.vader"
    l1 = concat_2(l0, 17u);
    std_io_write((uint8_t) 0, l1);
    { vader_gc_top = gc_frame.prev; return; }
}

static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
    t0 = (void*) vader_buffer_new((size_t) l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2) {
    vader_buffer_store_u8((vader_buffer_t*) l0, (size_t) l1, (uint8_t) l2);
    return;
}

static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    t0 = vader_buffer_intern_string((vader_buffer_t*) l0, (size_t) l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2) {
    vader_buffer_write_string((vader_buffer_t*) l0, (size_t) l1, l2);
    return;
}

/* vtable dispatchers */
static vader_box_t vader_vt_Async__resume(vader_box_t recv) {
    switch (recv.tag) {
        case 10u: return snippet___asyncstate_snippet_0_Async_resume(recv.payload.obj);
        case 13u: return snippet___asyncstate_snippet_1_Async_resume(recv.payload.obj);
        case 22u: return std_async_Sleep_Async_resume(recv.payload.obj);
        default: vader_unreachable("vtable miss in Async.resume");
    }
    vader_unreachable("vtable miss in Async.resume");
}

int main(int argc, char** argv) {
    vader_atom_init_with_comptime(vader_atom_comptime_table, VADER_COMPTIME_ATOM_COUNT);
    atexit(vader_atom_shutdown);
    atexit(vader_gc_shutdown);
    (void) argc;
    (void) argv;
    return (int) snippet_main();
}
