/* Generated by vader — do not edit. */
#include "vader.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

typedef struct vader_struct_std_core_Range__i32_t vader_struct_std_core_Range__i32_t;
typedef struct vader_struct___Tuple_i32_u8_99ae0d29_t vader_struct___Tuple_i32_u8_99ae0d29_t;
typedef struct vader_struct_std_core_Range__usize_t vader_struct_std_core_Range__usize_t;
typedef struct vader_struct___Tuple_usize_u8_de11f1ad_t vader_struct___Tuple_usize_u8_de11f1ad_t;
typedef struct vader_struct_std_core_Buffer_t vader_struct_std_core_Buffer_t;
typedef struct vader_struct_std_core___gen_state_std_core_0_t vader_struct_std_core___gen_state_std_core_0_t;
typedef struct vader_struct_std_iter___gen_state_std_iter_0_t vader_struct_std_iter___gen_state_std_iter_0_t;
typedef struct vader_struct___Tuple_string_u8_b910c566_t vader_struct___Tuple_string_u8_b910c566_t;
typedef struct vader_struct_std_iter___gen_state_std_iter_1_t vader_struct_std_iter___gen_state_std_iter_1_t;

struct vader_struct_std_core_Range__i32_t {
    vader_obj_header_t header;
    int32_t f_start;
    int32_t f_end;
    bool f_inclusive;
    int32_t f_cursor;
};
struct vader_struct___Tuple_i32_u8_99ae0d29_t {
    vader_obj_header_t header;
    int32_t f__0;
    uint8_t f__1;
};
struct vader_struct_std_core_Range__usize_t {
    vader_obj_header_t header;
    size_t f_start;
    size_t f_end;
    bool f_inclusive;
    size_t f_cursor;
};
struct vader_struct___Tuple_usize_u8_de11f1ad_t {
    vader_obj_header_t header;
    size_t f__0;
    uint8_t f__1;
};
struct vader_struct_std_core_Buffer_t {
    vader_obj_header_t header;
};
struct vader_struct_std_core___gen_state_std_core_0_t {
    vader_obj_header_t header;
    void* f_s0;
    size_t f_s1;
    size_t f_s2;
    int32_t f_state;
};
struct vader_struct_std_iter___gen_state_std_iter_0_t {
    vader_obj_header_t header;
    vader_box_t f_s0;
    void* f_s1;
    vader_box_t f_s2;
    void* f_s3;
    int32_t f_s4;
    int32_t f_state;
};
struct vader_struct___Tuple_string_u8_b910c566_t {
    vader_obj_header_t header;
    vader_string_t f__0;
    uint8_t f__1;
};
struct vader_struct_std_iter___gen_state_std_iter_1_t {
    vader_obj_header_t header;
    vader_box_t f_s0;
    void* f_s1;
    vader_box_t f_s2;
    void* f_s3;
    vader_string_t f_s4;
    int32_t f_state;
};

/* Compile-time atom table — see docs/ATOM_INTERNING.md. */
static const char vader_atom_blob[] = " " "\0" "lazy:" "\0" "fused:" "\0" "\n" "\0";

static const vader_atom_entry_t vader_atom_comptime_table[] = {
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[0] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[2] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[8] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[15] },
};

#define VADER_COMPTIME_ATOM_COUNT 4u

static vader_string_t snippet_to_text(int32_t l0);
static size_t snippet_text_len(vader_string_t l0);
static int32_t snippet_main(void);
static vader_string_t concat_2(vader_string_t l0, vader_string_t l1);
static void* std_core_Range_Iterator_next__i32(void* l0);
static void* std_core_Range_Iterator_next__usize(void* l0);
static void* std_core_new_byte_buffer(size_t l0);
static vader_string_t std_core_finish_buffer(void* l0, size_t l1);
static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2);
static size_t std_core_write_int(void* l0, size_t l1, int64_t l2);
static size_t std_core_write_unsigned(void* l0, size_t l1, uint64_t l2);
static int32_t std_core_three_way(bool l0, bool l1);
static vader_box_t std_core____Into_into__i32(void* l0);
static int32_t std_core_i32_Comparable_compare(int32_t l0, int32_t l1);
static bool std_core_i32_Comparable_gt(int32_t l0, int32_t l1);
static bool std_core_i32_Comparable_gte(int32_t l0, int32_t l1);
static int32_t std_core_usize_Comparable_compare(size_t l0, size_t l1);
static bool std_core_usize_Comparable_gt(size_t l0, size_t l1);
static bool std_core_usize_Comparable_gte(size_t l0, size_t l1);
static int32_t std_core_i32_Step_step(int32_t l0);
static size_t std_core_usize_Step_step(size_t l0);
static vader_box_t std_core_array_iter__i32(void* l0);
static void* std_core___gen_state_std_core_0_Iterator_next(void* l0);
static void std_io_write(uint8_t l0, vader_string_t l1);
static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2);
static void std_io_println__string(vader_string_t l0);
static vader_box_t std_iter_map__i32__string(vader_box_t l0, void* l1);
static void* std_iter___gen_state_std_iter_0_Iterator_next(void* l0);
static vader_box_t std_iter_map__string__usize(vader_box_t l0, void* l1);
static void* std_iter___gen_state_std_iter_1_Iterator_next(void* l0);
static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0);
static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2);
static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1);
static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2);

typedef vader_box_t (*vader_fn_erased_sig_0_t)(void* env);
typedef vader_box_t (*vader_fn_erased_sig_1_t)(void* env, vader_box_t a0);

static vader_box_t vader_fn_tramp_snippet_to_text(void* env, vader_box_t a0) {
    (void) env;
    return vader_box_string(2u, snippet_to_text(((int32_t) a0.payload.i)));
}

static vader_fn_t vader_fn_static_snippet_to_text = {
    { 18u, 0u, 0u, 0u, NULL }, (void*) &vader_fn_tramp_snippet_to_text, NULL,
};

static vader_box_t vader_fn_tramp_snippet_text_len(void* env, vader_box_t a0) {
    (void) env;
    return vader_box_i64(3u, (int64_t)(uint64_t) snippet_text_len(a0.payload.s));
}

static vader_fn_t vader_fn_static_snippet_text_len = {
    { 22u, 0u, 0u, 0u, NULL }, (void*) &vader_fn_tramp_snippet_text_len, NULL,
};

static const uint16_t vader_fn_ptr_offsets[] = { offsetof(vader_fn_t, env) };
static const uint16_t vader_array_ptr_offsets[] = { offsetof(vader_array_t, buf) };

const vader_type_info_t vader_type_info_table[30] = {
    [1] = { .slot_size = 4 },
    [2] = { .slot_size = 16 },
    [3] = { .slot_size = 8 },
    [4] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Range__i32_t),
        .slot_size = 8,
    },
    [5] = { .slot_size = 1 },
    [6] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t),
        .slot_size = 8,
    },
    [7] = { .slot_size = 1 },
    [8] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Range__usize_t),
        .slot_size = 8,
    },
    [9] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t),
        .slot_size = 8,
    },
    [10] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Buffer_t),
        .slot_size = 8,
    },
    [11] = { .slot_size = 8 },
    [12] = { .slot_size = 8 },
    [13] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [14] = { .slot_size = 16 },
    [15] = {
        .kind = VADER_TYPE_KIND_STRUCT,
        .size = sizeof(vader_struct_std_core___gen_state_std_core_0_t), .slot_size = 8,
        .ref_offsets = (const uint16_t[]){ offsetof(vader_struct_std_core___gen_state_std_core_0_t, f_s0) },
        .ref_count = 1,
    },
    [16] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [18] = {
        .kind = VADER_TYPE_KIND_FN, .size = sizeof(vader_fn_t), .slot_size = 8,
        .ptr_offsets = vader_fn_ptr_offsets, .ptr_count = 1,
    },
    [19] = { .slot_size = 16 },
    [20] = {
        .kind = VADER_TYPE_KIND_STRUCT,
        .size = sizeof(vader_struct_std_iter___gen_state_std_iter_0_t), .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct_std_iter___gen_state_std_iter_0_t, f_s0), offsetof(vader_struct_std_iter___gen_state_std_iter_0_t, f_s2) },
        .ptr_count = 2,
        .ref_offsets = (const uint16_t[]){ offsetof(vader_struct_std_iter___gen_state_std_iter_0_t, f_s1), offsetof(vader_struct_std_iter___gen_state_std_iter_0_t, f_s3) },
        .ref_count = 2,
    },
    [21] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___Tuple_string_u8_b910c566_t),
        .slot_size = 8,
        .string_offsets = (const uint16_t[]){ offsetof(vader_struct___Tuple_string_u8_b910c566_t, f__0) },
        .string_count = 1,
    },
    [22] = {
        .kind = VADER_TYPE_KIND_FN, .size = sizeof(vader_fn_t), .slot_size = 8,
        .ptr_offsets = vader_fn_ptr_offsets, .ptr_count = 1,
    },
    [23] = { .slot_size = 16 },
    [24] = {
        .kind = VADER_TYPE_KIND_STRUCT,
        .size = sizeof(vader_struct_std_iter___gen_state_std_iter_1_t), .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct_std_iter___gen_state_std_iter_1_t, f_s0), offsetof(vader_struct_std_iter___gen_state_std_iter_1_t, f_s2) },
        .ptr_count = 2,
        .string_offsets = (const uint16_t[]){ offsetof(vader_struct_std_iter___gen_state_std_iter_1_t, f_s4) },
        .string_count = 1,
        .ref_offsets = (const uint16_t[]){ offsetof(vader_struct_std_iter___gen_state_std_iter_1_t, f_s1), offsetof(vader_struct_std_iter___gen_state_std_iter_1_t, f_s3) },
        .ref_count = 2,
    },
    [25] = { .slot_size = 8 },
    [26] = { .slot_size = 16 },
    [27] = { .slot_size = 16 },
    [28] = { .slot_size = 16 },
    [29] = { .slot_size = 16 },
};
const size_t vader_type_info_count = 30;

/* Headers named by `@c_header` — they own the prototypes below. */
#include <unistd.h>

static size_t vader_host_std_core_byte_len(vader_string_t a0) {
    return vader_string_byte_len(a0);
}

static void* vader_host_std_core_bytes(vader_string_t a0) {
    return (void*) vader_string_bytes_view(a0, 16u, 7u);
}

static ptrdiff_t vader_host_system_posix_sys_write(int32_t a0, void* a1, size_t a2) {
    vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1);
    return write(a0, s1.ptr, a2);
}

/* vtable forwards */
static vader_box_t vader_vt_Iterator__next(vader_box_t recv);

static vader_string_t snippet_to_text(int32_t l0) {
    void* l1 = NULL;
    size_t l2;
    int64_t l3;
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l1 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 12 "tests/snippets/fusion_stages_change_type/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 20);
    l2 = (size_t) 0;
    l3 = ((int64_t) (int32_t) l0);
    l2 = std_core_write_int(l1, l2, l3);
    t0 = std_core_finish_buffer(l1, l2);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t snippet_text_len(vader_string_t l0) {
    size_t t0;
#line 14 "tests/snippets/fusion_stages_change_type/_main.vader"
    t0 = vader_host_std_core_byte_len(l0);
    return t0;
}

static int32_t snippet_main(void) {
    vader_string_t l0 = 0;
    vader_string_t l7 = 0;
    vader_box_t l1 = vader_box_null();
    void* l2 = NULL;
    void* l3 = NULL;
    size_t l4, l5, l8, l9;
    uint64_t l6;
    void* t0 = NULL;
    vader_box_t t1 = vader_box_null();
    int64_t t2;
    vader_string_t t3 = 0;
    int32_t t4;
    vader_box_t* gc_roots[2] = { &l1, &t1 };
    void** gc_raw_roots[3] = { &l2, &l3, &t0 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l7, &t3 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 2u, 3u, gc_roots, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 17 "tests/snippets/fusion_stages_change_type/_main.vader"
    l0 = 0u;
#line 18 "tests/snippets/fusion_stages_change_type/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(13u, 3u, 7u, 1u);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 2u] = (int32_t) INT32_C(333);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 1u] = (int32_t) INT32_C(22);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 0u] = (int32_t) INT32_C(1);
    t0 = (void*) _a0_arr;
    l1 = std_core____Into_into__i32(t0);
    l2 = (void*) &vader_fn_static_snippet_to_text;
    t1 = std_iter_map__i32__string(l1, l2);
    l2 = t1.payload.obj;
    l3 = (void*) &vader_fn_static_snippet_text_len;
    l1 = std_iter_map__string__usize(vader_ref_box(l2), l3);
#line 19 "tests/snippets/fusion_stages_change_type/_main.vader"
    for (;;) {
        t1 = vader_vt_Iterator__next(l1);
        l2 = t1.payload.obj;
        if (((vader_struct___Tuple_usize_u8_de11f1ad_t*) l2)->f__1 == INT32_C(1)) {
        } else {
            l4 = ((vader_struct___Tuple_usize_u8_de11f1ad_t*) l2)->f__0;
#line 20 "tests/snippets/fusion_stages_change_type/_main.vader"
            l3 = std_core_new_byte_buffer((size_t) 21);
            l5 = (size_t) 0;
            l5 = std_core_write_string_at(l3, l5, 1u);
            t2 = ((int64_t) (size_t) l4);
            l6 = (uint64_t) (int64_t) t2;
            l5 = std_core_write_unsigned(l3, l5, l6);
            l7 = std_core_finish_buffer(l3, l5);
            l0 = concat_2(l0, l7);
#line 19 "tests/snippets/fusion_stages_change_type/_main.vader"
            continue;
        }
        break;
    }
#line 22 "tests/snippets/fusion_stages_change_type/_main.vader"
    t3 = concat_2(2u, l0);
    std_io_println__string(t3);
#line 23 "tests/snippets/fusion_stages_change_type/_main.vader"
    l0 = 0u;
#line 24 "tests/snippets/fusion_stages_change_type/_main.vader"
    vader_array_t* _a1_arr = vader_array_new(13u, 3u, 7u, 1u);
    ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 2u] = (int32_t) INT32_C(333);
    ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 1u] = (int32_t) INT32_C(22);
    ((int32_t*) _a1_arr->buf->slots)[_a1_arr->offset + 0u] = (int32_t) INT32_C(1);
    l2 = (void*) _a1_arr;
    l4 = ((vader_array_t*) l2)->length;
    l5 = (size_t) 0;
    while ((l5 < l4)) {
        vader_array_t* _a2_slotarr = ((vader_array_t*) l2);
        VADER_ARRAY_RESOLVE_BUF(_a2_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a2_slotarr, l5)
        t4 = ((int32_t*) _a2_slotarr->buf->slots)[_a2_slotarr->offset + (size_t) l5];
#line 309 "lib/std/iter/iter.vader"
        t3 = snippet_to_text(t4);
        l8 = snippet_text_len(t3);
#line 25 "tests/snippets/fusion_stages_change_type/_main.vader"
        l3 = std_core_new_byte_buffer((size_t) 21);
        l9 = (size_t) 0;
        l9 = std_core_write_string_at(l3, l9, 1u);
        t2 = ((int64_t) (size_t) l8);
        l6 = (uint64_t) (int64_t) t2;
        l9 = std_core_write_unsigned(l3, l9, l6);
        l7 = std_core_finish_buffer(l3, l9);
        l0 = concat_2(l0, l7);
#line 24 "tests/snippets/fusion_stages_change_type/_main.vader"
        t2 = (l5 + INT64_C(1));
        l5 = (size_t) (int64_t) t2;
    }
#line 27 "tests/snippets/fusion_stages_change_type/_main.vader"
    t3 = concat_2(3u, l0);
    std_io_println__string(t3);
#line 28 "tests/snippets/fusion_stages_change_type/_main.vader"
    { vader_gc_top = gc_frame.prev; return INT32_C(0); }
}

static vader_string_t concat_2(vader_string_t l0, vader_string_t l1) {
    size_t l2, l3;
    void* l4 = NULL;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l4 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l1, &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    l2 = vader_host_std_core_byte_len(l0);
    l3 = vader_host_std_core_byte_len(l1);
    t0 = (l2 + l3);
    l3 = (size_t) (int64_t) t0;
    l4 = std_core_usize_BufferAlloc_new_buffer_vt(l3);
    std_core_Buffer_ByteAccess_write_string_vt(l4, (size_t) 0, l0);
    std_core_Buffer_ByteAccess_write_string_vt(l4, l2, l1);
    t1 = std_core_Buffer_ByteAccess_intern_string_vt(l4, l3);
    { vader_string_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_Range_Iterator_next__i32(void* l0) {
    bool l1;
    int32_t l2, l3;
    bool t0;
    int32_t t1;
    void* t2 = NULL;
    void** gc_raw_roots[2] = { &l0, &t2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 272 "lib/std/core/core.vader"
    t0 = ((vader_struct_std_core_Range__i32_t*) l0)->f_inclusive;
    if (t0) {
        l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__i32_t*) l0)->f_end;
        l1 = std_core_i32_Comparable_gt(l2, l3);
#line 273 "lib/std/core/core.vader"
    } else {
        l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__i32_t*) l0)->f_end;
        l1 = std_core_i32_Comparable_gte(l2, l3);
#line 272 "lib/std/core/core.vader"
    }
#line 276 "lib/std/core/core.vader"
    if (l1) {
        t1 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        vader_struct___Tuple_i32_u8_99ae0d29_t* _a0_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
        vader_obj_header_init(_a0_obj, 6u);
        _a0_obj->f__0 = t1;
        _a0_obj->f__1 = (uint8_t) 1;
        t2 = (void*) _a0_obj;
        { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
    }
#line 277 "lib/std/core/core.vader"
    l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
#line 278 "lib/std/core/core.vader"
    t1 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
    l3 = std_core_i32_Step_step(t1);
    ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor = l3;
#line 279 "lib/std/core/core.vader"
    vader_struct___Tuple_i32_u8_99ae0d29_t* _a1_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
    vader_obj_header_init(_a1_obj, 6u);
    _a1_obj->f__0 = l2;
    _a1_obj->f__1 = (uint8_t) 0;
    t2 = (void*) _a1_obj;
    { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_Range_Iterator_next__usize(void* l0) {
    bool l1;
    size_t l2, l3;
    bool t0;
    size_t t1;
    void* t2 = NULL;
    void** gc_raw_roots[2] = { &l0, &t2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 272 "lib/std/core/core.vader"
    t0 = ((vader_struct_std_core_Range__usize_t*) l0)->f_inclusive;
    if (t0) {
        l2 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__usize_t*) l0)->f_end;
        l1 = std_core_usize_Comparable_gt(l2, l3);
#line 273 "lib/std/core/core.vader"
    } else {
        l2 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__usize_t*) l0)->f_end;
        l1 = std_core_usize_Comparable_gte(l2, l3);
#line 272 "lib/std/core/core.vader"
    }
#line 276 "lib/std/core/core.vader"
    if (l1) {
        t1 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
        vader_struct___Tuple_usize_u8_de11f1ad_t* _a0_obj = (vader_struct___Tuple_usize_u8_de11f1ad_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t));
        vader_obj_header_init(_a0_obj, 9u);
        _a0_obj->f__0 = t1;
        _a0_obj->f__1 = (uint8_t) 1;
        t2 = (void*) _a0_obj;
        { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
    }
#line 277 "lib/std/core/core.vader"
    l2 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
#line 278 "lib/std/core/core.vader"
    t1 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
    l3 = std_core_usize_Step_step(t1);
    ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor = l3;
#line 279 "lib/std/core/core.vader"
    vader_struct___Tuple_usize_u8_de11f1ad_t* _a1_obj = (vader_struct___Tuple_usize_u8_de11f1ad_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t));
    vader_obj_header_init(_a1_obj, 9u);
    _a1_obj->f__0 = l2;
    _a1_obj->f__1 = (uint8_t) 0;
    t2 = (void*) _a1_obj;
    { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_new_byte_buffer(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 101 "lib/std/core/primitives.vader"
    t0 = std_core_usize_BufferAlloc_new_buffer_vt(l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t std_core_finish_buffer(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 104 "lib/std/core/primitives.vader"
    t0 = std_core_Buffer_ByteAccess_intern_string_vt(l0, l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2) {
    size_t l3;
#line 121 "lib/std/core/primitives.vader"
    std_core_Buffer_ByteAccess_write_string_vt(l0, l1, l2);
#line 122 "lib/std/core/primitives.vader"
    l3 = vader_host_std_core_byte_len(l2);
    return (size_t) (int64_t) (l1 + l3);
}

static size_t std_core_write_int(void* l0, size_t l1, int64_t l2) {
    bool l3;
    size_t l4, l6;
    int64_t l5;
    uint8_t l7, l8;
    int64_t t0;
    int32_t t1;
#line 127 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 128 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 129 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 127 "lib/std/core/primitives.vader"
    }
#line 131 "lib/std/core/primitives.vader"
    l3 = (l2 < INT64_C(0));
#line 132 "lib/std/core/primitives.vader"
    if ((l2 > INT64_C(0))) {
        l2 = -(l2);
    }
#line 133 "lib/std/core/primitives.vader"
    l4 = (size_t) 0;
#line 134 "lib/std/core/primitives.vader"
    l5 = l2;
#line 135 "lib/std/core/primitives.vader"
    while (l5 != INT64_C(0)) {
#line 136 "lib/std/core/primitives.vader"
        t0 = (l4 + INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 137 "lib/std/core/primitives.vader"
        l5 = vader_div_i64(l5, INT64_C(10));
#line 135 "lib/std/core/primitives.vader"
    }
#line 139 "lib/std/core/primitives.vader"
    if (l3) {
        t0 = (l4 + INT64_C(1));
        l6 = (size_t) (int64_t) t0;
    } else {
        l6 = l4;
    }
#line 140 "lib/std/core/primitives.vader"
    t0 = (l1 + l6);
    l4 = (size_t) (int64_t) t0;
#line 141 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 142 "lib/std/core/primitives.vader"
        t0 = (l4 - INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 143 "lib/std/core/primitives.vader"
        t0 = vader_mod_i64(l2, INT64_C(10));
        t1 = (((int32_t) (int64_t) -(t0)) & INT32_C(255));
        l7 = (uint8_t) (int32_t) t1;
        t1 = ((INT32_C(48) + l7) & INT32_C(255));
        l8 = (uint8_t) (int32_t) t1;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l4, l8);
#line 144 "lib/std/core/primitives.vader"
        l2 = vader_div_i64(l2, INT64_C(10));
#line 141 "lib/std/core/primitives.vader"
    }
#line 146 "lib/std/core/primitives.vader"
    if (l3) {
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 45);
    }
#line 147 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l6);
}

static size_t std_core_write_unsigned(void* l0, size_t l1, uint64_t l2) {
    size_t l3, l5;
    uint64_t l4;
    uint8_t l6, l7;
    int64_t t0;
    uint64_t t1;
    int32_t t2;
#line 152 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 153 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 154 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 152 "lib/std/core/primitives.vader"
    }
#line 156 "lib/std/core/primitives.vader"
    l3 = (size_t) 0;
#line 157 "lib/std/core/primitives.vader"
    l4 = l2;
#line 158 "lib/std/core/primitives.vader"
    while (l4 != INT64_C(0)) {
#line 159 "lib/std/core/primitives.vader"
        t0 = (l3 + INT64_C(1));
        l3 = (size_t) (int64_t) t0;
#line 160 "lib/std/core/primitives.vader"
        l4 = vader_div_u64(l4, INT64_C(10));
#line 158 "lib/std/core/primitives.vader"
    }
#line 162 "lib/std/core/primitives.vader"
    t0 = (l1 + l3);
    l5 = (size_t) (int64_t) t0;
#line 163 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 164 "lib/std/core/primitives.vader"
        t0 = (l5 - INT64_C(1));
        l5 = (size_t) (int64_t) t0;
#line 165 "lib/std/core/primitives.vader"
        t1 = vader_mod_u64(l2, INT64_C(10));
        t2 = (((int32_t) (uint64_t) t1) & INT32_C(255));
        l6 = (uint8_t) (int32_t) t2;
        t2 = ((INT32_C(48) + l6) & INT32_C(255));
        l7 = (uint8_t) (int32_t) t2;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l5, l7);
#line 166 "lib/std/core/primitives.vader"
        l2 = vader_div_u64(l2, INT64_C(10));
#line 163 "lib/std/core/primitives.vader"
    }
#line 168 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l3);
}

static int32_t std_core_three_way(bool l0, bool l1) {
    int32_t l2;
#line 312 "lib/std/core/primitives.vader"
    if (l0) {
        l2 = -(INT32_C(1));
    } else if (l1) {
        l2 = INT32_C(1);
    } else {
        l2 = INT32_C(0);
    }
    return l2;
}

static vader_box_t std_core____Into_into__i32(void* l0) {
    vader_box_t t0 = vader_box_null();
    vader_box_t* gc_roots[1] = { &t0 };
    void** gc_raw_roots[1] = { &l0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 1u, 1u, gc_roots, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 303 "lib/std/core/core.vader"
    t0 = std_core_array_iter__i32(l0);
    { vader_box_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static int32_t std_core_i32_Comparable_compare(int32_t l0, int32_t l1) {
    bool l2, l3;
    int32_t t0;
#line 316 "lib/std/core/primitives.vader"
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
}

static bool std_core_i32_Comparable_gt(int32_t l0, int32_t l1) {
    int32_t t0;
#line 323602 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
}

static bool std_core_i32_Comparable_gte(int32_t l0, int32_t l1) {
    int32_t t0;
#line 323602 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
}

static int32_t std_core_usize_Comparable_compare(size_t l0, size_t l1) {
    bool l2, l3;
    int32_t t0;
#line 323 "lib/std/core/primitives.vader"
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
}

static bool std_core_usize_Comparable_gt(size_t l0, size_t l1) {
    int32_t t0;
#line 330770 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
}

static bool std_core_usize_Comparable_gte(size_t l0, size_t l1) {
    int32_t t0;
#line 330770 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
}

static int32_t std_core_i32_Step_step(int32_t l0) {
#line 334 "lib/std/core/primitives.vader"
    return (l0 + INT32_C(1));
    return (l0 + INT32_C(1));
}

static size_t std_core_usize_Step_step(size_t l0) {
#line 341 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l0 + INT64_C(1));
    return (size_t) (int64_t) (l0 + INT64_C(1));
}

static vader_box_t std_core_array_iter__i32(void* l0) {
    void* t0 = NULL;
    void** gc_raw_roots[2] = { &l0, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 292 "lib/std/core/core.vader"
    vader_struct_std_core___gen_state_std_core_0_t* _a0_obj = (vader_struct_std_core___gen_state_std_core_0_t*) vader_gc_alloc(sizeof(vader_struct_std_core___gen_state_std_core_0_t));
    vader_obj_header_init(_a0_obj, 15u);
    _a0_obj->f_s0 = l0;
    _a0_obj->f_s1 = (size_t) 0;
    _a0_obj->f_s2 = (size_t) 0;
    _a0_obj->f_state = INT32_C(5);
    t0 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core___gen_state_std_core_0_Iterator_next(void* l0) {
    size_t l1, l2, l3, l6, l9;
    int32_t l4, l7;
    void* l5 = NULL;
    uint8_t l8;
    int32_t t0;
    size_t t1;
    int64_t t2;
    void* t3 = NULL;
    void** gc_raw_roots[3] = { &l0, &l5, &t3 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 292 "lib/std/core/core.vader"
    for (;;) {
        t0 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state;
        if (t0 == INT32_C(0)) {
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = INT32_C(-1);
            continue;
        }
        t0 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state;
        if (t0 == INT32_C(1)) {
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = INT32_C(0);
            continue;
        }
        t0 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state;
        if (t0 == INT32_C(2)) {
            l1 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s1;
            l2 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s2;
#line 293 "lib/std/core/core.vader"
#line 292 "lib/std/core/core.vader"
            if ((l1 < l2)) {
                ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = INT32_C(4);
            } else {
                ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = INT32_C(1);
            }
            continue;
        }
        t0 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state;
        if (t0 == INT32_C(3)) {
            t1 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s1;
#line 293 "lib/std/core/core.vader"
            t2 = (t1 + INT64_C(1));
            l3 = (size_t) (int64_t) t2;
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s1 = l3;
#line 292 "lib/std/core/core.vader"
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = INT32_C(2);
            continue;
        }
        t0 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state;
        if (t0 == INT32_C(4)) {
            l4 = INT32_C(3);
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = l4;
            l5 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s0;
            l6 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s1;
#line 294 "lib/std/core/core.vader"
            vader_array_t* _a0_slotarr = ((vader_array_t*) l5);
            VADER_ARRAY_RESOLVE_BUF(_a0_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a0_slotarr, l6)
            l7 = ((int32_t*) _a0_slotarr->buf->slots)[_a0_slotarr->offset + (size_t) l6];
#line 292 "lib/std/core/core.vader"
            l8 = (uint8_t) 0;
            vader_struct___Tuple_i32_u8_99ae0d29_t* _a1_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
            vader_obj_header_init(_a1_obj, 6u);
            _a1_obj->f__0 = l7;
            _a1_obj->f__1 = l8;
            t3 = (void*) _a1_obj;
            { void* __vret = t3; vader_gc_top = gc_frame.prev; return __vret; }
        }
        t0 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state;
        if (t0 == INT32_C(5)) {
#line 293 "lib/std/core/core.vader"
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s1 = (size_t) 0;
#line 292 "lib/std/core/core.vader"
#line 293 "lib/std/core/core.vader"
            l9 = ((vader_array_t*) ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s0)->length;
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s2 = l9;
#line 292 "lib/std/core/core.vader"
            ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = INT32_C(2);
        } else {
            vader_struct___Tuple_i32_u8_99ae0d29_t* _a2_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
            vader_obj_header_init(_a2_obj, 6u);
            _a2_obj->f__0 = INT32_C(0);
            _a2_obj->f__1 = (uint8_t) 1;
            t3 = (void*) _a2_obj;
            { void* __vret = t3; vader_gc_top = gc_frame.prev; return __vret; }
        }
        continue;
    }
    l4 = INT32_C(3);
    ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_state = l4;
    l5 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s0;
    l6 = ((vader_struct_std_core___gen_state_std_core_0_t*) l0)->f_s1;
#line 294 "lib/std/core/core.vader"
    vader_array_t* _a3_slotarr = ((vader_array_t*) l5);
    VADER_ARRAY_RESOLVE_BUF(_a3_slotarr)
    VADER_ARRAY_CHECK_INDEX(_a3_slotarr, l6)
    l7 = ((int32_t*) _a3_slotarr->buf->slots)[_a3_slotarr->offset + (size_t) l6];
#line 292 "lib/std/core/core.vader"
    l8 = (uint8_t) 0;
    vader_struct___Tuple_i32_u8_99ae0d29_t* _a4_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
    vader_obj_header_init(_a4_obj, 6u);
    _a4_obj->f__0 = l7;
    _a4_obj->f__1 = l8;
    t3 = (void*) _a4_obj;
    { void* __vret = t3; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_write(uint8_t l0, vader_string_t l1) {
    void* l2 = NULL;
    void* l6 = NULL;
    size_t l3, l4, l5, l7, l9;
    int32_t l8;
    int64_t t0;
    void** gc_raw_roots[2] = { &l2, &l6 };
    vader_string_t* gc_atom_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 205 "lib/std/io/io.vader"
    l2 = vader_host_std_core_bytes(l1);
#line 206 "lib/std/io/io.vader"
    l3 = (size_t) 0;
#line 207 "lib/std/io/io.vader"
    for (;;) {
#line 208 "lib/std/io/io.vader"
        l4 = ((vader_array_t*) l2)->length;
        if ((l3 >= l4)) {
#line 209 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 208 "lib/std/io/io.vader"
        }
#line 211 "lib/std/io/io.vader"
        l5 = ((vader_array_t*) l2)->length;
        vader_array_t* _a0_arr = vader_array_slice((vader_array_t*) l2, (size_t) l3, (size_t) l5);
        l6 = (void*) _a0_arr;
#line 212 "lib/std/io/io.vader"
        l7 = ((vader_array_t*) l6)->length;
        l8 = std_io_write_bytes(l0, l6, l7);
#line 213 "lib/std/io/io.vader"
        if ((l8 <= INT32_C(0))) {
#line 214 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 213 "lib/std/io/io.vader"
        }
#line 216 "lib/std/io/io.vader"
        t0 = ((int64_t) (int32_t) l8);
        l9 = (size_t) (int64_t) t0;
        t0 = (l3 + l9);
        l3 = (size_t) (int64_t) t0;
#line 207 "lib/std/io/io.vader"
        continue;
    }
#line 209 "lib/std/io/io.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2) {
    int32_t l3;
    ptrdiff_t t0;
    void** gc_raw_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 177 "lib/std/io/io.vader"
    if (l0 == INT32_C(0)) {
        l3 = INT32_C(1);
    } else {
        l3 = INT32_C(2);
    }
#line 180 "lib/std/io/io.vader"
    t0 = vader_host_system_posix_sys_write(l3, l1, l2);
    { int32_t __vret = ((int32_t) (ptrdiff_t) t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_println__string(vader_string_t l0) {
    vader_string_t l1 = 0;
    vader_string_t* gc_atom_roots[2] = { &l0, &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL, 2u, gc_atom_roots };
    vader_gc_top = &gc_frame;
#line 235 "lib/std/io/io.vader"
    l1 = concat_2(l0, 4u);
    std_io_write((uint8_t) 0, l1);
    { vader_gc_top = gc_frame.prev; return; }
}

static vader_box_t std_iter_map__i32__string(vader_box_t l0, void* l1) {
    vader_box_t l2 = vader_box_null();
    void* l3 = NULL;
    void* t0 = NULL;
    vader_box_t* gc_roots[2] = { &l0, &l2 };
    void** gc_raw_roots[3] = { &l1, &l3, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 2u, 3u, gc_roots, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 308 "lib/std/iter/iter.vader"
    l2 = vader_box_obj(0u, NULL);
    l3 = vader_box_obj(0u, NULL).payload.obj;
    vader_struct_std_iter___gen_state_std_iter_0_t* _a0_obj = (vader_struct_std_iter___gen_state_std_iter_0_t*) vader_gc_alloc(sizeof(vader_struct_std_iter___gen_state_std_iter_0_t));
    vader_obj_header_init(_a0_obj, 20u);
    _a0_obj->f_s0 = l0;
    _a0_obj->f_s1 = l1;
    _a0_obj->f_s2 = l2;
    _a0_obj->f_s3 = l3;
    _a0_obj->f_s4 = INT32_C(0);
    _a0_obj->f_state = INT32_C(11);
    t0 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_iter___gen_state_std_iter_0_Iterator_next(void* l0) {
    int32_t l1, l5;
    void* l2 = NULL;
    void* l6 = NULL;
    vader_string_t l3 = 0;
    uint8_t l4;
    vader_box_t l7 = vader_box_null();
    int32_t t0;
    vader_box_t t1 = vader_box_null();
    void* t2 = NULL;
    vader_box_t* gc_roots[2] = { &l7, &t1 };
    void** gc_raw_roots[4] = { &l0, &l2, &l6, &t2 };
    vader_string_t* gc_atom_roots[1] = { &l3 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 2u, 4u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 308 "lib/std/iter/iter.vader"
    for (;;) {
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(0)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(-1);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(1)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(0);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(2)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(10);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(3)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(2);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(4)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(3);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(5)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(1);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(6)) {
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(3);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(7)) {
            l1 = INT32_C(6);
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = l1;
            l2 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s1;
            t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s4;
#line 309 "lib/std/iter/iter.vader"
            vader_fn_t* _a0_fnobj = (vader_fn_t*) l2;
            t1 = ((vader_fn_erased_sig_1_t) _a0_fnobj->code)(_a0_fnobj->env, vader_box_i32(1u, t0));
            l3 = t1.payload.s;
#line 308 "lib/std/iter/iter.vader"
            l4 = (uint8_t) 0;
            vader_struct___Tuple_string_u8_b910c566_t* _a1_obj = (vader_struct___Tuple_string_u8_b910c566_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_string_u8_b910c566_t));
            vader_obj_header_init(_a1_obj, 21u);
            _a1_obj->f__0 = l3;
            _a1_obj->f__1 = l4;
            t2 = (void*) _a1_obj;
            { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
        if (t0 == INT32_C(8)) {
#line 309 "lib/std/iter/iter.vader"
            l5 = ((vader_struct___Tuple_i32_u8_99ae0d29_t*) ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s3)->f__0;
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s4 = l5;
#line 308 "lib/std/iter/iter.vader"
            ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(7);
        } else {
            t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
            if (t0 == INT32_C(9)) {
#line 309 "lib/std/iter/iter.vader"
#line 308 "lib/std/iter/iter.vader"
                if (((vader_struct___Tuple_i32_u8_99ae0d29_t*) ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s3)->f__1 == INT32_C(1)) {
                    ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(5);
                } else {
                    ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(8);
                }
            } else {
                t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
                if (t0 == INT32_C(10)) {
#line 309 "lib/std/iter/iter.vader"
                    t1 = vader_vt_Iterator__next(((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s2);
                    l6 = t1.payload.obj;
                    ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s3 = l6;
                    VADER_WRITE_BARRIER((vader_struct_std_iter___gen_state_std_iter_0_t*) l0);
#line 308 "lib/std/iter/iter.vader"
                    ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(9);
                } else {
                    t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state;
                    if (t0 == INT32_C(11)) {
                        l7 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s0;
#line 309 "lib/std/iter/iter.vader"
                        ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s2 = l7;
                        VADER_WRITE_BARRIER((vader_struct_std_iter___gen_state_std_iter_0_t*) l0);
#line 308 "lib/std/iter/iter.vader"
                        ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = INT32_C(2);
                    } else {
                        vader_struct___Tuple_string_u8_b910c566_t* _a2_obj = (vader_struct___Tuple_string_u8_b910c566_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_string_u8_b910c566_t));
                        vader_obj_header_init(_a2_obj, 21u);
                        _a2_obj->f__0 = 0u;
                        _a2_obj->f__1 = (uint8_t) 1;
                        t2 = (void*) _a2_obj;
                        { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
                    }
                }
            }
        }
        continue;
    }
    l1 = INT32_C(6);
    ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_state = l1;
    l2 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s1;
    t0 = ((vader_struct_std_iter___gen_state_std_iter_0_t*) l0)->f_s4;
#line 309 "lib/std/iter/iter.vader"
    vader_fn_t* _a3_fnobj = (vader_fn_t*) l2;
    t1 = ((vader_fn_erased_sig_1_t) _a3_fnobj->code)(_a3_fnobj->env, vader_box_i32(1u, t0));
    l3 = t1.payload.s;
#line 308 "lib/std/iter/iter.vader"
    l4 = (uint8_t) 0;
    vader_struct___Tuple_string_u8_b910c566_t* _a4_obj = (vader_struct___Tuple_string_u8_b910c566_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_string_u8_b910c566_t));
    vader_obj_header_init(_a4_obj, 21u);
    _a4_obj->f__0 = l3;
    _a4_obj->f__1 = l4;
    t2 = (void*) _a4_obj;
    { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_box_t std_iter_map__string__usize(vader_box_t l0, void* l1) {
    vader_box_t l2 = vader_box_null();
    void* l3 = NULL;
    void* t0 = NULL;
    vader_box_t* gc_roots[2] = { &l0, &l2 };
    void** gc_raw_roots[3] = { &l1, &l3, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 2u, 3u, gc_roots, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 308 "lib/std/iter/iter.vader"
    l2 = vader_box_obj(0u, NULL);
    l3 = vader_box_obj(0u, NULL).payload.obj;
    vader_struct_std_iter___gen_state_std_iter_1_t* _a0_obj = (vader_struct_std_iter___gen_state_std_iter_1_t*) vader_gc_alloc(sizeof(vader_struct_std_iter___gen_state_std_iter_1_t));
    vader_obj_header_init(_a0_obj, 24u);
    _a0_obj->f_s0 = l0;
    _a0_obj->f_s1 = l1;
    _a0_obj->f_s2 = l2;
    _a0_obj->f_s3 = l3;
    _a0_obj->f_s4 = 0u;
    _a0_obj->f_state = INT32_C(11);
    t0 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_iter___gen_state_std_iter_1_Iterator_next(void* l0) {
    int32_t l1;
    void* l2 = NULL;
    void* l6 = NULL;
    size_t l3;
    uint8_t l4;
    vader_string_t l5 = 0;
    vader_box_t l7 = vader_box_null();
    int32_t t0;
    vader_string_t t1 = 0;
    vader_box_t t2 = vader_box_null();
    void* t3 = NULL;
    vader_box_t* gc_roots[2] = { &l7, &t2 };
    void** gc_raw_roots[4] = { &l0, &l2, &l6, &t3 };
    vader_string_t* gc_atom_roots[2] = { &l5, &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 2u, 4u, gc_roots, gc_raw_roots, 0u, NULL, 2u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 308 "lib/std/iter/iter.vader"
    for (;;) {
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(0)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(-1);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(1)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(0);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(2)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(10);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(3)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(2);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(4)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(3);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(5)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(1);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(6)) {
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(3);
            continue;
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(7)) {
            l1 = INT32_C(6);
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = l1;
            l2 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s1;
            t1 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s4;
#line 309 "lib/std/iter/iter.vader"
            vader_fn_t* _a0_fnobj = (vader_fn_t*) l2;
            t2 = ((vader_fn_erased_sig_1_t) _a0_fnobj->code)(_a0_fnobj->env, vader_box_string(2u, t1));
            l3 = ((size_t) t2.payload.i);
#line 308 "lib/std/iter/iter.vader"
            l4 = (uint8_t) 0;
            vader_struct___Tuple_usize_u8_de11f1ad_t* _a1_obj = (vader_struct___Tuple_usize_u8_de11f1ad_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t));
            vader_obj_header_init(_a1_obj, 9u);
            _a1_obj->f__0 = l3;
            _a1_obj->f__1 = l4;
            t3 = (void*) _a1_obj;
            { void* __vret = t3; vader_gc_top = gc_frame.prev; return __vret; }
        }
        t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
        if (t0 == INT32_C(8)) {
#line 309 "lib/std/iter/iter.vader"
            l5 = ((vader_struct___Tuple_string_u8_b910c566_t*) ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s3)->f__0;
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s4 = l5;
            VADER_WRITE_BARRIER((vader_struct_std_iter___gen_state_std_iter_1_t*) l0);
#line 308 "lib/std/iter/iter.vader"
            ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(7);
        } else {
            t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
            if (t0 == INT32_C(9)) {
#line 309 "lib/std/iter/iter.vader"
#line 308 "lib/std/iter/iter.vader"
                if (((vader_struct___Tuple_string_u8_b910c566_t*) ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s3)->f__1 == INT32_C(1)) {
                    ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(5);
                } else {
                    ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(8);
                }
            } else {
                t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
                if (t0 == INT32_C(10)) {
#line 309 "lib/std/iter/iter.vader"
                    t2 = vader_vt_Iterator__next(((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s2);
                    l6 = t2.payload.obj;
                    ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s3 = l6;
                    VADER_WRITE_BARRIER((vader_struct_std_iter___gen_state_std_iter_1_t*) l0);
#line 308 "lib/std/iter/iter.vader"
                    ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(9);
                } else {
                    t0 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state;
                    if (t0 == INT32_C(11)) {
                        l7 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s0;
#line 309 "lib/std/iter/iter.vader"
                        ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s2 = l7;
                        VADER_WRITE_BARRIER((vader_struct_std_iter___gen_state_std_iter_1_t*) l0);
#line 308 "lib/std/iter/iter.vader"
                        ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = INT32_C(2);
                    } else {
                        vader_struct___Tuple_usize_u8_de11f1ad_t* _a2_obj = (vader_struct___Tuple_usize_u8_de11f1ad_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t));
                        vader_obj_header_init(_a2_obj, 9u);
                        _a2_obj->f__0 = (size_t) 0;
                        _a2_obj->f__1 = (uint8_t) 1;
                        t3 = (void*) _a2_obj;
                        { void* __vret = t3; vader_gc_top = gc_frame.prev; return __vret; }
                    }
                }
            }
        }
        continue;
    }
    l1 = INT32_C(6);
    ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_state = l1;
    l2 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s1;
    t1 = ((vader_struct_std_iter___gen_state_std_iter_1_t*) l0)->f_s4;
#line 309 "lib/std/iter/iter.vader"
    vader_fn_t* _a3_fnobj = (vader_fn_t*) l2;
    t2 = ((vader_fn_erased_sig_1_t) _a3_fnobj->code)(_a3_fnobj->env, vader_box_string(2u, t1));
    l3 = ((size_t) t2.payload.i);
#line 308 "lib/std/iter/iter.vader"
    l4 = (uint8_t) 0;
    vader_struct___Tuple_usize_u8_de11f1ad_t* _a4_obj = (vader_struct___Tuple_usize_u8_de11f1ad_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t));
    vader_obj_header_init(_a4_obj, 9u);
    _a4_obj->f__0 = l3;
    _a4_obj->f__1 = l4;
    t3 = (void*) _a4_obj;
    { void* __vret = t3; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
    t0 = (void*) vader_buffer_new((size_t) l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2) {
    vader_buffer_store_u8((vader_buffer_t*) l0, (size_t) l1, (uint8_t) l2);
    return;
}

static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    t0 = vader_buffer_intern_string((vader_buffer_t*) l0, (size_t) l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2) {
    vader_buffer_write_string((vader_buffer_t*) l0, (size_t) l1, l2);
    return;
}

/* vtable dispatchers */
static vader_box_t vader_vt_Iterator__next(vader_box_t recv) {
    switch (recv.tag) {
        case 4u: return vader_ref_box(std_core_Range_Iterator_next__i32(recv.payload.obj));
        case 8u: return vader_ref_box(std_core_Range_Iterator_next__usize(recv.payload.obj));
        case 15u: return vader_ref_box(std_core___gen_state_std_core_0_Iterator_next(recv.payload.obj));
        case 20u: return vader_ref_box(std_iter___gen_state_std_iter_0_Iterator_next(recv.payload.obj));
        case 24u: return vader_ref_box(std_iter___gen_state_std_iter_1_Iterator_next(recv.payload.obj));
        default: vader_unreachable("vtable miss in Iterator.next");
    }
    vader_unreachable("vtable miss in Iterator.next");
}

int main(int argc, char** argv) {
    vader_atom_init_with_comptime(vader_atom_comptime_table, VADER_COMPTIME_ATOM_COUNT);
    atexit(vader_atom_shutdown);
    atexit(vader_gc_shutdown);
    (void) argc;
    (void) argv;
    return (int) snippet_main();
}
