/* Generated by vader — do not edit. Foreign imports. */
#include "vader.h"

// Headers named by `@c_header` — they own the prototypes below.
#include <stdlib.h>
#include <windows.h>

// User @extern foreign symbols — resolved by the linker.
extern const char* vader_find_data_name(const void*);

static inline size_t vader_host_std_core_byte_len(vader_string_t a0) { return vader_string_byte_len(a0); }
static inline uint8_t vader_host_std_core_byte_at(vader_string_t a0, size_t a1) { return vader_string_byte_at(a0, a1); }
static inline vader_string_t vader_host_std_core_bytes_to_string(void* a0) { return vader_string_as_string((vader_array_t*) a0); }
static inline void* vader_host_std_core_bytes(vader_string_t a0) { return (void*) vader_string_bytes_view(a0, 11u, 172u); }
static inline uint64_t vader_host_std_core_string_Hash_hash(vader_string_t a0) { return vader_string_hash(a0); }
static inline vader_box_t vader_host_std_env_get_env(vader_string_t a0) { const char* c0 = vader_string_to_cstr(a0); const char* r = getenv(c0); vader_box_t out = r == NULL ? vader_box_null() : vader_box_i64(166u, (int64_t) vader_atom_intern(r, strlen(r))); vader_cstr_free_for(a0, c0); return out; }
static inline uint8_t vader_host_std_target_current_os(void) { return vader_current_os(); }
static inline uint8_t vader_host_std_target_current_arch(void) { return vader_current_arch(); }
static inline void* vader_host_system_windows_get_std_handle(uint32_t a0) { return GetStdHandle(a0); }
static inline uint32_t vader_host_system_windows_get_module_file_name(vader_box_t a0, void* a1, uint32_t a2) { void* p0 = (a0.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a0.payload.i; vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); return GetModuleFileNameW(p0, (void*) s1.ptr, a2); }
static inline uint32_t vader_host_system_windows_get_current_directory(uint32_t a0, void* a1) { vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); return GetCurrentDirectoryW(a0, (void*) s1.ptr); }
static inline uint32_t vader_host_system_windows_get_file_attributes(void* a0) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); return GetFileAttributesW(s0.ptr); }
static inline bool vader_host_system_windows_write_file(void* a0, void* a1, uint32_t a2, void* a3, vader_box_t a4) { vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); vader_slice_t s3 = vader_array_bytes((vader_array_t*) a3); void* p4 = (a4.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a4.payload.i; return WriteFile(a0, s1.ptr, a2, (void*) s3.ptr, p4); }
static inline int32_t vader_host_system_windows_multi_byte_to_wide_char(uint32_t a0, uint32_t a1, vader_string_t a2, int32_t a3, void* a4, int32_t a5) { const char* c2 = vader_string_to_cstr(a2); vader_slice_t s4 = vader_array_bytes((vader_array_t*) a4); int32_t r = MultiByteToWideChar(a0, a1, c2, a3, (void*) s4.ptr, a5); vader_cstr_free_for(a2, c2); return r; }
static inline int32_t vader_host_system_windows_wide_char_to_multi_byte(uint32_t a0, uint32_t a1, void* a2, int32_t a3, void* a4, int32_t a5, vader_box_t a6, vader_box_t a7) { vader_slice_t s2 = vader_array_bytes((vader_array_t*) a2); vader_slice_t s4 = vader_array_bytes((vader_array_t*) a4); void* p6 = (a6.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a6.payload.i; void* p7 = (a7.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a7.payload.i; return WideCharToMultiByte(a0, a1, s2.ptr, a3, (void*) s4.ptr, a5, p6, p7); }
static inline void* vader_host_system_windows_create_file_w(void* a0, uint32_t a1, uint32_t a2, vader_box_t a3, uint32_t a4, uint32_t a5, vader_box_t a6) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); void* p3 = (a3.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a3.payload.i; void* p6 = (a6.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a6.payload.i; return CreateFileW(s0.ptr, a1, a2, p3, a4, a5, p6); }
static inline void* vader_host_system_windows_find_first_file(void* a0, void* a1) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); return FindFirstFileW(s0.ptr, (void*) s1.ptr); }
static inline bool vader_host_system_windows_find_next_file(void* a0, void* a1) { vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); return FindNextFileW(a0, (void*) s1.ptr); }
static inline bool vader_host_system_windows_find_close(void* a0) { return FindClose(a0); }
static inline vader_string_t vader_host_system_windows_find_data_name(void* a0) { vader_slice_t s0 = vader_array_bytes((vader_array_t*) a0); const char* r = vader_find_data_name(s0.ptr); vader_string_t out = r == NULL ? vader_atom_intern("", 0) : vader_atom_intern(r, strlen(r)); return out; }
static inline bool vader_host_system_windows_get_console_mode(void* a0, void* a1) { vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); return GetConsoleMode(a0, (void*) s1.ptr); }
static inline bool vader_host_system_windows_set_console_mode(void* a0, uint32_t a1) { return SetConsoleMode(a0, a1); }
static inline bool vader_host_system_windows_read_file(void* a0, void* a1, uint32_t a2, void* a3, vader_box_t a4) { vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1); vader_slice_t s3 = vader_array_bytes((vader_array_t*) a3); void* p4 = (a4.tag == VADER_BOX_TAG_NULL) ? NULL : (void*) (intptr_t) a4.payload.i; return ReadFile(a0, (void*) s1.ptr, a2, (void*) s3.ptr, p4); }
static inline bool vader_host_system_windows_close_handle(void* a0) { return CloseHandle(a0); }
static inline size_t vader_host_vader_vm_ffi_open(vader_string_t a0) { const char* c0 = vader_string_to_cstr(a0); void* r = vader_ffi_open(c0); vader_cstr_free_for(a0, c0); return (size_t) (uintptr_t) r; }
static inline size_t vader_host_vader_vm_ffi_symbol(size_t a0, vader_string_t a1) { const char* c1 = vader_string_to_cstr(a1); void* r = vader_ffi_symbol((void*) (uintptr_t) a0, c1); vader_cstr_free_for(a1, c1); return (size_t) (uintptr_t) r; }
static inline vader_string_t vader_host_vader_vm_ffi_call(size_t a0, void* a1, void* a2) { return vader_ffi_call((void*) (uintptr_t) a0, (vader_array_t*) a1, (vader_array_t*) a2); }
static inline void vader_host_std_abort_panic(vader_string_t a0) { vader_panic(a0); }
static inline int64_t vader_host_std_process_spawn_start(void* a0) { return vader_spawn_start((vader_array_t*) a0); }
static inline int32_t vader_host_std_process_spawn_poll(int64_t a0) { return vader_spawn_poll(a0); }
static inline void vader_host_std_process_spawn_kill(int64_t a0) { vader_spawn_kill(a0); }
static inline vader_string_t vader_host_std_process_spawn_take_stdout(int64_t a0) { return vader_spawn_take_stdout(a0); }
static inline vader_string_t vader_host_std_process_spawn_take_stderr(int64_t a0) { return vader_spawn_take_stderr(a0); }

