/* Generated by vader — do not edit. */
#include "vader.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

typedef struct vader_struct___lambda_env_snippet_1_t vader_struct___lambda_env_snippet_1_t;
typedef struct vader_struct___lambda_env_snippet_3_t vader_struct___lambda_env_snippet_3_t;
typedef struct vader_struct_std_core_Range__i32_t vader_struct_std_core_Range__i32_t;
typedef struct vader_struct_std_core_Buffer_t vader_struct_std_core_Buffer_t;
typedef struct vader_struct__Cell_i32_t vader_struct__Cell_i32_t;

struct vader_struct___lambda_env_snippet_1_t {
    vader_obj_header_t header;
    vader_box_t f_cap_0;
};
struct vader_struct___lambda_env_snippet_3_t {
    vader_obj_header_t header;
    vader_box_t f_cap_0;
};
struct vader_struct_std_core_Range__i32_t {
    vader_obj_header_t header;
    int32_t f_start;
    int32_t f_end;
    bool f_inclusive;
    int32_t f_cursor;
};
struct vader_struct_std_core_Buffer_t {
    vader_obj_header_t header;
};
struct vader_struct__Cell_i32_t {
    vader_obj_header_t header;
    int32_t f_value;
};

/* Compile-time atom table — see docs/ATOM_INTERNING.md. */
static const char vader_atom_blob[] =
    "source " "\0"
    "bound " "\0"
    "limit " "\0"
    "adder " "\0"
    "above " "\0"
    "any_match = " "\0"
    "xs" "\0"
    "all_match = " "\0"
    "find = " "\0"
    "on empty = " "\0"
    "empty" "\0"
    "count = " "\0"
    "take = " "\0"
    "collect = " "\0"
    "for y = " "\0"
    "range = " "\0"
    "lo" "\0"
    "hi" "\0"
    "a" "\0"
    "b" "\0"
    "chain z = " "\0"
    "range value i = " "\0"
    "plain i = " "\0"
    "rebound i = " "\0"
    "in = " "\0"
    "true" "\0"
    "false" "\0"
    "\n" "\0";

static const vader_atom_entry_t vader_atom_comptime_table[] = {
    { 0u, 0u, 7u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[0] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[8] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[15] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[22] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[29] },
    { 0u, 0u, 12u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[36] },
    { 0u, 0u, 2u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[49] },
    { 0u, 0u, 12u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[52] },
    { 0u, 0u, 7u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[65] },
    { 0u, 0u, 11u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[73] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[85] },
    { 0u, 0u, 8u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[91] },
    { 0u, 0u, 7u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[100] },
    { 0u, 0u, 10u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[108] },
    { 0u, 0u, 8u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[119] },
    { 0u, 0u, 8u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[128] },
    { 0u, 0u, 2u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[137] },
    { 0u, 0u, 2u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[140] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[143] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[145] },
    { 0u, 0u, 10u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[147] },
    { 0u, 0u, 16u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[158] },
    { 0u, 0u, 10u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[175] },
    { 0u, 0u, 12u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[186] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[199] },
    { 0u, 0u, 4u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[205] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[210] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[216] },
};

#define VADER_COMPTIME_ATOM_COUNT 28u

static void* snippet_source(vader_string_t l0, void* l1);
static int32_t snippet_bound(vader_string_t l0, int32_t l1);
static size_t snippet_limit(size_t l0);
static void* snippet_adder(int32_t l0);
static void* snippet_above(int32_t l0);
static int32_t snippet_main(void);
static int32_t __lambda_snippet_0(void* l0, int32_t l1);
static bool __lambda_snippet_2(void* l0, int32_t l1);
static vader_string_t concat_2(vader_string_t l0, vader_string_t l1);
static void std_core_Range_Iterator_next__i32_v(void* l0, int32_t* __o0, uint8_t* __o1);
static void* std_core_new_byte_buffer(size_t l0);
static vader_string_t std_core_finish_buffer(void* l0, size_t l1);
static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2);
static size_t std_core_write_int(void* l0, size_t l1, int64_t l2);
static size_t std_core_write_unsigned(void* l0, size_t l1, uint64_t l2);
static size_t std_core_write_bool(void* l0, size_t l1, bool l2);
static int32_t std_core_three_way(bool l0, bool l1);
static int32_t std_core_i32_Comparable_compare(int32_t l0, int32_t l1);
static bool std_core_i32_Comparable_gt(int32_t l0, int32_t l1);
static bool std_core_i32_Comparable_gte(int32_t l0, int32_t l1);
static int32_t std_core_i32_Step_step(int32_t l0);
static void std_io_write(uint8_t l0, vader_string_t l1);
static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2);
static void std_io_println__string(vader_string_t l0);
static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0);
static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2);
static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1);
static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2);

typedef vader_box_t (*vader_fn_erased_sig_0_t)(void* env);
typedef vader_box_t (*vader_fn_erased_sig_1_t)(void* env, vader_box_t a0);

static vader_box_t vader_fn_lift___lambda_snippet_0(void* env, vader_box_t a0) {
    return vader_box_i32(3u, __lambda_snippet_0(env, ((int32_t) a0.payload.i)));
}

static vader_box_t vader_fn_lift___lambda_snippet_2(void* env, vader_box_t a0) {
    return vader_box_bool(7u, __lambda_snippet_2(env, ((int32_t) a0.payload.i)));
}

static const uint16_t vader_fn_ptr_offsets[] = { offsetof(vader_fn_t, env) };
static const uint16_t vader_array_ptr_offsets[] = { offsetof(vader_array_t, buf) };

const vader_type_info_t vader_type_info_table[20] = {
    [1] = { .slot_size = 16 },
    [2] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [3] = { .slot_size = 4 },
    [4] = { .slot_size = 8 },
    [5] = {
        .kind = VADER_TYPE_KIND_FN, .size = sizeof(vader_fn_t), .slot_size = 8,
        .ptr_offsets = vader_fn_ptr_offsets, .ptr_count = 1,
    },
    [6] = {
        .kind = VADER_TYPE_KIND_FN, .size = sizeof(vader_fn_t), .slot_size = 8,
        .ptr_offsets = vader_fn_ptr_offsets, .ptr_count = 1,
    },
    [7] = { .slot_size = 1 },
    [8] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___lambda_env_snippet_1_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___lambda_env_snippet_1_t, f_cap_0) },
        .ptr_count = 1,
    },
    [9] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___lambda_env_snippet_3_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___lambda_env_snippet_3_t, f_cap_0) },
        .ptr_count = 1,
    },
    [10] = { .slot_size = 16 },
    [11] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Range__i32_t),
        .slot_size = 8,
    },
    [12] = { .slot_size = 1 },
    [13] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Buffer_t),
        .slot_size = 8,
    },
    [14] = { .slot_size = 8 },
    [15] = { .slot_size = 8 },
    [16] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [18] = { .slot_size = 8 },
    [19] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct__Cell_i32_t), .slot_size = 8,
    },
};
const size_t vader_type_info_count = 20;

/* Headers named by `@c_header` — they own the prototypes below. */
#include <unistd.h>

static size_t vader_host_std_core_byte_len(vader_string_t a0) {
    return vader_string_byte_len(a0);
}

static void* vader_host_std_core_bytes(vader_string_t a0) {
    return (void*) vader_string_bytes_view(a0, 16u, 12u);
}

static ptrdiff_t vader_host_system_posix_sys_write(int32_t a0, void* a1, size_t a2) {
    vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1);
    return write(a0, s1.ptr, a2);
}

static void* snippet_source(vader_string_t l0, void* l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l1 };
    vader_string_t* gc_atom_roots[2] = { &l0, &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 2u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 18 "tests/snippets/iter_chain_operands/_main.vader"
    t0 = concat_2(1u, l0);
    std_io_println__string(t0);
#line 19 "tests/snippets/iter_chain_operands/_main.vader"
    { void* __vret = l1; vader_gc_top = gc_frame.prev; return __vret; }
}

static int32_t snippet_bound(vader_string_t l0, int32_t l1) {
    vader_string_t t0 = 0;
    vader_string_t* gc_atom_roots[2] = { &l0, &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL, 2u, gc_atom_roots };
    vader_gc_top = &gc_frame;
#line 23 "tests/snippets/iter_chain_operands/_main.vader"
    t0 = concat_2(2u, l0);
    std_io_println__string(t0);
#line 24 "tests/snippets/iter_chain_operands/_main.vader"
    { int32_t __vret = l1; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t snippet_limit(size_t l0) {
    void* l1 = NULL;
    size_t l2;
    uint64_t l3;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l1 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 28 "tests/snippets/iter_chain_operands/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 26);
    l2 = (size_t) 0;
    l2 = std_core_write_string_at(l1, l2, 3u);
    t0 = ((int64_t) (size_t) l0);
    l3 = (uint64_t) (int64_t) t0;
    l2 = std_core_write_unsigned(l1, l2, l3);
    t1 = std_core_finish_buffer(l1, l2);
    std_io_println__string(t1);
#line 29 "tests/snippets/iter_chain_operands/_main.vader"
    { size_t __vret = l0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_adder(int32_t l0) {
    vader_box_t l1 = vader_box_null();
    void* l2 = NULL;
    size_t l3;
    int64_t l4;
    void* t0 = NULL;
    vader_string_t t1 = 0;
    vader_box_t* gc_roots[1] = { &l1 };
    void** gc_raw_roots[2] = { &l2, &t0 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 1u, 2u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 32 "tests/snippets/iter_chain_operands/_main.vader"
    vader_struct__Cell_i32_t* _a0_obj = (vader_struct__Cell_i32_t*) vader_gc_alloc(sizeof(vader_struct__Cell_i32_t));
    vader_obj_header_init(_a0_obj, 19u);
    _a0_obj->f_value = l0;
    t0 = (void*) _a0_obj;
    l1 = vader_ref_box(t0);
#line 33 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = std_core_new_byte_buffer((size_t) 26);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l2, l3, 4u);
    l4 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l1.payload.obj)->f_value);
    l3 = std_core_write_int(l2, l3, l4);
    t1 = std_core_finish_buffer(l2, l3);
    std_io_println__string(t1);
#line 34 "tests/snippets/iter_chain_operands/_main.vader"
    vader_struct___lambda_env_snippet_1_t* _a1_obj = (vader_struct___lambda_env_snippet_1_t*) vader_gc_alloc(sizeof(vader_struct___lambda_env_snippet_1_t));
    vader_obj_header_init(_a1_obj, 8u);
    _a1_obj->f_cap_0 = l1;
    t0 = (void*) _a1_obj;
    vader_fn_t* _a2_closure = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));
    vader_obj_header_init(_a2_closure, 5u);
    _a2_closure->code = (void*) &vader_fn_lift___lambda_snippet_0;
    _a2_closure->env = t0;
    t0 = (void*) _a2_closure;
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* snippet_above(int32_t l0) {
    vader_box_t l1 = vader_box_null();
    void* l2 = NULL;
    size_t l3;
    int64_t l4;
    void* t0 = NULL;
    vader_string_t t1 = 0;
    vader_box_t* gc_roots[1] = { &l1 };
    void** gc_raw_roots[2] = { &l2, &t0 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 1u, 2u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 37 "tests/snippets/iter_chain_operands/_main.vader"
    vader_struct__Cell_i32_t* _a0_obj = (vader_struct__Cell_i32_t*) vader_gc_alloc(sizeof(vader_struct__Cell_i32_t));
    vader_obj_header_init(_a0_obj, 19u);
    _a0_obj->f_value = l0;
    t0 = (void*) _a0_obj;
    l1 = vader_ref_box(t0);
#line 38 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = std_core_new_byte_buffer((size_t) 26);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l2, l3, 5u);
    l4 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l1.payload.obj)->f_value);
    l3 = std_core_write_int(l2, l3, l4);
    t1 = std_core_finish_buffer(l2, l3);
    std_io_println__string(t1);
#line 39 "tests/snippets/iter_chain_operands/_main.vader"
    vader_struct___lambda_env_snippet_3_t* _a1_obj = (vader_struct___lambda_env_snippet_3_t*) vader_gc_alloc(sizeof(vader_struct___lambda_env_snippet_3_t));
    vader_obj_header_init(_a1_obj, 9u);
    _a1_obj->f_cap_0 = l1;
    t0 = (void*) _a1_obj;
    vader_fn_t* _a2_closure = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));
    vader_obj_header_init(_a2_closure, 6u);
    _a2_closure->code = (void*) &vader_fn_lift___lambda_snippet_2;
    _a2_closure->env = t0;
    t0 = (void*) _a2_closure;
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static int32_t snippet_main(void) {
    void* l0 = NULL;
    void* l1 = NULL;
    void* l2 = NULL;
    void* l4 = NULL;
    void* l5 = NULL;
    void* l6 = NULL;
    size_t l3, l8, l9, l13, l15, l16;
    bool l7;
    vader_box_t l10 = vader_box_null();
    int32_t l11, l17, l18;
    int64_t l12;
    uint64_t l14;
    uint8_t l19;
    int32_t t0;
    vader_box_t t1 = vader_box_null();
    bool t2;
    int64_t t3;
    vader_string_t t4 = 0;
    size_t t5;
    uint8_t t6;
    vader_box_t* gc_roots[2] = { &l10, &t1 };
    void** gc_raw_roots[6] = { &l0, &l1, &l2, &l4, &l5, &l6 };
    vader_string_t* gc_atom_roots[1] = { &t4 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 2u, 6u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 43 "tests/snippets/iter_chain_operands/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(2u, 5u, 7u, 3u);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 4u] = (int32_t) INT32_C(5);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 3u] = (int32_t) INT32_C(4);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 2u] = (int32_t) INT32_C(3);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 1u] = (int32_t) INT32_C(2);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 0u] = (int32_t) INT32_C(1);
    l0 = (void*) _a0_arr;
#line 44 "tests/snippets/iter_chain_operands/_main.vader"
    vader_array_t* _a1_arr = vader_array_new(2u, 0u, 7u, 3u);
    l1 = (void*) _a1_arr;
#line 46 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = std_core_new_byte_buffer((size_t) 17);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l2, l3, 6u);
    l4 = snippet_source(7u, l0);
    l5 = snippet_adder(INT32_C(1));
    l6 = snippet_above(INT32_C(100));
    l7 = false;
    l8 = ((vader_array_t*) l4)->length;
    l9 = (size_t) 0;
    for (;;) {
        if ((l9 < l8)) {
            vader_array_t* _a2_slotarr = ((vader_array_t*) l4);
            VADER_ARRAY_RESOLVE_BUF(_a2_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a2_slotarr, l9)
            t0 = ((int32_t*) _a2_slotarr->buf->slots)[_a2_slotarr->offset + (size_t) l9];
#line 263 "lib/std/iter/iter.vader"
            vader_fn_t* _a3_fnobj = (vader_fn_t*) l5;
            t1 = ((vader_fn_erased_sig_1_t) _a3_fnobj->code)(_a3_fnobj->env, vader_box_i32(3u, t0));
            t0 = ((int32_t) t1.payload.i);
#line 46 "tests/snippets/iter_chain_operands/_main.vader"
            vader_fn_t* _a4_fnobj = (vader_fn_t*) l6;
            t1 = ((vader_fn_erased_sig_1_t) _a4_fnobj->code)(_a4_fnobj->env, vader_box_i32(3u, t0));
            t2 = t1.payload.b;
            if (t2) {
                l7 = true;
            } else {
                t3 = (l9 + INT64_C(1));
                l9 = (size_t) (int64_t) t3;
                continue;
            }
        }
        break;
    }
    l3 = std_core_write_bool(l2, l3, l7);
    t4 = std_core_finish_buffer(l2, l3);
    std_io_println__string(t4);
#line 47 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = std_core_new_byte_buffer((size_t) 17);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l2, l3, 8u);
    l4 = snippet_source(7u, l0);
    l5 = snippet_adder(INT32_C(1));
    l6 = snippet_above(INT32_C(0));
    l7 = true;
    l8 = ((vader_array_t*) l4)->length;
    l9 = (size_t) 0;
    for (;;) {
        if ((l9 < l8)) {
            vader_array_t* _a5_slotarr = ((vader_array_t*) l4);
            VADER_ARRAY_RESOLVE_BUF(_a5_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a5_slotarr, l9)
            t0 = ((int32_t*) _a5_slotarr->buf->slots)[_a5_slotarr->offset + (size_t) l9];
#line 263 "lib/std/iter/iter.vader"
            vader_fn_t* _a6_fnobj = (vader_fn_t*) l5;
            t1 = ((vader_fn_erased_sig_1_t) _a6_fnobj->code)(_a6_fnobj->env, vader_box_i32(3u, t0));
            t0 = ((int32_t) t1.payload.i);
#line 47 "tests/snippets/iter_chain_operands/_main.vader"
            vader_fn_t* _a7_fnobj = (vader_fn_t*) l6;
            t1 = ((vader_fn_erased_sig_1_t) _a7_fnobj->code)(_a7_fnobj->env, vader_box_i32(3u, t0));
            t2 = t1.payload.b;
            if (!(t2)) {
                l7 = false;
            } else {
                t3 = (l9 + INT64_C(1));
                l9 = (size_t) (int64_t) t3;
                continue;
            }
        }
        break;
    }
    l3 = std_core_write_bool(l2, l3, l7);
    t4 = std_core_finish_buffer(l2, l3);
    std_io_println__string(t4);
#line 48 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = std_core_new_byte_buffer((size_t) 27);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l2, l3, 9u);
    l4 = snippet_source(7u, l0);
    l5 = snippet_adder(INT32_C(1));
    l6 = snippet_above(INT32_C(3));
    l10 = vader_box_obj(0u, NULL);
    l8 = ((vader_array_t*) l4)->length;
    l9 = (size_t) 0;
    for (;;) {
        if ((l9 < l8)) {
            vader_array_t* _a8_slotarr = ((vader_array_t*) l4);
            VADER_ARRAY_RESOLVE_BUF(_a8_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a8_slotarr, l9)
            t0 = ((int32_t*) _a8_slotarr->buf->slots)[_a8_slotarr->offset + (size_t) l9];
#line 263 "lib/std/iter/iter.vader"
            vader_fn_t* _a9_fnobj = (vader_fn_t*) l5;
            t1 = ((vader_fn_erased_sig_1_t) _a9_fnobj->code)(_a9_fnobj->env, vader_box_i32(3u, t0));
            l11 = ((int32_t) t1.payload.i);
#line 48 "tests/snippets/iter_chain_operands/_main.vader"
            vader_fn_t* _a10_fnobj = (vader_fn_t*) l6;
            t1 = ((vader_fn_erased_sig_1_t) _a10_fnobj->code)(_a10_fnobj->env, vader_box_i32(3u, l11));
            t2 = t1.payload.b;
            if (t2) {
                l10 = vader_box_i32(3u, l11);
            } else {
                t3 = (l9 + INT64_C(1));
                l9 = (size_t) (int64_t) t3;
                continue;
            }
        }
        break;
    }
    if (l10.tag == 0u) {
        l11 = INT32_C(0);
    } else {
        l11 = ((int32_t) l10.payload.i);
    }
    l12 = ((int64_t) (int32_t) l11);
    l3 = std_core_write_int(l2, l3, l12);
    t4 = std_core_finish_buffer(l2, l3);
    std_io_println__string(t4);
#line 49 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = std_core_new_byte_buffer((size_t) 16);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l2, l3, 10u);
    l1 = snippet_source(11u, l1);
    l4 = snippet_adder(INT32_C(1));
    l5 = snippet_above(INT32_C(0));
    l7 = false;
    l8 = ((vader_array_t*) l1)->length;
    l9 = (size_t) 0;
    for (;;) {
        if ((l9 < l8)) {
            vader_array_t* _a11_slotarr = ((vader_array_t*) l1);
            VADER_ARRAY_RESOLVE_BUF(_a11_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a11_slotarr, l9)
            t0 = ((int32_t*) _a11_slotarr->buf->slots)[_a11_slotarr->offset + (size_t) l9];
#line 263 "lib/std/iter/iter.vader"
            vader_fn_t* _a12_fnobj = (vader_fn_t*) l4;
            t1 = ((vader_fn_erased_sig_1_t) _a12_fnobj->code)(_a12_fnobj->env, vader_box_i32(3u, t0));
            t0 = ((int32_t) t1.payload.i);
#line 49 "tests/snippets/iter_chain_operands/_main.vader"
            vader_fn_t* _a13_fnobj = (vader_fn_t*) l5;
            t1 = ((vader_fn_erased_sig_1_t) _a13_fnobj->code)(_a13_fnobj->env, vader_box_i32(3u, t0));
            t2 = t1.payload.b;
            if (t2) {
                l7 = true;
            } else {
                t3 = (l9 + INT64_C(1));
                l9 = (size_t) (int64_t) t3;
                continue;
            }
        }
        break;
    }
    l3 = std_core_write_bool(l2, l3, l7);
    t4 = std_core_finish_buffer(l2, l3);
    std_io_println__string(t4);
#line 50 "tests/snippets/iter_chain_operands/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 28);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l1, l3, 12u);
    l2 = snippet_source(7u, l0);
    l4 = snippet_adder(INT32_C(1));
    l5 = snippet_above(INT32_C(2));
    l8 = (size_t) 0;
    l9 = ((vader_array_t*) l2)->length;
    l13 = (size_t) 0;
    while ((l13 < l9)) {
        vader_array_t* _a14_slotarr = ((vader_array_t*) l2);
        VADER_ARRAY_RESOLVE_BUF(_a14_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a14_slotarr, l13)
        t0 = ((int32_t*) _a14_slotarr->buf->slots)[_a14_slotarr->offset + (size_t) l13];
#line 263 "lib/std/iter/iter.vader"
        vader_fn_t* _a15_fnobj = (vader_fn_t*) l4;
        t1 = ((vader_fn_erased_sig_1_t) _a15_fnobj->code)(_a15_fnobj->env, vader_box_i32(3u, t0));
        t0 = ((int32_t) t1.payload.i);
#line 257 "lib/std/iter/iter.vader"
        vader_fn_t* _a16_fnobj = (vader_fn_t*) l5;
        t1 = ((vader_fn_erased_sig_1_t) _a16_fnobj->code)(_a16_fnobj->env, vader_box_i32(3u, t0));
        t2 = t1.payload.b;
        if (t2) {
#line 50 "tests/snippets/iter_chain_operands/_main.vader"
            t3 = (l8 + INT64_C(1));
            l8 = (size_t) (int64_t) t3;
#line 257 "lib/std/iter/iter.vader"
        }
#line 50 "tests/snippets/iter_chain_operands/_main.vader"
        t3 = (l13 + INT64_C(1));
        l13 = (size_t) (int64_t) t3;
    }
    t3 = ((int64_t) (size_t) l8);
    l14 = (uint64_t) (int64_t) t3;
    l3 = std_core_write_unsigned(l1, l3, l14);
    t4 = std_core_finish_buffer(l1, l3);
    std_io_println__string(t4);
#line 51 "tests/snippets/iter_chain_operands/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 27);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l1, l3, 13u);
    l2 = snippet_source(7u, l0);
    l8 = snippet_limit((size_t) 2);
    l9 = (size_t) 0;
#line 269 "lib/std/iter/iter.vader"
    if (l8 == INT64_C(0)) {
#line 272 "lib/std/iter/iter.vader"
    } else {
        l13 = (size_t) 0;
#line 51 "tests/snippets/iter_chain_operands/_main.vader"
        l15 = ((vader_array_t*) l2)->length;
        l16 = (size_t) 0;
        for (;;) {
            if ((l16 < l15)) {
                t3 = (l9 + INT64_C(1));
                l9 = (size_t) (int64_t) t3;
#line 275 "lib/std/iter/iter.vader"
                t3 = (l13 + INT64_C(1));
                l13 = (size_t) (int64_t) t3;
#line 276 "lib/std/iter/iter.vader"
                if ((l13 >= l8)) {
#line 51 "tests/snippets/iter_chain_operands/_main.vader"
                } else {
                    t3 = (l16 + INT64_C(1));
                    l16 = (size_t) (int64_t) t3;
                    continue;
#line 276 "lib/std/iter/iter.vader"
                }
#line 51 "tests/snippets/iter_chain_operands/_main.vader"
            }
            break;
        }
#line 269 "lib/std/iter/iter.vader"
    }
#line 51 "tests/snippets/iter_chain_operands/_main.vader"
    t3 = ((int64_t) (size_t) l9);
    l14 = (uint64_t) (int64_t) t3;
    l3 = std_core_write_unsigned(l1, l3, l14);
    t4 = std_core_finish_buffer(l1, l3);
    std_io_println__string(t4);
#line 52 "tests/snippets/iter_chain_operands/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 30);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l1, l3, 14u);
    l2 = snippet_source(7u, l0);
    l4 = snippet_above(INT32_C(3));
    vader_array_t* _a17_arr = vader_array_new(2u, 0u, 7u, 3u);
    l5 = (void*) _a17_arr;
    l8 = ((vader_array_t*) l2)->length;
    l9 = (size_t) 0;
    while ((l9 < l8)) {
        vader_array_t* _a18_slotarr = ((vader_array_t*) l2);
        VADER_ARRAY_RESOLVE_BUF(_a18_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a18_slotarr, l9)
        l11 = ((int32_t*) _a18_slotarr->buf->slots)[_a18_slotarr->offset + (size_t) l9];
#line 257 "lib/std/iter/iter.vader"
        vader_fn_t* _a19_fnobj = (vader_fn_t*) l4;
        t1 = ((vader_fn_erased_sig_1_t) _a19_fnobj->code)(_a19_fnobj->env, vader_box_i32(3u, l11));
        t2 = t1.payload.b;
        if (t2) {
            l17 = l11;
#line 52 "tests/snippets/iter_chain_operands/_main.vader"
            vader_array_push_i32((vader_array_t*) l5, l17);
#line 257 "lib/std/iter/iter.vader"
        }
#line 52 "tests/snippets/iter_chain_operands/_main.vader"
        t3 = (l9 + INT64_C(1));
        l9 = (size_t) (int64_t) t3;
    }
    t5 = ((vader_array_t*) l5)->length;
    t3 = ((int64_t) (size_t) t5);
    l14 = (uint64_t) (int64_t) t3;
    l3 = std_core_write_unsigned(l1, l3, l14);
    t4 = std_core_finish_buffer(l1, l3);
    std_io_println__string(t4);
#line 53 "tests/snippets/iter_chain_operands/_main.vader"
    l0 = snippet_source(7u, l0);
    l1 = snippet_adder(INT32_C(10));
    l2 = snippet_above(INT32_C(13));
    l3 = ((vader_array_t*) l0)->length;
    l8 = (size_t) 0;
    while ((l8 < l3)) {
        vader_array_t* _a20_slotarr = ((vader_array_t*) l0);
        VADER_ARRAY_RESOLVE_BUF(_a20_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a20_slotarr, l8)
        t0 = ((int32_t*) _a20_slotarr->buf->slots)[_a20_slotarr->offset + (size_t) l8];
#line 263 "lib/std/iter/iter.vader"
        vader_fn_t* _a21_fnobj = (vader_fn_t*) l1;
        t1 = ((vader_fn_erased_sig_1_t) _a21_fnobj->code)(_a21_fnobj->env, vader_box_i32(3u, t0));
        l11 = ((int32_t) t1.payload.i);
#line 257 "lib/std/iter/iter.vader"
        vader_fn_t* _a22_fnobj = (vader_fn_t*) l2;
        t1 = ((vader_fn_erased_sig_1_t) _a22_fnobj->code)(_a22_fnobj->env, vader_box_i32(3u, l11));
        t2 = t1.payload.b;
        if (t2) {
            l17 = l11;
#line 54 "tests/snippets/iter_chain_operands/_main.vader"
            l4 = std_core_new_byte_buffer((size_t) 28);
            l9 = (size_t) 0;
            l9 = std_core_write_string_at(l4, l9, 15u);
            l12 = ((int64_t) (int32_t) l17);
            l9 = std_core_write_int(l4, l9, l12);
            t4 = std_core_finish_buffer(l4, l9);
            std_io_println__string(t4);
#line 257 "lib/std/iter/iter.vader"
        }
#line 53 "tests/snippets/iter_chain_operands/_main.vader"
        t3 = (l8 + INT64_C(1));
        l8 = (size_t) (int64_t) t3;
    }
#line 56 "tests/snippets/iter_chain_operands/_main.vader"
    l0 = std_core_new_byte_buffer((size_t) 28);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l0, l3, 16u);
    l17 = snippet_bound(17u, INT32_C(0));
    l11 = snippet_bound(18u, INT32_C(3));
    l1 = snippet_adder(INT32_C(1));
    l8 = (size_t) 0;
    while ((l17 < l11)) {
#line 263 "lib/std/iter/iter.vader"
        vader_fn_t* _a23_fnobj = (vader_fn_t*) l1;
        t1 = ((vader_fn_erased_sig_1_t) _a23_fnobj->code)(_a23_fnobj->env, vader_box_i32(3u, l17));
        t0 = ((int32_t) t1.payload.i);
#line 56 "tests/snippets/iter_chain_operands/_main.vader"
        t3 = (l8 + INT64_C(1));
        l8 = (size_t) (int64_t) t3;
        l17 = (l17 + INT32_C(1));
    }
    t3 = ((int64_t) (size_t) l8);
    l14 = (uint64_t) (int64_t) t3;
    l3 = std_core_write_unsigned(l0, l3, l14);
    t4 = std_core_finish_buffer(l0, l3);
    std_io_println__string(t4);
#line 57 "tests/snippets/iter_chain_operands/_main.vader"
    vader_array_t* _a24_arr = vader_array_new(2u, 2u, 7u, 3u);
    ((int32_t*) _a24_arr->buf->slots)[_a24_arr->offset + 1u] = (int32_t) INT32_C(2);
    ((int32_t*) _a24_arr->buf->slots)[_a24_arr->offset + 0u] = (int32_t) INT32_C(1);
    l0 = (void*) _a24_arr;
    l0 = snippet_source(19u, l0);
    vader_array_t* _a25_arr = vader_array_new(2u, 1u, 7u, 3u);
    ((int32_t*) _a25_arr->buf->slots)[_a25_arr->offset + 0u] = (int32_t) INT32_C(3);
    l1 = (void*) _a25_arr;
    l1 = snippet_source(20u, l1);
    l3 = ((vader_array_t*) l0)->length;
    l8 = (size_t) 0;
    while ((l8 < l3)) {
        vader_array_t* _a26_slotarr = ((vader_array_t*) l0);
        VADER_ARRAY_RESOLVE_BUF(_a26_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a26_slotarr, l8)
        l11 = ((int32_t*) _a26_slotarr->buf->slots)[_a26_slotarr->offset + (size_t) l8];
#line 58 "tests/snippets/iter_chain_operands/_main.vader"
        l2 = std_core_new_byte_buffer((size_t) 30);
        l9 = (size_t) 0;
        l9 = std_core_write_string_at(l2, l9, 21u);
        l12 = ((int64_t) (int32_t) l11);
        l9 = std_core_write_int(l2, l9, l12);
        t4 = std_core_finish_buffer(l2, l9);
        std_io_println__string(t4);
#line 57 "tests/snippets/iter_chain_operands/_main.vader"
        t3 = (l8 + INT64_C(1));
        l8 = (size_t) (int64_t) t3;
    }
    l3 = ((vader_array_t*) l1)->length;
    l8 = (size_t) 0;
    while ((l8 < l3)) {
        vader_array_t* _a27_slotarr = ((vader_array_t*) l1);
        VADER_ARRAY_RESOLVE_BUF(_a27_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a27_slotarr, l8)
        l11 = ((int32_t*) _a27_slotarr->buf->slots)[_a27_slotarr->offset + (size_t) l8];
#line 58 "tests/snippets/iter_chain_operands/_main.vader"
        l0 = std_core_new_byte_buffer((size_t) 30);
        l9 = (size_t) 0;
        l9 = std_core_write_string_at(l0, l9, 21u);
        l12 = ((int64_t) (int32_t) l11);
        l9 = std_core_write_int(l0, l9, l12);
        t4 = std_core_finish_buffer(l0, l9);
        std_io_println__string(t4);
#line 57 "tests/snippets/iter_chain_operands/_main.vader"
        t3 = (l8 + INT64_C(1));
        l8 = (size_t) (int64_t) t3;
    }
#line 61 "tests/snippets/iter_chain_operands/_main.vader"
    l11 = snippet_bound(17u, INT32_C(0));
    l17 = snippet_bound(18u, INT32_C(2));
    vader_struct_std_core_Range__i32_t* _a28_obj = (vader_struct_std_core_Range__i32_t*) vader_gc_alloc(sizeof(vader_struct_std_core_Range__i32_t));
    vader_obj_header_init(_a28_obj, 11u);
    _a28_obj->f_start = l11;
    _a28_obj->f_end = l17;
    _a28_obj->f_inclusive = false;
    _a28_obj->f_cursor = l11;
    l0 = (void*) _a28_obj;
#line 62 "tests/snippets/iter_chain_operands/_main.vader"
    for (;;) {
        std_core_Range_Iterator_next__i32_v(l0, &t0, &t6);
        l19 = t6;
        l18 = t0;
        if (l19 == INT32_C(1)) {
        } else {
            l11 = l18;
#line 63 "tests/snippets/iter_chain_operands/_main.vader"
            l1 = std_core_new_byte_buffer((size_t) 36);
            l3 = (size_t) 0;
            l3 = std_core_write_string_at(l1, l3, 22u);
            l12 = ((int64_t) (int32_t) l11);
            l3 = std_core_write_int(l1, l3, l12);
            t4 = std_core_finish_buffer(l1, l3);
            std_io_println__string(t4);
#line 62 "tests/snippets/iter_chain_operands/_main.vader"
            continue;
        }
        break;
    }
#line 65 "tests/snippets/iter_chain_operands/_main.vader"
    l11 = snippet_bound(17u, INT32_C(0));
    l17 = snippet_bound(18u, INT32_C(2));
    while ((l11 < l17)) {
#line 66 "tests/snippets/iter_chain_operands/_main.vader"
        l0 = std_core_new_byte_buffer((size_t) 30);
        l3 = (size_t) 0;
        l3 = std_core_write_string_at(l0, l3, 23u);
        l12 = ((int64_t) (int32_t) l11);
        l3 = std_core_write_int(l0, l3, l12);
        t4 = std_core_finish_buffer(l0, l3);
        std_io_println__string(t4);
#line 65 "tests/snippets/iter_chain_operands/_main.vader"
        l11 = (l11 + INT32_C(1));
    }
#line 69 "tests/snippets/iter_chain_operands/_main.vader"
    l11 = INT32_C(0);
    while ((l11 < INT32_C(2))) {
#line 71 "tests/snippets/iter_chain_operands/_main.vader"
        l0 = std_core_new_byte_buffer((size_t) 32);
        l3 = (size_t) 0;
        l3 = std_core_write_string_at(l0, l3, 24u);
        l12 = ((int64_t) (int32_t) l11);
        l3 = std_core_write_int(l0, l3, l12);
        t4 = std_core_finish_buffer(l0, l3);
        std_io_println__string(t4);
#line 69 "tests/snippets/iter_chain_operands/_main.vader"
        l11 = (l11 + INT32_C(1));
    }
#line 73 "tests/snippets/iter_chain_operands/_main.vader"
    l11 = -(INT32_C(1));
#line 74 "tests/snippets/iter_chain_operands/_main.vader"
    l0 = std_core_new_byte_buffer((size_t) 10);
    l3 = (size_t) 0;
    l3 = std_core_write_string_at(l0, l3, 25u);
    l17 = snippet_bound(17u, INT32_C(0));
    l18 = snippet_bound(18u, INT32_C(3));
    if ((l17 <= l11)) {
        l7 = (l11 < l18);
    } else {
        l7 = false;
    }
    l3 = std_core_write_bool(l0, l3, l7);
    t4 = std_core_finish_buffer(l0, l3);
    std_io_println__string(t4);
#line 75 "tests/snippets/iter_chain_operands/_main.vader"
    { vader_gc_top = gc_frame.prev; return INT32_C(0); }
}

static int32_t __lambda_snippet_0(void* l0, int32_t l1) {
    int32_t l2;
#line 34 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = ((vader_struct__Cell_i32_t*) ((vader_struct___lambda_env_snippet_1_t*) l0)->f_cap_0.payload.obj)->f_value;
    return (l1 + l2);
}

static bool __lambda_snippet_2(void* l0, int32_t l1) {
    int32_t l2;
#line 39 "tests/snippets/iter_chain_operands/_main.vader"
    l2 = ((vader_struct__Cell_i32_t*) ((vader_struct___lambda_env_snippet_3_t*) l0)->f_cap_0.payload.obj)->f_value;
    return (l1 > l2);
}

static vader_string_t concat_2(vader_string_t l0, vader_string_t l1) {
    size_t l2, l3;
    void* l4 = NULL;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l4 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l1, &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    l2 = vader_host_std_core_byte_len(l0);
    l3 = vader_host_std_core_byte_len(l1);
    t0 = (l2 + l3);
    l3 = (size_t) (int64_t) t0;
    l4 = std_core_usize_BufferAlloc_new_buffer_vt(l3);
    std_core_Buffer_ByteAccess_write_string_vt(l4, (size_t) 0, l0);
    std_core_Buffer_ByteAccess_write_string_vt(l4, l2, l1);
    t1 = std_core_Buffer_ByteAccess_intern_string_vt(l4, l3);
    { vader_string_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Range_Iterator_next__i32_v(void* l0, int32_t* __o0, uint8_t* __o1) {
    bool l1;
    int32_t l2, l3;
    bool t0;
    int32_t t1;
#line 309 "lib/std/core/core.vader"
    t0 = ((vader_struct_std_core_Range__i32_t*) l0)->f_inclusive;
    if (t0) {
        l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__i32_t*) l0)->f_end;
        l1 = std_core_i32_Comparable_gt(l2, l3);
#line 310 "lib/std/core/core.vader"
    } else {
        l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__i32_t*) l0)->f_end;
        l1 = std_core_i32_Comparable_gte(l2, l3);
#line 309 "lib/std/core/core.vader"
    }
#line 313 "lib/std/core/core.vader"
    if (l1) {
        t1 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        *__o1 = (uint8_t) 1; *__o0 = t1; return;
    }
#line 314 "lib/std/core/core.vader"
    l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
#line 315 "lib/std/core/core.vader"
    t1 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
    l3 = std_core_i32_Step_step(t1);
    ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor = l3;
#line 316 "lib/std/core/core.vader"
    *__o1 = (uint8_t) 0; *__o0 = l2; return;
}

static void* std_core_new_byte_buffer(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 101 "lib/std/core/primitives.vader"
    t0 = std_core_usize_BufferAlloc_new_buffer_vt(l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t std_core_finish_buffer(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 104 "lib/std/core/primitives.vader"
    t0 = std_core_Buffer_ByteAccess_intern_string_vt(l0, l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2) {
    size_t l3;
#line 121 "lib/std/core/primitives.vader"
    std_core_Buffer_ByteAccess_write_string_vt(l0, l1, l2);
#line 122 "lib/std/core/primitives.vader"
    l3 = vader_host_std_core_byte_len(l2);
    return (size_t) (int64_t) (l1 + l3);
}

static size_t std_core_write_int(void* l0, size_t l1, int64_t l2) {
    bool l3;
    size_t l4, l6;
    int64_t l5;
    uint8_t l7, l8;
    int64_t t0;
    int32_t t1;
#line 127 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 128 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 129 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 127 "lib/std/core/primitives.vader"
    }
#line 131 "lib/std/core/primitives.vader"
    l3 = (l2 < INT64_C(0));
#line 132 "lib/std/core/primitives.vader"
    if ((l2 > INT64_C(0))) {
        l2 = -(l2);
    }
#line 133 "lib/std/core/primitives.vader"
    l4 = (size_t) 0;
#line 134 "lib/std/core/primitives.vader"
    l5 = l2;
#line 135 "lib/std/core/primitives.vader"
    while (l5 != INT64_C(0)) {
#line 136 "lib/std/core/primitives.vader"
        t0 = (l4 + INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 137 "lib/std/core/primitives.vader"
        l5 = vader_div_i64(l5, INT64_C(10));
#line 135 "lib/std/core/primitives.vader"
    }
#line 139 "lib/std/core/primitives.vader"
    if (l3) {
        t0 = (l4 + INT64_C(1));
        l6 = (size_t) (int64_t) t0;
    } else {
        l6 = l4;
    }
#line 140 "lib/std/core/primitives.vader"
    t0 = (l1 + l6);
    l4 = (size_t) (int64_t) t0;
#line 141 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 142 "lib/std/core/primitives.vader"
        t0 = (l4 - INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 143 "lib/std/core/primitives.vader"
        t0 = vader_mod_i64(l2, INT64_C(10));
        t1 = ((int32_t) (int64_t) -(t0));
        l7 = (uint8_t) (int32_t) t1;
        t1 = (INT32_C(48) + l7);
        l8 = (uint8_t) (int32_t) t1;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l4, l8);
#line 144 "lib/std/core/primitives.vader"
        l2 = vader_div_i64(l2, INT64_C(10));
#line 141 "lib/std/core/primitives.vader"
    }
#line 146 "lib/std/core/primitives.vader"
    if (l3) {
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 45);
    }
#line 147 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l6);
}

static size_t std_core_write_unsigned(void* l0, size_t l1, uint64_t l2) {
    size_t l3, l5;
    uint64_t l4;
    uint8_t l6, l7;
    int64_t t0;
    uint64_t t1;
    int32_t t2;
#line 152 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 153 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 154 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 152 "lib/std/core/primitives.vader"
    }
#line 156 "lib/std/core/primitives.vader"
    l3 = (size_t) 0;
#line 157 "lib/std/core/primitives.vader"
    l4 = l2;
#line 158 "lib/std/core/primitives.vader"
    while (l4 != INT64_C(0)) {
#line 159 "lib/std/core/primitives.vader"
        t0 = (l3 + INT64_C(1));
        l3 = (size_t) (int64_t) t0;
#line 160 "lib/std/core/primitives.vader"
        l4 = vader_div_u64(l4, INT64_C(10));
#line 158 "lib/std/core/primitives.vader"
    }
#line 162 "lib/std/core/primitives.vader"
    t0 = (l1 + l3);
    l5 = (size_t) (int64_t) t0;
#line 163 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 164 "lib/std/core/primitives.vader"
        t0 = (l5 - INT64_C(1));
        l5 = (size_t) (int64_t) t0;
#line 165 "lib/std/core/primitives.vader"
        t1 = vader_mod_u64(l2, INT64_C(10));
        t2 = ((int32_t) (uint64_t) t1);
        l6 = (uint8_t) (int32_t) t2;
        t2 = (INT32_C(48) + l6);
        l7 = (uint8_t) (int32_t) t2;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l5, l7);
#line 166 "lib/std/core/primitives.vader"
        l2 = vader_div_u64(l2, INT64_C(10));
#line 163 "lib/std/core/primitives.vader"
    }
#line 168 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l3);
}

static size_t std_core_write_bool(void* l0, size_t l1, bool l2) {
    size_t t0;
#line 173 "lib/std/core/primitives.vader"
    if (l2) {
        t0 = std_core_write_string_at(l0, l1, 26u);
        return t0;
    }
#line 174 "lib/std/core/primitives.vader"
    t0 = std_core_write_string_at(l0, l1, 27u);
    return t0;
}

static int32_t std_core_three_way(bool l0, bool l1) {
    int32_t l2;
#line 312 "lib/std/core/primitives.vader"
    if (l0) {
        l2 = -(INT32_C(1));
    } else if (l1) {
        l2 = INT32_C(1);
    } else {
        l2 = INT32_C(0);
    }
    return l2;
}

static int32_t std_core_i32_Comparable_compare(int32_t l0, int32_t l1) {
    bool l2, l3;
    int32_t t0;
#line 316 "lib/std/core/primitives.vader"
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
}

static bool std_core_i32_Comparable_gt(int32_t l0, int32_t l1) {
    int32_t t0;
#line 323602 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
}

static bool std_core_i32_Comparable_gte(int32_t l0, int32_t l1) {
    int32_t t0;
#line 323602 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
}

static int32_t std_core_i32_Step_step(int32_t l0) {
#line 334 "lib/std/core/primitives.vader"
    return (l0 + INT32_C(1));
    return (l0 + INT32_C(1));
}

static void std_io_write(uint8_t l0, vader_string_t l1) {
    void* l2 = NULL;
    void* l6 = NULL;
    size_t l3, l4, l5, l7, l9;
    int32_t l8;
    int64_t t0;
    void** gc_raw_roots[2] = { &l2, &l6 };
    vader_string_t* gc_atom_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 205 "lib/std/io/io.vader"
    l2 = vader_host_std_core_bytes(l1);
#line 206 "lib/std/io/io.vader"
    l3 = (size_t) 0;
#line 207 "lib/std/io/io.vader"
    for (;;) {
#line 208 "lib/std/io/io.vader"
        l4 = ((vader_array_t*) l2)->length;
        if ((l3 >= l4)) {
#line 209 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 208 "lib/std/io/io.vader"
        }
#line 211 "lib/std/io/io.vader"
        l5 = ((vader_array_t*) l2)->length;
        vader_array_t* _a0_arr = vader_array_slice((vader_array_t*) l2, (size_t) l3, (size_t) l5);
        l6 = (void*) _a0_arr;
#line 212 "lib/std/io/io.vader"
        l7 = ((vader_array_t*) l6)->length;
        l8 = std_io_write_bytes(l0, l6, l7);
#line 213 "lib/std/io/io.vader"
        if ((l8 <= INT32_C(0))) {
#line 214 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 213 "lib/std/io/io.vader"
        }
#line 216 "lib/std/io/io.vader"
        t0 = ((int64_t) (int32_t) l8);
        l9 = (size_t) (int64_t) t0;
        t0 = (l3 + l9);
        l3 = (size_t) (int64_t) t0;
#line 207 "lib/std/io/io.vader"
        continue;
    }
#line 209 "lib/std/io/io.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2) {
    int32_t l3;
    ptrdiff_t t0;
    void** gc_raw_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 177 "lib/std/io/io.vader"
    if (l0 == INT32_C(0)) {
        l3 = INT32_C(1);
    } else {
        l3 = INT32_C(2);
    }
#line 180 "lib/std/io/io.vader"
    t0 = vader_host_system_posix_sys_write(l3, l1, l2);
    { int32_t __vret = ((int32_t) (ptrdiff_t) t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_println__string(vader_string_t l0) {
    vader_string_t l1 = 0;
    vader_string_t* gc_atom_roots[2] = { &l0, &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL, 2u, gc_atom_roots };
    vader_gc_top = &gc_frame;
#line 235 "lib/std/io/io.vader"
    l1 = concat_2(l0, 28u);
    std_io_write((uint8_t) 0, l1);
    { vader_gc_top = gc_frame.prev; return; }
}

static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
    t0 = (void*) vader_buffer_new((size_t) l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2) {
    vader_buffer_store_u8((vader_buffer_t*) l0, (size_t) l1, (uint8_t) l2);
    return;
}

static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    t0 = vader_buffer_intern_string((vader_buffer_t*) l0, (size_t) l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2) {
    vader_buffer_write_string((vader_buffer_t*) l0, (size_t) l1, l2);
    return;
}

int main(int argc, char** argv) {
    vader_atom_init_with_comptime(vader_atom_comptime_table, VADER_COMPTIME_ATOM_COUNT);
    atexit(vader_atom_shutdown);
    atexit(vader_gc_shutdown);
    (void) argc;
    (void) argv;
    return (int) snippet_main();
}
