/* Generated by vader — do not edit. */
#include "vader.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

typedef struct vader_struct___defer_env_snippet_1_t vader_struct___defer_env_snippet_1_t;
typedef struct vader_struct___genstate_evens_t vader_struct___genstate_evens_t;
typedef struct vader_struct___Tuple_i32_u8_99ae0d29_t vader_struct___Tuple_i32_u8_99ae0d29_t;
typedef struct vader_struct_std_core_Range__i32_t vader_struct_std_core_Range__i32_t;
typedef struct vader_struct_std_core_Range__usize_t vader_struct_std_core_Range__usize_t;
typedef struct vader_struct___Tuple_usize_u8_de11f1ad_t vader_struct___Tuple_usize_u8_de11f1ad_t;
typedef struct vader_struct_std_core_Buffer_t vader_struct_std_core_Buffer_t;
typedef struct vader_struct__Cell_i32_t vader_struct__Cell_i32_t;

struct vader_struct___defer_env_snippet_1_t {
    vader_obj_header_t header;
    vader_box_t f_cap_0;
};
struct vader_struct___genstate_evens_t {
    vader_obj_header_t header;
    int32_t f_s0;
    int32_t f_s1;
    int32_t f_state;
};
struct vader_struct___Tuple_i32_u8_99ae0d29_t {
    vader_obj_header_t header;
    int32_t f__0;
    uint8_t f__1;
};
struct vader_struct_std_core_Range__i32_t {
    vader_obj_header_t header;
    int32_t f_start;
    int32_t f_end;
    bool f_inclusive;
    int32_t f_cursor;
};
struct vader_struct_std_core_Range__usize_t {
    vader_obj_header_t header;
    size_t f_start;
    size_t f_end;
    bool f_inclusive;
    size_t f_cursor;
};
struct vader_struct___Tuple_usize_u8_de11f1ad_t {
    vader_obj_header_t header;
    size_t f__0;
    uint8_t f__1;
};
struct vader_struct_std_core_Buffer_t {
    vader_obj_header_t header;
};
struct vader_struct__Cell_i32_t {
    vader_obj_header_t header;
    int32_t f_value;
};

/* Compile-time atom table — see docs/ATOM_INTERNING.md. */
static const char vader_atom_blob[] =
    "range: runaway" "\0"
    "range " "\0"
    "chain: runaway" "\0"
    "chain " "\0"
    "argument: runaway" "\0"
    "argument total " "\0"
    "match: runaway" "\0"
    "match " "\0"
    "fused range: runaway" "\0"
    "fused range " "\0"
    "outer: runaway" "\0"
    "outer " "\0"
    "," "\0"
    "labelled " "\0"
    "body " "\0"
    "generator " "\0"
    "defer " "\0"
    "\n" "\0";

static const vader_atom_entry_t vader_atom_comptime_table[] = {
    { 0u, 0u, 14u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[0] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[15] },
    { 0u, 0u, 14u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[22] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[37] },
    { 0u, 0u, 17u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[44] },
    { 0u, 0u, 15u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[62] },
    { 0u, 0u, 14u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[78] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[93] },
    { 0u, 0u, 20u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[100] },
    { 0u, 0u, 12u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[121] },
    { 0u, 0u, 14u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[134] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[149] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[156] },
    { 0u, 0u, 9u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[158] },
    { 0u, 0u, 5u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[168] },
    { 0u, 0u, 10u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[174] },
    { 0u, 0u, 6u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[185] },
    { 0u, 0u, 1u, VADER_ATOM_FLAG_PERM, 0u, &vader_atom_blob[192] },
};

#define VADER_COMPTIME_ATOM_COUNT 18u

static int32_t snippet_inc(int32_t l0);
static int32_t snippet_id(int32_t l0);
static vader_box_t snippet_maybe(int32_t l0);
static void snippet_range_continue_and_break(void);
static void snippet_chain_continue_and_break(void);
static void snippet_continue_in_argument(void);
static void snippet_continue_in_match(void);
static void snippet_fused_range_continue(void);
static void snippet_continue_outer(void);
static void snippet_labelled_and_named(void);
static void snippet_continue_with_defer(void);
static vader_box_t snippet_evens(int32_t l0);
static void snippet_generator_continue(void);
static int32_t snippet_main(void);
static void __defer_snippet_0(void* l0);
static void* snippet___genstate_evens_Iterator_next(void* l0);
static vader_string_t concat_2(vader_string_t l0, vader_string_t l1);
static void* std_core_Range_Iterator_next__i32(void* l0);
static void std_core_Range_Iterator_next__i32_v(void* l0, int32_t* __o0, uint8_t* __o1);
static void* std_core_Range_Iterator_next__usize(void* l0);
static void std_core_Range_Iterator_next__usize_v(void* l0, size_t* __o0, uint8_t* __o1);
static void* std_core_new_byte_buffer(size_t l0);
static vader_string_t std_core_finish_buffer(void* l0, size_t l1);
static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2);
static size_t std_core_write_int(void* l0, size_t l1, int64_t l2);
static int32_t std_core_three_way(bool l0, bool l1);
static int32_t std_core_i32_Comparable_compare(int32_t l0, int32_t l1);
static bool std_core_i32_Comparable_gt(int32_t l0, int32_t l1);
static bool std_core_i32_Comparable_gte(int32_t l0, int32_t l1);
static int32_t std_core_usize_Comparable_compare(size_t l0, size_t l1);
static bool std_core_usize_Comparable_gt(size_t l0, size_t l1);
static bool std_core_usize_Comparable_gte(size_t l0, size_t l1);
static int32_t std_core_i32_Step_step(int32_t l0);
static size_t std_core_usize_Step_step(size_t l0);
static void std_io_write(uint8_t l0, vader_string_t l1);
static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2);
static void std_io_println__string(vader_string_t l0);
static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0);
static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2);
static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1);
static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2);

typedef vader_box_t (*vader_fn_erased_sig_0_t)(void* env);

static vader_box_t vader_fn_lift___defer_snippet_0(void* env) {
    __defer_snippet_0(env);
    return vader_box_null();
}

static const uint16_t vader_fn_ptr_offsets[] = { offsetof(vader_fn_t, env) };
static const uint16_t vader_array_ptr_offsets[] = { offsetof(vader_array_t, buf) };

const vader_type_info_t vader_type_info_table[24] = {
    [1] = { .slot_size = 4 },
    [2] = { .slot_size = 16 },
    [4] = { .slot_size = 16 },
    [5] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___defer_env_snippet_1_t),
        .slot_size = 8,
        .ptr_offsets = (const uint16_t[]){ offsetof(vader_struct___defer_env_snippet_1_t, f_cap_0) },
        .ptr_count = 1,
    },
    [6] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___genstate_evens_t),
        .slot_size = 8,
    },
    [7] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t),
        .slot_size = 8,
    },
    [8] = { .slot_size = 1 },
    [9] = { .slot_size = 16 },
    [10] = { .slot_size = 16 },
    [11] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Range__i32_t),
        .slot_size = 8,
    },
    [12] = { .slot_size = 1 },
    [13] = { .slot_size = 8 },
    [14] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Range__usize_t),
        .slot_size = 8,
    },
    [15] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t),
        .slot_size = 8,
    },
    [16] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct_std_core_Buffer_t),
        .slot_size = 8,
    },
    [17] = { .slot_size = 8 },
    [18] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [19] = { .slot_size = 8 },
    [20] = {
        .kind = VADER_TYPE_KIND_ARRAY, .size = sizeof(vader_array_t), .slot_size = 8,
        .ptr_offsets = vader_array_ptr_offsets, .ptr_count = 1,
    },
    [21] = {
        .kind = VADER_TYPE_KIND_STRUCT, .size = sizeof(vader_struct__Cell_i32_t), .slot_size = 8,
    },
    [22] = {
        .kind = VADER_TYPE_KIND_FN, .size = sizeof(vader_fn_t), .slot_size = 8,
        .ptr_offsets = vader_fn_ptr_offsets, .ptr_count = 1,
    },
    [23] = { .slot_size = 16 },
};
const size_t vader_type_info_count = 24;

/* Headers named by `@c_header` — they own the prototypes below. */
#include <unistd.h>

static size_t vader_host_std_core_byte_len(vader_string_t a0) {
    return vader_string_byte_len(a0);
}

static void* vader_host_std_core_bytes(vader_string_t a0) {
    return (void*) vader_string_bytes_view(a0, 18u, 8u);
}

static ptrdiff_t vader_host_system_posix_sys_write(int32_t a0, void* a1, size_t a2) {
    vader_slice_t s1 = vader_array_bytes((vader_array_t*) a1);
    return write(a0, s1.ptr, a2);
}

/* vtable forwards */
static vader_box_t vader_vt_Iterator__next(vader_box_t recv);

static int32_t snippet_inc(int32_t l0) {
#line 15 "tests/snippets/counted_loop_continue/_main.vader"
    return (l0 + INT32_C(1));
}

static int32_t snippet_id(int32_t l0) {
#line 17 "tests/snippets/counted_loop_continue/_main.vader"
    return l0;
}

static vader_box_t snippet_maybe(int32_t l0) {
    vader_box_t l1;
    int32_t t0;
#line 19 "tests/snippets/counted_loop_continue/_main.vader"
    t0 = vader_mod_i32(l0, INT32_C(2));
    if (t0 == INT32_C(0)) {
        l1 = vader_box_i32(1u, l0);
    } else {
        l1 = vader_box_obj(0u, NULL);
    }
    return l1;
}

static void snippet_range_continue_and_break(void) {
    int32_t l0, l1;
    void* l2 = NULL;
    size_t l3;
    int64_t l4;
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l2 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 23 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
#line 24 "tests/snippets/counted_loop_continue/_main.vader"
    l1 = INT32_C(0);
    for (;;) {
        if ((l1 < INT32_C(5))) {
#line 25 "tests/snippets/counted_loop_continue/_main.vader"
            l0 = (l0 + INT32_C(1));
#line 26 "tests/snippets/counted_loop_continue/_main.vader"
            if ((l0 > INT32_C(20))) {
#line 27 "tests/snippets/counted_loop_continue/_main.vader"
                std_io_println__string(1u);
#line 26 "tests/snippets/counted_loop_continue/_main.vader"
#line 30 "tests/snippets/counted_loop_continue/_main.vader"
            } else {
                if (l1 == INT32_C(1)) {
#line 24 "tests/snippets/counted_loop_continue/_main.vader"
                    l1 = (l1 + INT32_C(1));
#line 31 "tests/snippets/counted_loop_continue/_main.vader"
                    continue;
#line 30 "tests/snippets/counted_loop_continue/_main.vader"
                }
#line 33 "tests/snippets/counted_loop_continue/_main.vader"
                if (l1 == INT32_C(3)) {
#line 36 "tests/snippets/counted_loop_continue/_main.vader"
                } else {
                    l2 = std_core_new_byte_buffer((size_t) 26);
                    l3 = (size_t) 0;
                    l3 = std_core_write_string_at(l2, l3, 2u);
                    l4 = ((int64_t) (int32_t) l1);
                    l3 = std_core_write_int(l2, l3, l4);
                    t0 = std_core_finish_buffer(l2, l3);
                    std_io_println__string(t0);
#line 24 "tests/snippets/counted_loop_continue/_main.vader"
                    l1 = (l1 + INT32_C(1));
                    continue;
#line 33 "tests/snippets/counted_loop_continue/_main.vader"
                }
#line 26 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 24 "tests/snippets/counted_loop_continue/_main.vader"
        }
        break;
    }
#line 22 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_chain_continue_and_break(void) {
    int32_t l0, l4;
    void* l1 = NULL;
    void* l5 = NULL;
    size_t l2, l3, l6;
    int64_t l7;
    int32_t t0;
    int64_t t1;
    vader_string_t t2 = 0;
    void** gc_raw_roots[2] = { &l1, &l5 };
    vader_string_t* gc_atom_roots[1] = { &t2 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 41 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
#line 42 "tests/snippets/counted_loop_continue/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(20u, 5u, 7u, 1u);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 4u] = (int32_t) INT32_C(4);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 3u] = (int32_t) INT32_C(3);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 2u] = (int32_t) INT32_C(2);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 1u] = (int32_t) INT32_C(1);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 0u] = (int32_t) INT32_C(0);
    l1 = (void*) _a0_arr;
    l2 = ((vader_array_t*) l1)->length;
    l3 = (size_t) 0;
    for (;;) {
        if ((l3 < l2)) {
            vader_array_t* _a1_slotarr = ((vader_array_t*) l1);
            VADER_ARRAY_RESOLVE_BUF(_a1_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a1_slotarr, l3)
            t0 = ((int32_t*) _a1_slotarr->buf->slots)[_a1_slotarr->offset + (size_t) l3];
#line 263 "lib/std/iter/iter.vader"
            l4 = snippet_inc(t0);
#line 43 "tests/snippets/counted_loop_continue/_main.vader"
            l0 = (l0 + INT32_C(1));
#line 44 "tests/snippets/counted_loop_continue/_main.vader"
            if ((l0 > INT32_C(20))) {
#line 45 "tests/snippets/counted_loop_continue/_main.vader"
                std_io_println__string(3u);
#line 44 "tests/snippets/counted_loop_continue/_main.vader"
#line 48 "tests/snippets/counted_loop_continue/_main.vader"
            } else {
                if (l4 == INT32_C(2)) {
#line 42 "tests/snippets/counted_loop_continue/_main.vader"
                    t1 = (l3 + INT64_C(1));
                    l3 = (size_t) (int64_t) t1;
#line 49 "tests/snippets/counted_loop_continue/_main.vader"
                    continue;
#line 48 "tests/snippets/counted_loop_continue/_main.vader"
                }
#line 51 "tests/snippets/counted_loop_continue/_main.vader"
                if (l4 == INT32_C(4)) {
#line 54 "tests/snippets/counted_loop_continue/_main.vader"
                } else {
                    l5 = std_core_new_byte_buffer((size_t) 26);
                    l6 = (size_t) 0;
                    l6 = std_core_write_string_at(l5, l6, 4u);
                    l7 = ((int64_t) (int32_t) l4);
                    l6 = std_core_write_int(l5, l6, l7);
                    t2 = std_core_finish_buffer(l5, l6);
                    std_io_println__string(t2);
#line 42 "tests/snippets/counted_loop_continue/_main.vader"
                    t1 = (l3 + INT64_C(1));
                    l3 = (size_t) (int64_t) t1;
                    continue;
#line 51 "tests/snippets/counted_loop_continue/_main.vader"
                }
#line 44 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 42 "tests/snippets/counted_loop_continue/_main.vader"
        }
        break;
    }
#line 40 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_continue_in_argument(void) {
    int32_t l0, l1, l2, l4;
    vader_box_t l3 = vader_box_null();
    void* l5 = NULL;
    size_t l6;
    int64_t l7;
    int32_t t0;
    vader_string_t t1 = 0;
    vader_box_t* gc_roots[1] = { &l3 };
    void** gc_raw_roots[1] = { &l5 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 1u, 1u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 60 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
#line 61 "tests/snippets/counted_loop_continue/_main.vader"
    l1 = INT32_C(0);
#line 62 "tests/snippets/counted_loop_continue/_main.vader"
    l2 = INT32_C(0);
    for (;;) {
        if ((l2 < INT32_C(6))) {
#line 63 "tests/snippets/counted_loop_continue/_main.vader"
            l1 = (l1 + INT32_C(1));
#line 64 "tests/snippets/counted_loop_continue/_main.vader"
            if ((l1 > INT32_C(20))) {
#line 65 "tests/snippets/counted_loop_continue/_main.vader"
                std_io_println__string(5u);
#line 64 "tests/snippets/counted_loop_continue/_main.vader"
#line 68 "tests/snippets/counted_loop_continue/_main.vader"
            } else {
                l3 = snippet_maybe(l2);
                if (l3.tag == 0u) {
#line 62 "tests/snippets/counted_loop_continue/_main.vader"
                    l2 = (l2 + INT32_C(1));
#line 68 "tests/snippets/counted_loop_continue/_main.vader"
                    continue;
                }
                t0 = ((int32_t) l3.payload.i);
                l4 = snippet_id(t0);
                l0 = (l0 + l4);
#line 62 "tests/snippets/counted_loop_continue/_main.vader"
                l2 = (l2 + INT32_C(1));
                continue;
#line 64 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 62 "tests/snippets/counted_loop_continue/_main.vader"
        }
        break;
    }
#line 70 "tests/snippets/counted_loop_continue/_main.vader"
    l5 = std_core_new_byte_buffer((size_t) 35);
    l6 = (size_t) 0;
    l6 = std_core_write_string_at(l5, l6, 6u);
    l7 = ((int64_t) (int32_t) l0);
    l6 = std_core_write_int(l5, l6, l7);
    t1 = std_core_finish_buffer(l5, l6);
    std_io_println__string(t1);
#line 59 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_continue_in_match(void) {
    int32_t l0, l4;
    void* l1 = NULL;
    void* l5 = NULL;
    size_t l2, l3, l6;
    int64_t l7;
    int32_t t0;
    int64_t t1;
    vader_string_t t2 = 0;
    void** gc_raw_roots[2] = { &l1, &l5 };
    vader_string_t* gc_atom_roots[1] = { &t2 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 74 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
#line 75 "tests/snippets/counted_loop_continue/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(20u, 4u, 7u, 1u);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 3u] = (int32_t) INT32_C(13);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 2u] = (int32_t) INT32_C(12);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 1u] = (int32_t) INT32_C(11);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 0u] = (int32_t) INT32_C(10);
    l1 = (void*) _a0_arr;
    l2 = ((vader_array_t*) l1)->length;
    l3 = (size_t) 0;
    for (;;) {
        if ((l3 < l2)) {
            vader_array_t* _a1_slotarr = ((vader_array_t*) l1);
            VADER_ARRAY_RESOLVE_BUF(_a1_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a1_slotarr, l3)
            l4 = ((int32_t*) _a1_slotarr->buf->slots)[_a1_slotarr->offset + (size_t) l3];
#line 76 "tests/snippets/counted_loop_continue/_main.vader"
            l0 = (l0 + INT32_C(1));
#line 77 "tests/snippets/counted_loop_continue/_main.vader"
            if ((l0 > INT32_C(20))) {
#line 78 "tests/snippets/counted_loop_continue/_main.vader"
                std_io_println__string(7u);
#line 77 "tests/snippets/counted_loop_continue/_main.vader"
#line 81 "tests/snippets/counted_loop_continue/_main.vader"
            } else {
                t0 = vader_mod_i32(l4, INT32_C(3));
#line 82 "tests/snippets/counted_loop_continue/_main.vader"
                if (t0 == INT32_C(1)) {
#line 75 "tests/snippets/counted_loop_continue/_main.vader"
                    t1 = (l3 + INT64_C(1));
                    l3 = (size_t) (int64_t) t1;
#line 82 "tests/snippets/counted_loop_continue/_main.vader"
                    continue;
                }
#line 85 "tests/snippets/counted_loop_continue/_main.vader"
                l5 = std_core_new_byte_buffer((size_t) 26);
                l6 = (size_t) 0;
                l6 = std_core_write_string_at(l5, l6, 8u);
                l7 = ((int64_t) (int32_t) l4);
                l6 = std_core_write_int(l5, l6, l7);
                t2 = std_core_finish_buffer(l5, l6);
                std_io_println__string(t2);
#line 75 "tests/snippets/counted_loop_continue/_main.vader"
                t1 = (l3 + INT64_C(1));
                l3 = (size_t) (int64_t) t1;
                continue;
#line 77 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 75 "tests/snippets/counted_loop_continue/_main.vader"
        }
        break;
    }
#line 73 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_fused_range_continue(void) {
    int32_t l0, l1, l2;
    void* l3 = NULL;
    size_t l4;
    int64_t l5;
    int32_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l3 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 90 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
#line 91 "tests/snippets/counted_loop_continue/_main.vader"
    l1 = INT32_C(0);
    for (;;) {
        if ((l1 < INT32_C(5))) {
#line 263 "lib/std/iter/iter.vader"
            l2 = snippet_inc(l1);
#line 92 "tests/snippets/counted_loop_continue/_main.vader"
            l0 = (l0 + INT32_C(1));
#line 93 "tests/snippets/counted_loop_continue/_main.vader"
            if ((l0 > INT32_C(20))) {
#line 94 "tests/snippets/counted_loop_continue/_main.vader"
                std_io_println__string(9u);
#line 93 "tests/snippets/counted_loop_continue/_main.vader"
#line 97 "tests/snippets/counted_loop_continue/_main.vader"
            } else {
                t0 = vader_mod_i32(l2, INT32_C(2));
                if (t0 == INT32_C(0)) {
#line 91 "tests/snippets/counted_loop_continue/_main.vader"
                    l1 = (l1 + INT32_C(1));
#line 98 "tests/snippets/counted_loop_continue/_main.vader"
                    continue;
#line 97 "tests/snippets/counted_loop_continue/_main.vader"
                }
#line 100 "tests/snippets/counted_loop_continue/_main.vader"
                l3 = std_core_new_byte_buffer((size_t) 32);
                l4 = (size_t) 0;
                l4 = std_core_write_string_at(l3, l4, 10u);
                l5 = ((int64_t) (int32_t) l2);
                l4 = std_core_write_int(l3, l4, l5);
                t1 = std_core_finish_buffer(l3, l4);
                std_io_println__string(t1);
#line 91 "tests/snippets/counted_loop_continue/_main.vader"
                l1 = (l1 + INT32_C(1));
                continue;
#line 93 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 91 "tests/snippets/counted_loop_continue/_main.vader"
        }
        break;
    }
#line 89 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_continue_outer(void) {
    int32_t l0, l1, l2, l7;
    void* l3 = NULL;
    size_t l4;
    int64_t l5, l6;
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l3 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 106 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
#line 107 "tests/snippets/counted_loop_continue/_main.vader"
    l1 = INT32_C(0);
    loop_5: while ((l1 < INT32_C(3))) {
#line 108 "tests/snippets/counted_loop_continue/_main.vader"
        l2 = INT32_C(0);
        for (;;) {
            if ((l2 < INT32_C(3))) {
#line 109 "tests/snippets/counted_loop_continue/_main.vader"
                l0 = (l0 + INT32_C(1));
#line 110 "tests/snippets/counted_loop_continue/_main.vader"
                if ((l0 > INT32_C(20))) {
#line 111 "tests/snippets/counted_loop_continue/_main.vader"
                    std_io_println__string(11u);
#line 110 "tests/snippets/counted_loop_continue/_main.vader"
#line 114 "tests/snippets/counted_loop_continue/_main.vader"
                } else {
                    if (l2 == INT32_C(1)) {
#line 107 "tests/snippets/counted_loop_continue/_main.vader"
                        l1 = (l1 + INT32_C(1));
#line 115 "tests/snippets/counted_loop_continue/_main.vader"
                        goto loop_5;
#line 114 "tests/snippets/counted_loop_continue/_main.vader"
                    }
#line 117 "tests/snippets/counted_loop_continue/_main.vader"
                    l3 = std_core_new_byte_buffer((size_t) 47);
                    l4 = (size_t) 0;
                    l4 = std_core_write_string_at(l3, l4, 12u);
                    l5 = ((int64_t) (int32_t) l1);
                    l4 = std_core_write_int(l3, l4, l5);
                    l4 = std_core_write_string_at(l3, l4, 13u);
                    l6 = ((int64_t) (int32_t) l2);
                    l4 = std_core_write_int(l3, l4, l6);
                    t0 = std_core_finish_buffer(l3, l4);
                    std_io_println__string(t0);
#line 108 "tests/snippets/counted_loop_continue/_main.vader"
                    l2 = (l2 + INT32_C(1));
                    continue;
#line 110 "tests/snippets/counted_loop_continue/_main.vader"
                }
#line 108 "tests/snippets/counted_loop_continue/_main.vader"
#line 107 "tests/snippets/counted_loop_continue/_main.vader"
            } else {
                l7 = INT32_C(1);
                l1 = (l1 + l7);
                goto loop_5;
#line 108 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 105 "tests/snippets/counted_loop_continue/_main.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 108 "tests/snippets/counted_loop_continue/_main.vader"
        }
#line 107 "tests/snippets/counted_loop_continue/_main.vader"
        l7 = INT32_C(1);
        l1 = (l1 + l7);
    }
#line 105 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_labelled_and_named(void) {
    void* l0 = NULL;
    void* l4 = NULL;
    void* l8 = NULL;
    size_t l1, l2, l5, l6, l9;
    int32_t l3, l7;
    int64_t l10, l11;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[3] = { &l0, &l4, &l8 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 3u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 126 "tests/snippets/counted_loop_continue/_main.vader"
    vader_array_t* _a0_arr = vader_array_new(20u, 3u, 7u, 1u);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 2u] = (int32_t) INT32_C(2);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 1u] = (int32_t) INT32_C(1);
    ((int32_t*) _a0_arr->buf->slots)[_a0_arr->offset + 0u] = (int32_t) INT32_C(0);
    l0 = (void*) _a0_arr;
    l1 = ((vader_array_t*) l0)->length;
    l2 = (size_t) 0;
    loop_10: while ((l2 < l1)) {
        vader_array_t* _a1_slotarr = ((vader_array_t*) l0);
        VADER_ARRAY_RESOLVE_BUF(_a1_slotarr)
        VADER_ARRAY_CHECK_INDEX(_a1_slotarr, l2)
        l3 = ((int32_t*) _a1_slotarr->buf->slots)[_a1_slotarr->offset + (size_t) l2];
#line 127 "tests/snippets/counted_loop_continue/_main.vader"
        vader_array_t* _a2_arr = vader_array_new(20u, 3u, 7u, 1u);
        ((int32_t*) _a2_arr->buf->slots)[_a2_arr->offset + 2u] = (int32_t) INT32_C(2);
        ((int32_t*) _a2_arr->buf->slots)[_a2_arr->offset + 1u] = (int32_t) INT32_C(1);
        ((int32_t*) _a2_arr->buf->slots)[_a2_arr->offset + 0u] = (int32_t) INT32_C(0);
        l4 = (void*) _a2_arr;
        l5 = ((vader_array_t*) l4)->length;
        l6 = (size_t) 0;
        while ((l6 < l5)) {
            vader_array_t* _a3_slotarr = ((vader_array_t*) l4);
            VADER_ARRAY_RESOLVE_BUF(_a3_slotarr)
            VADER_ARRAY_CHECK_INDEX(_a3_slotarr, l6)
            l7 = ((int32_t*) _a3_slotarr->buf->slots)[_a3_slotarr->offset + (size_t) l6];
#line 128 "tests/snippets/counted_loop_continue/_main.vader"
            if (l7 == INT32_C(1)) {
#line 126 "tests/snippets/counted_loop_continue/_main.vader"
                t0 = (l2 + INT64_C(1));
                l2 = (size_t) (int64_t) t0;
#line 129 "tests/snippets/counted_loop_continue/_main.vader"
                goto loop_10;
#line 128 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 131 "tests/snippets/counted_loop_continue/_main.vader"
            if (l3 == INT32_C(2)) {
#line 126 "tests/snippets/counted_loop_continue/_main.vader"
                t0 = (l2 + INT64_C(1));
                l2 = (size_t) (int64_t) t0;
#line 132 "tests/snippets/counted_loop_continue/_main.vader"
                goto loop_10;
#line 131 "tests/snippets/counted_loop_continue/_main.vader"
            }
#line 134 "tests/snippets/counted_loop_continue/_main.vader"
            l8 = std_core_new_byte_buffer((size_t) 50);
            l9 = (size_t) 0;
            l9 = std_core_write_string_at(l8, l9, 14u);
            l10 = ((int64_t) (int32_t) l3);
            l9 = std_core_write_int(l8, l9, l10);
            l9 = std_core_write_string_at(l8, l9, 13u);
            l11 = ((int64_t) (int32_t) l7);
            l9 = std_core_write_int(l8, l9, l11);
            t1 = std_core_finish_buffer(l8, l9);
            std_io_println__string(t1);
#line 127 "tests/snippets/counted_loop_continue/_main.vader"
            t0 = (l6 + INT64_C(1));
            l6 = (size_t) (int64_t) t0;
        }
#line 126 "tests/snippets/counted_loop_continue/_main.vader"
        t0 = (l2 + INT64_C(1));
        l2 = (size_t) (int64_t) t0;
    }
#line 125 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static void snippet_continue_with_defer(void) {
    int32_t l0;
    vader_box_t l1 = vader_box_null();
    void* l2 = NULL;
    size_t l3;
    int64_t l4;
    void* t0 = NULL;
    vader_string_t t1 = 0;
    vader_box_t* gc_roots[1] = { &l1 };
    void** gc_raw_roots[2] = { &l2, &t0 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 1u, 2u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 141 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = INT32_C(0);
    while ((l0 < INT32_C(3))) {
        vader_struct__Cell_i32_t* _a0_obj = (vader_struct__Cell_i32_t*) vader_gc_alloc(sizeof(vader_struct__Cell_i32_t));
        vader_obj_header_init(_a0_obj, 21u);
        _a0_obj->f_value = l0;
        t0 = (void*) _a0_obj;
        l1 = vader_ref_box(t0);
#line 142 "tests/snippets/counted_loop_continue/_main.vader"
        vader_struct___defer_env_snippet_1_t* _a1_obj = (vader_struct___defer_env_snippet_1_t*) vader_gc_alloc(sizeof(vader_struct___defer_env_snippet_1_t));
        vader_obj_header_init(_a1_obj, 5u);
        _a1_obj->f_cap_0 = l1;
        t0 = (void*) _a1_obj;
        vader_fn_t* _a2_closure = (vader_fn_t*) vader_gc_alloc(sizeof(vader_fn_t));
        vader_obj_header_init(_a2_closure, 22u);
        _a2_closure->code = (void*) &vader_fn_lift___defer_snippet_0;
        _a2_closure->env = t0;
        t0 = (void*) _a2_closure;
        vader_defer_push(vader_ref_box(t0));
#line 143 "tests/snippets/counted_loop_continue/_main.vader"
        if (((vader_struct__Cell_i32_t*) l1.payload.obj)->f_value == INT32_C(1)) {
#line 144 "tests/snippets/counted_loop_continue/_main.vader"
            vader_defer_pop_exec(1u);
#line 141 "tests/snippets/counted_loop_continue/_main.vader"
            l0 = (l0 + INT32_C(1));
#line 144 "tests/snippets/counted_loop_continue/_main.vader"
            continue;
#line 143 "tests/snippets/counted_loop_continue/_main.vader"
        }
#line 146 "tests/snippets/counted_loop_continue/_main.vader"
        l2 = std_core_new_byte_buffer((size_t) 25);
        l3 = (size_t) 0;
        l3 = std_core_write_string_at(l2, l3, 15u);
        l4 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) l1.payload.obj)->f_value);
        l3 = std_core_write_int(l2, l3, l4);
        t1 = std_core_finish_buffer(l2, l3);
        std_io_println__string(t1);
        vader_defer_pop_exec(1u);
#line 141 "tests/snippets/counted_loop_continue/_main.vader"
        l0 = (l0 + INT32_C(1));
    }
#line 140 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static vader_box_t snippet_evens(int32_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
    vader_struct___genstate_evens_t* _a0_obj = (vader_struct___genstate_evens_t*) vader_gc_alloc(sizeof(vader_struct___genstate_evens_t));
    vader_obj_header_init(_a0_obj, 6u);
    _a0_obj->f_s0 = l0;
    _a0_obj->f_s1 = INT32_C(0);
    _a0_obj->f_state = INT32_C(8);
    t0 = (void*) _a0_obj;
    { vader_box_t __vret = vader_ref_box(t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void snippet_generator_continue(void) {
    vader_box_t l0 = vader_box_null();
    void* l1 = NULL;
    void* l3 = NULL;
    int32_t l2;
    size_t l4;
    int64_t l5;
    vader_box_t t0 = vader_box_null();
    vader_string_t t1 = 0;
    vader_box_t* gc_roots[2] = { &l0, &t0 };
    void** gc_raw_roots[2] = { &l1, &l3 };
    vader_string_t* gc_atom_roots[1] = { &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 2u, 2u, gc_roots, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 161 "tests/snippets/counted_loop_continue/_main.vader"
    l0 = snippet_evens(INT32_C(6));
#line 162 "tests/snippets/counted_loop_continue/_main.vader"
    for (;;) {
        t0 = vader_vt_Iterator__next(l0);
        l1 = t0.payload.obj;
        if (((vader_struct___Tuple_i32_u8_99ae0d29_t*) l1)->f__1 == INT32_C(1)) {
        } else {
            l2 = ((vader_struct___Tuple_i32_u8_99ae0d29_t*) l1)->f__0;
#line 163 "tests/snippets/counted_loop_continue/_main.vader"
            l3 = std_core_new_byte_buffer((size_t) 30);
            l4 = (size_t) 0;
            l4 = std_core_write_string_at(l3, l4, 16u);
            l5 = ((int64_t) (int32_t) l2);
            l4 = std_core_write_int(l3, l4, l5);
            t1 = std_core_finish_buffer(l3, l4);
            std_io_println__string(t1);
#line 162 "tests/snippets/counted_loop_continue/_main.vader"
            continue;
        }
        break;
    }
#line 160 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static int32_t snippet_main(void) {
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 168 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_range_continue_and_break();
#line 169 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_chain_continue_and_break();
#line 170 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_continue_in_argument();
#line 171 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_continue_in_match();
#line 172 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_fused_range_continue();
#line 173 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_continue_outer();
#line 174 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_labelled_and_named();
#line 175 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_continue_with_defer();
#line 176 "tests/snippets/counted_loop_continue/_main.vader"
    snippet_generator_continue();
#line 177 "tests/snippets/counted_loop_continue/_main.vader"
    { vader_gc_top = gc_frame.prev; return INT32_C(0); }
}

static void __defer_snippet_0(void* l0) {
    void* l1 = NULL;
    size_t l2;
    int64_t l3;
    vader_string_t t0 = 0;
    void** gc_raw_roots[2] = { &l0, &l1 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 142 "tests/snippets/counted_loop_continue/_main.vader"
    l1 = std_core_new_byte_buffer((size_t) 26);
    l2 = (size_t) 0;
    l2 = std_core_write_string_at(l1, l2, 17u);
    l3 = ((int64_t) (int32_t) ((vader_struct__Cell_i32_t*) ((vader_struct___defer_env_snippet_1_t*) l0)->f_cap_0.payload.obj)->f_value);
    l2 = std_core_write_int(l1, l2, l3);
    t0 = std_core_finish_buffer(l1, l2);
    std_io_println__string(t0);
    { vader_gc_top = gc_frame.prev; return; }
}

static void* snippet___genstate_evens_Iterator_next(void* l0) {
    int32_t l1, l2, l3, l4, l5, l7;
    uint8_t l6;
    int32_t t0, t2;
    void* t1 = NULL;
    void** gc_raw_roots[2] = { &l0, &t1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
    for (;;) {
        t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
        if (t0 == INT32_C(0)) {
            ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(-1);
            continue;
        }
        t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
        if (t0 == INT32_C(1)) {
            ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(0);
            continue;
        }
        t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
        if (t0 == INT32_C(2)) {
            l1 = ((vader_struct___genstate_evens_t*) l0)->f_s1;
            l2 = ((vader_struct___genstate_evens_t*) l0)->f_s0;
#line 152 "tests/snippets/counted_loop_continue/_main.vader"
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
            if ((l1 < l2)) {
                ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(7);
            } else {
                ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(1);
            }
            continue;
        }
        t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
        if (t0 == INT32_C(3)) {
            t0 = ((vader_struct___genstate_evens_t*) l0)->f_s1;
#line 152 "tests/snippets/counted_loop_continue/_main.vader"
            l3 = (t0 + INT32_C(1));
            ((vader_struct___genstate_evens_t*) l0)->f_s1 = l3;
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
            ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(2);
            continue;
        }
        t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
        if (t0 == INT32_C(4)) {
            l4 = INT32_C(3);
            ((vader_struct___genstate_evens_t*) l0)->f_state = l4;
            l5 = ((vader_struct___genstate_evens_t*) l0)->f_s1;
            l6 = (uint8_t) 0;
            vader_struct___Tuple_i32_u8_99ae0d29_t* _a0_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
            vader_obj_header_init(_a0_obj, 7u);
            _a0_obj->f__0 = l5;
            _a0_obj->f__1 = l6;
            t1 = (void*) _a0_obj;
            { void* __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
        }
        t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
        if (t0 == INT32_C(5)) {
            ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(4);
        } else {
            t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
            if (t0 == INT32_C(6)) {
                t0 = ((vader_struct___genstate_evens_t*) l0)->f_s1;
#line 152 "tests/snippets/counted_loop_continue/_main.vader"
                l7 = (t0 + INT32_C(1));
                ((vader_struct___genstate_evens_t*) l0)->f_s1 = l7;
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
                ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(2);
            } else {
                t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
                if (t0 == INT32_C(7)) {
                    t0 = ((vader_struct___genstate_evens_t*) l0)->f_s1;
#line 153 "tests/snippets/counted_loop_continue/_main.vader"
                    t2 = vader_mod_i32(t0, INT32_C(2));
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
                    if (t2 == INT32_C(1)) {
                        ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(6);
                    } else {
                        ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(4);
                    }
                } else {
                    t0 = ((vader_struct___genstate_evens_t*) l0)->f_state;
                    if (t0 == INT32_C(8)) {
#line 152 "tests/snippets/counted_loop_continue/_main.vader"
                        ((vader_struct___genstate_evens_t*) l0)->f_s1 = INT32_C(0);
#line 151 "tests/snippets/counted_loop_continue/_main.vader"
                        ((vader_struct___genstate_evens_t*) l0)->f_state = INT32_C(2);
                    } else {
                        vader_struct___Tuple_i32_u8_99ae0d29_t* _a1_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
                        vader_obj_header_init(_a1_obj, 7u);
                        _a1_obj->f__0 = INT32_C(0);
                        _a1_obj->f__1 = (uint8_t) 1;
                        t1 = (void*) _a1_obj;
                        { void* __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
                    }
                }
            }
        }
        continue;
    }
    l4 = INT32_C(3);
    ((vader_struct___genstate_evens_t*) l0)->f_state = l4;
    l5 = ((vader_struct___genstate_evens_t*) l0)->f_s1;
    l6 = (uint8_t) 0;
    vader_struct___Tuple_i32_u8_99ae0d29_t* _a2_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
    vader_obj_header_init(_a2_obj, 7u);
    _a2_obj->f__0 = l5;
    _a2_obj->f__1 = l6;
    t1 = (void*) _a2_obj;
    { void* __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t concat_2(vader_string_t l0, vader_string_t l1) {
    size_t l2, l3;
    void* l4 = NULL;
    int64_t t0;
    vader_string_t t1 = 0;
    void** gc_raw_roots[1] = { &l4 };
    vader_string_t* gc_atom_roots[3] = { &l0, &l1, &t1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 3u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    l2 = vader_host_std_core_byte_len(l0);
    l3 = vader_host_std_core_byte_len(l1);
    t0 = (l2 + l3);
    l3 = (size_t) (int64_t) t0;
    l4 = std_core_usize_BufferAlloc_new_buffer_vt(l3);
    std_core_Buffer_ByteAccess_write_string_vt(l4, (size_t) 0, l0);
    std_core_Buffer_ByteAccess_write_string_vt(l4, l2, l1);
    t1 = std_core_Buffer_ByteAccess_intern_string_vt(l4, l3);
    { vader_string_t __vret = t1; vader_gc_top = gc_frame.prev; return __vret; }
}

static void* std_core_Range_Iterator_next__i32(void* l0) {
    uint8_t l1;
    int32_t t0;
    uint8_t t1;
    void* t2 = NULL;
    void** gc_raw_roots[2] = { &l0, &t2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 308 "lib/std/core/core.vader"
    std_core_Range_Iterator_next__i32_v(l0, &t0, &t1);
    l1 = t1;
    vader_struct___Tuple_i32_u8_99ae0d29_t* _a0_obj = (vader_struct___Tuple_i32_u8_99ae0d29_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_i32_u8_99ae0d29_t));
    vader_obj_header_init(_a0_obj, 7u);
    _a0_obj->f__0 = t0;
    _a0_obj->f__1 = l1;
    t2 = (void*) _a0_obj;
    { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Range_Iterator_next__i32_v(void* l0, int32_t* __o0, uint8_t* __o1) {
    bool l1;
    int32_t l2, l3;
    bool t0;
    int32_t t1;
#line 309 "lib/std/core/core.vader"
    t0 = ((vader_struct_std_core_Range__i32_t*) l0)->f_inclusive;
    if (t0) {
        l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__i32_t*) l0)->f_end;
        l1 = std_core_i32_Comparable_gt(l2, l3);
#line 310 "lib/std/core/core.vader"
    } else {
        l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__i32_t*) l0)->f_end;
        l1 = std_core_i32_Comparable_gte(l2, l3);
#line 309 "lib/std/core/core.vader"
    }
#line 313 "lib/std/core/core.vader"
    if (l1) {
        t1 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
        *__o1 = (uint8_t) 1; *__o0 = t1; return;
    }
#line 314 "lib/std/core/core.vader"
    l2 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
#line 315 "lib/std/core/core.vader"
    t1 = ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor;
    l3 = std_core_i32_Step_step(t1);
    ((vader_struct_std_core_Range__i32_t*) l0)->f_cursor = l3;
#line 316 "lib/std/core/core.vader"
    *__o1 = (uint8_t) 0; *__o0 = l2; return;
}

static void* std_core_Range_Iterator_next__usize(void* l0) {
    uint8_t l1;
    size_t t0;
    uint8_t t1;
    void* t2 = NULL;
    void** gc_raw_roots[2] = { &l0, &t2 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 308 "lib/std/core/core.vader"
    std_core_Range_Iterator_next__usize_v(l0, &t0, &t1);
    l1 = t1;
    vader_struct___Tuple_usize_u8_de11f1ad_t* _a0_obj = (vader_struct___Tuple_usize_u8_de11f1ad_t*) vader_gc_alloc(sizeof(vader_struct___Tuple_usize_u8_de11f1ad_t));
    vader_obj_header_init(_a0_obj, 15u);
    _a0_obj->f__0 = t0;
    _a0_obj->f__1 = l1;
    t2 = (void*) _a0_obj;
    { void* __vret = t2; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Range_Iterator_next__usize_v(void* l0, size_t* __o0, uint8_t* __o1) {
    bool l1;
    size_t l2, l3;
    bool t0;
    size_t t1;
#line 309 "lib/std/core/core.vader"
    t0 = ((vader_struct_std_core_Range__usize_t*) l0)->f_inclusive;
    if (t0) {
        l2 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__usize_t*) l0)->f_end;
        l1 = std_core_usize_Comparable_gt(l2, l3);
#line 310 "lib/std/core/core.vader"
    } else {
        l2 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
        l3 = ((vader_struct_std_core_Range__usize_t*) l0)->f_end;
        l1 = std_core_usize_Comparable_gte(l2, l3);
#line 309 "lib/std/core/core.vader"
    }
#line 313 "lib/std/core/core.vader"
    if (l1) {
        t1 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
        *__o1 = (uint8_t) 1; *__o0 = t1; return;
    }
#line 314 "lib/std/core/core.vader"
    l2 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
#line 315 "lib/std/core/core.vader"
    t1 = ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor;
    l3 = std_core_usize_Step_step(t1);
    ((vader_struct_std_core_Range__usize_t*) l0)->f_cursor = l3;
#line 316 "lib/std/core/core.vader"
    *__o1 = (uint8_t) 0; *__o0 = l2; return;
}

static void* std_core_new_byte_buffer(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 101 "lib/std/core/primitives.vader"
    t0 = std_core_usize_BufferAlloc_new_buffer_vt(l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static vader_string_t std_core_finish_buffer(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 104 "lib/std/core/primitives.vader"
    t0 = std_core_Buffer_ByteAccess_intern_string_vt(l0, l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static size_t std_core_write_string_at(void* l0, size_t l1, vader_string_t l2) {
    size_t l3;
#line 121 "lib/std/core/primitives.vader"
    std_core_Buffer_ByteAccess_write_string_vt(l0, l1, l2);
#line 122 "lib/std/core/primitives.vader"
    l3 = vader_host_std_core_byte_len(l2);
    return (size_t) (int64_t) (l1 + l3);
}

static size_t std_core_write_int(void* l0, size_t l1, int64_t l2) {
    bool l3;
    size_t l4, l6;
    int64_t l5;
    uint8_t l7, l8;
    int64_t t0;
    int32_t t1;
#line 127 "lib/std/core/primitives.vader"
    if (l2 == INT64_C(0)) {
#line 128 "lib/std/core/primitives.vader"
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 48);
#line 129 "lib/std/core/primitives.vader"
        return (size_t) (int64_t) (l1 + INT64_C(1));
#line 127 "lib/std/core/primitives.vader"
    }
#line 131 "lib/std/core/primitives.vader"
    l3 = (l2 < INT64_C(0));
#line 132 "lib/std/core/primitives.vader"
    if ((l2 > INT64_C(0))) {
        l2 = -(l2);
    }
#line 133 "lib/std/core/primitives.vader"
    l4 = (size_t) 0;
#line 134 "lib/std/core/primitives.vader"
    l5 = l2;
#line 135 "lib/std/core/primitives.vader"
    while (l5 != INT64_C(0)) {
#line 136 "lib/std/core/primitives.vader"
        t0 = (l4 + INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 137 "lib/std/core/primitives.vader"
        l5 = vader_div_i64(l5, INT64_C(10));
#line 135 "lib/std/core/primitives.vader"
    }
#line 139 "lib/std/core/primitives.vader"
    if (l3) {
        t0 = (l4 + INT64_C(1));
        l6 = (size_t) (int64_t) t0;
    } else {
        l6 = l4;
    }
#line 140 "lib/std/core/primitives.vader"
    t0 = (l1 + l6);
    l4 = (size_t) (int64_t) t0;
#line 141 "lib/std/core/primitives.vader"
    while (l2 != INT64_C(0)) {
#line 142 "lib/std/core/primitives.vader"
        t0 = (l4 - INT64_C(1));
        l4 = (size_t) (int64_t) t0;
#line 143 "lib/std/core/primitives.vader"
        t0 = vader_mod_i64(l2, INT64_C(10));
        t1 = ((int32_t) (int64_t) -(t0));
        l7 = (uint8_t) (int32_t) t1;
        t1 = (INT32_C(48) + l7);
        l8 = (uint8_t) (int32_t) t1;
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l4, l8);
#line 144 "lib/std/core/primitives.vader"
        l2 = vader_div_i64(l2, INT64_C(10));
#line 141 "lib/std/core/primitives.vader"
    }
#line 146 "lib/std/core/primitives.vader"
    if (l3) {
        std_core_Buffer_ByteAccess_store_u8_vt(l0, l1, (uint8_t) 45);
    }
#line 147 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l1 + l6);
}

static int32_t std_core_three_way(bool l0, bool l1) {
    int32_t l2;
#line 312 "lib/std/core/primitives.vader"
    if (l0) {
        l2 = -(INT32_C(1));
    } else if (l1) {
        l2 = INT32_C(1);
    } else {
        l2 = INT32_C(0);
    }
    return l2;
}

static int32_t std_core_i32_Comparable_compare(int32_t l0, int32_t l1) {
    bool l2, l3;
    int32_t t0;
#line 316 "lib/std/core/primitives.vader"
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
}

static bool std_core_i32_Comparable_gt(int32_t l0, int32_t l1) {
    int32_t t0;
#line 323602 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
}

static bool std_core_i32_Comparable_gte(int32_t l0, int32_t l1) {
    int32_t t0;
#line 323602 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
    t0 = std_core_i32_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
}

static int32_t std_core_usize_Comparable_compare(size_t l0, size_t l1) {
    bool l2, l3;
    int32_t t0;
#line 323 "lib/std/core/primitives.vader"
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
    l2 = (l0 < l1);
    l3 = (l0 > l1);
    t0 = std_core_three_way(l2, l3);
    return t0;
}

static bool std_core_usize_Comparable_gt(size_t l0, size_t l1) {
    int32_t t0;
#line 330770 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 > INT32_C(0));
}

static bool std_core_usize_Comparable_gte(size_t l0, size_t l1) {
    int32_t t0;
#line 330770 "<clone>:lib/std/core/primitives.vader"
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
    t0 = std_core_usize_Comparable_compare(l0, l1);
    return (t0 >= INT32_C(0));
}

static int32_t std_core_i32_Step_step(int32_t l0) {
#line 334 "lib/std/core/primitives.vader"
    return (l0 + INT32_C(1));
    return (l0 + INT32_C(1));
}

static size_t std_core_usize_Step_step(size_t l0) {
#line 341 "lib/std/core/primitives.vader"
    return (size_t) (int64_t) (l0 + INT64_C(1));
    return (size_t) (int64_t) (l0 + INT64_C(1));
}

static void std_io_write(uint8_t l0, vader_string_t l1) {
    void* l2 = NULL;
    void* l6 = NULL;
    size_t l3, l4, l5, l7, l9;
    int32_t l8;
    int64_t t0;
    void** gc_raw_roots[2] = { &l2, &l6 };
    vader_string_t* gc_atom_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 2u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
#line 205 "lib/std/io/io.vader"
    l2 = vader_host_std_core_bytes(l1);
#line 206 "lib/std/io/io.vader"
    l3 = (size_t) 0;
#line 207 "lib/std/io/io.vader"
    for (;;) {
#line 208 "lib/std/io/io.vader"
        l4 = ((vader_array_t*) l2)->length;
        if ((l3 >= l4)) {
#line 209 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 208 "lib/std/io/io.vader"
        }
#line 211 "lib/std/io/io.vader"
        l5 = ((vader_array_t*) l2)->length;
        vader_array_t* _a0_arr = vader_array_slice((vader_array_t*) l2, (size_t) l3, (size_t) l5);
        l6 = (void*) _a0_arr;
#line 212 "lib/std/io/io.vader"
        l7 = ((vader_array_t*) l6)->length;
        l8 = std_io_write_bytes(l0, l6, l7);
#line 213 "lib/std/io/io.vader"
        if ((l8 <= INT32_C(0))) {
#line 214 "lib/std/io/io.vader"
            { vader_gc_top = gc_frame.prev; return; }
#line 213 "lib/std/io/io.vader"
        }
#line 216 "lib/std/io/io.vader"
        t0 = ((int64_t) (int32_t) l8);
        l9 = (size_t) (int64_t) t0;
        t0 = (l3 + l9);
        l3 = (size_t) (int64_t) t0;
#line 207 "lib/std/io/io.vader"
        continue;
    }
#line 209 "lib/std/io/io.vader"
    { vader_gc_top = gc_frame.prev; return; }
}

static int32_t std_io_write_bytes(uint8_t l0, void* l1, size_t l2) {
    int32_t l3;
    ptrdiff_t t0;
    void** gc_raw_roots[1] = { &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
#line 177 "lib/std/io/io.vader"
    if (l0 == INT32_C(0)) {
        l3 = INT32_C(1);
    } else {
        l3 = INT32_C(2);
    }
#line 180 "lib/std/io/io.vader"
    t0 = vader_host_system_posix_sys_write(l3, l1, l2);
    { int32_t __vret = ((int32_t) (ptrdiff_t) t0); vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_io_println__string(vader_string_t l0) {
    vader_string_t l1 = 0;
    vader_string_t* gc_atom_roots[2] = { &l0, &l1 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 0u, NULL, NULL, 0u, NULL, 2u, gc_atom_roots };
    vader_gc_top = &gc_frame;
#line 235 "lib/std/io/io.vader"
    l1 = concat_2(l0, 18u);
    std_io_write((uint8_t) 0, l1);
    { vader_gc_top = gc_frame.prev; return; }
}

static void* std_core_usize_BufferAlloc_new_buffer_vt(size_t l0) {
    void* t0 = NULL;
    void** gc_raw_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = { vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL };
    vader_gc_top = &gc_frame;
    t0 = (void*) vader_buffer_new((size_t) l0);
    { void* __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_store_u8_vt(void* l0, size_t l1, uint8_t l2) {
    vader_buffer_store_u8((vader_buffer_t*) l0, (size_t) l1, (uint8_t) l2);
    return;
}

static vader_string_t std_core_Buffer_ByteAccess_intern_string_vt(void* l0, size_t l1) {
    vader_string_t t0 = 0;
    void** gc_raw_roots[1] = { &l0 };
    vader_string_t* gc_atom_roots[1] = { &t0 };
    vader_gc_frame_t gc_frame = {
        vader_gc_top, 0u, 1u, NULL, gc_raw_roots, 0u, NULL, 1u, gc_atom_roots,
    };
    vader_gc_top = &gc_frame;
    t0 = vader_buffer_intern_string((vader_buffer_t*) l0, (size_t) l1);
    { vader_string_t __vret = t0; vader_gc_top = gc_frame.prev; return __vret; }
}

static void std_core_Buffer_ByteAccess_write_string_vt(void* l0, size_t l1, vader_string_t l2) {
    vader_buffer_write_string((vader_buffer_t*) l0, (size_t) l1, l2);
    return;
}

/* vtable dispatchers */
static vader_box_t vader_vt_Iterator__next(vader_box_t recv) {
    switch (recv.tag) {
        case 6u: return vader_ref_box(snippet___genstate_evens_Iterator_next(recv.payload.obj));
        case 11u: return vader_ref_box(std_core_Range_Iterator_next__i32(recv.payload.obj));
        case 14u: return vader_ref_box(std_core_Range_Iterator_next__usize(recv.payload.obj));
        default: vader_unreachable("vtable miss in Iterator.next");
    }
    vader_unreachable("vtable miss in Iterator.next");
}

int main(int argc, char** argv) {
    vader_atom_init_with_comptime(vader_atom_comptime_table, VADER_COMPTIME_ATOM_COUNT);
    atexit(vader_atom_shutdown);
    atexit(vader_gc_shutdown);
    (void) argc;
    (void) argv;
    return (int) snippet_main();
}
