// Bytecode peephole optimizations.
//
// Run as a single linear scan after each fn body is emitted. All transforms
// here are sound because:
//   - Vader's `br` / `br_if` use depth (label-stack relative), not absolute
//     op indices, so removing or rewriting ops never invalidates branch
//     targets.
//   - Each transform preserves the value-stack shape across the rewrite,
//     so downstream verifier / VM / C-emit see the same effective operation.
//
// All transforms are gated by a single `optimize` flag plumbed through
// `emitBytecode` (default on; CLI exposes `--no-bytecode-opt`).
//
// Current rules:
//   1. `local.set N; local.get N`            → `local.tee N`
//   2. `<num>.<cmp>; bool.not`               → `<num>.<inverse cmp>`
//   3. `bool.const X; bool.not`              → `bool.const !X`
//   4. `bool.not; bool.not`                  → ε
//   5. Dead-store elimination on tail-slots — if a local is never read after
//      every rule above settles, drop its writes (`local.set` → `drop`,
//      `local.tee` → ε) and remove the slot from the locals list. Slots are
//      renumbered so surviving `local.{get,set,tee}` indices stay dense.
//      Massive savings on the CFG-emit path which materialises every sub-
//      expression into a tmp slot — most of those become dead after rule 1.
//   6. Const-prop through single-use primitive locals — when slot N has
//      exactly 1 set and 1 get (no tees) AND the set is fed by a constant
//      op (`<T>.const K`) of a matching val type, propagate the const to
//      the get site. Eliminates the temp local entirely (Rule 5 then drops
//      the slot). Massive on struct-literal lowering, where each field
//      expr is stashed in a fresh slot for evaluation-order safety.

import type { Op } from "./ops.ts";
import type { BcLocal, DebugPos } from "./module.ts";
import { slotRead, slotTouched, slotWrite, withRemappedSlot } from "./slot-refs.ts";
import type { ValType } from "./types.ts";

const INVERSE_VERB: Record<string, string> = {
  lt: "ge", le: "gt", gt: "le", ge: "lt",
  eq: "ne", ne: "eq",
};

interface MutFn {
  body: Op[];
  debug: (DebugPos | null)[];
  locals: BcLocal[];
  signature: { readonly params: readonly unknown[] };
}

export function runPeepholes(fn: MutFn): void {
  applyLocalRules(fn);
  propagateConstSingleUse(fn);
  propagateLocalAlias(fn);
  dropDeadStores(fn);
}

function applyLocalRules(fn: MutFn): void {
  const out: Op[] = [];
  const dbg: (DebugPos | null)[] = [];
  for (let i = 0; i < fn.body.length; i++) {
    const op = fn.body[i]!;
    const span = fn.debug[i]!;

    // Bool-folding rules (2/3/4) all fire on `bool.not` paired with the
    // previous op. Single guard, dispatch on `prev.kind`.
    if (op.kind === "bool.not" && out.length > 0) {
      const prev = out[out.length - 1]!;
      if (prev.kind === "bool.not") {                                 // Rule 4
        out.pop(); dbg.pop(); continue;
      }
      if (prev.kind === "bool.const") {                               // Rule 3
        out[out.length - 1] = { kind: "bool.const", value: !prev.value };
        continue;
      }
      const inv = invertCmp(prev);                                    // Rule 2
      if (inv !== null) { out[out.length - 1] = inv; continue; }
    }

    // Rule 1 — `local.set N; local.get N` → `local.tee N`.
    if (op.kind === "local.set") {
      const next = fn.body[i + 1];
      if (next?.kind === "local.get" && next.slot === op.slot) {
        out.push({ kind: "local.tee", slot: op.slot });
        dbg.push(span);
        i++;
        continue;
      }
    }

    out.push(op);
    dbg.push(span);
  }
  // `body.push(...out)` spreads `out` as args ; engines cap that at ~16k,
  // tripping a RangeError on bodies generated by union-common-field
  // lowering (each access expands to a 25-arm if/else cascade). Replace
  // the array contents in place — same observable result, no stack walk.
  fn.body.length = 0;
  for (const op of out) fn.body.push(op);
  fn.debug.length = 0;
  for (const d of dbg) fn.debug.push(d);
}

/** Rule 5 — eliminate locals whose only references are writes. After
 *  `applyLocalRules` collapses every `set N ; get N` adjacency into a tee,
 *  the CFG-emit path leaves long tails of dead `local.tee N` (the value
 *  stays on stack for the next op, but the local itself is never read).
 *  We drop those writes and shrink the locals table so the C emit stops
 *  declaring slots no one consumes. */
function dropDeadStores(fn: MutFn): void {
  const paramCount = fn.signature.params.length;
  const totalSlots = paramCount + fn.locals.length;
  const reads = new Array<number>(totalSlots).fill(0);
  for (const op of fn.body) {
    const r = slotRead(op);
    if (r !== null) reads[r]!++;
  }

  // Param slots stay alive even when unread — the ABI keeps their slot index
  // pinned at 0..N-1. Local slots become "dead" iff reads === 0.
  const dead = new Array<boolean>(totalSlots).fill(false);
  let anyDead = false;
  for (let s = paramCount; s < totalSlots; s++) {
    if (reads[s] === 0) { dead[s] = true; anyDead = true; }
  }
  if (!anyDead) return;

  // Build slot remap : surviving slots stay dense from 0 upward.
  const remap = new Array<number>(totalSlots).fill(-1);
  let next = 0;
  for (let s = 0; s < totalSlots; s++) if (!dead[s]) remap[s] = next++;

  // Rewrite the body : drop dead writes, renumber surviving accesses.
  const out: Op[] = [];
  const dbg: (DebugPos | null)[] = [];
  for (let i = 0; i < fn.body.length; i++) {
    const op = fn.body[i]!;
    const span = fn.debug[i]!;
    if (op.kind === "local.set" && dead[op.slot]) {
      out.push({ kind: "drop" });
      dbg.push(span);
      continue;
    }
    if (op.kind === "local.tee" && dead[op.slot]) {
      // tee = set + push. With set dead, we just leave the value on stack —
      // the consumer reads it directly.
      continue;
    }
    // Surviving slot-touching ops get their slot renumbered into the
    // compacted range ; other ops pass through unchanged.
    const slot = slotTouched(op);
    out.push(slot !== null ? withRemappedSlot(op, remap[slot]!) : op);
    dbg.push(span);
  }
  fn.body.length = 0;
  fn.body.push(...out);
  fn.debug.length = 0;
  fn.debug.push(...dbg);

  // Compact the locals list. Param slots are not in `fn.locals` (they live
  // in `signature.params`), so we only filter the per-fn locals tail.
  const newLocals: BcLocal[] = [];
  for (let s = paramCount; s < totalSlots; s++) {
    if (!dead[s]) newLocals.push(fn.locals[s - paramCount]!);
  }
  fn.locals.length = 0;
  fn.locals.push(...newLocals);
}

/** Rule 6 — propagate a constant op through a single-use primitive local.
 *
 *  Detects:                      Becomes:
 *      <T>.const K                   <ops between>          // const + set both gone
 *      local.set N                   <T>.const K            // pushed at the get site
 *      <ops between>                 <T>.const K
 *      local.get N
 *
 *  Conditions :
 *    - Slot N is a non-param local (params can't be eliminated — ABI fixes
 *      their indices).
 *    - Slot N has exactly 1 `local.set`, 1 `local.get`, 0 `local.tee`.
 *    - The op immediately preceding the `local.set N` is a constant op
 *      whose val type matches the slot's val type (avoids losing an
 *      implicit numeric coercion that the original `local.set` performed).
 *    - The set's IP is strictly before the get's IP (no backward dataflow).
 *
 *  Why it's safe to "move" the const past arbitrary intervening ops :
 *  pure constants have no observable effect on the value stack at the
 *  set-IP (they push K then are immediately popped by the set), and pushing
 *  the same K at the get-IP yields the identical stack effect as the
 *  original `local.get N` (same value, same type). Stack discipline
 *  preserved. Branch targets are depth-relative, so deleting two ops
 *  doesn't invalidate them.
 *
 *  After this pass the slot has 0 reads and 0 writes ; `dropDeadStores`
 *  collects it and renumbers surviving slots dense.
 */
function propagateConstSingleUse(fn: MutFn): void {
  const paramCount = fn.signature.params.length;
  const totalSlots = paramCount + fn.locals.length;
  if (totalSlots <= paramCount) return;

  type SlotStat = { setIdx: number; getIdx: number; sets: number; gets: number; tees: number };
  const stats: SlotStat[] = [];
  for (let s = 0; s < totalSlots; s++) {
    stats.push({ setIdx: -1, getIdx: -1, sets: 0, gets: 0, tees: 0 });
  }
  for (let i = 0; i < fn.body.length; i++) {
    const op = fn.body[i]!;
    if (op.kind === "local.set") { stats[op.slot]!.sets++; stats[op.slot]!.setIdx = i; continue; }
    if (op.kind === "local.tee") { stats[op.slot]!.tees++; continue; }
    // Any slot-reading op (bare local.get or a fused read like
    // local.field) counts toward the get tally — otherwise const-prop
    // would happily drop a `set` whose value is consumed by the fused op.
    const r = slotRead(op);
    if (r !== null) { stats[r]!.gets++; stats[r]!.getIdx = i; }
  }

  const toDelete = new Set<number>();
  const replaceWith = new Map<number, Op[]>();
  for (let s = paramCount; s < totalSlots; s++) {
    const stat = stats[s]!;
    if (stat.tees !== 0 || stat.sets !== 1 || stat.gets !== 1) continue;
    const setIdx = stat.setIdx;
    const getIdx = stat.getIdx;
    if (setIdx === 0 || getIdx <= setIdx) continue;
    const constOp = fn.body[setIdx - 1]!;
    const constValType = constOpValType(constOp);
    if (constValType === null) continue;
    const slotVal = fn.locals[s - paramCount]!.val;
    if (constValType === slotVal) {
      toDelete.add(setIdx - 1);
      toDelete.add(setIdx);
      replaceWith.set(getIdx, [constOp]);
      continue;
    }
    // Integer-narrowing case: the original `local.set` performed an implicit
    // coerce (e.g. `i32.const 3; local.set N (u8)`). To keep the consumer's
    // typed eq/cmp happy at the get site we emit `<const>; <from>.to_<slot>`.
    // The lowerer already validated the value fit at the original set, so we
    // trust the convert here.
    if (canNumericConvert(constValType, slotVal)) {
      toDelete.add(setIdx - 1);
      toDelete.add(setIdx);
      const convert: Op = { kind: `${constValType}.to_${slotVal}` } as Op;
      replaceWith.set(getIdx, [constOp, convert]);
    }
  }

  if (toDelete.size === 0) return;

  const newBody: Op[] = [];
  const newDbg: (DebugPos | null)[] = [];
  for (let i = 0; i < fn.body.length; i++) {
    if (toDelete.has(i)) continue;
    const replacement = replaceWith.get(i);
    if (replacement !== undefined) {
      for (const op of replacement) {
        newBody.push(op);
        newDbg.push(fn.debug[i]!);
      }
    } else {
      newBody.push(fn.body[i]!);
      newDbg.push(fn.debug[i]!);
    }
  }
  fn.body.length = 0;
  for (const op of newBody) fn.body.push(op);
  fn.debug.length = 0;
  for (const d of newDbg) fn.debug.push(d);
}

/** True iff `from` and `to` are both numeric (or char) widths the
 *  `${from}.to_${to}` ConvertOpKind covers. */
function canNumericConvert(from: ValType, to: ValType): boolean {
  return NUMERIC_OR_CHAR.has(from) && NUMERIC_OR_CHAR.has(to);
}

/** Rule 7 — local-alias propagation. The `is X as bind ->` lowering
 *  produces a chain of `local.get N ; local.set M` where M is a fresh
 *  slot that just shadows N for the arm body. Forwarding the reads of
 *  M to N erases the copy and lets `dropDeadStores` collect M.
 *
 *  Detects:                       Becomes:
 *      local.get N                <ops>             // copy gone
 *      local.set M                <ops>
 *      <ops>                      local.get N       // M's read sites
 *      local.get M                                  // rewritten
 *
 *  Conditions :
 *    - M is a non-param slot with exactly 1 set, 0 tees, ≥ 1 read.
 *    - The op preceding `local.set M` is `local.get N` (with N ≠ M).
 *    - M and N share the same ValType (no implicit coerce to preserve).
 *    - N is not written between the alias point and M's last read —
 *      otherwise the forwarded read would see a different value.
 *      Conservative check : no `local.set N` / `local.tee N` in that
 *      range.
 *
 *  Slot-aware ops (`local.get M`, `local.field M T F`) all forward via
 *  `withRemappedSlot`. After this pass M has 0 reads / writes ;
 *  `dropDeadStores` collects it.
 */
function propagateLocalAlias(fn: MutFn): void {
  const paramCount = fn.signature.params.length;
  const totalSlots = paramCount + fn.locals.length;
  if (totalSlots <= paramCount) return;

  type SlotStat = { setIdx: number; sets: number; gets: number; tees: number };
  const stats: SlotStat[] = [];
  for (let s = 0; s < totalSlots; s++) {
    stats.push({ setIdx: -1, sets: 0, gets: 0, tees: 0 });
  }
  for (let i = 0; i < fn.body.length; i++) {
    const op = fn.body[i]!;
    if (op.kind === "local.set") { stats[op.slot]!.sets++; stats[op.slot]!.setIdx = i; continue; }
    if (op.kind === "local.tee") { stats[op.slot]!.tees++; continue; }
    const r = slotRead(op);
    if (r !== null) stats[r]!.gets++;
  }

  const toDelete = new Set<number>();
  const remapReads = new Map<number, number>();   // body index → new slot for that read
  for (let s = paramCount; s < totalSlots; s++) {
    const stat = stats[s]!;
    if (stat.tees !== 0 || stat.sets !== 1 || stat.gets < 1) continue;
    const setIdx = stat.setIdx;
    if (setIdx === 0) continue;
    const prev = fn.body[setIdx - 1]!;
    if (prev.kind !== "local.get" || prev.slot === s) continue;
    const sourceSlot = prev.slot;
    // Params are slot-typed too but their ValType lives in fn.signature ;
    // we only enforce the ValType match for local→local aliases.
    const sourceVal = sourceSlot < paramCount
      ? null
      : fn.locals[sourceSlot - paramCount]!.val;
    const targetVal = fn.locals[s - paramCount]!.val;
    if (sourceVal !== null && sourceVal !== targetVal) continue;

    // Collect every read of M after the alias point. If a write to N
    // appears, break — every read scanned so far precedes that write
    // and is safe to forward, but any later read of M is now stale.
    // The `readSites.length !== stat.gets` check below catches the
    // stale-read case (post-write reads aren't collected, count
    // mismatches).
    const readSites: number[] = [];
    for (let i = setIdx + 1; i < fn.body.length; i++) {
      const op = fn.body[i]!;
      if (slotRead(op) === s) readSites.push(i);
      else if (slotWrite(op) === sourceSlot) break;
    }
    if (readSites.length !== stat.gets) continue;

    toDelete.add(setIdx - 1);
    toDelete.add(setIdx);
    for (const idx of readSites) remapReads.set(idx, sourceSlot);
  }

  if (toDelete.size === 0 && remapReads.size === 0) return;

  const newBody: Op[] = [];
  const newDbg: (DebugPos | null)[] = [];
  for (let i = 0; i < fn.body.length; i++) {
    if (toDelete.has(i)) continue;
    const newSlot = remapReads.get(i);
    newBody.push(newSlot !== undefined ? withRemappedSlot(fn.body[i]!, newSlot) : fn.body[i]!);
    newDbg.push(fn.debug[i]!);
  }
  fn.body.length = 0;
  for (const op of newBody) fn.body.push(op);
  fn.debug.length = 0;
  for (const d of newDbg) fn.debug.push(d);
}

const NUMERIC_OR_CHAR: ReadonlySet<ValType> = new Set<ValType>([
  "i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize",
  "f32", "f64", "char",
]);

/** Val type produced by a constant op, or null if `op` isn't a constant. */
function constOpValType(op: Op): ValType | null {
  switch (op.kind) {
    case "i32.const":    return "i32";
    case "i64.const":    return "i64";
    case "f32.const":    return "f32";
    case "f64.const":    return "f64";
    case "bool.const":   return "bool";
    case "char.const":   return "char";
    case "string.const": return "string";
    // null.const pushes "any" via vader_box_obj — skip ; the type-match
    // guard wouldn't fire on `any` slots in practice (any is for ref/trait
    // boxes which the lowerer pins as GC roots).
    default:             return null;
  }
}

/** If `op` is a `<type>.<verb>` shape with `verb ∈ {lt,le,gt,ge,eq,ne}`,
 *  return the inverse-verb op. Returns null otherwise. The `as Op` cast is
 *  safe because `<type>` came from a real `CmpOpKind` (every numeric width
 *  has all 6 inverses; `bool`/`string`/`char`/`ref` only have eq/ne — both
 *  closed under inversion in INVERSE_VERB). */
function invertCmp(op: Op): Op | null {
  const kind = op.kind;
  const dot = kind.indexOf(".");
  if (dot < 0) return null;
  const verb = kind.slice(dot + 1);
  const inv = INVERSE_VERB[verb];
  if (inv === undefined) return null;
  return { kind: `${kind.slice(0, dot)}.${inv}` } as Op;
}
